.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_8004251C

glabel D_8004251C
    /* 32D1C 8004251C FFFFFF00 */ .word 0x00FFFFFF /* invalid instruction */
    /* 32D20 80042520 0480083C */ .word 0x3C088004
    /* 32D24 80042524 1C250825 */ .word 0x2508251C
    /* 32D28 80042528 FFFF8120 */ .word 0x2081FFFF
    /* 32D2C 8004252C 04002018 */ .word 0x18200004
    /* 32D30 80042530 0000028D */ .word 0x8D020000
    /* 32D34 80042534 40080400 */ .word 0x00040840
    /* 32D38 80042538 0800E003 */ .word 0x03E00008
    /* 32D3C 8004253C 000001AD */ .word 0xAD010000
    /* 32D40 80042540 FF00013C */ .word 0x3C0100FF
    /* 32D44 80042544 FFFF2134 */ .word 0x3421FFFF
    /* 32D48 80042548 0800E003 */ .word 0x03E00008
    /* 32D4C 8004254C 000001AD */ .word 0xAD010000
enddlabel D_8004251C

/* Handwritten function */
nonmatching func_80042550, 0x340

glabel func_80042550
    /* 32D50 80042550 0480083C */  lui        $t0, %hi(D_8004251C)
    /* 32D54 80042554 1C250825 */  addiu      $t0, $t0, %lo(D_8004251C)
    /* 32D58 80042558 0580063C */  lui        $a2, %hi(D_80052348)
    /* 32D5C 8004255C 4823C624 */  addiu      $a2, $a2, %lo(D_80052348)
    /* 32D60 80042560 0680073C */  lui        $a3, %hi(D_80062348)
    /* 32D64 80042564 4823E724 */  addiu      $a3, $a3, %lo(D_80062348)
    /* 32D68 80042568 0F008014 */  bnez       $a0, .L800425A8
    /* 32D6C 8004256C 0000098D */   lw        $t1, 0x0($t0)
    /* 32D70 80042570 0480083C */  lui        $t0, %hi(D_80042890)
    /* 32D74 80042574 90280825 */  addiu      $t0, $t0, %lo(D_80042890)
    /* 32D78 80042578 0000048D */  lw         $a0, 0x0($t0)
    /* 32D7C 8004257C 0400058D */  lw         $a1, 0x4($t0)
    /* 32D80 80042580 0800028D */  lw         $v0, 0x8($t0)
    /* 32D84 80042584 0C00038D */  lw         $v1, 0xC($t0)
    /* 32D88 80042588 10000C8D */  lw         $t4, 0x10($t0)
    /* 32D8C 8004258C 14000D8D */  lw         $t5, 0x14($t0)
    /* 32D90 80042590 1C000F8D */  lw         $t7, 0x1C($t0)
    /* 32D94 80042594 2000188D */  lw         $t8, 0x20($t0)
    /* 32D98 80042598 2400198D */  lw         $t9, 0x24($t0)
    /* 32D9C 8004259C 20482901 */  add        $t1, $t1, $t1 /* handwritten instruction */
    /* 32DA0 800425A0 5F000104 */  bgez       $zero, .L80042720
    /* 32DA4 800425A4 2070A900 */   add       $t6, $a1, $t1 /* handwritten instruction */
  .L800425A8:
    /* 32DA8 800425A8 20680000 */  add        $t5, $zero, $zero /* handwritten instruction */
    /* 32DAC 800425AC 20780000 */  add        $t7, $zero, $zero /* handwritten instruction */
    /* 32DB0 800425B0 20C00000 */  add        $t8, $zero, $zero /* handwritten instruction */
    /* 32DB4 800425B4 20C80000 */  add        $t9, $zero, $zero /* handwritten instruction */
    /* 32DB8 800425B8 20482901 */  add        $t1, $t1, $t1 /* handwritten instruction */
    /* 32DBC 800425BC 2070A900 */  add        $t6, $a1, $t1 /* handwritten instruction */
    /* 32DC0 800425C0 00008894 */  lhu        $t0, 0x0($a0)
    /* 32DC4 800425C4 02008994 */  lhu        $t1, 0x2($a0)
    /* 32DC8 800425C8 04008C94 */  lhu        $t4, 0x4($a0)
    /* 32DCC 800425CC 06008A94 */  lhu        $t2, 0x6($a0)
    /* 32DD0 800425D0 08008294 */  lhu        $v0, 0x8($a0)
    /* 32DD4 800425D4 0A008394 */  lhu        $v1, 0xA($a0)
    /* 32DD8 800425D8 FDFF4A21 */  addi       $t2, $t2, -0x3 /* handwritten instruction */
    /* 32DDC 800425DC 02004005 */  bltz       $t2, .L800425E8
    /* 32DE0 800425E0 80620C00 */   sll       $t4, $t4, 10
    /* 32DE4 800425E4 01000D20 */  addi       $t5, $zero, 0x1 /* handwritten instruction */
  .L800425E8:
    /* 32DE8 800425E8 0C008420 */  addi       $a0, $a0, 0xC /* handwritten instruction */
    /* 32DEC 800425EC 00140200 */  sll        $v0, $v0, 16
    /* 32DF0 800425F0 25104300 */  or         $v0, $v0, $v1
    /* 32DF4 800425F4 25180000 */  or         $v1, $zero, $zero
    /* 32DF8 800425F8 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 32DFC 800425FC 0200A9A4 */  sh         $t1, 0x2($a1)
    /* 32E00 80042600 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
  .L80042604:
    /* 32E04 80042604 3500A011 */  beqz       $t5, .L800426DC
    /* 32E08 80042608 82450200 */   srl       $t0, $v0, 22
    /* 32E0C 8004260C FF030139 */  xori       $at, $t0, 0x3FF
    /* 32E10 80042610 85002010 */  beqz       $at, .L80042828
    /* 32E14 80042614 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 32E18 80042618 FDFFA121 */  addi       $at, $t5, -0x3 /* handwritten instruction */
    /* 32E1C 8004261C 02002004 */  bltz       $at, .L80042628
    /* 32E20 80042620 00FCC120 */   addi      $at, $a2, -0x400 /* handwritten instruction */
    /* 32E24 80042624 00FC2120 */  addi       $at, $at, -0x400 /* handwritten instruction */
  .L80042628:
    /* 32E28 80042628 02460200 */  srl        $t0, $v0, 24
    /* 32E2C 8004262C 80400800 */  sll        $t0, $t0, 2
    /* 32E30 80042630 20400101 */  add        $t0, $t0, $at /* handwritten instruction */
    /* 32E34 80042634 00000995 */  lhu        $t1, 0x0($t0)
    /* 32E38 80042638 02000A95 */  lhu        $t2, 0x2($t0)
    /* 32E3C 8004263C 24400000 */  and        $t0, $zero, $zero
    /* 32E40 80042640 0A004011 */  beqz       $t2, .L8004266C
    /* 32E44 80042644 04102201 */   sllv      $v0, $v0, $t1
    /* 32E48 80042648 20000120 */  addi       $at, $zero, 0x20 /* handwritten instruction */
    /* 32E4C 8004264C 22082A00 */  sub        $at, $at, $t2 /* handwritten instruction */
    /* 32E50 80042650 06402200 */  srlv       $t0, $v0, $at
    /* 32E54 80042654 04004004 */  bltz       $v0, .L80042668
    /* 32E58 80042658 04104201 */   sllv      $v0, $v0, $t2
    /* 32E5C 8004265C FFFF0B20 */  addi       $t3, $zero, -0x1 /* handwritten instruction */
    /* 32E60 80042660 06582B00 */  srlv       $t3, $t3, $at
    /* 32E64 80042664 22400B01 */  sub        $t0, $t0, $t3 /* handwritten instruction */
  .L80042668:
    /* 32E68 80042668 20186A00 */  add        $v1, $v1, $t2 /* handwritten instruction */
  .L8004266C:
    /* 32E6C 8004266C 20186900 */  add        $v1, $v1, $t1 /* handwritten instruction */
    /* 32E70 80042670 10006130 */  andi       $at, $v1, 0x10
    /* 32E74 80042674 05002010 */  beqz       $at, .L8004268C
    /* 32E78 80042678 0F006330 */   andi      $v1, $v1, 0xF
    /* 32E7C 8004267C 00008994 */  lhu        $t1, 0x0($a0)
    /* 32E80 80042680 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 32E84 80042684 04486900 */  sllv       $t1, $t1, $v1
    /* 32E88 80042688 25104900 */  or         $v0, $v0, $t1
  .L8004268C:
    /* 32E8C 8004268C FEFFA121 */  addi       $at, $t5, -0x2 /* handwritten instruction */
    /* 32E90 80042690 0800201C */  bgtz       $at, .L800426B4
    /* 32E94 80042694 20482803 */   add       $t1, $t9, $t0 /* handwritten instruction */
    /* 32E98 80042698 04002010 */  beqz       $at, .L800426AC
    /* 32E9C 8004269C 20480803 */   add       $t1, $t8, $t0 /* handwritten instruction */
    /* 32EA0 800426A0 2048E801 */  add        $t1, $t7, $t0 /* handwritten instruction */
    /* 32EA4 800426A4 04000104 */  bgez       $zero, .L800426B8
    /* 32EA8 800426A8 2078E801 */   add       $t7, $t7, $t0 /* handwritten instruction */
  .L800426AC:
    /* 32EAC 800426AC 02000104 */  bgez       $zero, .L800426B8
    /* 32EB0 800426B0 20C00803 */   add       $t8, $t8, $t0 /* handwritten instruction */
  .L800426B4:
    /* 32EB4 800426B4 20C82803 */  add        $t9, $t9, $t0 /* handwritten instruction */
  .L800426B8:
    /* 32EB8 800426B8 80480900 */  sll        $t1, $t1, 2
    /* 32EBC 800426BC FF032931 */  andi       $t1, $t1, 0x3FF
    /* 32EC0 800426C0 25488901 */  or         $t1, $t4, $t1
    /* 32EC4 800426C4 0100AD21 */  addi       $t5, $t5, 0x1 /* handwritten instruction */
    /* 32EC8 800426C8 F9FFA121 */  addi       $at, $t5, -0x7 /* handwritten instruction */
    /* 32ECC 800426CC 11002014 */  bnez       $at, .L80042714
    /* 32ED0 800426D0 0000A9A4 */   sh        $t1, 0x0($a1)
    /* 32ED4 800426D4 0F000104 */  bgez       $zero, .L80042714
    /* 32ED8 800426D8 FAFFAD21 */   addi      $t5, $t5, -0x6 /* handwritten instruction */
  .L800426DC:
    /* 32EDC 800426DC FF010139 */  xori       $at, $t0, 0x1FF
    /* 32EE0 800426E0 51002010 */  beqz       $at, .L80042828
    /* 32EE4 800426E4 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 32EE8 800426E8 80120200 */  sll        $v0, $v0, 10
    /* 32EEC 800426EC 0A006320 */  addi       $v1, $v1, 0xA /* handwritten instruction */
    /* 32EF0 800426F0 10006130 */  andi       $at, $v1, 0x10
    /* 32EF4 800426F4 05002010 */  beqz       $at, .L8004270C
    /* 32EF8 800426F8 0F006330 */   andi      $v1, $v1, 0xF
    /* 32EFC 800426FC 00008994 */  lhu        $t1, 0x0($a0)
    /* 32F00 80042700 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 32F04 80042704 04486900 */  sllv       $t1, $t1, $v1
    /* 32F08 80042708 25104900 */  or         $v0, $v0, $t1
  .L8004270C:
    /* 32F0C 8004270C 25408801 */  or         $t0, $t4, $t0
    /* 32F10 80042710 0000A8A4 */  sh         $t0, 0x0($a1)
  .L80042714:
    /* 32F14 80042714 2308AE00 */  subu       $at, $a1, $t6
    /* 32F18 80042718 50002104 */  bgez       $at, .L8004285C
    /* 32F1C 8004271C 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
  .L80042720:
    /* 32F20 80042720 C2440200 */  srl        $t0, $v0, 19
    /* 32F24 80042724 C0400800 */  sll        $t0, $t0, 3
    /* 32F28 80042728 20400601 */  add        $t0, $t0, $a2 /* handwritten instruction */
    /* 32F2C 8004272C 0000098D */  lw         $t1, 0x0($t0)
    /* 32F30 80042730 00000000 */  nop
    /* 32F34 80042734 11002015 */  bnez       $t1, .L8004277C
    /* 32F38 80042738 FF002131 */   andi      $at, $t1, 0xFF
    /* 32F3C 8004273C 00120200 */  sll        $v0, $v0, 8
    /* 32F40 80042740 08006320 */  addi       $v1, $v1, 0x8 /* handwritten instruction */
    /* 32F44 80042744 10006130 */  andi       $at, $v1, 0x10
    /* 32F48 80042748 05002010 */  beqz       $at, .L80042760
    /* 32F4C 8004274C 0F006330 */   andi      $v1, $v1, 0xF
    /* 32F50 80042750 00008894 */  lhu        $t0, 0x0($a0)
    /* 32F54 80042754 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 32F58 80042758 04406800 */  sllv       $t0, $t0, $v1
    /* 32F5C 8004275C 25104800 */  or         $v0, $v0, $t0
  .L80042760:
    /* 32F60 80042760 C2450200 */  srl        $t0, $v0, 23
    /* 32F64 80042764 80400800 */  sll        $t0, $t0, 2
    /* 32F68 80042768 20400701 */  add        $t0, $t0, $a3 /* handwritten instruction */
    /* 32F6C 8004276C 0000098D */  lw         $t1, 0x0($t0)
    /* 32F70 80042770 20580000 */  add        $t3, $zero, $zero /* handwritten instruction */
    /* 32F74 80042774 02000104 */  bgez       $zero, .L80042780
    /* 32F78 80042778 FF002131 */   andi      $at, $t1, 0xFF
  .L8004277C:
    /* 32F7C 8004277C 04000B8D */  lw         $t3, 0x4($t0)
  .L80042780:
    /* 32F80 80042780 04102200 */  sllv       $v0, $v0, $at
    /* 32F84 80042784 20186100 */  add        $v1, $v1, $at /* handwritten instruction */
    /* 32F88 80042788 10006130 */  andi       $at, $v1, 0x10
    /* 32F8C 8004278C 05002010 */  beqz       $at, .L800427A4
    /* 32F90 80042790 0F006330 */   andi      $v1, $v1, 0xF
    /* 32F94 80042794 00008894 */  lhu        $t0, 0x0($a0)
    /* 32F98 80042798 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 32F9C 8004279C 04406800 */  sllv       $t0, $t0, $v1
    /* 32FA0 800427A0 25104800 */  or         $v0, $v0, $t0
  .L800427A4:
    /* 32FA4 800427A4 024C0900 */  srl        $t1, $t1, 16
    /* 32FA8 800427A8 1F7C2139 */  xori       $at, $t1, 0x7C1F
    /* 32FAC 800427AC 15002010 */  beqz       $at, .L80042804
    /* 32FB0 800427B0 00FE2139 */   xori      $at, $t1, 0xFE00
    /* 32FB4 800427B4 93FF2010 */  beqz       $at, .L80042604
    /* 32FB8 800427B8 0000A9A4 */   sh        $t1, 0x0($a1)
    /* 32FBC 800427BC D8FF6011 */  beqz       $t3, .L80042720
    /* 32FC0 800427C0 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 32FC4 800427C4 FFFF6A31 */  andi       $t2, $t3, 0xFFFF
    /* 32FC8 800427C8 1F7C4139 */  xori       $at, $t2, 0x7C1F
    /* 32FCC 800427CC 0D002010 */  beqz       $at, .L80042804
    /* 32FD0 800427D0 00FE4139 */   xori      $at, $t2, 0xFE00
    /* 32FD4 800427D4 8BFF2010 */  beqz       $at, .L80042604
    /* 32FD8 800427D8 0000AAA4 */   sh        $t2, 0x0($a1)
    /* 32FDC 800427DC 02540B00 */  srl        $t2, $t3, 16
    /* 32FE0 800427E0 CFFF4011 */  beqz       $t2, .L80042720
    /* 32FE4 800427E4 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 32FE8 800427E8 1F7C4139 */  xori       $at, $t2, 0x7C1F
    /* 32FEC 800427EC 05002010 */  beqz       $at, .L80042804
    /* 32FF0 800427F0 00FE4139 */   xori      $at, $t2, 0xFE00
    /* 32FF4 800427F4 83FF2010 */  beqz       $at, .L80042604
    /* 32FF8 800427F8 0000AAA4 */   sh        $t2, 0x0($a1)
    /* 32FFC 800427FC C8FF0104 */  bgez       $zero, .L80042720
    /* 33000 80042800 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
  .L80042804:
    /* 33004 80042804 02440200 */  srl        $t0, $v0, 16
    /* 33008 80042808 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 3300C 8004280C 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
    /* 33010 80042810 00008894 */  lhu        $t0, 0x0($a0)
    /* 33014 80042814 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 33018 80042818 00140200 */  sll        $v0, $v0, 16
    /* 3301C 8004281C 04406800 */  sllv       $t0, $t0, $v1
    /* 33020 80042820 BFFF0104 */  bgez       $zero, .L80042720
    /* 33024 80042824 25104800 */   or        $v0, $v0, $t0
  .L80042828:
    /* 33028 80042828 00FE0834 */  ori        $t0, $zero, 0xFE00
    /* 3302C 8004282C 40000220 */  addi       $v0, $zero, 0x40 /* handwritten instruction */
  .L80042830:
    /* 33030 80042830 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 33034 80042834 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
    /* 33038 80042838 FDFF4014 */  bnez       $v0, .L80042830
    /* 3303C 8004283C FFFF4220 */   addi      $v0, $v0, -0x1 /* handwritten instruction */
    /* 33040 80042840 00600940 */  mfc0       $t1, $12 /* handwritten instruction */
    /* 33044 80042844 00000000 */  nop
    /* 33048 80042848 0200013C */  lui        $at, (0x20000 >> 16)
    /* 3304C 8004284C 25482101 */  or         $t1, $t1, $at
    /* 33050 80042850 00608940 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 33054 80042854 0800E003 */  jr         $ra
    /* 33058 80042858 20100000 */   add       $v0, $zero, $zero /* handwritten instruction */
  .L8004285C:
    /* 3305C 8004285C 0480083C */  lui        $t0, %hi(D_80042890)
    /* 33060 80042860 90280825 */  addiu      $t0, $t0, %lo(D_80042890)
    /* 33064 80042864 000004AD */  sw         $a0, 0x0($t0)
    /* 33068 80042868 040005AD */  sw         $a1, 0x4($t0)
    /* 3306C 8004286C 080002AD */  sw         $v0, 0x8($t0)
    /* 33070 80042870 0C0003AD */  sw         $v1, 0xC($t0)
    /* 33074 80042874 10000CAD */  sw         $t4, 0x10($t0)
    /* 33078 80042878 14000DAD */  sw         $t5, 0x14($t0)
    /* 3307C 8004287C 1C000FAD */  sw         $t7, 0x1C($t0)
    /* 33080 80042880 200018AD */  sw         $t8, 0x20($t0)
    /* 33084 80042884 240019AD */  sw         $t9, 0x24($t0)
    /* 33088 80042888 0800E003 */  jr         $ra
    /* 3308C 8004288C 01000220 */   addi      $v0, $zero, 0x1 /* handwritten instruction */
endlabel func_80042550

nonmatching D_80042890, 0x4

glabel D_80042890
    /* 33090 80042890 00000000 */  nop
endlabel D_80042890
    /* 33094 80042894 00000000 */  nop
    /* 33098 80042898 00000000 */  nop
    /* 3309C 8004289C 00000000 */  nop
    /* 330A0 800428A0 00000000 */  nop
    /* 330A4 800428A4 00000000 */  nop
    /* 330A8 800428A8 00000000 */  nop
    /* 330AC 800428AC 00000000 */  nop
    /* 330B0 800428B0 00000000 */  nop

nonmatching InitHeap, 0xC

glabel InitHeap
    /* 330B4 800428B4 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 330B8 800428B8 08004001 */  jr         $t2
    /* 330BC 800428BC 39000924 */   addiu     $t1, $zero, 0x39
endlabel InitHeap
    /* 330C0 800428C0 00000000 */  nop

nonmatching FlushCache, 0xC

glabel FlushCache
    /* 330C4 800428C4 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 330C8 800428C8 08004001 */  jr         $t2
    /* 330CC 800428CC 44000924 */   addiu     $t1, $zero, 0x44
endlabel FlushCache
    /* 330D0 800428D0 00000000 */  nop

nonmatching _bu_init, 0xC

glabel _bu_init
    /* 330D4 800428D4 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 330D8 800428D8 08004001 */  jr         $t2
    /* 330DC 800428DC 70000924 */   addiu     $t1, $zero, 0x70
endlabel _bu_init
    /* 330E0 800428E0 00000000 */  nop

nonmatching func_800428E4, 0xC

glabel func_800428E4
    /* 330E4 800428E4 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 330E8 800428E8 08004001 */  jr         $t2
    /* 330EC 800428EC 72000924 */   addiu     $t1, $zero, 0x72
endlabel func_800428E4
    /* 330F0 800428F0 00000000 */  nop

nonmatching SetMem, 0xC

glabel SetMem
    /* 330F4 800428F4 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 330F8 800428F8 08004001 */  jr         $t2
    /* 330FC 800428FC 9F000924 */   addiu     $t1, $zero, 0x9F
endlabel SetMem
    /* 33100 80042900 00000000 */  nop

nonmatching SystemError, 0xC

glabel SystemError
    /* 33104 80042904 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 33108 80042908 08004001 */  jr         $t2
    /* 3310C 8004290C A1000924 */   addiu     $t1, $zero, 0xA1
endlabel SystemError
    /* 33110 80042910 00000000 */  nop

nonmatching DeliverEvent, 0xC

glabel DeliverEvent
    /* 33114 80042914 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33118 80042918 08004001 */  jr         $t2
    /* 3311C 8004291C 07000924 */   addiu     $t1, $zero, 0x7
endlabel DeliverEvent
    /* 33120 80042920 00000000 */  nop

nonmatching OpenEvent, 0xC

glabel OpenEvent
    /* 33124 80042924 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33128 80042928 08004001 */  jr         $t2
    /* 3312C 8004292C 08000924 */   addiu     $t1, $zero, 0x8
endlabel OpenEvent
    /* 33130 80042930 00000000 */  nop

nonmatching CloseEvent, 0xC

glabel CloseEvent
    /* 33134 80042934 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33138 80042938 08004001 */  jr         $t2
    /* 3313C 8004293C 09000924 */   addiu     $t1, $zero, 0x9
endlabel CloseEvent
    /* 33140 80042940 00000000 */  nop

nonmatching WaitEvent, 0xC

glabel WaitEvent
    /* 33144 80042944 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33148 80042948 08004001 */  jr         $t2
    /* 3314C 8004294C 0A000924 */   addiu     $t1, $zero, 0xA
endlabel WaitEvent
    /* 33150 80042950 00000000 */  nop

nonmatching TestEvent, 0xC

glabel TestEvent
    /* 33154 80042954 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33158 80042958 08004001 */  jr         $t2
    /* 3315C 8004295C 0B000924 */   addiu     $t1, $zero, 0xB
endlabel TestEvent
    /* 33160 80042960 00000000 */  nop

nonmatching EnableEvent, 0xC

glabel EnableEvent
    /* 33164 80042964 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33168 80042968 08004001 */  jr         $t2
    /* 3316C 8004296C 0C000924 */   addiu     $t1, $zero, 0xC
endlabel EnableEvent
    /* 33170 80042970 00000000 */  nop

nonmatching DisableEvent, 0xC

glabel DisableEvent
    /* 33174 80042974 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33178 80042978 08004001 */  jr         $t2
    /* 3317C 8004297C 0D000924 */   addiu     $t1, $zero, 0xD
endlabel DisableEvent
    /* 33180 80042980 00000000 */  nop

nonmatching InitPAD2, 0xC

glabel InitPAD2
    /* 33184 80042984 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33188 80042988 08004001 */  jr         $t2
    /* 3318C 8004298C 12000924 */   addiu     $t1, $zero, 0x12
endlabel InitPAD2
    /* 33190 80042990 00000000 */  nop

nonmatching StartPAD2, 0xC

glabel StartPAD2
    /* 33194 80042994 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33198 80042998 08004001 */  jr         $t2
    /* 3319C 8004299C 13000924 */   addiu     $t1, $zero, 0x13
endlabel StartPAD2
    /* 331A0 800429A0 00000000 */  nop

nonmatching StopPAD, 0xC

glabel StopPAD
    /* 331A4 800429A4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331A8 800429A8 08004001 */  jr         $t2
    /* 331AC 800429AC 14000924 */   addiu     $t1, $zero, 0x14
endlabel StopPAD
    /* 331B0 800429B0 00000000 */  nop

nonmatching PAD_init2, 0xC

glabel PAD_init2
    /* 331B4 800429B4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331B8 800429B8 08004001 */  jr         $t2
    /* 331BC 800429BC 15000924 */   addiu     $t1, $zero, 0x15
endlabel PAD_init2
    /* 331C0 800429C0 00000000 */  nop

nonmatching PAD_dr, 0xC

glabel PAD_dr
    /* 331C4 800429C4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331C8 800429C8 08004001 */  jr         $t2
    /* 331CC 800429CC 16000924 */   addiu     $t1, $zero, 0x16
endlabel PAD_dr
    /* 331D0 800429D0 00000000 */  nop

nonmatching ReturnFromException, 0xC

glabel ReturnFromException
    /* 331D4 800429D4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331D8 800429D8 08004001 */  jr         $t2
    /* 331DC 800429DC 17000924 */   addiu     $t1, $zero, 0x17
endlabel ReturnFromException
    /* 331E0 800429E0 00000000 */  nop

nonmatching ResetEntryInt, 0xC

glabel ResetEntryInt
    /* 331E4 800429E4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331E8 800429E8 08004001 */  jr         $t2
    /* 331EC 800429EC 18000924 */   addiu     $t1, $zero, 0x18
endlabel ResetEntryInt
    /* 331F0 800429F0 00000000 */  nop

nonmatching HookEntryInt, 0xC

glabel HookEntryInt
    /* 331F4 800429F4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 331F8 800429F8 08004001 */  jr         $t2
    /* 331FC 800429FC 19000924 */   addiu     $t1, $zero, 0x19
endlabel HookEntryInt
    /* 33200 80042A00 00000000 */  nop

nonmatching UnDeliverEvent, 0xC

glabel UnDeliverEvent
    /* 33204 80042A04 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33208 80042A08 08004001 */  jr         $t2
    /* 3320C 80042A0C 20000924 */   addiu     $t1, $zero, 0x20
endlabel UnDeliverEvent
    /* 33210 80042A10 00000000 */  nop

/* Handwritten function */
nonmatching func_80042A14, 0x10

glabel func_80042A14
    /* 33214 80042A14 01000424 */  addiu      $a0, $zero, 0x1
    /* 33218 80042A18 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3321C 80042A1C 0800E003 */  jr         $ra
    /* 33220 80042A20 00000000 */   nop
endlabel func_80042A14

/* Handwritten function */
nonmatching func_80042A24, 0x10

glabel func_80042A24
    /* 33224 80042A24 02000424 */  addiu      $a0, $zero, 0x2
    /* 33228 80042A28 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3322C 80042A2C 0800E003 */  jr         $ra
    /* 33230 80042A30 00000000 */   nop
endlabel func_80042A24

nonmatching func_80042A34, 0xC

glabel func_80042A34
    /* 33234 80042A34 2110A003 */  addu       $v0, $sp, $zero
    /* 33238 80042A38 0800E003 */  jr         $ra
    /* 3323C 80042A3C 21E88000 */   addu      $sp, $a0, $zero
endlabel func_80042A34

nonmatching func_80042A40, 0x4

glabel func_80042A40
    /* 33240 80042A40 00000000 */  nop
endlabel func_80042A40

nonmatching open, 0xC

glabel open
    /* 33244 80042A44 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33248 80042A48 08004001 */  jr         $t2
    /* 3324C 80042A4C 32000924 */   addiu     $t1, $zero, 0x32
endlabel open
    /* 33250 80042A50 00000000 */  nop

nonmatching read, 0xC

glabel read
    /* 33254 80042A54 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33258 80042A58 08004001 */  jr         $t2
    /* 3325C 80042A5C 34000924 */   addiu     $t1, $zero, 0x34
endlabel read
    /* 33260 80042A60 00000000 */  nop

nonmatching write, 0xC

glabel write
    /* 33264 80042A64 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33268 80042A68 08004001 */  jr         $t2
    /* 3326C 80042A6C 35000924 */   addiu     $t1, $zero, 0x35
endlabel write
    /* 33270 80042A70 00000000 */  nop

nonmatching close, 0xC

glabel close
    /* 33274 80042A74 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33278 80042A78 08004001 */  jr         $t2
    /* 3327C 80042A7C 36000924 */   addiu     $t1, $zero, 0x36
endlabel close
    /* 33280 80042A80 00000000 */  nop

nonmatching format, 0xC

glabel format
    /* 33284 80042A84 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33288 80042A88 08004001 */  jr         $t2
    /* 3328C 80042A8C 41000924 */   addiu     $t1, $zero, 0x41
endlabel format
    /* 33290 80042A90 00000000 */  nop

nonmatching firstfile, 0xC

glabel firstfile
    /* 33294 80042A94 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33298 80042A98 08004001 */  jr         $t2
    /* 3329C 80042A9C 42000924 */   addiu     $t1, $zero, 0x42
endlabel firstfile
    /* 332A0 80042AA0 00000000 */  nop

nonmatching nextfile, 0xC

glabel nextfile
    /* 332A4 80042AA4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 332A8 80042AA8 08004001 */  jr         $t2
    /* 332AC 80042AAC 43000924 */   addiu     $t1, $zero, 0x43
endlabel nextfile
    /* 332B0 80042AB0 00000000 */  nop

nonmatching erase, 0xC

glabel erase
    /* 332B4 80042AB4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 332B8 80042AB8 08004001 */  jr         $t2
    /* 332BC 80042ABC 45000924 */   addiu     $t1, $zero, 0x45
endlabel erase
    /* 332C0 80042AC0 00000000 */  nop

nonmatching ChangeClearPAD, 0xC

glabel ChangeClearPAD
    /* 332C4 80042AC4 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 332C8 80042AC8 08004001 */  jr         $t2
    /* 332CC 80042ACC 5B000924 */   addiu     $t1, $zero, 0x5B
endlabel ChangeClearPAD
    /* 332D0 80042AD0 00000000 */  nop

nonmatching ChangeClearRCnt, 0xC

glabel ChangeClearRCnt
    /* 332D4 80042AD4 C0000A24 */  addiu      $t2, $zero, 0xC0
    /* 332D8 80042AD8 08004001 */  jr         $t2
    /* 332DC 80042ADC 0A000924 */   addiu     $t1, $zero, 0xA
endlabel ChangeClearRCnt
    /* 332E0 80042AE0 00000000 */  nop

nonmatching SetRCnt, 0x74

glabel SetRCnt
    /* 332E4 80042AE4 FFFF8830 */  andi       $t0, $a0, 0xFFFF
    /* 332E8 80042AE8 03000229 */  slti       $v0, $t0, 0x3
    /* 332EC 80042AEC 03004014 */  bnez       $v0, COUNTER_OBJ_18
    /* 332F0 80042AF0 48000734 */   ori       $a3, $zero, 0x48
    /* 332F4 80042AF4 DF0A0108 */  j          COUNTER_OBJ_98
    /* 332F8 80042AF8 21100000 */   addu      $v0, $zero, $zero
  COUNTER_OBJ_18:
    /* 332FC 80042AFC 0680023C */  lui        $v0, %hi(D_80062B4C)
    /* 33300 80042B00 4C2B428C */  lw         $v0, %lo(D_80062B4C)($v0)
    /* 33304 80042B04 00190800 */  sll        $v1, $t0, 4
    /* 33308 80042B08 21186200 */  addu       $v1, $v1, $v0
    /* 3330C 80042B0C 0200022D */  sltiu      $v0, $t0, 0x2
    /* 33310 80042B10 040060A4 */  sh         $zero, 0x4($v1)
    /* 33314 80042B14 080065A4 */  sh         $a1, 0x8($v1)
    /* 33318 80042B18 08004010 */  beqz       $v0, COUNTER_OBJ_58
    /* 3331C 80042B1C 1000C230 */   andi      $v0, $a2, 0x10
    /* 33320 80042B20 02004010 */  beqz       $v0, COUNTER_OBJ_48
    /* 33324 80042B24 0100C230 */   andi      $v0, $a2, 0x1
    /* 33328 80042B28 49000734 */  ori        $a3, $zero, 0x49
  COUNTER_OBJ_48:
    /* 3332C 80042B2C 0A004014 */  bnez       $v0, COUNTER_OBJ_74
    /* 33330 80042B30 0010C230 */   andi      $v0, $a2, 0x1000
    /* 33334 80042B34 D60A0108 */  j          COUNTER_OBJ_74
    /* 33338 80042B38 0001E734 */   ori       $a3, $a3, 0x100
  COUNTER_OBJ_58:
    /* 3333C 80042B3C 02000234 */  ori        $v0, $zero, 0x2
    /* 33340 80042B40 05000215 */  bne        $t0, $v0, COUNTER_OBJ_74
    /* 33344 80042B44 0010C230 */   andi      $v0, $a2, 0x1000
    /* 33348 80042B48 0100C230 */  andi       $v0, $a2, 0x1
    /* 3334C 80042B4C 02004014 */  bnez       $v0, COUNTER_OBJ_74
    /* 33350 80042B50 0010C230 */   andi      $v0, $a2, 0x1000
    /* 33354 80042B54 48020734 */  ori        $a3, $zero, 0x248
endlabel SetRCnt

nonmatching COUNTER_OBJ_74, 0x24

glabel COUNTER_OBJ_74
    /* 33358 80042B58 02004010 */  beqz       $v0, COUNTER_OBJ_80
    /* 3335C 80042B5C 00190800 */   sll       $v1, $t0, 4
    /* 33360 80042B60 1000E734 */  ori        $a3, $a3, 0x10
  COUNTER_OBJ_80:
    /* 33364 80042B64 01000234 */  ori        $v0, $zero, 0x1
    /* 33368 80042B68 0680043C */  lui        $a0, %hi(D_80062B4C)
    /* 3336C 80042B6C 4C2B848C */  lw         $a0, %lo(D_80062B4C)($a0)
    /* 33370 80042B70 00000000 */  nop
    /* 33374 80042B74 21186400 */  addu       $v1, $v1, $a0
    /* 33378 80042B78 040067A4 */  sh         $a3, 0x4($v1)
endlabel COUNTER_OBJ_74

nonmatching COUNTER_OBJ_98, 0x8

glabel COUNTER_OBJ_98
    /* 3337C 80042B7C 0800E003 */  jr         $ra
    /* 33380 80042B80 00000000 */   nop
endlabel COUNTER_OBJ_98

nonmatching GetRCnt, 0x30

glabel GetRCnt
    /* 33384 80042B84 FFFF8330 */  andi       $v1, $a0, 0xFFFF
    /* 33388 80042B88 03006228 */  slti       $v0, $v1, 0x3
    /* 3338C 80042B8C 08004010 */  beqz       $v0, COUNTER_OBJ_CC
    /* 33390 80042B90 00190300 */   sll       $v1, $v1, 4
    /* 33394 80042B94 0680023C */  lui        $v0, %hi(D_80062B4C)
    /* 33398 80042B98 4C2B428C */  lw         $v0, %lo(D_80062B4C)($v0)
    /* 3339C 80042B9C 00000000 */  nop
    /* 333A0 80042BA0 21186200 */  addu       $v1, $v1, $v0
    /* 333A4 80042BA4 00006294 */  lhu        $v0, 0x0($v1)
    /* 333A8 80042BA8 ED0A0108 */  j          COUNTER_OBJ_D0
    /* 333AC 80042BAC 00000000 */   nop
  COUNTER_OBJ_CC:
    /* 333B0 80042BB0 21100000 */  addu       $v0, $zero, $zero
endlabel GetRCnt

nonmatching COUNTER_OBJ_D0, 0x8

glabel COUNTER_OBJ_D0
    /* 333B4 80042BB4 0800E003 */  jr         $ra
    /* 333B8 80042BB8 00000000 */   nop
endlabel COUNTER_OBJ_D0

nonmatching StartRCnt, 0x34

glabel StartRCnt
    /* 333BC 80042BBC FFFF8230 */  andi       $v0, $a0, 0xFFFF
    /* 333C0 80042BC0 80200200 */  sll        $a0, $v0, 2
    /* 333C4 80042BC4 0680053C */  lui        $a1, %hi(D_80062B48)
    /* 333C8 80042BC8 482BA58C */  lw         $a1, %lo(D_80062B48)($a1)
    /* 333CC 80042BCC 0680013C */  lui        $at, %hi(D_80062B50)
    /* 333D0 80042BD0 21082400 */  addu       $at, $at, $a0
    /* 333D4 80042BD4 502B248C */  lw         $a0, %lo(D_80062B50)($at)
    /* 333D8 80042BD8 0400A38C */  lw         $v1, 0x4($a1)
    /* 333DC 80042BDC 03004228 */  slti       $v0, $v0, 0x3
    /* 333E0 80042BE0 25186400 */  or         $v1, $v1, $a0
    /* 333E4 80042BE4 0400A3AC */  sw         $v1, 0x4($a1)
    /* 333E8 80042BE8 0800E003 */  jr         $ra
    /* 333EC 80042BEC 00000000 */   nop
endlabel StartRCnt

nonmatching StopRCnt, 0x34

glabel StopRCnt
    /* 333F0 80042BF0 FFFF8430 */  andi       $a0, $a0, 0xFFFF
    /* 333F4 80042BF4 80200400 */  sll        $a0, $a0, 2
    /* 333F8 80042BF8 0680053C */  lui        $a1, %hi(D_80062B48)
    /* 333FC 80042BFC 482BA58C */  lw         $a1, %lo(D_80062B48)($a1)
    /* 33400 80042C00 0680013C */  lui        $at, %hi(D_80062B50)
    /* 33404 80042C04 21082400 */  addu       $at, $at, $a0
    /* 33408 80042C08 502B228C */  lw         $v0, %lo(D_80062B50)($at)
    /* 3340C 80042C0C 0400A38C */  lw         $v1, 0x4($a1)
    /* 33410 80042C10 27100200 */  nor        $v0, $zero, $v0
    /* 33414 80042C14 24104300 */  and        $v0, $v0, $v1
    /* 33418 80042C18 0400A2AC */  sw         $v0, 0x4($a1)
    /* 3341C 80042C1C 0800E003 */  jr         $ra
    /* 33420 80042C20 01000234 */   ori       $v0, $zero, 0x1
endlabel StopRCnt

nonmatching ResetRCnt, 0x30

glabel ResetRCnt
    /* 33424 80042C24 FFFF8330 */  andi       $v1, $a0, 0xFFFF
    /* 33428 80042C28 03006228 */  slti       $v0, $v1, 0x3
    /* 3342C 80042C2C 08004010 */  beqz       $v0, COUNTER_OBJ_16C
    /* 33430 80042C30 01000234 */   ori       $v0, $zero, 0x1
    /* 33434 80042C34 0680043C */  lui        $a0, %hi(D_80062B4C)
    /* 33438 80042C38 4C2B848C */  lw         $a0, %lo(D_80062B4C)($a0)
    /* 3343C 80042C3C 00190300 */  sll        $v1, $v1, 4
    /* 33440 80042C40 21186400 */  addu       $v1, $v1, $a0
    /* 33444 80042C44 000060A4 */  sh         $zero, 0x0($v1)
    /* 33448 80042C48 150B0108 */  j          COUNTER_OBJ_170
    /* 3344C 80042C4C 00000000 */   nop
  COUNTER_OBJ_16C:
    /* 33450 80042C50 21100000 */  addu       $v0, $zero, $zero
endlabel ResetRCnt

nonmatching COUNTER_OBJ_170, 0x8

glabel COUNTER_OBJ_170
    /* 33454 80042C54 0800E003 */  jr         $ra
    /* 33458 80042C58 00000000 */   nop
endlabel COUNTER_OBJ_170

nonmatching exit, 0xC

glabel exit
    /* 3345C 80042C5C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33460 80042C60 08004001 */  jr         $t2
    /* 33464 80042C64 38000924 */   addiu     $t1, $zero, 0x38
endlabel exit
    /* 33468 80042C68 00000000 */  nop

nonmatching func_80042C6C, 0xC

glabel func_80042C6C
    /* 3346C 80042C6C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 33470 80042C70 08004001 */  jr         $t2
    /* 33474 80042C74 3F000924 */   addiu     $t1, $zero, 0x3F
endlabel func_80042C6C
    /* 33478 80042C78 00000000 */  nop

nonmatching setjmp, 0xC

glabel setjmp
    /* 3347C 80042C7C A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 33480 80042C80 08004001 */  jr         $t2
    /* 33484 80042C84 13000924 */   addiu     $t1, $zero, 0x13
endlabel setjmp
    /* 33488 80042C88 00000000 */  nop

nonmatching strcmp, 0xC

glabel strcmp
    /* 3348C 80042C8C A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 33490 80042C90 08004001 */  jr         $t2
    /* 33494 80042C94 17000924 */   addiu     $t1, $zero, 0x17
endlabel strcmp
    /* 33498 80042C98 00000000 */  nop

nonmatching strncmp, 0xC

glabel strncmp
    /* 3349C 80042C9C A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334A0 80042CA0 08004001 */  jr         $t2
    /* 334A4 80042CA4 18000924 */   addiu     $t1, $zero, 0x18
endlabel strncmp
    /* 334A8 80042CA8 00000000 */  nop

nonmatching bcopy, 0xC

glabel bcopy
    /* 334AC 80042CAC A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334B0 80042CB0 08004001 */  jr         $t2
    /* 334B4 80042CB4 27000924 */   addiu     $t1, $zero, 0x27
endlabel bcopy
    /* 334B8 80042CB8 00000000 */  nop

nonmatching memcpy, 0xC

glabel memcpy
    /* 334BC 80042CBC A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334C0 80042CC0 08004001 */  jr         $t2
    /* 334C4 80042CC4 2A000924 */   addiu     $t1, $zero, 0x2A
endlabel memcpy
    /* 334C8 80042CC8 00000000 */  nop

nonmatching rand, 0xC

glabel rand
    /* 334CC 80042CCC A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334D0 80042CD0 08004001 */  jr         $t2
    /* 334D4 80042CD4 2F000924 */   addiu     $t1, $zero, 0x2F
endlabel rand
    /* 334D8 80042CD8 00000000 */  nop

nonmatching srand, 0xC

glabel srand
    /* 334DC 80042CDC A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334E0 80042CE0 08004001 */  jr         $t2
    /* 334E4 80042CE4 30000924 */   addiu     $t1, $zero, 0x30
endlabel srand
    /* 334E8 80042CE8 00000000 */  nop

nonmatching printf, 0xC

glabel printf
    /* 334EC 80042CEC A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 334F0 80042CF0 08004001 */  jr         $t2
    /* 334F4 80042CF4 3F000924 */   addiu     $t1, $zero, 0x3F
endlabel printf
    /* 334F8 80042CF8 00000000 */  nop

nonmatching sprintf, 0x90

glabel sprintf
    /* 334FC 80042CFC 0400A5AF */  sw         $a1, 0x4($sp)
    /* 33500 80042D00 0800A6AF */  sw         $a2, 0x8($sp)
    /* 33504 80042D04 0C00A7AF */  sw         $a3, 0xC($sp)
    /* 33508 80042D08 B8FDBD27 */  addiu      $sp, $sp, -0x248
    /* 3350C 80042D0C 3402B3AF */  sw         $s3, 0x234($sp)
    /* 33510 80042D10 21988000 */  addu       $s3, $a0, $zero
    /* 33514 80042D14 5002A227 */  addiu      $v0, $sp, 0x250
    /* 33518 80042D18 4402BFAF */  sw         $ra, 0x244($sp)
    /* 3351C 80042D1C 4002B6AF */  sw         $s6, 0x240($sp)
    /* 33520 80042D20 3C02B5AF */  sw         $s5, 0x23C($sp)
    /* 33524 80042D24 3802B4AF */  sw         $s4, 0x238($sp)
    /* 33528 80042D28 3002B2AF */  sw         $s2, 0x230($sp)
    /* 3352C 80042D2C 2C02B1AF */  sw         $s1, 0x22C($sp)
    /* 33530 80042D30 2802B0AF */  sw         $s0, 0x228($sp)
    /* 33534 80042D34 4C02A5AF */  sw         $a1, 0x24C($sp)
    /* 33538 80042D38 2002A2AF */  sw         $v0, 0x220($sp)
    /* 3353C 80042D3C 0000A590 */  lbu        $a1, 0x0($a1)
    /* 33540 80042D40 00000000 */  nop
    /* 33544 80042D44 F601A010 */  beqz       $a1, SPRINTF_OBJ_824
    /* 33548 80042D48 21900000 */   addu      $s2, $zero, $zero
    /* 3354C 80042D4C 2D001634 */  ori        $s6, $zero, 0x2D
    /* 33550 80042D50 2B001534 */  ori        $s5, $zero, 0x2B
    /* 33554 80042D54 20001434 */  ori        $s4, $zero, 0x20
    /* 33558 80042D58 25000234 */  ori        $v0, $zero, 0x25
  SPRINTF_OBJ_60:
    /* 3355C 80042D5C C001A214 */  bne        $a1, $v0, SPRINTF_OBJ_764
    /* 33560 80042D60 21107202 */   addu      $v0, $s3, $s2
    /* 33564 80042D64 0680053C */  lui        $a1, %hi(D_80062B60)
    /* 33568 80042D68 602BA524 */  addiu      $a1, $a1, %lo(D_80062B60)
    /* 3356C 80042D6C 0000A28C */  lw         $v0, 0x0($a1)
    /* 33570 80042D70 0400A38C */  lw         $v1, 0x4($a1)
    /* 33574 80042D74 0800A48C */  lw         $a0, 0x8($a1)
    /* 33578 80042D78 1002A2AF */  sw         $v0, 0x210($sp)
    /* 3357C 80042D7C 1402A3AF */  sw         $v1, 0x214($sp)
    /* 33580 80042D80 1802A4AF */  sw         $a0, 0x218($sp)
    /* 33584 80042D84 23000634 */  ori        $a2, $zero, 0x23
    /* 33588 80042D88 30000334 */  ori        $v1, $zero, 0x30
endlabel sprintf

nonmatching SPRINTF_OBJ_90, 0x130

glabel SPRINTF_OBJ_90
    /* 3358C 80042D8C 4C02A48F */  lw         $a0, 0x24C($sp)
    /* 33590 80042D90 00000000 */  nop
    /* 33594 80042D94 01008224 */  addiu      $v0, $a0, 0x1
    /* 33598 80042D98 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 3359C 80042D9C 01008590 */  lbu        $a1, 0x1($a0)
    /* 335A0 80042DA0 00000000 */  nop
    /* 335A4 80042DA4 0600B614 */  bne        $a1, $s6, SPRINTF_OBJ_C4
    /* 335A8 80042DA8 00000000 */   nop
    /* 335AC 80042DAC 1002A28F */  lw         $v0, 0x210($sp)
    /* 335B0 80042DB0 00000000 */  nop
    /* 335B4 80042DB4 01004234 */  ori        $v0, $v0, 0x1
    /* 335B8 80042DB8 630B0108 */  j          SPRINTF_OBJ_90
    /* 335BC 80042DBC 1002A2AF */   sw        $v0, 0x210($sp)
  SPRINTF_OBJ_C4:
    /* 335C0 80042DC0 0600B514 */  bne        $a1, $s5, SPRINTF_OBJ_E0
    /* 335C4 80042DC4 00000000 */   nop
    /* 335C8 80042DC8 1002A28F */  lw         $v0, 0x210($sp)
    /* 335CC 80042DCC 00000000 */  nop
    /* 335D0 80042DD0 02004234 */  ori        $v0, $v0, 0x2
    /* 335D4 80042DD4 630B0108 */  j          SPRINTF_OBJ_90
    /* 335D8 80042DD8 1002A2AF */   sw        $v0, 0x210($sp)
  SPRINTF_OBJ_E0:
    /* 335DC 80042DDC 0300B414 */  bne        $a1, $s4, SPRINTF_OBJ_F0
    /* 335E0 80042DE0 00000000 */   nop
    /* 335E4 80042DE4 630B0108 */  j          SPRINTF_OBJ_90
    /* 335E8 80042DE8 1102A5A3 */   sb        $a1, 0x211($sp)
  SPRINTF_OBJ_F0:
    /* 335EC 80042DEC 0600A614 */  bne        $a1, $a2, SPRINTF_OBJ_10C
    /* 335F0 80042DF0 00000000 */   nop
    /* 335F4 80042DF4 1002A28F */  lw         $v0, 0x210($sp)
    /* 335F8 80042DF8 00000000 */  nop
    /* 335FC 80042DFC 04004234 */  ori        $v0, $v0, 0x4
    /* 33600 80042E00 630B0108 */  j          SPRINTF_OBJ_90
    /* 33604 80042E04 1002A2AF */   sw        $v0, 0x210($sp)
  SPRINTF_OBJ_10C:
    /* 33608 80042E08 0600A314 */  bne        $a1, $v1, SPRINTF_OBJ_128
    /* 3360C 80042E0C 2A000234 */   ori       $v0, $zero, 0x2A
    /* 33610 80042E10 1002A28F */  lw         $v0, 0x210($sp)
    /* 33614 80042E14 00000000 */  nop
    /* 33618 80042E18 08004234 */  ori        $v0, $v0, 0x8
    /* 3361C 80042E1C 630B0108 */  j          SPRINTF_OBJ_90
    /* 33620 80042E20 1002A2AF */   sw        $v0, 0x210($sp)
  SPRINTF_OBJ_128:
    /* 33624 80042E24 2200A214 */  bne        $a1, $v0, SPRINTF_OBJ_1B4
    /* 33628 80042E28 D0FFA224 */   addiu     $v0, $a1, -0x30
    /* 3362C 80042E2C 2002A38F */  lw         $v1, 0x220($sp)
    /* 33630 80042E30 00000000 */  nop
    /* 33634 80042E34 04006224 */  addiu      $v0, $v1, 0x4
    /* 33638 80042E38 2002A2AF */  sw         $v0, 0x220($sp)
    /* 3363C 80042E3C 0000628C */  lw         $v0, 0x0($v1)
    /* 33640 80042E40 00000000 */  nop
    /* 33644 80042E44 06004104 */  bgez       $v0, SPRINTF_OBJ_164
    /* 33648 80042E48 1402A2AF */   sw        $v0, 0x214($sp)
    /* 3364C 80042E4C 1002A38F */  lw         $v1, 0x210($sp)
    /* 33650 80042E50 23100200 */  negu       $v0, $v0
    /* 33654 80042E54 1402A2AF */  sw         $v0, 0x214($sp)
    /* 33658 80042E58 01006334 */  ori        $v1, $v1, 0x1
    /* 3365C 80042E5C 1002A3AF */  sw         $v1, 0x210($sp)
  SPRINTF_OBJ_164:
    /* 33660 80042E60 02008224 */  addiu      $v0, $a0, 0x2
    /* 33664 80042E64 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 33668 80042E68 02008590 */  lbu        $a1, 0x2($a0)
    /* 3366C 80042E6C AF0B0108 */  j          SPRINTF_OBJ_1C0
    /* 33670 80042E70 2E000234 */   ori       $v0, $zero, 0x2E
  SPRINTF_OBJ_178:
    /* 33674 80042E74 1402A38F */  lw         $v1, 0x214($sp)
    /* 33678 80042E78 00000000 */  nop
    /* 3367C 80042E7C 80100300 */  sll        $v0, $v1, 2
    /* 33680 80042E80 21104300 */  addu       $v0, $v0, $v1
    /* 33684 80042E84 40100200 */  sll        $v0, $v0, 1
    /* 33688 80042E88 D0FF4224 */  addiu      $v0, $v0, -0x30
    /* 3368C 80042E8C 21104500 */  addu       $v0, $v0, $a1
    /* 33690 80042E90 1402A2AF */  sw         $v0, 0x214($sp)
    /* 33694 80042E94 4C02A38F */  lw         $v1, 0x24C($sp)
    /* 33698 80042E98 00000000 */  nop
    /* 3369C 80042E9C 01006224 */  addiu      $v0, $v1, 0x1
    /* 336A0 80042EA0 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 336A4 80042EA4 01006590 */  lbu        $a1, 0x1($v1)
    /* 336A8 80042EA8 00000000 */  nop
    /* 336AC 80042EAC D0FFA224 */  addiu      $v0, $a1, -0x30
  SPRINTF_OBJ_1B4:
    /* 336B0 80042EB0 0A00422C */  sltiu      $v0, $v0, 0xA
    /* 336B4 80042EB4 EFFF4014 */  bnez       $v0, SPRINTF_OBJ_178
    /* 336B8 80042EB8 2E000234 */   ori       $v0, $zero, 0x2E
endlabel SPRINTF_OBJ_90

nonmatching SPRINTF_OBJ_1C0, 0xA0

glabel SPRINTF_OBJ_1C0
    /* 336BC 80042EBC 2F00A214 */  bne        $a1, $v0, SPRINTF_OBJ_280
    /* 336C0 80042EC0 00000000 */   nop
    /* 336C4 80042EC4 4C02A48F */  lw         $a0, 0x24C($sp)
    /* 336C8 80042EC8 00000000 */  nop
    /* 336CC 80042ECC 01008224 */  addiu      $v0, $a0, 0x1
    /* 336D0 80042ED0 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 336D4 80042ED4 01008590 */  lbu        $a1, 0x1($a0)
    /* 336D8 80042ED8 2A000234 */  ori        $v0, $zero, 0x2A
    /* 336DC 80042EDC 1C00A214 */  bne        $a1, $v0, SPRINTF_OBJ_254
    /* 336E0 80042EE0 D0FFA224 */   addiu     $v0, $a1, -0x30
    /* 336E4 80042EE4 2002A38F */  lw         $v1, 0x220($sp)
    /* 336E8 80042EE8 00000000 */  nop
    /* 336EC 80042EEC 04006224 */  addiu      $v0, $v1, 0x4
    /* 336F0 80042EF0 2002A2AF */  sw         $v0, 0x220($sp)
    /* 336F4 80042EF4 0000628C */  lw         $v0, 0x0($v1)
    /* 336F8 80042EF8 00000000 */  nop
    /* 336FC 80042EFC 1802A2AF */  sw         $v0, 0x218($sp)
    /* 33700 80042F00 02008224 */  addiu      $v0, $a0, 0x2
    /* 33704 80042F04 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 33708 80042F08 02008590 */  lbu        $a1, 0x2($a0)
    /* 3370C 80042F0C D70B0108 */  j          SPRINTF_OBJ_260
    /* 33710 80042F10 00000000 */   nop
  SPRINTF_OBJ_218:
    /* 33714 80042F14 1802A38F */  lw         $v1, 0x218($sp)
    /* 33718 80042F18 00000000 */  nop
    /* 3371C 80042F1C 80100300 */  sll        $v0, $v1, 2
    /* 33720 80042F20 21104300 */  addu       $v0, $v0, $v1
    /* 33724 80042F24 40100200 */  sll        $v0, $v0, 1
    /* 33728 80042F28 D0FF4224 */  addiu      $v0, $v0, -0x30
    /* 3372C 80042F2C 21104500 */  addu       $v0, $v0, $a1
    /* 33730 80042F30 1802A2AF */  sw         $v0, 0x218($sp)
    /* 33734 80042F34 4C02A38F */  lw         $v1, 0x24C($sp)
    /* 33738 80042F38 00000000 */  nop
    /* 3373C 80042F3C 01006224 */  addiu      $v0, $v1, 0x1
    /* 33740 80042F40 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 33744 80042F44 01006590 */  lbu        $a1, 0x1($v1)
    /* 33748 80042F48 00000000 */  nop
    /* 3374C 80042F4C D0FFA224 */  addiu      $v0, $a1, -0x30
  SPRINTF_OBJ_254:
    /* 33750 80042F50 0A00422C */  sltiu      $v0, $v0, 0xA
    /* 33754 80042F54 EFFF4014 */  bnez       $v0, SPRINTF_OBJ_218
    /* 33758 80042F58 00000000 */   nop
endlabel SPRINTF_OBJ_1C0

nonmatching SPRINTF_OBJ_260, 0x44

glabel SPRINTF_OBJ_260
    /* 3375C 80042F5C 1802A28F */  lw         $v0, 0x218($sp)
    /* 33760 80042F60 00000000 */  nop
    /* 33764 80042F64 05004004 */  bltz       $v0, SPRINTF_OBJ_280
    /* 33768 80042F68 00000000 */   nop
    /* 3376C 80042F6C 1002A28F */  lw         $v0, 0x210($sp)
    /* 33770 80042F70 00000000 */  nop
    /* 33774 80042F74 10004234 */  ori        $v0, $v0, 0x10
    /* 33778 80042F78 1002A2AF */  sw         $v0, 0x210($sp)
  SPRINTF_OBJ_280:
    /* 3377C 80042F7C 1002A38F */  lw         $v1, 0x210($sp)
    /* 33780 80042F80 00000000 */  nop
    /* 33784 80042F84 01006230 */  andi       $v0, $v1, 0x1
    /* 33788 80042F88 04004010 */  beqz       $v0, SPRINTF_OBJ_2A0
    /* 3378C 80042F8C 1002B127 */   addiu     $s1, $sp, 0x210
    /* 33790 80042F90 F7FF0224 */  addiu      $v0, $zero, -0x9
    /* 33794 80042F94 24106200 */  and        $v0, $v1, $v0
    /* 33798 80042F98 1002A2AF */  sw         $v0, 0x210($sp)
  SPRINTF_OBJ_2A0:
    /* 3379C 80042F9C B4FFA324 */  addiu      $v1, $a1, -0x4C
endlabel SPRINTF_OBJ_260

nonmatching SPRINTF_OBJ_2A4, 0x24

glabel SPRINTF_OBJ_2A4
    /* 337A0 80042FA0 2D00622C */  sltiu      $v0, $v1, 0x2D
    /* 337A4 80042FA4 2B014010 */  beqz       $v0, SPRINTF_OBJ_758
    /* 337A8 80042FA8 80100300 */   sll       $v0, $v1, 2
    /* 337AC 80042FAC 0180013C */  lui        $at, %hi(switchdataD_80010be4)
    /* 337B0 80042FB0 21082200 */  addu       $at, $at, $v0
    /* 337B4 80042FB4 E40B228C */  lw         $v0, %lo(switchdataD_80010be4)($at)
    /* 337B8 80042FB8 00000000 */  nop
    /* 337BC 80042FBC 08004000 */  jr         $v0
    /* 337C0 80042FC0 00000000 */   nop
endlabel SPRINTF_OBJ_2A4

nonmatching SPRINTF_OBJ_2C8, 0xC

glabel SPRINTF_OBJ_2C8
    /* 337C4 80042FC4 1002A28F */  lw         $v0, 0x210($sp)
    /* 337C8 80042FC8 FA0B0108 */  j          SPRINTF_OBJ_2EC
    /* 337CC 80042FCC 20004234 */   ori       $v0, $v0, 0x20
endlabel SPRINTF_OBJ_2C8

nonmatching SPRINTF_OBJ_2D4, 0xC

glabel SPRINTF_OBJ_2D4
    /* 337D0 80042FD0 1002A28F */  lw         $v0, 0x210($sp)
    /* 337D4 80042FD4 FA0B0108 */  j          SPRINTF_OBJ_2EC
    /* 337D8 80042FD8 40004234 */   ori       $v0, $v0, 0x40
endlabel SPRINTF_OBJ_2D4

nonmatching SPRINTF_OBJ_2E0, 0xC

glabel SPRINTF_OBJ_2E0
    /* 337DC 80042FDC 1002A28F */  lw         $v0, 0x210($sp)
    /* 337E0 80042FE0 00000000 */  nop
    /* 337E4 80042FE4 80004234 */  ori        $v0, $v0, 0x80
endlabel SPRINTF_OBJ_2E0

nonmatching SPRINTF_OBJ_2EC, 0x20

glabel SPRINTF_OBJ_2EC
    /* 337E8 80042FE8 1002A2AF */  sw         $v0, 0x210($sp)
    /* 337EC 80042FEC 4C02A38F */  lw         $v1, 0x24C($sp)
  func_80042FF0:
    /* 337F0 80042FF0 00000000 */  nop
    /* 337F4 80042FF4 01006224 */  addiu      $v0, $v1, 0x1
    /* 337F8 80042FF8 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 337FC 80042FFC 01006590 */  lbu        $a1, 0x1($v1)
    /* 33800 80043000 E80B0108 */  j          SPRINTF_OBJ_2A4
    /* 33804 80043004 B4FFA324 */   addiu     $v1, $a1, -0x4C
endlabel SPRINTF_OBJ_2EC

nonmatching SPRINTF_OBJ_30C, 0x50

glabel SPRINTF_OBJ_30C
    /* 33808 80043008 2002A38F */  lw         $v1, 0x220($sp)
    /* 3380C 8004300C 00000000 */  nop
    /* 33810 80043010 04006224 */  addiu      $v0, $v1, 0x4
    /* 33814 80043014 2002A2AF */  sw         $v0, 0x220($sp)
    /* 33818 80043018 0000648C */  lw         $a0, 0x0($v1)
    /* 3381C 8004301C 1002A38F */  lw         $v1, 0x210($sp)
    /* 33820 80043020 00000000 */  nop
    /* 33824 80043024 20006230 */  andi       $v0, $v1, 0x20
    /* 33828 80043028 02004010 */  beqz       $v0, SPRINTF_OBJ_338
    /* 3382C 8004302C 00140400 */   sll       $v0, $a0, 16
    /* 33830 80043030 03240200 */  sra        $a0, $v0, 16
  SPRINTF_OBJ_338:
    /* 33834 80043034 04008104 */  bgez       $a0, SPRINTF_OBJ_34C
    /* 33838 80043038 02006230 */   andi      $v0, $v1, 0x2
    /* 3383C 8004303C 23200400 */  negu       $a0, $a0
    /* 33840 80043040 210C0108 */  j          SPRINTF_OBJ_388
    /* 33844 80043044 1102B6A3 */   sb        $s6, 0x211($sp)
  SPRINTF_OBJ_34C:
    /* 33848 80043048 0E004010 */  beqz       $v0, SPRINTF_OBJ_388
    /* 3384C 8004304C 00000000 */   nop
    /* 33850 80043050 210C0108 */  j          SPRINTF_OBJ_388
    /* 33854 80043054 1102B5A3 */   sb        $s5, 0x211($sp)
endlabel SPRINTF_OBJ_30C

nonmatching SPRINTF_OBJ_35C, 0x2C

glabel SPRINTF_OBJ_35C
    /* 33858 80043058 2002A38F */  lw         $v1, 0x220($sp)
    /* 3385C 8004305C 00000000 */  nop
    /* 33860 80043060 04006224 */  addiu      $v0, $v1, 0x4
    /* 33864 80043064 2002A2AF */  sw         $v0, 0x220($sp)
    /* 33868 80043068 0000648C */  lw         $a0, 0x0($v1)
    /* 3386C 8004306C 1002A28F */  lw         $v0, 0x210($sp)
    /* 33870 80043070 00000000 */  nop
    /* 33874 80043074 20004230 */  andi       $v0, $v0, 0x20
    /* 33878 80043078 02004010 */  beqz       $v0, SPRINTF_OBJ_388
    /* 3387C 8004307C 1102A0A3 */   sb        $zero, 0x211($sp)
    /* 33880 80043080 FFFF8430 */  andi       $a0, $a0, 0xFFFF
endlabel SPRINTF_OBJ_35C

nonmatching SPRINTF_OBJ_388, 0xEC

glabel SPRINTF_OBJ_388
    /* 33884 80043084 1002A38F */  lw         $v1, 0x210($sp)
    /* 33888 80043088 00000000 */  nop
    /* 3388C 8004308C 10006230 */  andi       $v0, $v1, 0x10
    /* 33890 80043090 0F004014 */  bnez       $v0, SPRINTF_OBJ_3D4
    /* 33894 80043094 08006230 */   andi      $v0, $v1, 0x8
    /* 33898 80043098 08004010 */  beqz       $v0, SPRINTF_OBJ_3C0
    /* 3389C 8004309C 00000000 */   nop
    /* 338A0 800430A0 1402A38F */  lw         $v1, 0x214($sp)
    /* 338A4 800430A4 1102A293 */  lbu        $v0, 0x211($sp)
    /* 338A8 800430A8 00000000 */  nop
    /* 338AC 800430AC 03004010 */  beqz       $v0, SPRINTF_OBJ_3C0
    /* 338B0 800430B0 1802A3AF */   sw        $v1, 0x218($sp)
    /* 338B4 800430B4 FFFF6224 */  addiu      $v0, $v1, -0x1
    /* 338B8 800430B8 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_3C0:
    /* 338BC 800430BC 1802A28F */  lw         $v0, 0x218($sp)
    /* 338C0 800430C0 00000000 */  nop
    /* 338C4 800430C4 0200401C */  bgtz       $v0, SPRINTF_OBJ_3D4
    /* 338C8 800430C8 01000234 */   ori       $v0, $zero, 0x1
    /* 338CC 800430CC 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_3D4:
    /* 338D0 800430D0 10008010 */  beqz       $a0, SPRINTF_OBJ_418
    /* 338D4 800430D4 21800000 */   addu      $s0, $zero, $zero
    /* 338D8 800430D8 CCCC053C */  lui        $a1, (0xCCCCCCCD >> 16)
    /* 338DC 800430DC CDCCA534 */  ori        $a1, $a1, (0xCCCCCCCD & 0xFFFF)
  SPRINTF_OBJ_3E4:
    /* 338E0 800430E0 19008500 */  multu      $a0, $a1
    /* 338E4 800430E4 FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 338E8 800430E8 01001026 */  addiu      $s0, $s0, 0x1
    /* 338EC 800430EC 10180000 */  mfhi       $v1
    /* 338F0 800430F0 C2180300 */  srl        $v1, $v1, 3
    /* 338F4 800430F4 80100300 */  sll        $v0, $v1, 2
    /* 338F8 800430F8 21104300 */  addu       $v0, $v0, $v1
    /* 338FC 800430FC 40100200 */  sll        $v0, $v0, 1
    /* 33900 80043100 23108200 */  subu       $v0, $a0, $v0
    /* 33904 80043104 30004224 */  addiu      $v0, $v0, 0x30
    /* 33908 80043108 21206000 */  addu       $a0, $v1, $zero
    /* 3390C 8004310C F4FF8014 */  bnez       $a0, SPRINTF_OBJ_3E4
    /* 33910 80043110 000022A2 */   sb        $v0, 0x0($s1)
  SPRINTF_OBJ_418:
    /* 33914 80043114 1802A28F */  lw         $v0, 0x218($sp)
    /* 33918 80043118 00000000 */  nop
    /* 3391C 8004311C 2A100202 */  slt        $v0, $s0, $v0
    /* 33920 80043120 0A004010 */  beqz       $v0, SPRINTF_OBJ_450
    /* 33924 80043124 00000000 */   nop
    /* 33928 80043128 30000334 */  ori        $v1, $zero, 0x30
    /* 3392C 8004312C FFFF3126 */  addiu      $s1, $s1, -0x1
  SPRINTF_OBJ_434:
    /* 33930 80043130 000023A2 */  sb         $v1, 0x0($s1)
    /* 33934 80043134 1802A28F */  lw         $v0, 0x218($sp)
    /* 33938 80043138 01001026 */  addiu      $s0, $s0, 0x1
    /* 3393C 8004313C 2A100202 */  slt        $v0, $s0, $v0
    /* 33940 80043140 FBFF4014 */  bnez       $v0, SPRINTF_OBJ_434
    /* 33944 80043144 FFFF3126 */   addiu     $s1, $s1, -0x1
    /* 33948 80043148 01003126 */  addiu      $s1, $s1, 0x1
  SPRINTF_OBJ_450:
    /* 3394C 8004314C 1102A293 */  lbu        $v0, 0x211($sp)
    /* 33950 80043150 00000000 */  nop
    /* 33954 80043154 C5004010 */  beqz       $v0, SPRINTF_OBJ_770
    /* 33958 80043158 00000000 */   nop
    /* 3395C 8004315C FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33960 80043160 1102A293 */  lbu        $v0, 0x211($sp)
    /* 33964 80043164 01001026 */  addiu      $s0, $s0, 0x1
    /* 33968 80043168 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 3396C 8004316C 000022A2 */   sb        $v0, 0x0($s1)
endlabel SPRINTF_OBJ_388

nonmatching SPRINTF_OBJ_474, 0xF0

glabel SPRINTF_OBJ_474
    /* 33970 80043170 2002A38F */  lw         $v1, 0x220($sp)
    /* 33974 80043174 00000000 */  nop
    /* 33978 80043178 04006224 */  addiu      $v0, $v1, 0x4
    /* 3397C 8004317C 2002A2AF */  sw         $v0, 0x220($sp)
    /* 33980 80043180 0000648C */  lw         $a0, 0x0($v1)
    /* 33984 80043184 1002A38F */  lw         $v1, 0x210($sp)
    /* 33988 80043188 00000000 */  nop
    /* 3398C 8004318C 20006230 */  andi       $v0, $v1, 0x20
    /* 33990 80043190 02004010 */  beqz       $v0, SPRINTF_OBJ_4A0
    /* 33994 80043194 10006230 */   andi      $v0, $v1, 0x10
    /* 33998 80043198 FFFF8430 */  andi       $a0, $a0, 0xFFFF
  SPRINTF_OBJ_4A0:
    /* 3399C 8004319C 0B004014 */  bnez       $v0, SPRINTF_OBJ_4D0
    /* 339A0 800431A0 08006230 */   andi      $v0, $v1, 0x8
    /* 339A4 800431A4 04004010 */  beqz       $v0, SPRINTF_OBJ_4BC
    /* 339A8 800431A8 00000000 */   nop
    /* 339AC 800431AC 1402A28F */  lw         $v0, 0x214($sp)
    /* 339B0 800431B0 00000000 */  nop
    /* 339B4 800431B4 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_4BC:
    /* 339B8 800431B8 1802A28F */  lw         $v0, 0x218($sp)
    /* 339BC 800431BC 00000000 */  nop
    /* 339C0 800431C0 0200401C */  bgtz       $v0, SPRINTF_OBJ_4D0
    /* 339C4 800431C4 01000234 */   ori       $v0, $zero, 0x1
    /* 339C8 800431C8 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_4D0:
    /* 339CC 800431CC 08008010 */  beqz       $a0, SPRINTF_OBJ_4F4
    /* 339D0 800431D0 21800000 */   addu      $s0, $zero, $zero
  SPRINTF_OBJ_4D8:
    /* 339D4 800431D4 FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 339D8 800431D8 07008230 */  andi       $v0, $a0, 0x7
    /* 339DC 800431DC 30004224 */  addiu      $v0, $v0, 0x30
    /* 339E0 800431E0 000022A2 */  sb         $v0, 0x0($s1)
    /* 339E4 800431E4 C2200400 */  srl        $a0, $a0, 3
    /* 339E8 800431E8 FAFF8014 */  bnez       $a0, SPRINTF_OBJ_4D8
    /* 339EC 800431EC 01001026 */   addiu     $s0, $s0, 0x1
  SPRINTF_OBJ_4F4:
    /* 339F0 800431F0 1002A28F */  lw         $v0, 0x210($sp)
    /* 339F4 800431F4 00000000 */  nop
    /* 339F8 800431F8 04004230 */  andi       $v0, $v0, 0x4
    /* 339FC 800431FC 0A004010 */  beqz       $v0, SPRINTF_OBJ_52C
    /* 33A00 80043200 00000000 */   nop
    /* 33A04 80043204 08000012 */  beqz       $s0, SPRINTF_OBJ_52C
    /* 33A08 80043208 30000234 */   ori       $v0, $zero, 0x30
    /* 33A0C 8004320C 00002392 */  lbu        $v1, 0x0($s1)
    /* 33A10 80043210 00000000 */  nop
    /* 33A14 80043214 04006210 */  beq        $v1, $v0, SPRINTF_OBJ_52C
    /* 33A18 80043218 30000234 */   ori       $v0, $zero, 0x30
    /* 33A1C 8004321C FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33A20 80043220 000022A2 */  sb         $v0, 0x0($s1)
    /* 33A24 80043224 01001026 */  addiu      $s0, $s0, 0x1
  SPRINTF_OBJ_52C:
    /* 33A28 80043228 1802A28F */  lw         $v0, 0x218($sp)
    /* 33A2C 8004322C 00000000 */  nop
    /* 33A30 80043230 2A100202 */  slt        $v0, $s0, $v0
    /* 33A34 80043234 8D004010 */  beqz       $v0, SPRINTF_OBJ_770
    /* 33A38 80043238 30000334 */   ori       $v1, $zero, 0x30
    /* 33A3C 8004323C FFFF3126 */  addiu      $s1, $s1, -0x1
  SPRINTF_OBJ_544:
    /* 33A40 80043240 000023A2 */  sb         $v1, 0x0($s1)
    /* 33A44 80043244 1802A28F */  lw         $v0, 0x218($sp)
    /* 33A48 80043248 01001026 */  addiu      $s0, $s0, 0x1
    /* 33A4C 8004324C 2A100202 */  slt        $v0, $s0, $v0
    /* 33A50 80043250 FBFF4014 */  bnez       $v0, SPRINTF_OBJ_544
    /* 33A54 80043254 FFFF3126 */   addiu     $s1, $s1, -0x1
    /* 33A58 80043258 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33A5C 8004325C 01003126 */   addiu     $s1, $s1, 0x1
endlabel SPRINTF_OBJ_474

nonmatching SPRINTF_OBJ_564, 0x14

glabel SPRINTF_OBJ_564
    /* 33A60 80043260 1002A38F */  lw         $v1, 0x210($sp)
    /* 33A64 80043264 08000234 */  ori        $v0, $zero, 0x8
    /* 33A68 80043268 1802A2AF */  sw         $v0, 0x218($sp)
    /* 33A6C 8004326C 50006334 */  ori        $v1, $v1, 0x50
    /* 33A70 80043270 1002A3AF */  sw         $v1, 0x210($sp)
endlabel SPRINTF_OBJ_564

nonmatching SPRINTF_OBJ_578, 0x10

glabel SPRINTF_OBJ_578
    /* 33A74 80043274 0180073C */  lui        $a3, %hi(D_80010BBC)
    /* 33A78 80043278 BC0BE724 */  addiu      $a3, $a3, %lo(D_80010BBC)
    /* 33A7C 8004327C A30C0108 */  j          SPRINTF_OBJ_590
    /* 33A80 80043280 00000000 */   nop
endlabel SPRINTF_OBJ_578

nonmatching SPRINTF_OBJ_588, 0x8

glabel SPRINTF_OBJ_588
    /* 33A84 80043284 0180073C */  lui        $a3, %hi(D_80010BD0)
    /* 33A88 80043288 D00BE724 */  addiu      $a3, $a3, %lo(D_80010BD0)
endlabel SPRINTF_OBJ_588

nonmatching SPRINTF_OBJ_590, 0xF0

glabel SPRINTF_OBJ_590
    /* 33A8C 8004328C 2002A38F */  lw         $v1, 0x220($sp)
    /* 33A90 80043290 00000000 */  nop
    /* 33A94 80043294 04006224 */  addiu      $v0, $v1, 0x4
    /* 33A98 80043298 2002A2AF */  sw         $v0, 0x220($sp)
    /* 33A9C 8004329C 0000648C */  lw         $a0, 0x0($v1)
    /* 33AA0 800432A0 1002A38F */  lw         $v1, 0x210($sp)
    /* 33AA4 800432A4 00000000 */  nop
    /* 33AA8 800432A8 20006230 */  andi       $v0, $v1, 0x20
    /* 33AAC 800432AC 02004010 */  beqz       $v0, SPRINTF_OBJ_5BC
    /* 33AB0 800432B0 10006230 */   andi      $v0, $v1, 0x10
    /* 33AB4 800432B4 FFFF8430 */  andi       $a0, $a0, 0xFFFF
  SPRINTF_OBJ_5BC:
    /* 33AB8 800432B8 0D004014 */  bnez       $v0, SPRINTF_OBJ_5F4
    /* 33ABC 800432BC 08006230 */   andi      $v0, $v1, 0x8
    /* 33AC0 800432C0 06004010 */  beqz       $v0, SPRINTF_OBJ_5E0
    /* 33AC4 800432C4 04006230 */   andi      $v0, $v1, 0x4
    /* 33AC8 800432C8 1402A68F */  lw         $a2, 0x214($sp)
    /* 33ACC 800432CC 03004010 */  beqz       $v0, SPRINTF_OBJ_5E0
    /* 33AD0 800432D0 1802A6AF */   sw        $a2, 0x218($sp)
    /* 33AD4 800432D4 FEFFC224 */  addiu      $v0, $a2, -0x2
    /* 33AD8 800432D8 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_5E0:
    /* 33ADC 800432DC 1802A28F */  lw         $v0, 0x218($sp)
    /* 33AE0 800432E0 00000000 */  nop
    /* 33AE4 800432E4 0200401C */  bgtz       $v0, SPRINTF_OBJ_5F4
    /* 33AE8 800432E8 01000234 */   ori       $v0, $zero, 0x1
    /* 33AEC 800432EC 1802A2AF */  sw         $v0, 0x218($sp)
  SPRINTF_OBJ_5F4:
    /* 33AF0 800432F0 09008010 */  beqz       $a0, SPRINTF_OBJ_61C
    /* 33AF4 800432F4 21800000 */   addu      $s0, $zero, $zero
  SPRINTF_OBJ_5FC:
    /* 33AF8 800432F8 FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33AFC 800432FC 0F008230 */  andi       $v0, $a0, 0xF
    /* 33B00 80043300 02210400 */  srl        $a0, $a0, 4
    /* 33B04 80043304 2110E200 */  addu       $v0, $a3, $v0
    /* 33B08 80043308 00004290 */  lbu        $v0, 0x0($v0)
    /* 33B0C 8004330C 01001026 */  addiu      $s0, $s0, 0x1
    /* 33B10 80043310 F9FF8014 */  bnez       $a0, SPRINTF_OBJ_5FC
    /* 33B14 80043314 000022A2 */   sb        $v0, 0x0($s1)
  SPRINTF_OBJ_61C:
    /* 33B18 80043318 1802A28F */  lw         $v0, 0x218($sp)
    /* 33B1C 8004331C 00000000 */  nop
    /* 33B20 80043320 2A100202 */  slt        $v0, $s0, $v0
    /* 33B24 80043324 0A004010 */  beqz       $v0, SPRINTF_OBJ_654
    /* 33B28 80043328 00000000 */   nop
    /* 33B2C 8004332C 30000334 */  ori        $v1, $zero, 0x30
    /* 33B30 80043330 FFFF3126 */  addiu      $s1, $s1, -0x1
  SPRINTF_OBJ_638:
    /* 33B34 80043334 000023A2 */  sb         $v1, 0x0($s1)
    /* 33B38 80043338 1802A28F */  lw         $v0, 0x218($sp)
    /* 33B3C 8004333C 01001026 */  addiu      $s0, $s0, 0x1
    /* 33B40 80043340 2A100202 */  slt        $v0, $s0, $v0
    /* 33B44 80043344 FBFF4014 */  bnez       $v0, SPRINTF_OBJ_638
    /* 33B48 80043348 FFFF3126 */   addiu     $s1, $s1, -0x1
    /* 33B4C 8004334C 01003126 */  addiu      $s1, $s1, 0x1
  SPRINTF_OBJ_654:
    /* 33B50 80043350 1002A28F */  lw         $v0, 0x210($sp)
    /* 33B54 80043354 00000000 */  nop
    /* 33B58 80043358 04004230 */  andi       $v0, $v0, 0x4
    /* 33B5C 8004335C 43004010 */  beqz       $v0, SPRINTF_OBJ_770
    /* 33B60 80043360 30000234 */   ori       $v0, $zero, 0x30
    /* 33B64 80043364 FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33B68 80043368 000025A2 */  sb         $a1, 0x0($s1)
    /* 33B6C 8004336C FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33B70 80043370 02001026 */  addiu      $s0, $s0, 0x2
    /* 33B74 80043374 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33B78 80043378 000022A2 */   sb        $v0, 0x0($s1)
endlabel SPRINTF_OBJ_590

nonmatching SPRINTF_OBJ_680, 0x20

glabel SPRINTF_OBJ_680
    /* 33B7C 8004337C 2002A28F */  lw         $v0, 0x220($sp)
    /* 33B80 80043380 FFFF3126 */  addiu      $s1, $s1, -0x1
    /* 33B84 80043384 04004324 */  addiu      $v1, $v0, 0x4
    /* 33B88 80043388 2002A3AF */  sw         $v1, 0x220($sp)
    /* 33B8C 8004338C 00004290 */  lbu        $v0, 0x0($v0)
    /* 33B90 80043390 01001034 */  ori        $s0, $zero, 0x1
    /* 33B94 80043394 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33B98 80043398 000022A2 */   sb        $v0, 0x0($s1)
endlabel SPRINTF_OBJ_680

nonmatching SPRINTF_OBJ_6A0, 0x84

glabel SPRINTF_OBJ_6A0
    /* 33B9C 8004339C 2002A28F */  lw         $v0, 0x220($sp)
    /* 33BA0 800433A0 00000000 */  nop
    /* 33BA4 800433A4 04004324 */  addiu      $v1, $v0, 0x4
    /* 33BA8 800433A8 2002A3AF */  sw         $v1, 0x220($sp)
    /* 33BAC 800433AC 1002A38F */  lw         $v1, 0x210($sp)
    /* 33BB0 800433B0 0000518C */  lw         $s1, 0x0($v0)
    /* 33BB4 800433B4 04006230 */  andi       $v0, $v1, 0x4
    /* 33BB8 800433B8 0B004010 */  beqz       $v0, SPRINTF_OBJ_6EC
    /* 33BBC 800433BC 10006230 */   andi      $v0, $v1, 0x10
    /* 33BC0 800433C0 00003092 */  lbu        $s0, 0x0($s1)
    /* 33BC4 800433C4 29004010 */  beqz       $v0, SPRINTF_OBJ_770
    /* 33BC8 800433C8 01003126 */   addiu     $s1, $s1, 0x1
    /* 33BCC 800433CC 1802A38F */  lw         $v1, 0x218($sp)
    /* 33BD0 800433D0 00000000 */  nop
    /* 33BD4 800433D4 2A107000 */  slt        $v0, $v1, $s0
    /* 33BD8 800433D8 24004010 */  beqz       $v0, SPRINTF_OBJ_770
    /* 33BDC 800433DC 00000000 */   nop
    /* 33BE0 800433E0 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33BE4 800433E4 21806000 */   addu      $s0, $v1, $zero
  SPRINTF_OBJ_6EC:
    /* 33BE8 800433E8 05004014 */  bnez       $v0, SPRINTF_OBJ_704
    /* 33BEC 800433EC 21202002 */   addu      $a0, $s1, $zero
    /* 33BF0 800433F0 560D010C */  jal        strlen
    /* 33BF4 800433F4 21202002 */   addu      $a0, $s1, $zero
    /* 33BF8 800433F8 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33BFC 800433FC 21804000 */   addu      $s0, $v0, $zero
  SPRINTF_OBJ_704:
    /* 33C00 80043400 1802A68F */  lw         $a2, 0x218($sp)
    /* 33C04 80043404 5A0D010C */  jal        memchr
    /* 33C08 80043408 21280000 */   addu      $a1, $zero, $zero
    /* 33C0C 8004340C 17004014 */  bnez       $v0, SPRINTF_OBJ_770
    /* 33C10 80043410 23805100 */   subu      $s0, $v0, $s1
    /* 33C14 80043414 1802B08F */  lw         $s0, 0x218($sp)
    /* 33C18 80043418 1B0D0108 */  j          SPRINTF_OBJ_770
    /* 33C1C 8004341C 00000000 */   nop
endlabel SPRINTF_OBJ_6A0

nonmatching SPRINTF_OBJ_724, 0x34

glabel SPRINTF_OBJ_724
    /* 33C20 80043420 2002A28F */  lw         $v0, 0x220($sp)
    /* 33C24 80043424 00000000 */  nop
    /* 33C28 80043428 04004324 */  addiu      $v1, $v0, 0x4
    /* 33C2C 8004342C 2002A3AF */  sw         $v1, 0x220($sp)
    /* 33C30 80043430 1002A38F */  lw         $v1, 0x210($sp)
    /* 33C34 80043434 0000518C */  lw         $s1, 0x0($v0)
    /* 33C38 80043438 20006230 */  andi       $v0, $v1, 0x20
    /* 33C3C 8004343C 03004010 */  beqz       $v0, SPRINTF_OBJ_750
    /* 33C40 80043440 00000000 */   nop
    /* 33C44 80043444 400D0108 */  j          SPRINTF_OBJ_804
    /* 33C48 80043448 000032A6 */   sh        $s2, 0x0($s1)
  SPRINTF_OBJ_750:
    /* 33C4C 8004344C 400D0108 */  j          SPRINTF_OBJ_804
    /* 33C50 80043450 000032AE */   sw        $s2, 0x0($s1)
endlabel SPRINTF_OBJ_724

nonmatching SPRINTF_OBJ_758, 0x18

glabel SPRINTF_OBJ_758
    /* 33C54 80043454 25000234 */  ori        $v0, $zero, 0x25
    /* 33C58 80043458 3100A214 */  bne        $a1, $v0, SPRINTF_OBJ_824
    /* 33C5C 8004345C 21107202 */   addu      $v0, $s3, $s2
  SPRINTF_OBJ_764:
    /* 33C60 80043460 000045A0 */  sb         $a1, 0x0($v0)
    /* 33C64 80043464 400D0108 */  j          SPRINTF_OBJ_804
    /* 33C68 80043468 01005226 */   addiu     $s2, $s2, 0x1
endlabel SPRINTF_OBJ_758

nonmatching SPRINTF_OBJ_770, 0x94

glabel SPRINTF_OBJ_770
    /* 33C6C 8004346C 1402A28F */  lw         $v0, 0x214($sp)
    /* 33C70 80043470 00000000 */  nop
    /* 33C74 80043474 2A100202 */  slt        $v0, $s0, $v0
    /* 33C78 80043478 11004010 */  beqz       $v0, SPRINTF_OBJ_7C4
    /* 33C7C 8004347C 21207202 */   addu      $a0, $s3, $s2
    /* 33C80 80043480 1002A28F */  lw         $v0, 0x210($sp)
    /* 33C84 80043484 00000000 */  nop
    /* 33C88 80043488 01004230 */  andi       $v0, $v0, 0x1
    /* 33C8C 8004348C 0D004014 */  bnez       $v0, SPRINTF_OBJ_7C8
    /* 33C90 80043490 21282002 */   addu      $a1, $s1, $zero
    /* 33C94 80043494 21185302 */  addu       $v1, $s2, $s3
  SPRINTF_OBJ_79C:
    /* 33C98 80043498 000074A0 */  sb         $s4, 0x0($v1)
    /* 33C9C 8004349C 01006324 */  addiu      $v1, $v1, 0x1
    /* 33CA0 800434A0 1402A28F */  lw         $v0, 0x214($sp)
    /* 33CA4 800434A4 00000000 */  nop
    /* 33CA8 800434A8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 33CAC 800434AC 1402A2AF */  sw         $v0, 0x214($sp)
    /* 33CB0 800434B0 2A100202 */  slt        $v0, $s0, $v0
    /* 33CB4 800434B4 F8FF4014 */  bnez       $v0, SPRINTF_OBJ_79C
    /* 33CB8 800434B8 01005226 */   addiu     $s2, $s2, 0x1
    /* 33CBC 800434BC 21207202 */  addu       $a0, $s3, $s2
  SPRINTF_OBJ_7C4:
    /* 33CC0 800434C0 21282002 */  addu       $a1, $s1, $zero
  SPRINTF_OBJ_7C8:
    /* 33CC4 800434C4 5E0D010C */  jal        memmove
    /* 33CC8 800434C8 21300002 */   addu      $a2, $s0, $zero
    /* 33CCC 800434CC 1402A28F */  lw         $v0, 0x214($sp)
    /* 33CD0 800434D0 00000000 */  nop
    /* 33CD4 800434D4 2A100202 */  slt        $v0, $s0, $v0
    /* 33CD8 800434D8 09004010 */  beqz       $v0, SPRINTF_OBJ_804
    /* 33CDC 800434DC 21905002 */   addu      $s2, $s2, $s0
    /* 33CE0 800434E0 21185302 */  addu       $v1, $s2, $s3
  SPRINTF_OBJ_7E8:
    /* 33CE4 800434E4 000074A0 */  sb         $s4, 0x0($v1)
    /* 33CE8 800434E8 01006324 */  addiu      $v1, $v1, 0x1
    /* 33CEC 800434EC 1402A28F */  lw         $v0, 0x214($sp)
    /* 33CF0 800434F0 01001026 */  addiu      $s0, $s0, 0x1
    /* 33CF4 800434F4 2A100202 */  slt        $v0, $s0, $v0
    /* 33CF8 800434F8 FAFF4014 */  bnez       $v0, SPRINTF_OBJ_7E8
    /* 33CFC 800434FC 01005226 */   addiu     $s2, $s2, 0x1
endlabel SPRINTF_OBJ_770

nonmatching SPRINTF_OBJ_804, 0x58

glabel SPRINTF_OBJ_804
    /* 33D00 80043500 4C02A38F */  lw         $v1, 0x24C($sp)
    /* 33D04 80043504 00000000 */  nop
    /* 33D08 80043508 01006224 */  addiu      $v0, $v1, 0x1
    /* 33D0C 8004350C 4C02A2AF */  sw         $v0, 0x24C($sp)
    /* 33D10 80043510 01006590 */  lbu        $a1, 0x1($v1)
    /* 33D14 80043514 00000000 */  nop
    /* 33D18 80043518 10FEA014 */  bnez       $a1, SPRINTF_OBJ_60
    /* 33D1C 8004351C 25000234 */   ori       $v0, $zero, 0x25
  SPRINTF_OBJ_824:
    /* 33D20 80043520 21107202 */  addu       $v0, $s3, $s2
    /* 33D24 80043524 000040A0 */  sb         $zero, 0x0($v0)
    /* 33D28 80043528 21104002 */  addu       $v0, $s2, $zero
    /* 33D2C 8004352C 4402BF8F */  lw         $ra, 0x244($sp)
    /* 33D30 80043530 4002B68F */  lw         $s6, 0x240($sp)
    /* 33D34 80043534 3C02B58F */  lw         $s5, 0x23C($sp)
    /* 33D38 80043538 3802B48F */  lw         $s4, 0x238($sp)
    /* 33D3C 8004353C 3402B38F */  lw         $s3, 0x234($sp)
    /* 33D40 80043540 3002B28F */  lw         $s2, 0x230($sp)
    /* 33D44 80043544 2C02B18F */  lw         $s1, 0x22C($sp)
    /* 33D48 80043548 2802B08F */  lw         $s0, 0x228($sp)
    /* 33D4C 8004354C 4802BD27 */  addiu      $sp, $sp, 0x248
    /* 33D50 80043550 0800E003 */  jr         $ra
    /* 33D54 80043554 00000000 */   nop
endlabel SPRINTF_OBJ_804

nonmatching strlen, 0xC

glabel strlen
    /* 33D58 80043558 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 33D5C 8004355C 08004001 */  jr         $t2
    /* 33D60 80043560 1B000924 */   addiu     $t1, $zero, 0x1B
endlabel strlen
    /* 33D64 80043564 00000000 */  nop

nonmatching memchr, 0xC

glabel memchr
    /* 33D68 80043568 A0000A24 */  addiu      $t2, $zero, 0xA0
    /* 33D6C 8004356C 08004001 */  jr         $t2
    /* 33D70 80043570 2E000924 */   addiu     $t1, $zero, 0x2E
endlabel memchr
    /* 33D74 80043574 00000000 */  nop

nonmatching memmove, 0x64

glabel memmove
    /* 33D78 80043578 2B108500 */  sltu       $v0, $a0, $a1
    /* 33D7C 8004357C 0E004014 */  bnez       $v0, MEMMOVE_OBJ_40
    /* 33D80 80043580 2110C000 */   addu      $v0, $a2, $zero
    /* 33D84 80043584 15004018 */  blez       $v0, MEMMOVE_OBJ_64
    /* 33D88 80043588 FFFFC624 */   addiu     $a2, $a2, -0x1
    /* 33D8C 8004358C 2138C400 */  addu       $a3, $a2, $a0
    /* 33D90 80043590 2128C500 */  addu       $a1, $a2, $a1
  MEMMOVE_OBJ_1C:
    /* 33D94 80043594 0000A290 */  lbu        $v0, 0x0($a1)
    /* 33D98 80043598 FFFFA524 */  addiu      $a1, $a1, -0x1
    /* 33D9C 8004359C 2118C000 */  addu       $v1, $a2, $zero
    /* 33DA0 800435A0 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* 33DA4 800435A4 0000E2A0 */  sb         $v0, 0x0($a3)
    /* 33DA8 800435A8 FAFF601C */  bgtz       $v1, MEMMOVE_OBJ_1C
    /* 33DAC 800435AC FFFFE724 */   addiu     $a3, $a3, -0x1
    /* 33DB0 800435B0 770D0108 */  j          MEMMOVE_OBJ_64
    /* 33DB4 800435B4 00000000 */   nop
  MEMMOVE_OBJ_40:
    /* 33DB8 800435B8 08004018 */  blez       $v0, MEMMOVE_OBJ_64
    /* 33DBC 800435BC FFFFC624 */   addiu     $a2, $a2, -0x1
  MEMMOVE_OBJ_48:
    /* 33DC0 800435C0 0000A290 */  lbu        $v0, 0x0($a1)
    /* 33DC4 800435C4 0100A524 */  addiu      $a1, $a1, 0x1
    /* 33DC8 800435C8 2118C000 */  addu       $v1, $a2, $zero
    /* 33DCC 800435CC FFFFC624 */  addiu      $a2, $a2, -0x1
    /* 33DD0 800435D0 000082A0 */  sb         $v0, 0x0($a0)
    /* 33DD4 800435D4 FAFF601C */  bgtz       $v1, MEMMOVE_OBJ_48
    /* 33DD8 800435D8 01008424 */   addiu     $a0, $a0, 0x1
endlabel memmove

nonmatching MEMMOVE_OBJ_64, 0xF4

glabel MEMMOVE_OBJ_64
    /* 33DDC 800435DC 0800E003 */  jr         $ra
    /* 33DE0 800435E0 21108000 */   addu      $v0, $a0, $zero
    /* 33DE4 800435E4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 33DE8 800435E8 2400B3AF */  sw         $s3, 0x24($sp)
    /* 33DEC 800435EC 4000B38F */  lw         $s3, 0x40($sp)
    /* 33DF0 800435F0 4400A38F */  lw         $v1, 0x44($sp)
    /* 33DF4 800435F4 4800A28F */  lw         $v0, 0x48($sp)
    /* 33DF8 800435F8 21408000 */  addu       $t0, $a0, $zero
    /* 33DFC 800435FC 1800B0AF */  sw         $s0, 0x18($sp)
    /* 33E00 80043600 2180A000 */  addu       $s0, $a1, $zero
    /* 33E04 80043604 2000B2AF */  sw         $s2, 0x20($sp)
    /* 33E08 80043608 2190C000 */  addu       $s2, $a2, $zero
    /* 33E0C 8004360C 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 33E10 80043610 2188E000 */  addu       $s1, $a3, $zero
    /* 33E14 80043614 2800BFAF */  sw         $ra, 0x28($sp)
    /* 33E18 80043618 1000B1A7 */  sh         $s1, 0x10($sp)
    /* 33E1C 8004361C 1600A2A7 */  sh         $v0, 0x16($sp)
    /* 33E20 80043620 01000234 */  ori        $v0, $zero, 0x1
    /* 33E24 80043624 13000212 */  beq        $s0, $v0, .L80043674
    /* 33E28 80043628 1200B3A7 */   sh        $s3, 0x12($sp)
    /* 33E2C 8004362C 0200022A */  slti       $v0, $s0, 0x2
    /* 33E30 80043630 05004010 */  beqz       $v0, .L80043648
    /* 33E34 80043634 00000000 */   nop
    /* 33E38 80043638 08000012 */  beqz       $s0, .L8004365C
    /* 33E3C 8004363C 1000A427 */   addiu     $a0, $sp, 0x10
    /* 33E40 80043640 A40D0108 */  j          .L80043690
    /* 33E44 80043644 00000000 */   nop
  .L80043648:
    /* 33E48 80043648 02000234 */  ori        $v0, $zero, 0x2
    /* 33E4C 8004364C 0E000212 */  beq        $s0, $v0, .L80043688
    /* 33E50 80043650 1000A427 */   addiu     $a0, $sp, 0x10
    /* 33E54 80043654 A40D0108 */  j          .L80043690
    /* 33E58 80043658 00000000 */   nop
  .L8004365C:
    /* 33E5C 8004365C 02006104 */  bgez       $v1, .L80043668
    /* 33E60 80043660 21106000 */   addu      $v0, $v1, $zero
    /* 33E64 80043664 03006224 */  addiu      $v0, $v1, 0x3
  .L80043668:
    /* 33E68 80043668 83100200 */  sra        $v0, $v0, 2
    /* 33E6C 8004366C A30D0108 */  j          .L8004368C
    /* 33E70 80043670 1400A2A7 */   sh        $v0, 0x14($sp)
  .L80043674:
    /* 33E74 80043674 C2170300 */  srl        $v0, $v1, 31
    /* 33E78 80043678 21106200 */  addu       $v0, $v1, $v0
    /* 33E7C 8004367C 43100200 */  sra        $v0, $v0, 1
    /* 33E80 80043680 A30D0108 */  j          .L8004368C
    /* 33E84 80043684 1400A2A7 */   sh        $v0, 0x14($sp)
  .L80043688:
    /* 33E88 80043688 1400A3A7 */  sh         $v1, 0x14($sp)
  .L8004368C:
    /* 33E8C 8004368C 1000A427 */  addiu      $a0, $sp, 0x10
  .L80043690:
    /* 33E90 80043690 BF0F010C */  jal        func_80043EFC
    /* 33E94 80043694 21280001 */   addu      $a1, $t0, $zero
    /* 33E98 80043698 21200002 */  addu       $a0, $s0, $zero
    /* 33E9C 8004369C 21284002 */  addu       $a1, $s2, $zero
    /* 33EA0 800436A0 21302002 */  addu       $a2, $s1, $zero
    /* 33EA4 800436A4 1A19010C */  jal        func_80046468
    /* 33EA8 800436A8 21386002 */   addu      $a3, $s3, $zero
    /* 33EAC 800436AC FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 33EB0 800436B0 2800BF8F */  lw         $ra, 0x28($sp)
    /* 33EB4 800436B4 2400B38F */  lw         $s3, 0x24($sp)
    /* 33EB8 800436B8 2000B28F */  lw         $s2, 0x20($sp)
    /* 33EBC 800436BC 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 33EC0 800436C0 1800B08F */  lw         $s0, 0x18($sp)
    /* 33EC4 800436C4 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 33EC8 800436C8 0800E003 */  jr         $ra
    /* 33ECC 800436CC 00000000 */   nop
endlabel MEMMOVE_OBJ_64

nonmatching func_800436D0, 0x68

glabel func_800436D0
    /* 33ED0 800436D0 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 33ED4 800436D4 21108000 */  addu       $v0, $a0, $zero
    /* 33ED8 800436D8 1800B0AF */  sw         $s0, 0x18($sp)
    /* 33EDC 800436DC 2180A000 */  addu       $s0, $a1, $zero
    /* 33EE0 800436E0 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 33EE4 800436E4 2188C000 */  addu       $s1, $a2, $zero
    /* 33EE8 800436E8 1000A427 */  addiu      $a0, $sp, 0x10
    /* 33EEC 800436EC 21284000 */  addu       $a1, $v0, $zero
    /* 33EF0 800436F0 00010234 */  ori        $v0, $zero, 0x100
    /* 33EF4 800436F4 1400A2A7 */  sh         $v0, 0x14($sp)
    /* 33EF8 800436F8 01000234 */  ori        $v0, $zero, 0x1
    /* 33EFC 800436FC 2000BFAF */  sw         $ra, 0x20($sp)
    /* 33F00 80043700 1000B0A7 */  sh         $s0, 0x10($sp)
    /* 33F04 80043704 1200B1A7 */  sh         $s1, 0x12($sp)
    /* 33F08 80043708 BF0F010C */  jal        func_80043EFC
    /* 33F0C 8004370C 1600A2A7 */   sh        $v0, 0x16($sp)
    /* 33F10 80043710 21200002 */  addu       $a0, $s0, $zero
    /* 33F14 80043714 4C19010C */  jal        func_80046530
    /* 33F18 80043718 21282002 */   addu      $a1, $s1, $zero
    /* 33F1C 8004371C FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* 33F20 80043720 2000BF8F */  lw         $ra, 0x20($sp)
    /* 33F24 80043724 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 33F28 80043728 1800B08F */  lw         $s0, 0x18($sp)
    /* 33F2C 8004372C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 33F30 80043730 0800E003 */  jr         $ra
    /* 33F34 80043734 00000000 */   nop
endlabel func_800436D0

nonmatching func_80043738, 0xC0

glabel func_80043738
    /* 33F38 80043738 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 33F3C 8004373C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 33F40 80043740 3800B38F */  lw         $s3, 0x38($sp)
    /* 33F44 80043744 2000B4AF */  sw         $s4, 0x20($sp)
    /* 33F48 80043748 21A08000 */  addu       $s4, $a0, $zero
    /* 33F4C 8004374C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 33F50 80043750 2188A000 */  addu       $s1, $a1, $zero
    /* 33F54 80043754 1800B2AF */  sw         $s2, 0x18($sp)
    /* 33F58 80043758 2190C000 */  addu       $s2, $a2, $zero
    /* 33F5C 8004375C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 33F60 80043760 2400BFAF */  sw         $ra, 0x24($sp)
    /* 33F64 80043764 ADF6000C */  jal        func_8003DAB4
    /* 33F68 80043768 2180E000 */   addu      $s0, $a3, $zero
    /* 33F6C 8004376C 01000234 */  ori        $v0, $zero, 0x1
    /* 33F70 80043770 000091A6 */  sh         $s1, 0x0($s4)
    /* 33F74 80043774 020092A6 */  sh         $s2, 0x2($s4)
    /* 33F78 80043778 040090A6 */  sh         $s0, 0x4($s4)
    /* 33F7C 8004377C 0C0080A6 */  sh         $zero, 0xC($s4)
    /* 33F80 80043780 0E0080A6 */  sh         $zero, 0xE($s4)
    /* 33F84 80043784 100080A6 */  sh         $zero, 0x10($s4)
    /* 33F88 80043788 120080A6 */  sh         $zero, 0x12($s4)
    /* 33F8C 8004378C 190080A2 */  sb         $zero, 0x19($s4)
    /* 33F90 80043790 1A0080A2 */  sb         $zero, 0x1A($s4)
    /* 33F94 80043794 1B0080A2 */  sb         $zero, 0x1B($s4)
    /* 33F98 80043798 160082A2 */  sb         $v0, 0x16($s4)
    /* 33F9C 8004379C 170080A2 */  sb         $zero, 0x17($s4)
    /* 33FA0 800437A0 080091A6 */  sh         $s1, 0x8($s4)
    /* 33FA4 800437A4 0A0092A6 */  sh         $s2, 0xA($s4)
    /* 33FA8 800437A8 EF0E010C */  jal        func_80043BBC
    /* 33FAC 800437AC 060093A6 */   sh        $s3, 0x6($s4)
    /* 33FB0 800437B0 01000334 */  ori        $v1, $zero, 0x1
    /* 33FB4 800437B4 04004310 */  beq        $v0, $v1, .L800437C8
    /* 33FB8 800437B8 21108002 */   addu      $v0, $s4, $zero
    /* 33FBC 800437BC EF0E010C */  jal        func_80043BBC
    /* 33FC0 800437C0 00000000 */   nop
    /* 33FC4 800437C4 21108002 */  addu       $v0, $s4, $zero
  .L800437C8:
    /* 33FC8 800437C8 0A000334 */  ori        $v1, $zero, 0xA
    /* 33FCC 800437CC 140043A4 */  sh         $v1, 0x14($v0)
    /* 33FD0 800437D0 180040A0 */  sb         $zero, 0x18($v0)
    /* 33FD4 800437D4 2400BF8F */  lw         $ra, 0x24($sp)
    /* 33FD8 800437D8 2000B48F */  lw         $s4, 0x20($sp)
    /* 33FDC 800437DC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 33FE0 800437E0 1800B28F */  lw         $s2, 0x18($sp)
    /* 33FE4 800437E4 1400B18F */  lw         $s1, 0x14($sp)
    /* 33FE8 800437E8 1000B08F */  lw         $s0, 0x10($sp)
    /* 33FEC 800437EC 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 33FF0 800437F0 0800E003 */  jr         $ra
    /* 33FF4 800437F4 00000000 */   nop
endlabel func_80043738

nonmatching func_800437F8, 0x3C

glabel func_800437F8
    /* 33FF8 800437F8 1000A38F */  lw         $v1, 0x10($sp)
    /* 33FFC 800437FC 21108000 */  addu       $v0, $a0, $zero
    /* 34000 80043800 000045A4 */  sh         $a1, 0x0($v0)
    /* 34004 80043804 020046A4 */  sh         $a2, 0x2($v0)
    /* 34008 80043808 040047A4 */  sh         $a3, 0x4($v0)
    /* 3400C 8004380C 080040A4 */  sh         $zero, 0x8($v0)
    /* 34010 80043810 0A0040A4 */  sh         $zero, 0xA($v0)
    /* 34014 80043814 0C0040A4 */  sh         $zero, 0xC($v0)
    /* 34018 80043818 0E0040A4 */  sh         $zero, 0xE($v0)
    /* 3401C 8004381C 110040A0 */  sb         $zero, 0x11($v0)
    /* 34020 80043820 100040A0 */  sb         $zero, 0x10($v0)
    /* 34024 80043824 130040A0 */  sb         $zero, 0x13($v0)
    /* 34028 80043828 120040A0 */  sb         $zero, 0x12($v0)
    /* 3402C 8004382C 0800E003 */  jr         $ra
    /* 34030 80043830 060043A4 */   sh        $v1, 0x6($v0)
endlabel func_800437F8
