.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80043B10, 0xAC

glabel func_80043B10
    /* 34310 80043B10 0680023C */  lui        $v0, %hi(D_80062BB6)
    /* 34314 80043B14 B62B4290 */  lbu        $v0, %lo(D_80062BB6)($v0)
    /* 34318 80043B18 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3431C 80043B1C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 34320 80043B20 1400B1AF */  sw         $s1, 0x14($sp)
    /* 34324 80043B24 0680113C */  lui        $s1, %hi(D_80062BB5)
    /* 34328 80043B28 B52B3126 */  addiu      $s1, $s1, %lo(D_80062BB5)
    /* 3432C 80043B2C 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 34330 80043B30 1800B2AF */  sw         $s2, 0x18($sp)
    /* 34334 80043B34 00003292 */  lbu        $s2, 0x0($s1)
    /* 34338 80043B38 0200422C */  sltiu      $v0, $v0, 0x2
    /* 3433C 80043B3C 08004014 */  bnez       $v0, .L80043B60
    /* 34340 80043B40 21808000 */   addu      $s0, $a0, $zero
    /* 34344 80043B44 0180043C */  lui        $a0, %hi(D_80010D44)
    /* 34348 80043B48 440D8424 */  addiu      $a0, $a0, %lo(D_80010D44)
    /* 3434C 80043B4C 0680023C */  lui        $v0, %hi(D_80062BB0)
    /* 34350 80043B50 B02B428C */  lw         $v0, %lo(D_80062BB0)($v0)
    /* 34354 80043B54 00000000 */  nop
    /* 34358 80043B58 09F84000 */  jalr       $v0
    /* 3435C 80043B5C 21280002 */   addu      $a1, $s0, $zero
  .L80043B60:
    /* 34360 80043B60 00002292 */  lbu        $v0, 0x0($s1)
    /* 34364 80043B64 00000000 */  nop
    /* 34368 80043B68 0D000212 */  beq        $s0, $v0, .L80043BA0
    /* 3436C 80043B6C 21104002 */   addu      $v0, $s2, $zero
    /* 34370 80043B70 0680023C */  lui        $v0, %hi(D_80062BAC)
    /* 34374 80043B74 AC2B428C */  lw         $v0, %lo(D_80062BAC)($v0)
    /* 34378 80043B78 00000000 */  nop
    /* 3437C 80043B7C 3400428C */  lw         $v0, 0x34($v0)
    /* 34380 80043B80 00000000 */  nop
    /* 34384 80043B84 09F84000 */  jalr       $v0
    /* 34388 80043B88 01000434 */   ori       $a0, $zero, 0x1
    /* 3438C 80043B8C 02000434 */  ori        $a0, $zero, 0x2
    /* 34390 80043B90 21280000 */  addu       $a1, $zero, $zero
    /* 34394 80043B94 07F4000C */  jal        DMACallback
    /* 34398 80043B98 000030A2 */   sb        $s0, 0x0($s1)
    /* 3439C 80043B9C 21104002 */  addu       $v0, $s2, $zero
  .L80043BA0:
    /* 343A0 80043BA0 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 343A4 80043BA4 1800B28F */  lw         $s2, 0x18($sp)
    /* 343A8 80043BA8 1400B18F */  lw         $s1, 0x14($sp)
    /* 343AC 80043BAC 1000B08F */  lw         $s0, 0x10($sp)
    /* 343B0 80043BB0 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 343B4 80043BB4 0800E003 */  jr         $ra
    /* 343B8 80043BB8 00000000 */   nop
endlabel func_80043B10

nonmatching func_80043BBC, 0x10

glabel func_80043BBC
    /* 343BC 80043BBC 0680023C */  lui        $v0, %hi(D_80062BB4)
    /* 343C0 80043BC0 B42B4290 */  lbu        $v0, %lo(D_80062BB4)($v0)
    /* 343C4 80043BC4 0800E003 */  jr         $ra
    /* 343C8 80043BC8 00000000 */   nop
endlabel func_80043BBC

nonmatching func_80043BCC, 0x10

glabel func_80043BCC
    /* 343CC 80043BCC 0680023C */  lui        $v0, %hi(D_80062BB6)
    /* 343D0 80043BD0 B62B4290 */  lbu        $v0, %lo(D_80062BB6)($v0)
    /* 343D4 80043BD4 0800E003 */  jr         $ra
    /* 343D8 80043BD8 00000000 */   nop
endlabel func_80043BCC

nonmatching func_80043BDC, 0x5C

glabel func_80043BDC
    /* 343DC 80043BDC 0680023C */  lui        $v0, %hi(D_80062BB6)
    /* 343E0 80043BE0 B62B4290 */  lbu        $v0, %lo(D_80062BB6)($v0)
    /* 343E4 80043BE4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 343E8 80043BE8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 343EC 80043BEC 21808000 */  addu       $s0, $a0, $zero
    /* 343F0 80043BF0 0200422C */  sltiu      $v0, $v0, 0x2
    /* 343F4 80043BF4 07004014 */  bnez       $v0, .L80043C14
    /* 343F8 80043BF8 1400BFAF */   sw        $ra, 0x14($sp)
    /* 343FC 80043BFC 0680023C */  lui        $v0, %hi(D_80062BB0)
    /* 34400 80043C00 B02B428C */  lw         $v0, %lo(D_80062BB0)($v0)
    /* 34404 80043C04 0180043C */  lui        $a0, %hi(D_80010D58)
    /* 34408 80043C08 580D8424 */  addiu      $a0, $a0, %lo(D_80010D58)
    /* 3440C 80043C0C 09F84000 */  jalr       $v0
    /* 34410 80043C10 21280002 */   addu      $a1, $s0, $zero
  .L80043C14:
    /* 34414 80043C14 0680023C */  lui        $v0, %hi(D_80062BC0)
    /* 34418 80043C18 C02B428C */  lw         $v0, %lo(D_80062BC0)($v0)
    /* 3441C 80043C1C 0680013C */  lui        $at, %hi(D_80062BC0)
    /* 34420 80043C20 C02B30AC */  sw         $s0, %lo(D_80062BC0)($at)
    /* 34424 80043C24 1400BF8F */  lw         $ra, 0x14($sp)
    /* 34428 80043C28 1000B08F */  lw         $s0, 0x10($sp)
    /* 3442C 80043C2C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 34430 80043C30 0800E003 */  jr         $ra
    /* 34434 80043C34 00000000 */   nop
endlabel func_80043BDC
