.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80033C38, 0x40

glabel func_80033C38
    /* 24438 80033C38 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2443C 80033C3C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24440 80033C40 30D0000C */  jal        func_800340C0
    /* 24444 80033C44 00000000 */   nop
  .L80033C48:
    /* 24448 80033C48 D4D2000C */  jal        func_80034B50
    /* 2444C 80033C4C 00000000 */   nop
    /* 24450 80033C50 FDFF4014 */  bnez       $v0, .L80033C48
    /* 24454 80033C54 00000000 */   nop
    /* 24458 80033C58 2AF7000C */  jal        func_8003DCA8
    /* 2445C 80033C5C 00000000 */   nop
    /* 24460 80033C60 0FF7000C */  jal        func_8003DC3C
    /* 24464 80033C64 21200000 */   addu      $a0, $zero, $zero
    /* 24468 80033C68 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2446C 80033C6C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24470 80033C70 0800E003 */  jr         $ra
    /* 24474 80033C74 00000000 */   nop
endlabel func_80033C38

nonmatching func_80033C78, 0x78

glabel func_80033C78
    /* 24478 80033C78 0A80023C */  lui        $v0, %hi(D_8009A218)
    /* 2447C 80033C7C 18A2428C */  lw         $v0, %lo(D_8009A218)($v0)
    /* 24480 80033C80 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24484 80033C84 01004230 */  andi       $v0, $v0, 0x1
    /* 24488 80033C88 07004010 */  beqz       $v0, .L80033CA8
    /* 2448C 80033C8C 1000BFAF */   sw        $ra, 0x10($sp)
    /* 24490 80033C90 8C0184A3 */  sb         $a0, %gp_rel(D_80062E84)($gp)
    /* 24494 80033C94 8D0185A3 */  sb         $a1, %gp_rel(D_80062E85)($gp)
    /* 24498 80033C98 8E0186A3 */  sb         $a2, %gp_rel(D_80062E86)($gp)
    /* 2449C 80033C9C 8F0187A3 */  sb         $a3, %gp_rel(D_80062E87)($gp)
    /* 244A0 80033CA0 34CF0008 */  j          .L80033CD0
    /* 244A4 80033CA4 00000000 */   nop
  .L80033CA8:
    /* 244A8 80033CA8 C2170400 */  srl        $v0, $a0, 31
    /* 244AC 80033CAC 21108200 */  addu       $v0, $a0, $v0
    /* 244B0 80033CB0 43100200 */  sra        $v0, $v0, 1
    /* 244B4 80033CB4 8C0182A3 */  sb         $v0, %gp_rel(D_80062E84)($gp)
    /* 244B8 80033CB8 8D0182A3 */  sb         $v0, %gp_rel(D_80062E85)($gp)
    /* 244BC 80033CBC C2170600 */  srl        $v0, $a2, 31
    /* 244C0 80033CC0 2110C200 */  addu       $v0, $a2, $v0
    /* 244C4 80033CC4 43100200 */  sra        $v0, $v0, 1
    /* 244C8 80033CC8 8E0182A3 */  sb         $v0, %gp_rel(D_80062E86)($gp)
    /* 244CC 80033CCC 8F0182A3 */  sb         $v0, %gp_rel(D_80062E87)($gp)
  .L80033CD0:
    /* 244D0 80033CD0 0680043C */  lui        $a0, %hi(D_80062E84)
    /* 244D4 80033CD4 842E8424 */  addiu      $a0, $a0, %lo(D_80062E84)
    /* 244D8 80033CD8 5AF8000C */  jal        func_8003E168
    /* 244DC 80033CDC 00000000 */   nop
    /* 244E0 80033CE0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 244E4 80033CE4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 244E8 80033CE8 0800E003 */  jr         $ra
    /* 244EC 80033CEC 00000000 */   nop
endlabel func_80033C78

nonmatching func_80033CF0, 0xF4

glabel func_80033CF0
    /* 244F0 80033CF0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 244F4 80033CF4 2800B6AF */  sw         $s6, 0x28($sp)
    /* 244F8 80033CF8 4000B68F */  lw         $s6, 0x40($sp)
    /* 244FC 80033CFC 2400B5AF */  sw         $s5, 0x24($sp)
    /* 24500 80033D00 21A88000 */  addu       $s5, $a0, $zero
    /* 24504 80033D04 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24508 80033D08 2188A000 */  addu       $s1, $a1, $zero
    /* 2450C 80033D0C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 24510 80033D10 2190C000 */  addu       $s2, $a2, $zero
    /* 24514 80033D14 2000B4AF */  sw         $s4, 0x20($sp)
    /* 24518 80033D18 21A0E000 */  addu       $s4, $a3, $zero
    /* 2451C 80033D1C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24520 80033D20 12001334 */  ori        $s3, $zero, 0x12
    /* 24524 80033D24 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 24528 80033D28 1000B0AF */  sw         $s0, 0x10($sp)
  .L80033D2C:
    /* 2452C 80033D2C D4D2000C */  jal        func_80034B50
    /* 24530 80033D30 00000000 */   nop
    /* 24534 80033D34 21804000 */  addu       $s0, $v0, $zero
    /* 24538 80033D38 0800022A */  slti       $v0, $s0, 0x8
    /* 2453C 80033D3C 0E004014 */  bnez       $v0, .L80033D78
    /* 24540 80033D40 0B00022A */   slti      $v0, $s0, 0xB
    /* 24544 80033D44 05004014 */  bnez       $v0, .L80033D5C
    /* 24548 80033D48 00000000 */   nop
    /* 2454C 80033D4C 07001312 */  beq        $s0, $s3, .L80033D6C
    /* 24550 80033D50 09000434 */   ori       $a0, $zero, 0x9
    /* 24554 80033D54 5ECF0008 */  j          .L80033D78
    /* 24558 80033D58 00000000 */   nop
  .L80033D5C:
    /* 2455C 80033D5C 81D5000C */  jal        func_80035604
    /* 24560 80033D60 00000000 */   nop
    /* 24564 80033D64 5ECF0008 */  j          .L80033D78
    /* 24568 80033D68 00000000 */   nop
  .L80033D6C:
    /* 2456C 80033D6C 21280000 */  addu       $a1, $zero, $zero
    /* 24570 80033D70 70F7000C */  jal        func_8003DDC0
    /* 24574 80033D74 21300000 */   addu      $a2, $zero, $zero
  .L80033D78:
    /* 24578 80033D78 ECFF0016 */  bnez       $s0, .L80033D2C
    /* 2457C 80033D7C 00000000 */   nop
    /* 24580 80033D80 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24584 80033D84 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24588 80033D88 7DF8000C */  jal        func_8003E1F4
    /* 2458C 80033D8C 21202002 */   addu      $a0, $s1, $zero
    /* 24590 80033D90 FF074226 */  addiu      $v0, $s2, 0x7FF
    /* 24594 80033D94 C2120200 */  srl        $v0, $v0, 11
    /* 24598 80033D98 0780013C */  lui        $at, %hi(D_80071B98)
    /* 2459C 80033D9C 981B22AC */  sw         $v0, %lo(D_80071B98)($at)
    /* 245A0 80033DA0 0780013C */  lui        $at, %hi(D_80071BAC)
    /* 245A4 80033DA4 AC1B34AC */  sw         $s4, %lo(D_80071BAC)($at)
    /* 245A8 80033DA8 0780013C */  lui        $at, %hi(D_80071BB0)
    /* 245AC 80033DAC B01B36AC */  sw         $s6, %lo(D_80071BB0)($at)
    /* 245B0 80033DB0 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 245B4 80033DB4 8C1B35AC */  sw         $s5, %lo(g_cd_unknown_80071B8C)($at)
    /* 245B8 80033DB8 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 245BC 80033DBC 2800B68F */  lw         $s6, 0x28($sp)
    /* 245C0 80033DC0 2400B58F */  lw         $s5, 0x24($sp)
    /* 245C4 80033DC4 2000B48F */  lw         $s4, 0x20($sp)
    /* 245C8 80033DC8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 245CC 80033DCC 1800B28F */  lw         $s2, 0x18($sp)
    /* 245D0 80033DD0 1400B18F */  lw         $s1, 0x14($sp)
    /* 245D4 80033DD4 1000B08F */  lw         $s0, 0x10($sp)
    /* 245D8 80033DD8 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 245DC 80033DDC 0800E003 */  jr         $ra
    /* 245E0 80033DE0 00000000 */   nop
endlabel func_80033CF0

nonmatching func_80033DE4, 0x38

glabel func_80033DE4
    /* 245E4 80033DE4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 245E8 80033DE8 21108000 */  addu       $v0, $a0, $zero
    /* 245EC 80033DEC 01000434 */  ori        $a0, $zero, 0x1
    /* 245F0 80033DF0 1000A5AF */  sw         $a1, 0x10($sp)
    /* 245F4 80033DF4 21284000 */  addu       $a1, $v0, $zero
    /* 245F8 80033DF8 21300000 */  addu       $a2, $zero, $zero
    /* 245FC 80033DFC 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24600 80033E00 3CCF000C */  jal        func_80033CF0
    /* 24604 80033E04 21380000 */   addu      $a3, $zero, $zero
    /* 24608 80033E08 21100000 */  addu       $v0, $zero, $zero
    /* 2460C 80033E0C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24610 80033E10 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 24614 80033E14 0800E003 */  jr         $ra
    /* 24618 80033E18 00000000 */   nop
endlabel func_80033DE4

nonmatching func_80033E1C, 0x50

glabel func_80033E1C
    /* 2461C 80033E1C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24620 80033E20 21288000 */  addu       $a1, $a0, $zero
    /* 24624 80033E24 21200000 */  addu       $a0, $zero, $zero
    /* 24628 80033E28 21300000 */  addu       $a2, $zero, $zero
    /* 2462C 80033E2C 21380000 */  addu       $a3, $zero, $zero
    /* 24630 80033E30 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24634 80033E34 3CCF000C */  jal        func_80033CF0
    /* 24638 80033E38 1000A0AF */   sw        $zero, 0x10($sp)
    /* 2463C 80033E3C 02000434 */  ori        $a0, $zero, 0x2
  .L80033E40:
    /* 24640 80033E40 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24644 80033E44 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24648 80033E48 70F7000C */  jal        func_8003DDC0
    /* 2464C 80033E4C 21300000 */   addu      $a2, $zero, $zero
    /* 24650 80033E50 FBFF4010 */  beqz       $v0, .L80033E40
    /* 24654 80033E54 02000434 */   ori       $a0, $zero, 0x2
    /* 24658 80033E58 21100000 */  addu       $v0, $zero, $zero
    /* 2465C 80033E5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24660 80033E60 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 24664 80033E64 0800E003 */  jr         $ra
    /* 24668 80033E68 00000000 */   nop
endlabel func_80033E1C

nonmatching func_80033E6C, 0x40

glabel func_80033E6C
    /* 2466C 80033E6C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24670 80033E70 21108000 */  addu       $v0, $a0, $zero
    /* 24674 80033E74 2118A000 */  addu       $v1, $a1, $zero
    /* 24678 80033E78 2140C000 */  addu       $t0, $a2, $zero
    /* 2467C 80033E7C 03000434 */  ori        $a0, $zero, 0x3
    /* 24680 80033E80 21284000 */  addu       $a1, $v0, $zero
    /* 24684 80033E84 21306000 */  addu       $a2, $v1, $zero
    /* 24688 80033E88 1000A7AF */  sw         $a3, 0x10($sp)
    /* 2468C 80033E8C 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24690 80033E90 3CCF000C */  jal        func_80033CF0
    /* 24694 80033E94 21380001 */   addu      $a3, $t0, $zero
    /* 24698 80033E98 21100000 */  addu       $v0, $zero, $zero
    /* 2469C 80033E9C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 246A0 80033EA0 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 246A4 80033EA4 0800E003 */  jr         $ra
    /* 246A8 80033EA8 00000000 */   nop
endlabel func_80033E6C

nonmatching func_80033EAC, 0x64

glabel func_80033EAC
    /* 246AC 80033EAC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 246B0 80033EB0 1800B0AF */  sw         $s0, 0x18($sp)
    /* 246B4 80033EB4 21808000 */  addu       $s0, $a0, $zero
    /* 246B8 80033EB8 2110A000 */  addu       $v0, $a1, $zero
    /* 246BC 80033EBC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 246C0 80033EC0 2188C000 */  addu       $s1, $a2, $zero
    /* 246C4 80033EC4 0B000434 */  ori        $a0, $zero, 0xB
    /* 246C8 80033EC8 21280002 */  addu       $a1, $s0, $zero
    /* 246CC 80033ECC 21304000 */  addu       $a2, $v0, $zero
    /* 246D0 80033ED0 1000A7AF */  sw         $a3, 0x10($sp)
    /* 246D4 80033ED4 2000BFAF */  sw         $ra, 0x20($sp)
    /* 246D8 80033ED8 3CCF000C */  jal        func_80033CF0
    /* 246DC 80033EDC 21382002 */   addu      $a3, $s1, $zero
    /* 246E0 80033EE0 0780043C */  lui        $a0, %hi(D_80069A3C)
    /* 246E4 80033EE4 3C9A8424 */  addiu      $a0, $a0, %lo(D_80069A3C)
    /* 246E8 80033EE8 900190AF */  sw         $s0, %gp_rel(D_80062E88)($gp)
    /* 246EC 80033EEC 4ED3000C */  jal        func_80034D38
    /* 246F0 80033EF0 21282002 */   addu      $a1, $s1, $zero
    /* 246F4 80033EF4 21100000 */  addu       $v0, $zero, $zero
    /* 246F8 80033EF8 2000BF8F */  lw         $ra, 0x20($sp)
    /* 246FC 80033EFC 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 24700 80033F00 1800B08F */  lw         $s0, 0x18($sp)
    /* 24704 80033F04 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24708 80033F08 0800E003 */  jr         $ra
    /* 2470C 80033F0C 00000000 */   nop
endlabel func_80033EAC

nonmatching func_80033F10, 0x64

glabel func_80033F10
    /* 24710 80033F10 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24714 80033F14 1000B0AF */  sw         $s0, 0x10($sp)
    /* 24718 80033F18 21808000 */  addu       $s0, $a0, $zero
    /* 2471C 80033F1C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24720 80033F20 2188A000 */  addu       $s1, $a1, $zero
    /* 24724 80033F24 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24728 80033F28 21200002 */  addu       $a0, $s0, $zero
  .L80033F2C:
    /* 2472C 80033F2C 79CF000C */  jal        func_80033DE4
    /* 24730 80033F30 21282002 */   addu      $a1, $s1, $zero
    /* 24734 80033F34 FDFF4014 */  bnez       $v0, .L80033F2C
    /* 24738 80033F38 21200002 */   addu      $a0, $s0, $zero
  .L80033F3C:
    /* 2473C 80033F3C D4D2000C */  jal        func_80034B50
    /* 24740 80033F40 00000000 */   nop
    /* 24744 80033F44 05004010 */  beqz       $v0, .L80033F5C
    /* 24748 80033F48 21100000 */   addu      $v0, $zero, $zero
    /* 2474C 80033F4C 76F3000C */  jal        VSync
    /* 24750 80033F50 21200000 */   addu      $a0, $zero, $zero
    /* 24754 80033F54 CFCF0008 */  j          .L80033F3C
    /* 24758 80033F58 00000000 */   nop
  .L80033F5C:
    /* 2475C 80033F5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24760 80033F60 1400B18F */  lw         $s1, 0x14($sp)
    /* 24764 80033F64 1000B08F */  lw         $s0, 0x10($sp)
    /* 24768 80033F68 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2476C 80033F6C 0800E003 */  jr         $ra
    /* 24770 80033F70 00000000 */   nop
endlabel func_80033F10

nonmatching func_80033F74, 0x84

glabel func_80033F74
    /* 24774 80033F74 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 24778 80033F78 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2477C 80033F7C 21808000 */  addu       $s0, $a0, $zero
    /* 24780 80033F80 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24784 80033F84 2188A000 */  addu       $s1, $a1, $zero
    /* 24788 80033F88 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2478C 80033F8C 2190C000 */  addu       $s2, $a2, $zero
    /* 24790 80033F90 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24794 80033F94 2198E000 */  addu       $s3, $a3, $zero
    /* 24798 80033F98 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2479C 80033F9C 21200002 */  addu       $a0, $s0, $zero
  .L80033FA0:
    /* 247A0 80033FA0 21282002 */  addu       $a1, $s1, $zero
    /* 247A4 80033FA4 21304002 */  addu       $a2, $s2, $zero
    /* 247A8 80033FA8 9BCF000C */  jal        func_80033E6C
    /* 247AC 80033FAC 21386002 */   addu      $a3, $s3, $zero
    /* 247B0 80033FB0 FBFF4014 */  bnez       $v0, .L80033FA0
    /* 247B4 80033FB4 21200002 */   addu      $a0, $s0, $zero
  .L80033FB8:
    /* 247B8 80033FB8 D4D2000C */  jal        func_80034B50
    /* 247BC 80033FBC 00000000 */   nop
    /* 247C0 80033FC0 05004010 */  beqz       $v0, .L80033FD8
    /* 247C4 80033FC4 21100000 */   addu      $v0, $zero, $zero
    /* 247C8 80033FC8 76F3000C */  jal        VSync
    /* 247CC 80033FCC 21200000 */   addu      $a0, $zero, $zero
    /* 247D0 80033FD0 EECF0008 */  j          .L80033FB8
    /* 247D4 80033FD4 00000000 */   nop
  .L80033FD8:
    /* 247D8 80033FD8 2000BF8F */  lw         $ra, 0x20($sp)
    /* 247DC 80033FDC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 247E0 80033FE0 1800B28F */  lw         $s2, 0x18($sp)
    /* 247E4 80033FE4 1400B18F */  lw         $s1, 0x14($sp)
    /* 247E8 80033FE8 1000B08F */  lw         $s0, 0x10($sp)
    /* 247EC 80033FEC 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 247F0 80033FF0 0800E003 */  jr         $ra
    /* 247F4 80033FF4 00000000 */   nop
endlabel func_80033F74

nonmatching func_80033FF8, 0x84

glabel func_80033FF8
    /* 247F8 80033FF8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 247FC 80033FFC 1000B0AF */  sw         $s0, 0x10($sp)
    /* 24800 80034000 21808000 */  addu       $s0, $a0, $zero
    /* 24804 80034004 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24808 80034008 2188A000 */  addu       $s1, $a1, $zero
    /* 2480C 8003400C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 24810 80034010 2190C000 */  addu       $s2, $a2, $zero
    /* 24814 80034014 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24818 80034018 2198E000 */  addu       $s3, $a3, $zero
    /* 2481C 8003401C 2000BFAF */  sw         $ra, 0x20($sp)
    /* 24820 80034020 21200002 */  addu       $a0, $s0, $zero
  .L80034024:
    /* 24824 80034024 21282002 */  addu       $a1, $s1, $zero
    /* 24828 80034028 21304002 */  addu       $a2, $s2, $zero
    /* 2482C 8003402C ABCF000C */  jal        func_80033EAC
    /* 24830 80034030 21386002 */   addu      $a3, $s3, $zero
    /* 24834 80034034 FBFF4014 */  bnez       $v0, .L80034024
    /* 24838 80034038 21200002 */   addu      $a0, $s0, $zero
  .L8003403C:
    /* 2483C 8003403C D4D2000C */  jal        func_80034B50
    /* 24840 80034040 00000000 */   nop
    /* 24844 80034044 05004010 */  beqz       $v0, .L8003405C
    /* 24848 80034048 21100000 */   addu      $v0, $zero, $zero
    /* 2484C 8003404C 76F3000C */  jal        VSync
    /* 24850 80034050 21200000 */   addu      $a0, $zero, $zero
    /* 24854 80034054 0FD00008 */  j          .L8003403C
    /* 24858 80034058 00000000 */   nop
  .L8003405C:
    /* 2485C 8003405C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 24860 80034060 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 24864 80034064 1800B28F */  lw         $s2, 0x18($sp)
    /* 24868 80034068 1400B18F */  lw         $s1, 0x14($sp)
    /* 2486C 8003406C 1000B08F */  lw         $s0, 0x10($sp)
    /* 24870 80034070 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24874 80034074 0800E003 */  jr         $ra
    /* 24878 80034078 00000000 */   nop
endlabel func_80033FF8

nonmatching func_8003407C, 0x44

glabel func_8003407C
    /* 2487C 8003407C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24880 80034080 13000234 */  ori        $v0, $zero, 0x13
    /* 24884 80034084 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24888 80034088 0780013C */  lui        $at, %hi(D_80071B98)
    /* 2488C 8003408C 981B20AC */  sw         $zero, %lo(D_80071B98)($at)
    /* 24890 80034090 0780013C */  lui        $at, %hi(D_80071BAC)
    /* 24894 80034094 AC1B20AC */  sw         $zero, %lo(D_80071BAC)($at)
    /* 24898 80034098 0780013C */  lui        $at, %hi(D_80071BB0)
    /* 2489C 8003409C B01B20AC */  sw         $zero, %lo(D_80071BB0)($at)
    /* 248A0 800340A0 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 248A4 800340A4 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 248A8 800340A8 D4D2000C */  jal        func_80034B50
    /* 248AC 800340AC 00000000 */   nop
    /* 248B0 800340B0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 248B4 800340B4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 248B8 800340B8 0800E003 */  jr         $ra
    /* 248BC 800340BC 00000000 */   nop
endlabel func_8003407C

nonmatching func_800340C0, 0x78

glabel func_800340C0
    /* 248C0 800340C0 0780033C */  lui        $v1, %hi(g_cd_unknown_80071B8C)
    /* 248C4 800340C4 8C1B638C */  lw         $v1, %lo(g_cd_unknown_80071B8C)($v1)
    /* 248C8 800340C8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 248CC 800340CC 1300622C */  sltiu      $v0, $v1, 0x13
    /* 248D0 800340D0 13004010 */  beqz       $v0, .L80034120
    /* 248D4 800340D4 1000BFAF */   sw        $ra, 0x10($sp)
    /* 248D8 800340D8 80100300 */  sll        $v0, $v1, 2
    /* 248DC 800340DC 0180013C */  lui        $at, %hi(switchdataD_80010450)
    /* 248E0 800340E0 50042124 */  addiu      $at, $at, %lo(switchdataD_80010450)
    /* 248E4 800340E4 21082200 */  addu       $at, $at, $v0
    /* 248E8 800340E8 0000228C */  lw         $v0, 0x0($at)
    /* 248EC 800340EC 00000000 */  nop
    /* 248F0 800340F0 08004000 */  jr         $v0
    /* 248F4 800340F4 00000000 */   nop
    /* 248F8 800340F8 64F7000C */  jal        func_8003DD90
    /* 248FC 800340FC 21200000 */   addu      $a0, $zero, $zero
    /* 24900 80034100 6AF7000C */  jal        func_8003DDA8
    /* 24904 80034104 21200000 */   addu      $a0, $zero, $zero
    /* 24908 80034108 48D00008 */  j          .L80034120
    /* 2490C 8003410C 00000000 */   nop
    /* 24910 80034110 81D5000C */  jal        func_80035604
    /* 24914 80034114 00000000 */   nop
    /* 24918 80034118 4AD00008 */  j          .L80034128
    /* 2491C 8003411C 00000000 */   nop
  .L80034120:
    /* 24920 80034120 1FD0000C */  jal        func_8003407C
    /* 24924 80034124 00000000 */   nop
  .L80034128:
    /* 24928 80034128 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2492C 8003412C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24930 80034130 0800E003 */  jr         $ra
    /* 24934 80034134 00000000 */   nop
endlabel func_800340C0

nonmatching func_80034138, 0x4C

glabel func_80034138
    /* 24938 80034138 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2493C 8003413C 0E000434 */  ori        $a0, $zero, 0xE
    /* 24940 80034140 21280000 */  addu       $a1, $zero, $zero
    /* 24944 80034144 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24948 80034148 09F8000C */  jal        ff7_unknown_8003E024
    /* 2494C 8003414C 21300000 */   addu      $a2, $zero, $zero
    /* 24950 80034150 76F3000C */  jal        VSync
    /* 24954 80034154 03000434 */   ori       $a0, $zero, 0x3
    /* 24958 80034158 08000434 */  ori        $a0, $zero, 0x8
    /* 2495C 8003415C 21280000 */  addu       $a1, $zero, $zero
    /* 24960 80034160 09F8000C */  jal        ff7_unknown_8003E024
    /* 24964 80034164 21300000 */   addu      $a2, $zero, $zero
    /* 24968 80034168 07000234 */  ori        $v0, $zero, 0x7
    /* 2496C 8003416C 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24970 80034170 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24974 80034174 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24978 80034178 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2497C 8003417C 0800E003 */  jr         $ra
    /* 24980 80034180 00000000 */   nop
endlabel func_80034138

nonmatching func_80034184, 0x200

glabel func_80034184
    /* 24984 80034184 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 24988 80034188 0780033C */  lui        $v1, %hi(g_cd_unknown_80071B8C)
    /* 2498C 8003418C 8C1B638C */  lw         $v1, %lo(g_cd_unknown_80071B8C)($v1)
    /* 24990 80034190 07000234 */  ori        $v0, $zero, 0x7
    /* 24994 80034194 2400BFAF */  sw         $ra, 0x24($sp)
    /* 24998 80034198 74006214 */  bne        $v1, $v0, .L8003436C
    /* 2499C 8003419C 2000B0AF */   sw        $s0, 0x20($sp)
    /* 249A0 800341A0 01000434 */  ori        $a0, $zero, 0x1
    /* 249A4 800341A4 21280000 */  addu       $a1, $zero, $zero
    /* 249A8 800341A8 09F8000C */  jal        ff7_unknown_8003E024
    /* 249AC 800341AC 1000A627 */   addiu     $a2, $sp, 0x10
    /* 249B0 800341B0 1000A293 */  lbu        $v0, 0x10($sp)
    /* 249B4 800341B4 00000000 */  nop
    /* 249B8 800341B8 10004230 */  andi       $v0, $v0, 0x10
    /* 249BC 800341BC 03004010 */  beqz       $v0, .L800341CC
    /* 249C0 800341C0 58021034 */   ori       $s0, $zero, 0x258
    /* 249C4 800341C4 DCD00008 */  j          .L80034370
    /* 249C8 800341C8 03000234 */   ori       $v0, $zero, 0x3
  .L800341CC:
    /* 249CC 800341CC 07000434 */  ori        $a0, $zero, 0x7
    /* 249D0 800341D0 21280000 */  addu       $a1, $zero, $zero
    /* 249D4 800341D4 09F8000C */  jal        ff7_unknown_8003E024
    /* 249D8 800341D8 21300000 */   addu      $a2, $zero, $zero
  .L800341DC:
    /* 249DC 800341DC 76F3000C */  jal        VSync
    /* 249E0 800341E0 21200000 */   addu      $a0, $zero, $zero
    /* 249E4 800341E4 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 249E8 800341E8 5C000012 */  beqz       $s0, .L8003435C
    /* 249EC 800341EC 01000434 */   ori       $a0, $zero, 0x1
    /* 249F0 800341F0 21280000 */  addu       $a1, $zero, $zero
    /* 249F4 800341F4 09F8000C */  jal        ff7_unknown_8003E024
    /* 249F8 800341F8 1000A627 */   addiu     $a2, $sp, 0x10
    /* 249FC 800341FC 1000A293 */  lbu        $v0, 0x10($sp)
    /* 24A00 80034200 00000000 */  nop
    /* 24A04 80034204 02004230 */  andi       $v0, $v0, 0x2
    /* 24A08 80034208 F4FF4010 */  beqz       $v0, .L800341DC
    /* 24A0C 8003420C 00000000 */   nop
    /* 24A10 80034210 5B01010C */  jal        func_8004056C
    /* 24A14 80034214 21200000 */   addu      $a0, $zero, $zero
    /* 24A18 80034218 21804000 */  addu       $s0, $v0, $zero
    /* 24A1C 8003421C 05000234 */  ori        $v0, $zero, 0x5
    /* 24A20 80034220 0C000212 */  beq        $s0, $v0, .L80034254
    /* 24A24 80034224 0600022A */   slti      $v0, $s0, 0x6
    /* 24A28 80034228 05004010 */  beqz       $v0, .L80034240
    /* 24A2C 8003422C 02000234 */   ori       $v0, $zero, 0x2
    /* 24A30 80034230 0A000212 */  beq        $s0, $v0, .L8003425C
    /* 24A34 80034234 01000234 */   ori       $v0, $zero, 0x1
    /* 24A38 80034238 DCD00008 */  j          .L80034370
    /* 24A3C 8003423C 00000000 */   nop
  .L80034240:
    /* 24A40 80034240 10000234 */  ori        $v0, $zero, 0x10
    /* 24A44 80034244 4A000212 */  beq        $s0, $v0, .L80034370
    /* 24A48 80034248 03000234 */   ori       $v0, $zero, 0x3
    /* 24A4C 8003424C DCD00008 */  j          .L80034370
    /* 24A50 80034250 01000234 */   ori       $v0, $zero, 0x1
  .L80034254:
    /* 24A54 80034254 DCD00008 */  j          .L80034370
    /* 24A58 80034258 02000234 */   ori       $v0, $zero, 0x2
  .L8003425C:
    /* 24A5C 8003425C A401010C */  jal        func_80040690
    /* 24A60 80034260 00000000 */   nop
    /* 24A64 80034264 21184000 */  addu       $v1, $v0, $zero
    /* 24A68 80034268 01000234 */  ori        $v0, $zero, 0x1
    /* 24A6C 8003426C 0D006210 */  beq        $v1, $v0, .L800342A4
    /* 24A70 80034270 02006228 */   slti      $v0, $v1, 0x2
    /* 24A74 80034274 05004010 */  beqz       $v0, .L8003428C
    /* 24A78 80034278 00000000 */   nop
    /* 24A7C 8003427C 3C006010 */  beqz       $v1, .L80034370
    /* 24A80 80034280 05000234 */   ori       $v0, $zero, 0x5
    /* 24A84 80034284 DCD00008 */  j          .L80034370
    /* 24A88 80034288 01000234 */   ori       $v0, $zero, 0x1
  .L8003428C:
    /* 24A8C 8003428C 07007010 */  beq        $v1, $s0, .L800342AC
    /* 24A90 80034290 10000234 */   ori       $v0, $zero, 0x10
    /* 24A94 80034294 36006210 */  beq        $v1, $v0, .L80034370
    /* 24A98 80034298 03000234 */   ori       $v0, $zero, 0x3
    /* 24A9C 8003429C DCD00008 */  j          .L80034370
    /* 24AA0 800342A0 01000234 */   ori       $v0, $zero, 0x1
  .L800342A4:
    /* 24AA4 800342A4 DCD00008 */  j          .L80034370
    /* 24AA8 800342A8 04000234 */   ori       $v0, $zero, 0x4
  .L800342AC:
    /* 24AAC 800342AC 17000434 */  ori        $a0, $zero, 0x17
    /* 24AB0 800342B0 1800B027 */  addiu      $s0, $sp, 0x18
    /* 24AB4 800342B4 7DF8000C */  jal        func_8003E1F4
    /* 24AB8 800342B8 21280002 */   addu      $a1, $s0, $zero
    /* 24ABC 800342BC 15000434 */  ori        $a0, $zero, 0x15
    /* 24AC0 800342C0 21280002 */  addu       $a1, $s0, $zero
    /* 24AC4 800342C4 09F8000C */  jal        ff7_unknown_8003E024
    /* 24AC8 800342C8 1000A627 */   addiu     $a2, $sp, 0x10
    /* 24ACC 800342CC 1000A293 */  lbu        $v0, 0x10($sp)
    /* 24AD0 800342D0 00000000 */  nop
    /* 24AD4 800342D4 01004230 */  andi       $v0, $v0, 0x1
    /* 24AD8 800342D8 25004014 */  bnez       $v0, .L80034370
    /* 24ADC 800342DC 01000234 */   ori       $v0, $zero, 0x1
    /* 24AE0 800342E0 1100A293 */  lbu        $v0, 0x11($sp)
    /* 24AE4 800342E4 00000000 */  nop
    /* 24AE8 800342E8 40004230 */  andi       $v0, $v0, 0x40
    /* 24AEC 800342EC 20004014 */  bnez       $v0, .L80034370
    /* 24AF0 800342F0 01000234 */   ori       $v0, $zero, 0x1
    /* 24AF4 800342F4 0E000434 */  ori        $a0, $zero, 0xE
    /* 24AF8 800342F8 80000534 */  ori        $a1, $zero, 0x80
    /* 24AFC 800342FC 09F8000C */  jal        ff7_unknown_8003E024
    /* 24B00 80034300 1000A627 */   addiu     $a2, $sp, 0x10
    /* 24B04 80034304 76F3000C */  jal        VSync
    /* 24B08 80034308 03000434 */   ori       $a0, $zero, 0x3
    /* 24B0C 8003430C 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24B10 80034310 8C1B20AC */  sw         $zero, %lo(g_cd_unknown_80071B8C)($at)
    /* 24B14 80034314 E1D0000C */  jal        ff7_unknown_80034384
    /* 24B18 80034318 00000000 */   nop
    /* 24B1C 8003431C 21184000 */  addu       $v1, $v0, $zero
    /* 24B20 80034320 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 24B24 80034324 0780013C */  lui        $at, %hi(g_cd_unknown_80071B90)
    /* 24B28 80034328 901B23AC */  sw         $v1, %lo(g_cd_unknown_80071B90)($at)
    /* 24B2C 8003432C 07006210 */  beq        $v1, $v0, .L8003434C
    /* 24B30 80034330 00000000 */   nop
    /* 24B34 80034334 0B006014 */  bnez       $v1, .L80034364
    /* 24B38 80034338 00000000 */   nop
    /* 24B3C 8003433C 4ED0000C */  jal        func_80034138
    /* 24B40 80034340 00000000 */   nop
    /* 24B44 80034344 DCD00008 */  j          .L80034370
    /* 24B48 80034348 06000234 */   ori       $v0, $zero, 0x6
  .L8003434C:
    /* 24B4C 8003434C 4ED0000C */  jal        func_80034138
    /* 24B50 80034350 00000000 */   nop
    /* 24B54 80034354 DCD00008 */  j          .L80034370
    /* 24B58 80034358 01000234 */   ori       $v0, $zero, 0x1
  .L8003435C:
    /* 24B5C 8003435C DCD00008 */  j          .L80034370
    /* 24B60 80034360 05000234 */   ori       $v0, $zero, 0x5
  .L80034364:
    /* 24B64 80034364 DAD3000C */  jal        ff7_unknown_80034F68
    /* 24B68 80034368 00000000 */   nop
  .L8003436C:
    /* 24B6C 8003436C 21100000 */  addu       $v0, $zero, $zero
  .L80034370:
    /* 24B70 80034370 2400BF8F */  lw         $ra, 0x24($sp)
    /* 24B74 80034374 2000B08F */  lw         $s0, 0x20($sp)
    /* 24B78 80034378 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24B7C 8003437C 0800E003 */  jr         $ra
    /* 24B80 80034380 00000000 */   nop
endlabel func_80034184

nonmatching ff7_unknown_80034384, 0xA0

glabel ff7_unknown_80034384
    /* 24B84 80034384 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 24B88 80034388 2800BFAF */  sw         $ra, 0x28($sp)
  .L8003438C:
    /* 24B8C 8003438C D4D2000C */  jal        func_80034B50
    /* 24B90 80034390 00000000 */   nop
    /* 24B94 80034394 FDFF4014 */  bnez       $v0, .L8003438C
    /* 24B98 80034398 00000000 */   nop
  .L8003439C:
    /* 24B9C 8003439C 0180053C */  lui        $a1, %hi(D_80010438)
    /* 24BA0 800343A0 3804A524 */  addiu      $a1, $a1, %lo(D_80010438)
    /* 24BA4 800343A4 ACFE000C */  jal        func_8003FAB0
    /* 24BA8 800343A8 1000A427 */   addiu     $a0, $sp, 0x10
    /* 24BAC 800343AC 0500401C */  bgtz       $v0, .L800343C4
    /* 24BB0 800343B0 FFFF4228 */   slti      $v0, $v0, -0x1
    /* 24BB4 800343B4 04004014 */  bnez       $v0, .L800343C8
    /* 24BB8 800343B8 02000434 */   ori       $a0, $zero, 0x2
    /* 24BBC 800343BC 05D10008 */  j          .L80034414
    /* 24BC0 800343C0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L800343C4:
    /* 24BC4 800343C4 02000434 */  ori        $a0, $zero, 0x2
  .L800343C8:
    /* 24BC8 800343C8 1000A527 */  addiu      $a1, $sp, 0x10
    /* 24BCC 800343CC 09F8000C */  jal        ff7_unknown_8003E024
    /* 24BD0 800343D0 21300000 */   addu      $a2, $zero, $zero
    /* 24BD4 800343D4 01000434 */  ori        $a0, $zero, 0x1
    /* 24BD8 800343D8 0780053C */  lui        $a1, %hi(D_80069A3C)
    /* 24BDC 800343DC 3C9AA524 */  addiu      $a1, $a1, %lo(D_80069A3C)
    /* 24BE0 800343E0 1307010C */  jal        func_80041C4C
    /* 24BE4 800343E4 80000634 */   ori       $a2, $zero, 0x80
    /* 24BE8 800343E8 01000434 */  ori        $a0, $zero, 0x1
  .L800343EC:
    /* 24BEC 800343EC 5507010C */  jal        func_80041D54
    /* 24BF0 800343F0 21280000 */   addu      $a1, $zero, $zero
    /* 24BF4 800343F4 FDFF401C */  bgtz       $v0, .L800343EC
    /* 24BF8 800343F8 01000434 */   ori       $a0, $zero, 0x1
    /* 24BFC 800343FC E7FF4014 */  bnez       $v0, .L8003439C
    /* 24C00 80034400 00000000 */   nop
    /* 24C04 80034404 0780023C */  lui        $v0, %hi(D_80069A43)
    /* 24C08 80034408 439A4290 */  lbu        $v0, %lo(D_80069A43)($v0)
    /* 24C0C 8003440C 00000000 */  nop
    /* 24C10 80034410 D0FF4224 */  addiu      $v0, $v0, -0x30
  .L80034414:
    /* 24C14 80034414 2800BF8F */  lw         $ra, 0x28($sp)
    /* 24C18 80034418 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 24C1C 8003441C 0800E003 */  jr         $ra
    /* 24C20 80034420 00000000 */   nop
endlabel ff7_unknown_80034384

nonmatching func_80034424, 0x20

glabel func_80034424
    /* 24C24 80034424 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24C28 80034428 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24C2C 8003442C E1D0000C */  jal        ff7_unknown_80034384
    /* 24C30 80034430 00000000 */   nop
    /* 24C34 80034434 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24C38 80034438 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24C3C 8003443C 0800E003 */  jr         $ra
    /* 24C40 80034440 00000000 */   nop
endlabel func_80034424

nonmatching func_80034444, 0x10

glabel func_80034444
    /* 24C44 80034444 0780023C */  lui        $v0, %hi(g_cd_unknown_80071B8C)
    /* 24C48 80034448 8C1B428C */  lw         $v0, %lo(g_cd_unknown_80071B8C)($v0)
    /* 24C4C 8003444C 0800E003 */  jr         $ra
    /* 24C50 80034450 00000000 */   nop
endlabel func_80034444

nonmatching func_80034454, 0x8

glabel func_80034454
    /* 24C54 80034454 0800E003 */  jr         $ra
    /* 24C58 80034458 00000000 */   nop
endlabel func_80034454

nonmatching func_8003445C, 0x8

glabel func_8003445C
    /* 24C5C 8003445C 0800E003 */  jr         $ra
    /* 24C60 80034460 00000000 */   nop
endlabel func_8003445C

nonmatching func_80034464, 0x14

glabel func_80034464
    /* 24C64 80034464 10000234 */  ori        $v0, $zero, 0x10
    /* 24C68 80034468 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24C6C 8003446C 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24C70 80034470 0800E003 */  jr         $ra
    /* 24C74 80034474 00000000 */   nop
endlabel func_80034464

nonmatching func_80034478, 0x38

glabel func_80034478
    /* 24C78 80034478 0780023C */  lui        $v0, %hi(D_80071BB0)
    /* 24C7C 8003447C B01B428C */  lw         $v0, %lo(D_80071BB0)($v0)
    /* 24C80 80034480 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24C84 80034484 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24C88 80034488 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24C8C 8003448C 8C1B20AC */  sw         $zero, %lo(g_cd_unknown_80071B8C)($at)
    /* 24C90 80034490 03004010 */  beqz       $v0, .L800344A0
    /* 24C94 80034494 00000000 */   nop
    /* 24C98 80034498 09F84000 */  jalr       $v0
    /* 24C9C 8003449C 00000000 */   nop
  .L800344A0:
    /* 24CA0 800344A0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24CA4 800344A4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24CA8 800344A8 0800E003 */  jr         $ra
    /* 24CAC 800344AC 00000000 */   nop
endlabel func_80034478

nonmatching func_800344B0, 0x40

glabel func_800344B0
    /* 24CB0 800344B0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24CB4 800344B4 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24CB8 800344B8 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24CBC 800344BC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24CC0 800344C0 BEF7000C */  jal        func_8003DEF8
    /* 24CC4 800344C4 02000434 */   ori       $a0, $zero, 0x2
    /* 24CC8 800344C8 02000234 */  ori        $v0, $zero, 0x2
    /* 24CCC 800344CC 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24CD0 800344D0 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24CD4 800344D4 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24CD8 800344D8 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 24CDC 800344DC 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24CE0 800344E0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24CE4 800344E4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24CE8 800344E8 0800E003 */  jr         $ra
    /* 24CEC 800344EC 00000000 */   nop
endlabel func_800344B0

nonmatching func_800344F0, 0xF8

glabel func_800344F0
    /* 24CF0 800344F0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24CF4 800344F4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24CF8 800344F8 01000434 */  ori        $a0, $zero, 0x1
    /* 24CFC 800344FC 54F7000C */  jal        func_8003DD50
    /* 24D00 80034500 21280000 */   addu      $a1, $zero, $zero
    /* 24D04 80034504 21184000 */  addu       $v1, $v0, $zero
    /* 24D08 80034508 02000234 */  ori        $v0, $zero, 0x2
    /* 24D0C 8003450C 05006210 */  beq        $v1, $v0, .L80034524
    /* 24D10 80034510 05000234 */   ori       $v0, $zero, 0x5
    /* 24D14 80034514 08006210 */  beq        $v1, $v0, .L80034538
    /* 24D18 80034518 00000000 */   nop
    /* 24D1C 8003451C 62D10008 */  j          .L80034588
    /* 24D20 80034520 00000000 */   nop
  .L80034524:
    /* 24D24 80034524 11000234 */  ori        $v0, $zero, 0x11
    /* 24D28 80034528 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24D2C 8003452C 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24D30 80034530 76D10008 */  j          .L800345D8
    /* 24D34 80034534 00000000 */   nop
  .L80034538:
    /* 24D38 80034538 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24D3C 8003453C 00000000 */  nop
    /* 24D40 80034540 01004224 */  addiu      $v0, $v0, 0x1
    /* 24D44 80034544 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24D48 80034548 10004228 */  slti       $v0, $v0, 0x10
    /* 24D4C 8003454C 0A004014 */  bnez       $v0, .L80034578
    /* 24D50 80034550 01000234 */   ori       $v0, $zero, 0x1
    /* 24D54 80034554 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24D58 80034558 4ED0000C */  jal        func_80034138
    /* 24D5C 8003455C 00000000 */   nop
  .L80034560:
    /* 24D60 80034560 2ED3000C */  jal        func_80034CB8
    /* 24D64 80034564 03000434 */   ori       $a0, $zero, 0x3
    /* 24D68 80034568 61D0000C */  jal        func_80034184
    /* 24D6C 8003456C 00000000 */   nop
    /* 24D70 80034570 FBFF4014 */  bnez       $v0, .L80034560
    /* 24D74 80034574 01000234 */   ori       $v0, $zero, 0x1
  .L80034578:
    /* 24D78 80034578 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24D7C 8003457C 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24D80 80034580 76D10008 */  j          .L800345D8
    /* 24D84 80034584 00000000 */   nop
  .L80034588:
    /* 24D88 80034588 76F3000C */  jal        VSync
    /* 24D8C 8003458C FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 24D90 80034590 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 24D94 80034594 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 24D98 80034598 0000A38C */  lw         $v1, 0x0($a1)
    /* 24D9C 8003459C 21204000 */  addu       $a0, $v0, $zero
    /* 24DA0 800345A0 0D006410 */  beq        $v1, $a0, .L800345D8
    /* 24DA4 800345A4 100E0334 */   ori       $v1, $zero, 0xE10
    /* 24DA8 800345A8 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 24DAC 800345AC 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 24DB0 800345B0 0000A4AC */  sw         $a0, 0x0($a1)
    /* 24DB4 800345B4 01004224 */  addiu      $v0, $v0, 0x1
    /* 24DB8 800345B8 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24DBC 800345BC 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 24DC0 800345C0 05004314 */  bne        $v0, $v1, .L800345D8
    /* 24DC4 800345C4 01000234 */   ori       $v0, $zero, 0x1
    /* 24DC8 800345C8 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24DCC 800345CC 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24DD0 800345D0 2ED3000C */  jal        func_80034CB8
    /* 24DD4 800345D4 03000434 */   ori       $a0, $zero, 0x3
  .L800345D8:
    /* 24DD8 800345D8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24DDC 800345DC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24DE0 800345E0 0800E003 */  jr         $ra
    /* 24DE4 800345E4 00000000 */   nop
endlabel func_800344F0

nonmatching func_800345E8, 0x40

glabel func_800345E8
    /* 24DE8 800345E8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24DEC 800345EC 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24DF0 800345F0 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24DF4 800345F4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24DF8 800345F8 BEF7000C */  jal        func_8003DEF8
    /* 24DFC 800345FC 02000434 */   ori       $a0, $zero, 0x2
    /* 24E00 80034600 04000234 */  ori        $v0, $zero, 0x4
    /* 24E04 80034604 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24E08 80034608 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24E0C 8003460C 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24E10 80034610 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 24E14 80034614 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24E18 80034618 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24E1C 8003461C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24E20 80034620 0800E003 */  jr         $ra
    /* 24E24 80034624 00000000 */   nop
endlabel func_800345E8

nonmatching func_80034628, 0xF4

glabel func_80034628
    /* 24E28 80034628 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24E2C 8003462C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24E30 80034630 01000434 */  ori        $a0, $zero, 0x1
    /* 24E34 80034634 54F7000C */  jal        func_8003DD50
    /* 24E38 80034638 21280000 */   addu      $a1, $zero, $zero
    /* 24E3C 8003463C 21184000 */  addu       $v1, $v0, $zero
    /* 24E40 80034640 02000234 */  ori        $v0, $zero, 0x2
    /* 24E44 80034644 05006210 */  beq        $v1, $v0, .L8003465C
    /* 24E48 80034648 05000234 */   ori       $v0, $zero, 0x5
    /* 24E4C 8003464C 07006210 */  beq        $v1, $v0, .L8003466C
    /* 24E50 80034650 00000000 */   nop
    /* 24E54 80034654 AFD10008 */  j          .L800346BC
    /* 24E58 80034658 00000000 */   nop
  .L8003465C:
    /* 24E5C 8003465C 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24E60 80034660 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24E64 80034664 C3D10008 */  j          .L8003470C
    /* 24E68 80034668 00000000 */   nop
  .L8003466C:
    /* 24E6C 8003466C 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24E70 80034670 00000000 */  nop
    /* 24E74 80034674 01004224 */  addiu      $v0, $v0, 0x1
    /* 24E78 80034678 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24E7C 8003467C 10004228 */  slti       $v0, $v0, 0x10
    /* 24E80 80034680 0A004014 */  bnez       $v0, .L800346AC
    /* 24E84 80034684 03000234 */   ori       $v0, $zero, 0x3
    /* 24E88 80034688 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24E8C 8003468C 4ED0000C */  jal        func_80034138
    /* 24E90 80034690 00000000 */   nop
  .L80034694:
    /* 24E94 80034694 2ED3000C */  jal        func_80034CB8
    /* 24E98 80034698 03000434 */   ori       $a0, $zero, 0x3
    /* 24E9C 8003469C 61D0000C */  jal        func_80034184
    /* 24EA0 800346A0 00000000 */   nop
    /* 24EA4 800346A4 FBFF4014 */  bnez       $v0, .L80034694
    /* 24EA8 800346A8 03000234 */   ori       $v0, $zero, 0x3
  .L800346AC:
    /* 24EAC 800346AC 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24EB0 800346B0 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24EB4 800346B4 C3D10008 */  j          .L8003470C
    /* 24EB8 800346B8 00000000 */   nop
  .L800346BC:
    /* 24EBC 800346BC 76F3000C */  jal        VSync
    /* 24EC0 800346C0 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 24EC4 800346C4 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 24EC8 800346C8 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 24ECC 800346CC 0000A38C */  lw         $v1, 0x0($a1)
    /* 24ED0 800346D0 21204000 */  addu       $a0, $v0, $zero
    /* 24ED4 800346D4 0D006410 */  beq        $v1, $a0, .L8003470C
    /* 24ED8 800346D8 100E0334 */   ori       $v1, $zero, 0xE10
    /* 24EDC 800346DC 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 24EE0 800346E0 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 24EE4 800346E4 0000A4AC */  sw         $a0, 0x0($a1)
    /* 24EE8 800346E8 01004224 */  addiu      $v0, $v0, 0x1
    /* 24EEC 800346EC 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24EF0 800346F0 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 24EF4 800346F4 05004314 */  bne        $v0, $v1, .L8003470C
    /* 24EF8 800346F8 03000234 */   ori       $v0, $zero, 0x3
    /* 24EFC 800346FC 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24F00 80034700 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24F04 80034704 2ED3000C */  jal        func_80034CB8
    /* 24F08 80034708 03000434 */   ori       $a0, $zero, 0x3
  .L8003470C:
    /* 24F0C 8003470C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24F10 80034710 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24F14 80034714 0800E003 */  jr         $ra
    /* 24F18 80034718 00000000 */   nop
endlabel func_80034628

nonmatching func_8003471C, 0x5C

glabel func_8003471C
    /* 24F1C 8003471C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24F20 80034720 0780043C */  lui        $a0, %hi(D_80071B98)
    /* 24F24 80034724 981B848C */  lw         $a0, %lo(D_80071B98)($a0)
    /* 24F28 80034728 0780053C */  lui        $a1, %hi(D_80071BAC)
    /* 24F2C 8003472C AC1BA58C */  lw         $a1, %lo(D_80071BAC)($a1)
    /* 24F30 80034730 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24F34 80034734 1307010C */  jal        func_80041C4C
    /* 24F38 80034738 80000634 */   ori       $a2, $zero, 0x80
    /* 24F3C 8003473C 08004014 */  bnez       $v0, .L80034760
    /* 24F40 80034740 06000234 */   ori       $v0, $zero, 0x6
    /* 24F44 80034744 03000234 */  ori        $v0, $zero, 0x3
    /* 24F48 80034748 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24F4C 8003474C 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24F50 80034750 2ED3000C */  jal        func_80034CB8
    /* 24F54 80034754 10000434 */   ori       $a0, $zero, 0x10
    /* 24F58 80034758 DAD10008 */  j          .L80034768
    /* 24F5C 8003475C 00000000 */   nop
  .L80034760:
    /* 24F60 80034760 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24F64 80034764 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
  .L80034768:
    /* 24F68 80034768 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24F6C 8003476C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24F70 80034770 0800E003 */  jr         $ra
    /* 24F74 80034774 00000000 */   nop
endlabel func_8003471C

nonmatching func_80034778, 0x60

glabel func_80034778
    /* 24F78 80034778 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24F7C 8003477C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24F80 80034780 01000434 */  ori        $a0, $zero, 0x1
    /* 24F84 80034784 5507010C */  jal        func_80041D54
    /* 24F88 80034788 21280000 */   addu      $a1, $zero, $zero
    /* 24F8C 8003478C 21184000 */  addu       $v1, $v0, $zero
    /* 24F90 80034790 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 24F94 80034794 07006210 */  beq        $v1, $v0, .L800347B4
    /* 24F98 80034798 00000000 */   nop
    /* 24F9C 8003479C 0A006014 */  bnez       $v1, .L800347C8
    /* 24FA0 800347A0 11000234 */   ori       $v0, $zero, 0x11
    /* 24FA4 800347A4 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24FA8 800347A8 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24FAC 800347AC F2D10008 */  j          .L800347C8
    /* 24FB0 800347B0 00000000 */   nop
  .L800347B4:
    /* 24FB4 800347B4 03000234 */  ori        $v0, $zero, 0x3
    /* 24FB8 800347B8 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24FBC 800347BC 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24FC0 800347C0 2ED3000C */  jal        func_80034CB8
    /* 24FC4 800347C4 03000434 */   ori       $a0, $zero, 0x3
  .L800347C8:
    /* 24FC8 800347C8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24FCC 800347CC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24FD0 800347D0 0800E003 */  jr         $ra
    /* 24FD4 800347D4 00000000 */   nop
endlabel func_80034778

nonmatching func_800347D8, 0x40

glabel func_800347D8
    /* 24FD8 800347D8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24FDC 800347DC 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24FE0 800347E0 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24FE4 800347E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24FE8 800347E8 BEF7000C */  jal        func_8003DEF8
    /* 24FEC 800347EC 02000434 */   ori       $a0, $zero, 0x2
    /* 24FF0 800347F0 0C000234 */  ori        $v0, $zero, 0xC
    /* 24FF4 800347F4 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 24FF8 800347F8 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 24FFC 800347FC 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25000 80034800 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 25004 80034804 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 25008 80034808 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2500C 8003480C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25010 80034810 0800E003 */  jr         $ra
    /* 25014 80034814 00000000 */   nop
endlabel func_800347D8

nonmatching func_80034818, 0xF8

glabel func_80034818
    /* 25018 80034818 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2501C 8003481C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25020 80034820 01000434 */  ori        $a0, $zero, 0x1
    /* 25024 80034824 54F7000C */  jal        func_8003DD50
    /* 25028 80034828 21280000 */   addu      $a1, $zero, $zero
    /* 2502C 8003482C 21184000 */  addu       $v1, $v0, $zero
    /* 25030 80034830 02000234 */  ori        $v0, $zero, 0x2
    /* 25034 80034834 05006210 */  beq        $v1, $v0, .L8003484C
    /* 25038 80034838 05000234 */   ori       $v0, $zero, 0x5
    /* 2503C 8003483C 08006210 */  beq        $v1, $v0, .L80034860
    /* 25040 80034840 00000000 */   nop
    /* 25044 80034844 2CD20008 */  j          .L800348B0
    /* 25048 80034848 00000000 */   nop
  .L8003484C:
    /* 2504C 8003484C 0D000234 */  ori        $v0, $zero, 0xD
    /* 25050 80034850 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 25054 80034854 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 25058 80034858 40D20008 */  j          .L80034900
    /* 2505C 8003485C 00000000 */   nop
  .L80034860:
    /* 25060 80034860 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 25064 80034864 00000000 */  nop
    /* 25068 80034868 01004224 */  addiu      $v0, $v0, 0x1
    /* 2506C 8003486C 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 25070 80034870 10004228 */  slti       $v0, $v0, 0x10
    /* 25074 80034874 0A004014 */  bnez       $v0, .L800348A0
    /* 25078 80034878 0B000234 */   ori       $v0, $zero, 0xB
    /* 2507C 8003487C 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 25080 80034880 4ED0000C */  jal        func_80034138
    /* 25084 80034884 00000000 */   nop
  .L80034888:
    /* 25088 80034888 2ED3000C */  jal        func_80034CB8
    /* 2508C 8003488C 03000434 */   ori       $a0, $zero, 0x3
    /* 25090 80034890 61D0000C */  jal        func_80034184
    /* 25094 80034894 00000000 */   nop
    /* 25098 80034898 FBFF4014 */  bnez       $v0, .L80034888
    /* 2509C 8003489C 0B000234 */   ori       $v0, $zero, 0xB
  .L800348A0:
    /* 250A0 800348A0 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 250A4 800348A4 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 250A8 800348A8 40D20008 */  j          .L80034900
    /* 250AC 800348AC 00000000 */   nop
  .L800348B0:
    /* 250B0 800348B0 76F3000C */  jal        VSync
    /* 250B4 800348B4 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 250B8 800348B8 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 250BC 800348BC 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 250C0 800348C0 0000A38C */  lw         $v1, 0x0($a1)
    /* 250C4 800348C4 21204000 */  addu       $a0, $v0, $zero
    /* 250C8 800348C8 0D006410 */  beq        $v1, $a0, .L80034900
    /* 250CC 800348CC 100E0334 */   ori       $v1, $zero, 0xE10
    /* 250D0 800348D0 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 250D4 800348D4 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 250D8 800348D8 0000A4AC */  sw         $a0, 0x0($a1)
    /* 250DC 800348DC 01004224 */  addiu      $v0, $v0, 0x1
    /* 250E0 800348E0 0780013C */  lui        $at, %hi(D_8006E240)
    /* 250E4 800348E4 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 250E8 800348E8 05004314 */  bne        $v0, $v1, .L80034900
    /* 250EC 800348EC 0B000234 */   ori       $v0, $zero, 0xB
    /* 250F0 800348F0 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 250F4 800348F4 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 250F8 800348F8 2ED3000C */  jal        func_80034CB8
    /* 250FC 800348FC 03000434 */   ori       $a0, $zero, 0x3
  .L80034900:
    /* 25100 80034900 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25104 80034904 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25108 80034908 0800E003 */  jr         $ra
    /* 2510C 8003490C 00000000 */   nop
endlabel func_80034818

nonmatching func_80034910, 0x80

glabel func_80034910
    /* 25110 80034910 0780023C */  lui        $v0, %hi(D_80071B98)
    /* 25114 80034914 981B428C */  lw         $v0, %lo(D_80071B98)($v0)
    /* 25118 80034918 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2511C 8003491C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25120 80034920 0780013C */  lui        $at, %hi(D_8006E244)
    /* 25124 80034924 44E222AC */  sw         $v0, %lo(D_8006E244)($at)
    /* 25128 80034928 0900422C */  sltiu      $v0, $v0, 0x9
    /* 2512C 8003492C 03004014 */  bnez       $v0, .L8003493C
    /* 25130 80034930 09000234 */   ori       $v0, $zero, 0x9
    /* 25134 80034934 0780013C */  lui        $at, %hi(D_8006E244)
    /* 25138 80034938 44E222AC */  sw         $v0, %lo(D_8006E244)($at)
  .L8003493C:
    /* 2513C 8003493C 0780043C */  lui        $a0, %hi(D_8006E244)
    /* 25140 80034940 44E2848C */  lw         $a0, %lo(D_8006E244)($a0)
    /* 25144 80034944 0780053C */  lui        $a1, %hi(D_80069A3C)
    /* 25148 80034948 3C9AA524 */  addiu      $a1, $a1, %lo(D_80069A3C)
    /* 2514C 8003494C 1307010C */  jal        func_80041C4C
    /* 25150 80034950 80000634 */   ori       $a2, $zero, 0x80
    /* 25154 80034954 08004014 */  bnez       $v0, .L80034978
    /* 25158 80034958 0E000234 */   ori       $v0, $zero, 0xE
    /* 2515C 8003495C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25160 80034960 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 25164 80034964 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 25168 80034968 2ED3000C */  jal        func_80034CB8
    /* 2516C 8003496C 03000434 */   ori       $a0, $zero, 0x3
    /* 25170 80034970 60D20008 */  j          .L80034980
    /* 25174 80034974 00000000 */   nop
  .L80034978:
    /* 25178 80034978 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 2517C 8003497C 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
  .L80034980:
    /* 25180 80034980 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25184 80034984 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25188 80034988 0800E003 */  jr         $ra
    /* 2518C 8003498C 00000000 */   nop
endlabel func_80034910

nonmatching func_80034990, 0xD4

glabel func_80034990
    /* 25190 80034990 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 25194 80034994 01000434 */  ori        $a0, $zero, 0x1
    /* 25198 80034998 21280000 */  addu       $a1, $zero, $zero
    /* 2519C 8003499C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 251A0 800349A0 5507010C */  jal        func_80041D54
    /* 251A4 800349A4 1000B0AF */   sw        $s0, 0x10($sp)
    /* 251A8 800349A8 21184000 */  addu       $v1, $v0, $zero
    /* 251AC 800349AC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 251B0 800349B0 1D006210 */  beq        $v1, $v0, .L80034A28
    /* 251B4 800349B4 00000000 */   nop
    /* 251B8 800349B8 25006014 */  bnez       $v1, .L80034A50
    /* 251BC 800349BC 00000000 */   nop
    /* 251C0 800349C0 0780023C */  lui        $v0, %hi(D_80069A3C)
    /* 251C4 800349C4 3C9A4224 */  addiu      $v0, $v0, %lo(D_80069A3C)
    /* 251C8 800349C8 0780103C */  lui        $s0, %hi(g_cd_unknown_80071B8C)
    /* 251CC 800349CC 8C1B1026 */  addiu      $s0, $s0, %lo(g_cd_unknown_80071B8C)
    /* 251D0 800349D0 0380013C */  lui        $at, %hi(D_80034CFC)
    /* 251D4 800349D4 FC4C22AC */  sw         $v0, %lo(D_80034CFC)($at)
    /* 251D8 800349D8 0780023C */  lui        $v0, %hi(D_80071B98)
    /* 251DC 800349DC 981B428C */  lw         $v0, %lo(D_80071B98)($v0)
    /* 251E0 800349E0 9001838F */  lw         $v1, %gp_rel(D_80062E88)($gp)
    /* 251E4 800349E4 F7FF4224 */  addiu      $v0, $v0, -0x9
    /* 251E8 800349E8 09006324 */  addiu      $v1, $v1, 0x9
    /* 251EC 800349EC 0780013C */  lui        $at, %hi(D_80071B98)
    /* 251F0 800349F0 981B22AC */  sw         $v0, %lo(D_80071B98)($at)
    /* 251F4 800349F4 900183AF */  sw         $v1, %gp_rel(D_80062E88)($gp)
    /* 251F8 800349F8 5AD3000C */  jal        func_80034D68
    /* 251FC 800349FC 00000000 */   nop
    /* 25200 80034A00 03004014 */  bnez       $v0, .L80034A10
    /* 25204 80034A04 11000234 */   ori       $v0, $zero, 0x11
    /* 25208 80034A08 94D20008 */  j          .L80034A50
    /* 2520C 80034A0C 000002AE */   sw        $v0, 0x0($s0)
  .L80034A10:
    /* 25210 80034A10 9001848F */  lw         $a0, %gp_rel(D_80062E88)($gp)
    /* 25214 80034A14 7DF8000C */  jal        func_8003E1F4
    /* 25218 80034A18 08000526 */   addiu     $a1, $s0, 0x8
    /* 2521C 80034A1C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25220 80034A20 94D20008 */  j          .L80034A50
    /* 25224 80034A24 000002AE */   sw        $v0, 0x0($s0)
  .L80034A28:
    /* 25228 80034A28 9001848F */  lw         $a0, %gp_rel(D_80062E88)($gp)
    /* 2522C 80034A2C 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 25230 80034A30 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 25234 80034A34 7DF8000C */  jal        func_8003E1F4
    /* 25238 80034A38 00000000 */   nop
    /* 2523C 80034A3C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25240 80034A40 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 25244 80034A44 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 25248 80034A48 2ED3000C */  jal        func_80034CB8
    /* 2524C 80034A4C 03000434 */   ori       $a0, $zero, 0x3
  .L80034A50:
    /* 25250 80034A50 1400BF8F */  lw         $ra, 0x14($sp)
    /* 25254 80034A54 1000B08F */  lw         $s0, 0x10($sp)
    /* 25258 80034A58 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2525C 80034A5C 0800E003 */  jr         $ra
    /* 25260 80034A60 00000000 */   nop
endlabel func_80034990

nonmatching func_80034A64, 0x38

glabel func_80034A64
    /* 25264 80034A64 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 25268 80034A68 09000434 */  ori        $a0, $zero, 0x9
    /* 2526C 80034A6C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25270 80034A70 BEF7000C */  jal        func_8003DEF8
    /* 25274 80034A74 21280000 */   addu      $a1, $zero, $zero
    /* 25278 80034A78 14000234 */  ori        $v0, $zero, 0x14
    /* 2527C 80034A7C 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 25280 80034A80 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 25284 80034A84 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25288 80034A88 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 2528C 80034A8C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25290 80034A90 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25294 80034A94 0800E003 */  jr         $ra
    /* 25298 80034A98 00000000 */   nop
endlabel func_80034A64

nonmatching func_80034A9C, 0xB4

glabel func_80034A9C
    /* 2529C 80034A9C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 252A0 80034AA0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 252A4 80034AA4 01000434 */  ori        $a0, $zero, 0x1
    /* 252A8 80034AA8 54F7000C */  jal        func_8003DD50
    /* 252AC 80034AAC 21280000 */   addu      $a1, $zero, $zero
    /* 252B0 80034AB0 21184000 */  addu       $v1, $v0, $zero
    /* 252B4 80034AB4 02000234 */  ori        $v0, $zero, 0x2
    /* 252B8 80034AB8 05006210 */  beq        $v1, $v0, .L80034AD0
    /* 252BC 80034ABC 05000234 */   ori       $v0, $zero, 0x5
    /* 252C0 80034AC0 07006210 */  beq        $v1, $v0, .L80034AE0
    /* 252C4 80034AC4 13000234 */   ori       $v0, $zero, 0x13
    /* 252C8 80034AC8 BCD20008 */  j          .L80034AF0
    /* 252CC 80034ACC 00000000 */   nop
  .L80034AD0:
    /* 252D0 80034AD0 1ED1000C */  jal        func_80034478
    /* 252D4 80034AD4 00000000 */   nop
    /* 252D8 80034AD8 D0D20008 */  j          .L80034B40
    /* 252DC 80034ADC 00000000 */   nop
  .L80034AE0:
    /* 252E0 80034AE0 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 252E4 80034AE4 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 252E8 80034AE8 D0D20008 */  j          .L80034B40
    /* 252EC 80034AEC 00000000 */   nop
  .L80034AF0:
    /* 252F0 80034AF0 76F3000C */  jal        VSync
    /* 252F4 80034AF4 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 252F8 80034AF8 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 252FC 80034AFC 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 25300 80034B00 0000A38C */  lw         $v1, 0x0($a1)
    /* 25304 80034B04 21204000 */  addu       $a0, $v0, $zero
    /* 25308 80034B08 0D006410 */  beq        $v1, $a0, .L80034B40
    /* 2530C 80034B0C 100E0334 */   ori       $v1, $zero, 0xE10
    /* 25310 80034B10 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 25314 80034B14 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 25318 80034B18 0000A4AC */  sw         $a0, 0x0($a1)
    /* 2531C 80034B1C 01004224 */  addiu      $v0, $v0, 0x1
    /* 25320 80034B20 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25324 80034B24 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 25328 80034B28 05004314 */  bne        $v0, $v1, .L80034B40
    /* 2532C 80034B2C 13000234 */   ori       $v0, $zero, 0x13
    /* 25330 80034B30 0780013C */  lui        $at, %hi(g_cd_unknown_80071B8C)
    /* 25334 80034B34 8C1B22AC */  sw         $v0, %lo(g_cd_unknown_80071B8C)($at)
    /* 25338 80034B38 2ED3000C */  jal        func_80034CB8
    /* 2533C 80034B3C 03000434 */   ori       $a0, $zero, 0x3
  .L80034B40:
    /* 25340 80034B40 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25344 80034B44 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25348 80034B48 0800E003 */  jr         $ra
    /* 2534C 80034B4C 00000000 */   nop
endlabel func_80034A9C

nonmatching func_80034B50, 0x6C

glabel func_80034B50
    /* 25350 80034B50 0780023C */  lui        $v0, %hi(g_cd_unknown_80071B8C)
    /* 25354 80034B54 8C1B428C */  lw         $v0, %lo(g_cd_unknown_80071B8C)($v0)
    /* 25358 80034B58 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2535C 80034B5C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 25360 80034B60 1500422C */  sltiu      $v0, $v0, 0x15
    /* 25364 80034B64 03004014 */  bnez       $v0, .L80034B74
    /* 25368 80034B68 1000B0AF */   sw        $s0, 0x10($sp)
  .L80034B6C:
    /* 2536C 80034B6C DBD20008 */  j          .L80034B6C
    /* 25370 80034B70 00000000 */   nop
  .L80034B74:
    /* 25374 80034B74 0780103C */  lui        $s0, %hi(g_cd_unknown_80071B8C)
    /* 25378 80034B78 8C1B1026 */  addiu      $s0, $s0, %lo(g_cd_unknown_80071B8C)
    /* 2537C 80034B7C 0000028E */  lw         $v0, 0x0($s0)
    /* 25380 80034B80 00000000 */  nop
    /* 25384 80034B84 80100200 */  sll        $v0, $v0, 2
    /* 25388 80034B88 0580013C */  lui        $at, %hi(D_8004A5E8)
    /* 2538C 80034B8C E8A52124 */  addiu      $at, $at, %lo(D_8004A5E8)
    /* 25390 80034B90 21082200 */  addu       $at, $at, $v0
    /* 25394 80034B94 0000228C */  lw         $v0, 0x0($at)
    /* 25398 80034B98 00000000 */  nop
    /* 2539C 80034B9C 09F84000 */  jalr       $v0
    /* 253A0 80034BA0 00000000 */   nop
    /* 253A4 80034BA4 0000028E */  lw         $v0, 0x0($s0)
    /* 253A8 80034BA8 1400BF8F */  lw         $ra, 0x14($sp)
    /* 253AC 80034BAC 1000B08F */  lw         $s0, 0x10($sp)
    /* 253B0 80034BB0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 253B4 80034BB4 0800E003 */  jr         $ra
    /* 253B8 80034BB8 00000000 */   nop
endlabel func_80034B50

nonmatching func_80034BBC, 0xFC

glabel func_80034BBC
    /* 253BC 80034BBC 21308000 */  addu       $a2, $a0, $zero
    /* 253C0 80034BC0 21400000 */  addu       $t0, $zero, $zero
    /* 253C4 80034BC4 21380000 */  addu       $a3, $zero, $zero
    /* 253C8 80034BC8 0000C28C */  lw         $v0, 0x0($a2)
    /* 253CC 80034BCC 2148A000 */  addu       $t1, $a1, $zero
    /* 253D0 80034BD0 2110C200 */  addu       $v0, $a2, $v0
    /* 253D4 80034BD4 04004A24 */  addiu      $t2, $v0, 0x4
    /* 253D8 80034BD8 0400C624 */  addiu      $a2, $a2, 0x4
  .L80034BDC:
    /* 253DC 80034BDC 07000015 */  bnez       $t0, .L80034BFC
    /* 253E0 80034BE0 0100E230 */   andi      $v0, $a3, 0x1
    /* 253E4 80034BE4 2B10CA00 */  sltu       $v0, $a2, $t2
    /* 253E8 80034BE8 31004010 */  beqz       $v0, .L80034CB0
    /* 253EC 80034BEC 08000834 */   ori       $t0, $zero, 0x8
    /* 253F0 80034BF0 0000C790 */  lbu        $a3, 0x0($a2)
    /* 253F4 80034BF4 0100C624 */  addiu      $a2, $a2, 0x1
    /* 253F8 80034BF8 0100E230 */  andi       $v0, $a3, 0x1
  .L80034BFC:
    /* 253FC 80034BFC 08004010 */  beqz       $v0, .L80034C20
    /* 25400 80034C00 2B10CA00 */   sltu      $v0, $a2, $t2
    /* 25404 80034C04 2A004010 */  beqz       $v0, .L80034CB0
    /* 25408 80034C08 00000000 */   nop
    /* 2540C 80034C0C 0000C290 */  lbu        $v0, 0x0($a2)
    /* 25410 80034C10 0100C624 */  addiu      $a2, $a2, 0x1
    /* 25414 80034C14 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 25418 80034C18 29D30008 */  j          .L80034CA4
    /* 2541C 80034C1C 0100A524 */   addiu     $a1, $a1, 0x1
  .L80034C20:
    /* 25420 80034C20 23004010 */  beqz       $v0, .L80034CB0
    /* 25424 80034C24 00000000 */   nop
    /* 25428 80034C28 0000C490 */  lbu        $a0, 0x0($a2)
    /* 2542C 80034C2C 0100C624 */  addiu      $a2, $a2, 0x1
    /* 25430 80034C30 0000C390 */  lbu        $v1, 0x0($a2)
    /* 25434 80034C34 0100C624 */  addiu      $a2, $a2, 0x1
    /* 25438 80034C38 F0006230 */  andi       $v0, $v1, 0xF0
    /* 2543C 80034C3C 00110200 */  sll        $v0, $v0, 4
    /* 25440 80034C40 25208200 */  or         $a0, $a0, $v0
    /* 25444 80034C44 2310A900 */  subu       $v0, $a1, $t1
    /* 25448 80034C48 EE0F4224 */  addiu      $v0, $v0, 0xFEE
    /* 2544C 80034C4C 23104400 */  subu       $v0, $v0, $a0
    /* 25450 80034C50 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 25454 80034C54 2320A200 */  subu       $a0, $a1, $v0
    /* 25458 80034C58 0F006330 */  andi       $v1, $v1, 0xF
    /* 2545C 80034C5C 2118A300 */  addu       $v1, $a1, $v1
    /* 25460 80034C60 2B108900 */  sltu       $v0, $a0, $t1
    /* 25464 80034C64 0C004010 */  beqz       $v0, .L80034C98
    /* 25468 80034C68 03006324 */   addiu     $v1, $v1, 0x3
  .L80034C6C:
    /* 2546C 80034C6C 0000A0A0 */  sb         $zero, 0x0($a1)
    /* 25470 80034C70 01008424 */  addiu      $a0, $a0, 0x1
    /* 25474 80034C74 2B108900 */  sltu       $v0, $a0, $t1
    /* 25478 80034C78 FCFF4014 */  bnez       $v0, .L80034C6C
    /* 2547C 80034C7C 0100A524 */   addiu     $a1, $a1, 0x1
    /* 25480 80034C80 27D30008 */  j          .L80034C9C
    /* 25484 80034C84 2B10A300 */   sltu      $v0, $a1, $v1
  .L80034C88:
    /* 25488 80034C88 00008290 */  lbu        $v0, 0x0($a0)
    /* 2548C 80034C8C 01008424 */  addiu      $a0, $a0, 0x1
    /* 25490 80034C90 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 25494 80034C94 0100A524 */  addiu      $a1, $a1, 0x1
  .L80034C98:
    /* 25498 80034C98 2B10A300 */  sltu       $v0, $a1, $v1
  .L80034C9C:
    /* 2549C 80034C9C FAFF4014 */  bnez       $v0, .L80034C88
    /* 254A0 80034CA0 00000000 */   nop
  .L80034CA4:
    /* 254A4 80034CA4 43380700 */  sra        $a3, $a3, 1
    /* 254A8 80034CA8 F7D20008 */  j          .L80034BDC
    /* 254AC 80034CAC FFFF0825 */   addiu     $t0, $t0, -0x1
  .L80034CB0:
    /* 254B0 80034CB0 0800E003 */  jr         $ra
    /* 254B4 80034CB4 00000000 */   nop
endlabel func_80034BBC

nonmatching func_80034CB8, 0x44

glabel func_80034CB8
    /* 254B8 80034CB8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 254BC 80034CBC 30000234 */  ori        $v0, $zero, 0x30
    /* 254C0 80034CC0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 254C4 80034CC4 0A80013C */  lui        $at, %hi(D_8009A118)
    /* 254C8 80034CC8 18A122A4 */  sh         $v0, %lo(D_8009A118)($at)
    /* 254CC 80034CCC 0A80013C */  lui        $at, %hi(D_8009A11C)
    /* 254D0 80034CD0 1CA124AC */  sw         $a0, %lo(D_8009A11C)($at)
    /* 254D4 80034CD4 0A80013C */  lui        $at, %hi(D_8009A120)
    /* 254D8 80034CD8 20A124AC */  sw         $a0, %lo(D_8009A120)($at)
    /* 254DC 80034CDC B5B6000C */  jal        func_8002DAD4
    /* 254E0 80034CE0 00000000 */   nop
    /* 254E4 80034CE4 76F3000C */  jal        VSync
    /* 254E8 80034CE8 3C000434 */   ori       $a0, $zero, 0x3C
    /* 254EC 80034CEC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 254F0 80034CF0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 254F4 80034CF4 0800E003 */  jr         $ra
    /* 254F8 80034CF8 00000000 */   nop
endlabel func_80034CB8
  alabel D_80034CFC
    /* 254FC 80034CFC 00000000 */  nop
  alabel D_80034D00
    /* 25500 80034D00 00000000 */  nop
  alabel D_80034D04
    /* 25504 80034D04 00000000 */  nop
  alabel D_80034D08
    /* 25508 80034D08 00000000 */  nop
  alabel D_80034D0C
    /* 2550C 80034D0C 00000000 */  nop
  alabel D_80034D10
    /* 25510 80034D10 00000000 */  nop
  alabel D_80034D14
    /* 25514 80034D14 00000000 */  nop
    /* 25518 80034D18 00000000 */  nop
  alabel D_80034D1C
    /* 2551C 80034D1C 00000000 */  nop
  jtbl_80034D20:
    /* 25520 80034D20 00000000 */  nop

nonmatching func_80034D24, 0x14

glabel func_80034D24
    /* 25524 80034D24 80280500 */  sll        $a1, $a1, 2
    /* 25528 80034D28 21188500 */  addu       $v1, $a0, $a1
    /* 2552C 80034D2C 0000628C */  lw         $v0, 0x0($v1)
    /* 25530 80034D30 0800E003 */  jr         $ra
    /* 25534 80034D34 21104400 */   addu      $v0, $v0, $a0
endlabel func_80034D24

nonmatching func_80034D38, 0x30

glabel func_80034D38
    /* 25538 80034D38 0380023C */  lui        $v0, %hi(func_80034E0C)
    /* 2553C 80034D3C 0C4E4224 */  addiu      $v0, $v0, %lo(func_80034E0C)
    /* 25540 80034D40 0380013C */  lui        $at, %hi(D_80034CFC)
    /* 25544 80034D44 FC4C24AC */  sw         $a0, %lo(D_80034CFC)($at)
    /* 25548 80034D48 0380013C */  lui        $at, %hi(D_80034D00)
    /* 2554C 80034D4C 004D25AC */  sw         $a1, %lo(D_80034D00)($at)
    /* 25550 80034D50 0380013C */  lui        $at, %hi(D_80034D08)
    /* 25554 80034D54 084D25AC */  sw         $a1, %lo(D_80034D08)($at)
    /* 25558 80034D58 0380013C */  lui        $at, %hi(jtbl_80034D20)
    /* 2555C 80034D5C 204D22AC */  sw         $v0, %lo(jtbl_80034D20)($at)
    /* 25560 80034D60 0800E003 */  jr         $ra
    /* 25564 80034D64 00000000 */   nop
endlabel func_80034D38

nonmatching func_80034D68, 0x54

glabel func_80034D68
    /* 25568 80034D68 0380023C */  lui        $v0, %hi(jtbl_80034D20)
    /* 2556C 80034D6C 204D428C */  lw         $v0, %lo(jtbl_80034D20)($v0)
    /* 25570 80034D70 0380083C */  lui        $t0, %hi(D_80034CFC)
    /* 25574 80034D74 FC4C088D */  lw         $t0, %lo(D_80034CFC)($t0)
    /* 25578 80034D78 0380093C */  lui        $t1, %hi(D_80034D00)
    /* 2557C 80034D7C 004D298D */  lw         $t1, %lo(D_80034D00)($t1)
    /* 25580 80034D80 03800A3C */  lui        $t2, %hi(D_80034D04)
    /* 25584 80034D84 044D4A8D */  lw         $t2, %lo(D_80034D04)($t2)
    /* 25588 80034D88 03800C3C */  lui        $t4, %hi(D_80034D08)
    /* 2558C 80034D8C 084D8C8D */  lw         $t4, %lo(D_80034D08)($t4)
    /* 25590 80034D90 03800D3C */  lui        $t5, %hi(D_80034D0C)
    /* 25594 80034D94 0C4DAD8D */  lw         $t5, %lo(D_80034D0C)($t5)
    /* 25598 80034D98 03800E3C */  lui        $t6, %hi(D_80034D10)
    /* 2559C 80034D9C 104DCE8D */  lw         $t6, %lo(D_80034D10)($t6)
    /* 255A0 80034DA0 00480F34 */  ori        $t7, $zero, 0x4800
    /* 255A4 80034DA4 0380043C */  lui        $a0, %hi(D_80034D14)
    /* 255A8 80034DA8 144D848C */  lw         $a0, %lo(D_80034D14)($a0)
    /* 255AC 80034DAC 0380013C */  lui        $at, %hi(D_80034D1C)
    /* 255B0 80034DB0 1C4D3FAC */  sw         $ra, %lo(D_80034D1C)($at)
    /* 255B4 80034DB4 08004000 */  jr         $v0
    /* 255B8 80034DB8 00000000 */   nop
endlabel func_80034D68

nonmatching func_80034DBC, 0x50

glabel func_80034DBC
    /* 255BC 80034DBC 0380013C */  lui        $at, %hi(jtbl_80034D20)
    /* 255C0 80034DC0 204D3FAC */  sw         $ra, %lo(jtbl_80034D20)($at)
    /* 255C4 80034DC4 03801F3C */  lui        $ra, %hi(D_80034D1C)
    /* 255C8 80034DC8 1C4DFF8F */  lw         $ra, %lo(D_80034D1C)($ra)
    /* 255CC 80034DCC 0380013C */  lui        $at, %hi(D_80034CFC)
    /* 255D0 80034DD0 FC4C28AC */  sw         $t0, %lo(D_80034CFC)($at)
    /* 255D4 80034DD4 0380013C */  lui        $at, %hi(D_80034D00)
    /* 255D8 80034DD8 004D29AC */  sw         $t1, %lo(D_80034D00)($at)
    /* 255DC 80034DDC 0380013C */  lui        $at, %hi(D_80034D04)
    /* 255E0 80034DE0 044D2AAC */  sw         $t2, %lo(D_80034D04)($at)
    /* 255E4 80034DE4 0380013C */  lui        $at, %hi(D_80034D08)
    /* 255E8 80034DE8 084D2CAC */  sw         $t4, %lo(D_80034D08)($at)
    /* 255EC 80034DEC 0380013C */  lui        $at, %hi(D_80034D0C)
    /* 255F0 80034DF0 0C4D2DAC */  sw         $t5, %lo(D_80034D0C)($at)
    /* 255F4 80034DF4 0380013C */  lui        $at, %hi(D_80034D10)
    /* 255F8 80034DF8 104D2EAC */  sw         $t6, %lo(D_80034D10)($at)
    /* 255FC 80034DFC 0380013C */  lui        $at, %hi(D_80034D14)
    /* 25600 80034E00 144D24AC */  sw         $a0, %lo(D_80034D14)($at)
    /* 25604 80034E04 0800E003 */  jr         $ra
    /* 25608 80034E08 01000234 */   ori       $v0, $zero, 0x1
endlabel func_80034DBC

nonmatching func_80034E0C, 0x13C

glabel func_80034E0C
    /* 2560C 80034E0C 00000A8D */  lw         $t2, 0x0($t0)
    /* 25610 80034E10 04000825 */  addiu      $t0, $t0, 0x4
    /* 25614 80034E14 FCFFEF25 */  addiu      $t7, $t7, -0x4
    /* 25618 80034E18 21700000 */  addu       $t6, $zero, $zero
  .L80034E1C:
    /* 2561C 80034E1C 0B00C015 */  bnez       $t6, .L80034E4C
    /* 25620 80034E20 00000000 */   nop
    /* 25624 80034E24 08000E34 */  ori        $t6, $zero, 0x8
    /* 25628 80034E28 00000D91 */  lbu        $t5, 0x0($t0)
    /* 2562C 80034E2C 01000825 */  addiu      $t0, $t0, 0x1
    /* 25630 80034E30 FFFF4A25 */  addiu      $t2, $t2, -0x1
    /* 25634 80034E34 42004011 */  beqz       $t2, .L80034F40
    /* 25638 80034E38 FFFFEF25 */   addiu     $t7, $t7, -0x1
    /* 2563C 80034E3C 0300E015 */  bnez       $t7, .L80034E4C
    /* 25640 80034E40 00000000 */   nop
    /* 25644 80034E44 6FD3000C */  jal        func_80034DBC
    /* 25648 80034E48 00000000 */   nop
  .L80034E4C:
    /* 2564C 80034E4C 0100A231 */  andi       $v0, $t5, 0x1
    /* 25650 80034E50 0D004010 */  beqz       $v0, .L80034E88
    /* 25654 80034E54 00000000 */   nop
    /* 25658 80034E58 00000291 */  lbu        $v0, 0x0($t0)
    /* 2565C 80034E5C 01000825 */  addiu      $t0, $t0, 0x1
    /* 25660 80034E60 000022A1 */  sb         $v0, 0x0($t1)
    /* 25664 80034E64 01002925 */  addiu      $t1, $t1, 0x1
    /* 25668 80034E68 FFFF4A25 */  addiu      $t2, $t2, -0x1
    /* 2566C 80034E6C 34004011 */  beqz       $t2, .L80034F40
    /* 25670 80034E70 FFFFEF25 */   addiu     $t7, $t7, -0x1
    /* 25674 80034E74 2E00E015 */  bnez       $t7, .L80034F30
    /* 25678 80034E78 00000000 */   nop
    /* 2567C 80034E7C 6FD3000C */  jal        func_80034DBC
    /* 25680 80034E80 00000000 */   nop
    /* 25684 80034E84 CCD30008 */  j          .L80034F30
  .L80034E88:
    /* 25688 80034E88 00000491 */   lbu       $a0, 0x0($t0)
    /* 2568C 80034E8C 01000825 */  addiu      $t0, $t0, 0x1
    /* 25690 80034E90 FFFFEF25 */  addiu      $t7, $t7, -0x1
    /* 25694 80034E94 0300E015 */  bnez       $t7, .L80034EA4
    /* 25698 80034E98 00000000 */   nop
    /* 2569C 80034E9C 6FD3000C */  jal        func_80034DBC
    /* 256A0 80034EA0 00000000 */   nop
  .L80034EA4:
    /* 256A4 80034EA4 00000591 */  lbu        $a1, 0x0($t0)
    /* 256A8 80034EA8 01000825 */  addiu      $t0, $t0, 0x1
    /* 256AC 80034EAC F000A230 */  andi       $v0, $a1, 0xF0
    /* 256B0 80034EB0 00110200 */  sll        $v0, $v0, 4
    /* 256B4 80034EB4 25208200 */  or         $a0, $a0, $v0
    /* 256B8 80034EB8 0F00A230 */  andi       $v0, $a1, 0xF
    /* 256BC 80034EBC 21582201 */  addu       $t3, $t1, $v0
    /* 256C0 80034EC0 03006B25 */  addiu      $t3, $t3, 0x3
    /* 256C4 80034EC4 12F08224 */  addiu      $v0, $a0, -0xFEE
    /* 256C8 80034EC8 23182C01 */  subu       $v1, $t1, $t4
    /* 256CC 80034ECC 23106200 */  subu       $v0, $v1, $v0
    /* 256D0 80034ED0 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 256D4 80034ED4 23382201 */  subu       $a3, $t1, $v0
  .L80034ED8:
    /* 256D8 80034ED8 2B10EC00 */  sltu       $v0, $a3, $t4
    /* 256DC 80034EDC 05004010 */  beqz       $v0, .L80034EF4
    /* 256E0 80034EE0 00000000 */   nop
    /* 256E4 80034EE4 000020A1 */  sb         $zero, 0x0($t1)
    /* 256E8 80034EE8 01002925 */  addiu      $t1, $t1, 0x1
    /* 256EC 80034EEC B6D30008 */  j          .L80034ED8
    /* 256F0 80034EF0 0100E724 */   addiu     $a3, $a3, 0x1
  .L80034EF4:
    /* 256F4 80034EF4 2B102B01 */  sltu       $v0, $t1, $t3
    /* 256F8 80034EF8 06004010 */  beqz       $v0, .L80034F14
    /* 256FC 80034EFC 00000000 */   nop
    /* 25700 80034F00 0000E290 */  lbu        $v0, 0x0($a3)
    /* 25704 80034F04 0100E724 */  addiu      $a3, $a3, 0x1
    /* 25708 80034F08 000022A1 */  sb         $v0, 0x0($t1)
    /* 2570C 80034F0C BDD30008 */  j          .L80034EF4
    /* 25710 80034F10 01002925 */   addiu     $t1, $t1, 0x1
  .L80034F14:
    /* 25714 80034F14 FEFF4A25 */  addiu      $t2, $t2, -0x2
    /* 25718 80034F18 09004011 */  beqz       $t2, .L80034F40
    /* 2571C 80034F1C FFFFEF25 */   addiu     $t7, $t7, -0x1
    /* 25720 80034F20 0300E01D */  bgtz       $t7, .L80034F30
    /* 25724 80034F24 00000000 */   nop
    /* 25728 80034F28 6FD3000C */  jal        func_80034DBC
    /* 2572C 80034F2C 00000000 */   nop
  .L80034F30:
    /* 25730 80034F30 43680D00 */  sra        $t5, $t5, 1
    /* 25734 80034F34 FFFFCE25 */  addiu      $t6, $t6, -0x1
    /* 25738 80034F38 87D30008 */  j          .L80034E1C
    /* 2573C 80034F3C 00000000 */   nop
  .L80034F40:
    /* 25740 80034F40 0800E003 */  jr         $ra
    /* 25744 80034F44 21100000 */   addu      $v0, $zero, $zero
endlabel func_80034E0C
