.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80033C38, 0x40

glabel func_80033C38
    /* 24438 80033C38 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2443C 80033C3C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24440 80033C40 30D0000C */  jal        func_800340C0
    /* 24444 80033C44 00000000 */   nop
  .L80033C48:
    /* 24448 80033C48 D4D2000C */  jal        func_80034B50
    /* 2444C 80033C4C 00000000 */   nop
    /* 24450 80033C50 FDFF4014 */  bnez       $v0, .L80033C48
    /* 24454 80033C54 00000000 */   nop
    /* 24458 80033C58 2AF7000C */  jal        func_8003DCA8
    /* 2445C 80033C5C 00000000 */   nop
    /* 24460 80033C60 0FF7000C */  jal        func_8003DC3C
    /* 24464 80033C64 21200000 */   addu      $a0, $zero, $zero
    /* 24468 80033C68 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2446C 80033C6C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24470 80033C70 0800E003 */  jr         $ra
    /* 24474 80033C74 00000000 */   nop
endlabel func_80033C38

nonmatching func_80033C78, 0x78

glabel func_80033C78
    /* 24478 80033C78 0A80023C */  lui        $v0, %hi(D_8009A218)
    /* 2447C 80033C7C 18A2428C */  lw         $v0, %lo(D_8009A218)($v0)
    /* 24480 80033C80 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24484 80033C84 01004230 */  andi       $v0, $v0, 0x1
    /* 24488 80033C88 07004010 */  beqz       $v0, .L80033CA8
    /* 2448C 80033C8C 1000BFAF */   sw        $ra, 0x10($sp)
    /* 24490 80033C90 8C0184A3 */  sb         $a0, %gp_rel(D_80062E84)($gp)
    /* 24494 80033C94 8D0185A3 */  sb         $a1, %gp_rel(D_80062E85)($gp)
    /* 24498 80033C98 8E0186A3 */  sb         $a2, %gp_rel(D_80062E86)($gp)
    /* 2449C 80033C9C 8F0187A3 */  sb         $a3, %gp_rel(D_80062E87)($gp)
    /* 244A0 80033CA0 34CF0008 */  j          .L80033CD0
    /* 244A4 80033CA4 00000000 */   nop
  .L80033CA8:
    /* 244A8 80033CA8 C2170400 */  srl        $v0, $a0, 31
    /* 244AC 80033CAC 21108200 */  addu       $v0, $a0, $v0
    /* 244B0 80033CB0 43100200 */  sra        $v0, $v0, 1
    /* 244B4 80033CB4 8C0182A3 */  sb         $v0, %gp_rel(D_80062E84)($gp)
    /* 244B8 80033CB8 8D0182A3 */  sb         $v0, %gp_rel(D_80062E85)($gp)
    /* 244BC 80033CBC C2170600 */  srl        $v0, $a2, 31
    /* 244C0 80033CC0 2110C200 */  addu       $v0, $a2, $v0
    /* 244C4 80033CC4 43100200 */  sra        $v0, $v0, 1
    /* 244C8 80033CC8 8E0182A3 */  sb         $v0, %gp_rel(D_80062E86)($gp)
    /* 244CC 80033CCC 8F0182A3 */  sb         $v0, %gp_rel(D_80062E87)($gp)
  .L80033CD0:
    /* 244D0 80033CD0 0680043C */  lui        $a0, %hi(D_80062E84)
    /* 244D4 80033CD4 842E8424 */  addiu      $a0, $a0, %lo(D_80062E84)
    /* 244D8 80033CD8 5AF8000C */  jal        func_8003E168
    /* 244DC 80033CDC 00000000 */   nop
    /* 244E0 80033CE0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 244E4 80033CE4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 244E8 80033CE8 0800E003 */  jr         $ra
    /* 244EC 80033CEC 00000000 */   nop
endlabel func_80033C78

nonmatching func_80033CF0, 0xF4

glabel func_80033CF0
    /* 244F0 80033CF0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 244F4 80033CF4 2800B6AF */  sw         $s6, 0x28($sp)
    /* 244F8 80033CF8 4000B68F */  lw         $s6, 0x40($sp)
    /* 244FC 80033CFC 2400B5AF */  sw         $s5, 0x24($sp)
    /* 24500 80033D00 21A88000 */  addu       $s5, $a0, $zero
    /* 24504 80033D04 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24508 80033D08 2188A000 */  addu       $s1, $a1, $zero
    /* 2450C 80033D0C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 24510 80033D10 2190C000 */  addu       $s2, $a2, $zero
    /* 24514 80033D14 2000B4AF */  sw         $s4, 0x20($sp)
    /* 24518 80033D18 21A0E000 */  addu       $s4, $a3, $zero
    /* 2451C 80033D1C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24520 80033D20 12001334 */  ori        $s3, $zero, 0x12
    /* 24524 80033D24 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 24528 80033D28 1000B0AF */  sw         $s0, 0x10($sp)
  .L80033D2C:
    /* 2452C 80033D2C D4D2000C */  jal        func_80034B50
    /* 24530 80033D30 00000000 */   nop
    /* 24534 80033D34 21804000 */  addu       $s0, $v0, $zero
    /* 24538 80033D38 0800022A */  slti       $v0, $s0, 0x8
    /* 2453C 80033D3C 0E004014 */  bnez       $v0, .L80033D78
    /* 24540 80033D40 0B00022A */   slti      $v0, $s0, 0xB
    /* 24544 80033D44 05004014 */  bnez       $v0, .L80033D5C
    /* 24548 80033D48 00000000 */   nop
    /* 2454C 80033D4C 07001312 */  beq        $s0, $s3, .L80033D6C
    /* 24550 80033D50 09000434 */   ori       $a0, $zero, 0x9
    /* 24554 80033D54 5ECF0008 */  j          .L80033D78
    /* 24558 80033D58 00000000 */   nop
  .L80033D5C:
    /* 2455C 80033D5C 81D5000C */  jal        func_80035604
    /* 24560 80033D60 00000000 */   nop
    /* 24564 80033D64 5ECF0008 */  j          .L80033D78
    /* 24568 80033D68 00000000 */   nop
  .L80033D6C:
    /* 2456C 80033D6C 21280000 */  addu       $a1, $zero, $zero
    /* 24570 80033D70 70F7000C */  jal        func_8003DDC0
    /* 24574 80033D74 21300000 */   addu      $a2, $zero, $zero
  .L80033D78:
    /* 24578 80033D78 ECFF0016 */  bnez       $s0, .L80033D2C
    /* 2457C 80033D7C 00000000 */   nop
    /* 24580 80033D80 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24584 80033D84 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24588 80033D88 7DF8000C */  jal        func_8003E1F4
    /* 2458C 80033D8C 21202002 */   addu      $a0, $s1, $zero
    /* 24590 80033D90 FF074226 */  addiu      $v0, $s2, 0x7FF
    /* 24594 80033D94 C2120200 */  srl        $v0, $v0, 11
    /* 24598 80033D98 0780013C */  lui        $at, %hi(D_80071B98)
    /* 2459C 80033D9C 981B22AC */  sw         $v0, %lo(D_80071B98)($at)
    /* 245A0 80033DA0 0780013C */  lui        $at, %hi(D_80071BAC)
    /* 245A4 80033DA4 AC1B34AC */  sw         $s4, %lo(D_80071BAC)($at)
    /* 245A8 80033DA8 0780013C */  lui        $at, %hi(D_80071BB0)
    /* 245AC 80033DAC B01B36AC */  sw         $s6, %lo(D_80071BB0)($at)
    /* 245B0 80033DB0 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 245B4 80033DB4 8C1B35AC */  sw         $s5, %lo(g_cd_task_index)($at)
    /* 245B8 80033DB8 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 245BC 80033DBC 2800B68F */  lw         $s6, 0x28($sp)
    /* 245C0 80033DC0 2400B58F */  lw         $s5, 0x24($sp)
    /* 245C4 80033DC4 2000B48F */  lw         $s4, 0x20($sp)
    /* 245C8 80033DC8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 245CC 80033DCC 1800B28F */  lw         $s2, 0x18($sp)
    /* 245D0 80033DD0 1400B18F */  lw         $s1, 0x14($sp)
    /* 245D4 80033DD4 1000B08F */  lw         $s0, 0x10($sp)
    /* 245D8 80033DD8 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 245DC 80033DDC 0800E003 */  jr         $ra
    /* 245E0 80033DE0 00000000 */   nop
endlabel func_80033CF0

nonmatching func_80033DE4, 0x38

glabel func_80033DE4
    /* 245E4 80033DE4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 245E8 80033DE8 21108000 */  addu       $v0, $a0, $zero
    /* 245EC 80033DEC 01000434 */  ori        $a0, $zero, 0x1
    /* 245F0 80033DF0 1000A5AF */  sw         $a1, 0x10($sp)
    /* 245F4 80033DF4 21284000 */  addu       $a1, $v0, $zero
    /* 245F8 80033DF8 21300000 */  addu       $a2, $zero, $zero
    /* 245FC 80033DFC 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24600 80033E00 3CCF000C */  jal        func_80033CF0
    /* 24604 80033E04 21380000 */   addu      $a3, $zero, $zero
    /* 24608 80033E08 21100000 */  addu       $v0, $zero, $zero
    /* 2460C 80033E0C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24610 80033E10 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 24614 80033E14 0800E003 */  jr         $ra
    /* 24618 80033E18 00000000 */   nop
endlabel func_80033DE4

nonmatching func_80033E1C, 0x50

glabel func_80033E1C
    /* 2461C 80033E1C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24620 80033E20 21288000 */  addu       $a1, $a0, $zero
    /* 24624 80033E24 21200000 */  addu       $a0, $zero, $zero
    /* 24628 80033E28 21300000 */  addu       $a2, $zero, $zero
    /* 2462C 80033E2C 21380000 */  addu       $a3, $zero, $zero
    /* 24630 80033E30 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24634 80033E34 3CCF000C */  jal        func_80033CF0
    /* 24638 80033E38 1000A0AF */   sw        $zero, 0x10($sp)
    /* 2463C 80033E3C 02000434 */  ori        $a0, $zero, 0x2
  .L80033E40:
    /* 24640 80033E40 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24644 80033E44 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24648 80033E48 70F7000C */  jal        func_8003DDC0
    /* 2464C 80033E4C 21300000 */   addu      $a2, $zero, $zero
    /* 24650 80033E50 FBFF4010 */  beqz       $v0, .L80033E40
    /* 24654 80033E54 02000434 */   ori       $a0, $zero, 0x2
    /* 24658 80033E58 21100000 */  addu       $v0, $zero, $zero
    /* 2465C 80033E5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24660 80033E60 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 24664 80033E64 0800E003 */  jr         $ra
    /* 24668 80033E68 00000000 */   nop
endlabel func_80033E1C

nonmatching func_80033E6C, 0x40

glabel func_80033E6C
    /* 2466C 80033E6C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24670 80033E70 21108000 */  addu       $v0, $a0, $zero
    /* 24674 80033E74 2118A000 */  addu       $v1, $a1, $zero
    /* 24678 80033E78 2140C000 */  addu       $t0, $a2, $zero
    /* 2467C 80033E7C 03000434 */  ori        $a0, $zero, 0x3
    /* 24680 80033E80 21284000 */  addu       $a1, $v0, $zero
    /* 24684 80033E84 21306000 */  addu       $a2, $v1, $zero
    /* 24688 80033E88 1000A7AF */  sw         $a3, 0x10($sp)
    /* 2468C 80033E8C 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24690 80033E90 3CCF000C */  jal        func_80033CF0
    /* 24694 80033E94 21380001 */   addu      $a3, $t0, $zero
    /* 24698 80033E98 21100000 */  addu       $v0, $zero, $zero
    /* 2469C 80033E9C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 246A0 80033EA0 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 246A4 80033EA4 0800E003 */  jr         $ra
    /* 246A8 80033EA8 00000000 */   nop
endlabel func_80033E6C

nonmatching func_80033EAC, 0x64

glabel func_80033EAC
    /* 246AC 80033EAC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 246B0 80033EB0 1800B0AF */  sw         $s0, 0x18($sp)
    /* 246B4 80033EB4 21808000 */  addu       $s0, $a0, $zero
    /* 246B8 80033EB8 2110A000 */  addu       $v0, $a1, $zero
    /* 246BC 80033EBC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 246C0 80033EC0 2188C000 */  addu       $s1, $a2, $zero
    /* 246C4 80033EC4 0B000434 */  ori        $a0, $zero, 0xB
    /* 246C8 80033EC8 21280002 */  addu       $a1, $s0, $zero
    /* 246CC 80033ECC 21304000 */  addu       $a2, $v0, $zero
    /* 246D0 80033ED0 1000A7AF */  sw         $a3, 0x10($sp)
    /* 246D4 80033ED4 2000BFAF */  sw         $ra, 0x20($sp)
    /* 246D8 80033ED8 3CCF000C */  jal        func_80033CF0
    /* 246DC 80033EDC 21382002 */   addu      $a3, $s1, $zero
    /* 246E0 80033EE0 0780043C */  lui        $a0, %hi(g_cd_diskinfo_buffer)
    /* 246E4 80033EE4 3C9A8424 */  addiu      $a0, $a0, %lo(g_cd_diskinfo_buffer)
    /* 246E8 80033EE8 900190AF */  sw         $s0, %gp_rel(D_80062E88)($gp)
    /* 246EC 80033EEC 4ED3000C */  jal        func_80034D38
    /* 246F0 80033EF0 21282002 */   addu      $a1, $s1, $zero
    /* 246F4 80033EF4 21100000 */  addu       $v0, $zero, $zero
    /* 246F8 80033EF8 2000BF8F */  lw         $ra, 0x20($sp)
    /* 246FC 80033EFC 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 24700 80033F00 1800B08F */  lw         $s0, 0x18($sp)
    /* 24704 80033F04 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24708 80033F08 0800E003 */  jr         $ra
    /* 2470C 80033F0C 00000000 */   nop
endlabel func_80033EAC

nonmatching func_80033F10, 0x64

glabel func_80033F10
    /* 24710 80033F10 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 24714 80033F14 1000B0AF */  sw         $s0, 0x10($sp)
    /* 24718 80033F18 21808000 */  addu       $s0, $a0, $zero
    /* 2471C 80033F1C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24720 80033F20 2188A000 */  addu       $s1, $a1, $zero
    /* 24724 80033F24 1800BFAF */  sw         $ra, 0x18($sp)
    /* 24728 80033F28 21200002 */  addu       $a0, $s0, $zero
  .L80033F2C:
    /* 2472C 80033F2C 79CF000C */  jal        func_80033DE4
    /* 24730 80033F30 21282002 */   addu      $a1, $s1, $zero
    /* 24734 80033F34 FDFF4014 */  bnez       $v0, .L80033F2C
    /* 24738 80033F38 21200002 */   addu      $a0, $s0, $zero
  .L80033F3C:
    /* 2473C 80033F3C D4D2000C */  jal        func_80034B50
    /* 24740 80033F40 00000000 */   nop
    /* 24744 80033F44 05004010 */  beqz       $v0, .L80033F5C
    /* 24748 80033F48 21100000 */   addu      $v0, $zero, $zero
    /* 2474C 80033F4C 76F3000C */  jal        VSync
    /* 24750 80033F50 21200000 */   addu      $a0, $zero, $zero
    /* 24754 80033F54 CFCF0008 */  j          .L80033F3C
    /* 24758 80033F58 00000000 */   nop
  .L80033F5C:
    /* 2475C 80033F5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 24760 80033F60 1400B18F */  lw         $s1, 0x14($sp)
    /* 24764 80033F64 1000B08F */  lw         $s0, 0x10($sp)
    /* 24768 80033F68 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2476C 80033F6C 0800E003 */  jr         $ra
    /* 24770 80033F70 00000000 */   nop
endlabel func_80033F10

nonmatching func_80033F74, 0x84

glabel func_80033F74
    /* 24774 80033F74 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 24778 80033F78 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2477C 80033F7C 21808000 */  addu       $s0, $a0, $zero
    /* 24780 80033F80 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24784 80033F84 2188A000 */  addu       $s1, $a1, $zero
    /* 24788 80033F88 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2478C 80033F8C 2190C000 */  addu       $s2, $a2, $zero
    /* 24790 80033F90 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24794 80033F94 2198E000 */  addu       $s3, $a3, $zero
    /* 24798 80033F98 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2479C 80033F9C 21200002 */  addu       $a0, $s0, $zero
  .L80033FA0:
    /* 247A0 80033FA0 21282002 */  addu       $a1, $s1, $zero
    /* 247A4 80033FA4 21304002 */  addu       $a2, $s2, $zero
    /* 247A8 80033FA8 9BCF000C */  jal        func_80033E6C
    /* 247AC 80033FAC 21386002 */   addu      $a3, $s3, $zero
    /* 247B0 80033FB0 FBFF4014 */  bnez       $v0, .L80033FA0
    /* 247B4 80033FB4 21200002 */   addu      $a0, $s0, $zero
  .L80033FB8:
    /* 247B8 80033FB8 D4D2000C */  jal        func_80034B50
    /* 247BC 80033FBC 00000000 */   nop
    /* 247C0 80033FC0 05004010 */  beqz       $v0, .L80033FD8
    /* 247C4 80033FC4 21100000 */   addu      $v0, $zero, $zero
    /* 247C8 80033FC8 76F3000C */  jal        VSync
    /* 247CC 80033FCC 21200000 */   addu      $a0, $zero, $zero
    /* 247D0 80033FD0 EECF0008 */  j          .L80033FB8
    /* 247D4 80033FD4 00000000 */   nop
  .L80033FD8:
    /* 247D8 80033FD8 2000BF8F */  lw         $ra, 0x20($sp)
    /* 247DC 80033FDC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 247E0 80033FE0 1800B28F */  lw         $s2, 0x18($sp)
    /* 247E4 80033FE4 1400B18F */  lw         $s1, 0x14($sp)
    /* 247E8 80033FE8 1000B08F */  lw         $s0, 0x10($sp)
    /* 247EC 80033FEC 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 247F0 80033FF0 0800E003 */  jr         $ra
    /* 247F4 80033FF4 00000000 */   nop
endlabel func_80033F74

nonmatching func_80033FF8, 0x84

glabel func_80033FF8
    /* 247F8 80033FF8 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 247FC 80033FFC 1000B0AF */  sw         $s0, 0x10($sp)
    /* 24800 80034000 21808000 */  addu       $s0, $a0, $zero
    /* 24804 80034004 1400B1AF */  sw         $s1, 0x14($sp)
    /* 24808 80034008 2188A000 */  addu       $s1, $a1, $zero
    /* 2480C 8003400C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 24810 80034010 2190C000 */  addu       $s2, $a2, $zero
    /* 24814 80034014 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 24818 80034018 2198E000 */  addu       $s3, $a3, $zero
    /* 2481C 8003401C 2000BFAF */  sw         $ra, 0x20($sp)
    /* 24820 80034020 21200002 */  addu       $a0, $s0, $zero
  .L80034024:
    /* 24824 80034024 21282002 */  addu       $a1, $s1, $zero
    /* 24828 80034028 21304002 */  addu       $a2, $s2, $zero
    /* 2482C 8003402C ABCF000C */  jal        func_80033EAC
    /* 24830 80034030 21386002 */   addu      $a3, $s3, $zero
    /* 24834 80034034 FBFF4014 */  bnez       $v0, .L80034024
    /* 24838 80034038 21200002 */   addu      $a0, $s0, $zero
  .L8003403C:
    /* 2483C 8003403C D4D2000C */  jal        func_80034B50
    /* 24840 80034040 00000000 */   nop
    /* 24844 80034044 05004010 */  beqz       $v0, .L8003405C
    /* 24848 80034048 21100000 */   addu      $v0, $zero, $zero
    /* 2484C 8003404C 76F3000C */  jal        VSync
    /* 24850 80034050 21200000 */   addu      $a0, $zero, $zero
    /* 24854 80034054 0FD00008 */  j          .L8003403C
    /* 24858 80034058 00000000 */   nop
  .L8003405C:
    /* 2485C 8003405C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 24860 80034060 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 24864 80034064 1800B28F */  lw         $s2, 0x18($sp)
    /* 24868 80034068 1400B18F */  lw         $s1, 0x14($sp)
    /* 2486C 8003406C 1000B08F */  lw         $s0, 0x10($sp)
    /* 24870 80034070 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24874 80034074 0800E003 */  jr         $ra
    /* 24878 80034078 00000000 */   nop
endlabel func_80033FF8

nonmatching func_8003407C, 0x44

glabel func_8003407C
    /* 2487C 8003407C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24880 80034080 13000234 */  ori        $v0, $zero, 0x13
    /* 24884 80034084 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24888 80034088 0780013C */  lui        $at, %hi(D_80071B98)
    /* 2488C 8003408C 981B20AC */  sw         $zero, %lo(D_80071B98)($at)
    /* 24890 80034090 0780013C */  lui        $at, %hi(D_80071BAC)
    /* 24894 80034094 AC1B20AC */  sw         $zero, %lo(D_80071BAC)($at)
    /* 24898 80034098 0780013C */  lui        $at, %hi(D_80071BB0)
    /* 2489C 8003409C B01B20AC */  sw         $zero, %lo(D_80071BB0)($at)
    /* 248A0 800340A0 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 248A4 800340A4 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 248A8 800340A8 D4D2000C */  jal        func_80034B50
    /* 248AC 800340AC 00000000 */   nop
    /* 248B0 800340B0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 248B4 800340B4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 248B8 800340B8 0800E003 */  jr         $ra
    /* 248BC 800340BC 00000000 */   nop
endlabel func_8003407C

nonmatching func_800340C0, 0x78

glabel func_800340C0
    /* 248C0 800340C0 0780033C */  lui        $v1, %hi(g_cd_task_index)
    /* 248C4 800340C4 8C1B638C */  lw         $v1, %lo(g_cd_task_index)($v1)
    /* 248C8 800340C8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 248CC 800340CC 1300622C */  sltiu      $v0, $v1, 0x13
    /* 248D0 800340D0 13004010 */  beqz       $v0, .L80034120
    /* 248D4 800340D4 1000BFAF */   sw        $ra, 0x10($sp)
    /* 248D8 800340D8 80100300 */  sll        $v0, $v1, 2
    /* 248DC 800340DC 0180013C */  lui        $at, %hi(switchdataD_80010450)
    /* 248E0 800340E0 50042124 */  addiu      $at, $at, %lo(switchdataD_80010450)
    /* 248E4 800340E4 21082200 */  addu       $at, $at, $v0
    /* 248E8 800340E8 0000228C */  lw         $v0, 0x0($at)
    /* 248EC 800340EC 00000000 */  nop
    /* 248F0 800340F0 08004000 */  jr         $v0
    /* 248F4 800340F4 00000000 */   nop
    /* 248F8 800340F8 64F7000C */  jal        func_8003DD90
    /* 248FC 800340FC 21200000 */   addu      $a0, $zero, $zero
    /* 24900 80034100 6AF7000C */  jal        func_8003DDA8
    /* 24904 80034104 21200000 */   addu      $a0, $zero, $zero
    /* 24908 80034108 48D00008 */  j          .L80034120
    /* 2490C 8003410C 00000000 */   nop
    /* 24910 80034110 81D5000C */  jal        func_80035604
    /* 24914 80034114 00000000 */   nop
    /* 24918 80034118 4AD00008 */  j          .L80034128
    /* 2491C 8003411C 00000000 */   nop
  .L80034120:
    /* 24920 80034120 1FD0000C */  jal        func_8003407C
    /* 24924 80034124 00000000 */   nop
  .L80034128:
    /* 24928 80034128 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2492C 8003412C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24930 80034130 0800E003 */  jr         $ra
    /* 24934 80034134 00000000 */   nop
endlabel func_800340C0

nonmatching func_80034138, 0x4C

glabel func_80034138
    /* 24938 80034138 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2493C 8003413C 0E000434 */  ori        $a0, $zero, 0xE
    /* 24940 80034140 21280000 */  addu       $a1, $zero, $zero
    /* 24944 80034144 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24948 80034148 09F8000C */  jal        CdControlB
    /* 2494C 8003414C 21300000 */   addu      $a2, $zero, $zero
    /* 24950 80034150 76F3000C */  jal        VSync
    /* 24954 80034154 03000434 */   ori       $a0, $zero, 0x3
    /* 24958 80034158 08000434 */  ori        $a0, $zero, 0x8
    /* 2495C 8003415C 21280000 */  addu       $a1, $zero, $zero
    /* 24960 80034160 09F8000C */  jal        CdControlB
    /* 24964 80034164 21300000 */   addu      $a2, $zero, $zero
    /* 24968 80034168 07000234 */  ori        $v0, $zero, 0x7
    /* 2496C 8003416C 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24970 80034170 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24974 80034174 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24978 80034178 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2497C 8003417C 0800E003 */  jr         $ra
    /* 24980 80034180 00000000 */   nop
endlabel func_80034138

nonmatching func_80034184, 0x200

glabel func_80034184
    /* 24984 80034184 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 24988 80034188 0780033C */  lui        $v1, %hi(g_cd_task_index)
    /* 2498C 8003418C 8C1B638C */  lw         $v1, %lo(g_cd_task_index)($v1)
    /* 24990 80034190 07000234 */  ori        $v0, $zero, 0x7
    /* 24994 80034194 2400BFAF */  sw         $ra, 0x24($sp)
    /* 24998 80034198 74006214 */  bne        $v1, $v0, .L8003436C
    /* 2499C 8003419C 2000B0AF */   sw        $s0, 0x20($sp)
    /* 249A0 800341A0 01000434 */  ori        $a0, $zero, 0x1
    /* 249A4 800341A4 21280000 */  addu       $a1, $zero, $zero
    /* 249A8 800341A8 09F8000C */  jal        CdControlB
    /* 249AC 800341AC 1000A627 */   addiu     $a2, $sp, 0x10
    /* 249B0 800341B0 1000A293 */  lbu        $v0, 0x10($sp)
    /* 249B4 800341B4 00000000 */  nop
    /* 249B8 800341B8 10004230 */  andi       $v0, $v0, 0x10
    /* 249BC 800341BC 03004010 */  beqz       $v0, .L800341CC
    /* 249C0 800341C0 58021034 */   ori       $s0, $zero, 0x258
    /* 249C4 800341C4 DCD00008 */  j          .L80034370
    /* 249C8 800341C8 03000234 */   ori       $v0, $zero, 0x3
  .L800341CC:
    /* 249CC 800341CC 07000434 */  ori        $a0, $zero, 0x7
    /* 249D0 800341D0 21280000 */  addu       $a1, $zero, $zero
    /* 249D4 800341D4 09F8000C */  jal        CdControlB
    /* 249D8 800341D8 21300000 */   addu      $a2, $zero, $zero
  .L800341DC:
    /* 249DC 800341DC 76F3000C */  jal        VSync
    /* 249E0 800341E0 21200000 */   addu      $a0, $zero, $zero
    /* 249E4 800341E4 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 249E8 800341E8 5C000012 */  beqz       $s0, .L8003435C
    /* 249EC 800341EC 01000434 */   ori       $a0, $zero, 0x1
    /* 249F0 800341F0 21280000 */  addu       $a1, $zero, $zero
    /* 249F4 800341F4 09F8000C */  jal        CdControlB
    /* 249F8 800341F8 1000A627 */   addiu     $a2, $sp, 0x10
    /* 249FC 800341FC 1000A293 */  lbu        $v0, 0x10($sp)
    /* 24A00 80034200 00000000 */  nop
    /* 24A04 80034204 02004230 */  andi       $v0, $v0, 0x2
    /* 24A08 80034208 F4FF4010 */  beqz       $v0, .L800341DC
    /* 24A0C 8003420C 00000000 */   nop
    /* 24A10 80034210 5B01010C */  jal        func_8004056C
    /* 24A14 80034214 21200000 */   addu      $a0, $zero, $zero
    /* 24A18 80034218 21804000 */  addu       $s0, $v0, $zero
    /* 24A1C 8003421C 05000234 */  ori        $v0, $zero, 0x5
    /* 24A20 80034220 0C000212 */  beq        $s0, $v0, .L80034254
    /* 24A24 80034224 0600022A */   slti      $v0, $s0, 0x6
    /* 24A28 80034228 05004010 */  beqz       $v0, .L80034240
    /* 24A2C 8003422C 02000234 */   ori       $v0, $zero, 0x2
    /* 24A30 80034230 0A000212 */  beq        $s0, $v0, .L8003425C
    /* 24A34 80034234 01000234 */   ori       $v0, $zero, 0x1
    /* 24A38 80034238 DCD00008 */  j          .L80034370
    /* 24A3C 8003423C 00000000 */   nop
  .L80034240:
    /* 24A40 80034240 10000234 */  ori        $v0, $zero, 0x10
    /* 24A44 80034244 4A000212 */  beq        $s0, $v0, .L80034370
    /* 24A48 80034248 03000234 */   ori       $v0, $zero, 0x3
    /* 24A4C 8003424C DCD00008 */  j          .L80034370
    /* 24A50 80034250 01000234 */   ori       $v0, $zero, 0x1
  .L80034254:
    /* 24A54 80034254 DCD00008 */  j          .L80034370
    /* 24A58 80034258 02000234 */   ori       $v0, $zero, 0x2
  .L8003425C:
    /* 24A5C 8003425C A401010C */  jal        func_80040690
    /* 24A60 80034260 00000000 */   nop
    /* 24A64 80034264 21184000 */  addu       $v1, $v0, $zero
    /* 24A68 80034268 01000234 */  ori        $v0, $zero, 0x1
    /* 24A6C 8003426C 0D006210 */  beq        $v1, $v0, .L800342A4
    /* 24A70 80034270 02006228 */   slti      $v0, $v1, 0x2
    /* 24A74 80034274 05004010 */  beqz       $v0, .L8003428C
    /* 24A78 80034278 00000000 */   nop
    /* 24A7C 8003427C 3C006010 */  beqz       $v1, .L80034370
    /* 24A80 80034280 05000234 */   ori       $v0, $zero, 0x5
    /* 24A84 80034284 DCD00008 */  j          .L80034370
    /* 24A88 80034288 01000234 */   ori       $v0, $zero, 0x1
  .L8003428C:
    /* 24A8C 8003428C 07007010 */  beq        $v1, $s0, .L800342AC
    /* 24A90 80034290 10000234 */   ori       $v0, $zero, 0x10
    /* 24A94 80034294 36006210 */  beq        $v1, $v0, .L80034370
    /* 24A98 80034298 03000234 */   ori       $v0, $zero, 0x3
    /* 24A9C 8003429C DCD00008 */  j          .L80034370
    /* 24AA0 800342A0 01000234 */   ori       $v0, $zero, 0x1
  .L800342A4:
    /* 24AA4 800342A4 DCD00008 */  j          .L80034370
    /* 24AA8 800342A8 04000234 */   ori       $v0, $zero, 0x4
  .L800342AC:
    /* 24AAC 800342AC 17000434 */  ori        $a0, $zero, 0x17
    /* 24AB0 800342B0 1800B027 */  addiu      $s0, $sp, 0x18
    /* 24AB4 800342B4 7DF8000C */  jal        func_8003E1F4
    /* 24AB8 800342B8 21280002 */   addu      $a1, $s0, $zero
    /* 24ABC 800342BC 15000434 */  ori        $a0, $zero, 0x15
    /* 24AC0 800342C0 21280002 */  addu       $a1, $s0, $zero
    /* 24AC4 800342C4 09F8000C */  jal        CdControlB
    /* 24AC8 800342C8 1000A627 */   addiu     $a2, $sp, 0x10
    /* 24ACC 800342CC 1000A293 */  lbu        $v0, 0x10($sp)
    /* 24AD0 800342D0 00000000 */  nop
    /* 24AD4 800342D4 01004230 */  andi       $v0, $v0, 0x1
    /* 24AD8 800342D8 25004014 */  bnez       $v0, .L80034370
    /* 24ADC 800342DC 01000234 */   ori       $v0, $zero, 0x1
    /* 24AE0 800342E0 1100A293 */  lbu        $v0, 0x11($sp)
    /* 24AE4 800342E4 00000000 */  nop
    /* 24AE8 800342E8 40004230 */  andi       $v0, $v0, 0x40
    /* 24AEC 800342EC 20004014 */  bnez       $v0, .L80034370
    /* 24AF0 800342F0 01000234 */   ori       $v0, $zero, 0x1
    /* 24AF4 800342F4 0E000434 */  ori        $a0, $zero, 0xE
    /* 24AF8 800342F8 80000534 */  ori        $a1, $zero, 0x80
    /* 24AFC 800342FC 09F8000C */  jal        CdControlB
    /* 24B00 80034300 1000A627 */   addiu     $a2, $sp, 0x10
    /* 24B04 80034304 76F3000C */  jal        VSync
    /* 24B08 80034308 03000434 */   ori       $a0, $zero, 0x3
    /* 24B0C 8003430C 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24B10 80034310 8C1B20AC */  sw         $zero, %lo(g_cd_task_index)($at)
    /* 24B14 80034314 E1D0000C */  jal        ff7_unknown_80034384
    /* 24B18 80034318 00000000 */   nop
    /* 24B1C 8003431C 21184000 */  addu       $v1, $v0, $zero
    /* 24B20 80034320 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 24B24 80034324 0780013C */  lui        $at, %hi(g_cd_current_disk)
    /* 24B28 80034328 901B23AC */  sw         $v1, %lo(g_cd_current_disk)($at)
    /* 24B2C 8003432C 07006210 */  beq        $v1, $v0, .L8003434C
    /* 24B30 80034330 00000000 */   nop
    /* 24B34 80034334 0B006014 */  bnez       $v1, .L80034364
    /* 24B38 80034338 00000000 */   nop
    /* 24B3C 8003433C 4ED0000C */  jal        func_80034138
    /* 24B40 80034340 00000000 */   nop
    /* 24B44 80034344 DCD00008 */  j          .L80034370
    /* 24B48 80034348 06000234 */   ori       $v0, $zero, 0x6
  .L8003434C:
    /* 24B4C 8003434C 4ED0000C */  jal        func_80034138
    /* 24B50 80034350 00000000 */   nop
    /* 24B54 80034354 DCD00008 */  j          .L80034370
    /* 24B58 80034358 01000234 */   ori       $v0, $zero, 0x1
  .L8003435C:
    /* 24B5C 8003435C DCD00008 */  j          .L80034370
    /* 24B60 80034360 05000234 */   ori       $v0, $zero, 0x5
  .L80034364:
    /* 24B64 80034364 DAD3000C */  jal        ff7_unknown_80034F68
    /* 24B68 80034368 00000000 */   nop
  .L8003436C:
    /* 24B6C 8003436C 21100000 */  addu       $v0, $zero, $zero
  .L80034370:
    /* 24B70 80034370 2400BF8F */  lw         $ra, 0x24($sp)
    /* 24B74 80034374 2000B08F */  lw         $s0, 0x20($sp)
    /* 24B78 80034378 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 24B7C 8003437C 0800E003 */  jr         $ra
    /* 24B80 80034380 00000000 */   nop
endlabel func_80034184
