.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80042228, 0x90

glabel func_80042228
    /* 32A28 80042228 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 32A2C 8004222C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 32A30 80042230 21888000 */  addu       $s1, $a0, $zero
    /* 32A34 80042234 1000B0AF */  sw         $s0, 0x10($sp)
    /* 32A38 80042238 1800BFAF */  sw         $ra, 0x18($sp)
    /* 32A3C 8004223C D408010C */  jal        func_80042350
    /* 32A40 80042240 2180A000 */   addu      $s0, $a1, $zero
    /* 32A44 80042244 0580033C */  lui        $v1, %hi(ptr_DMA_DPCR)
    /* 32A48 80042248 441B638C */  lw         $v1, %lo(ptr_DMA_DPCR)($v1)
    /* 32A4C 8004224C 00000000 */  nop
    /* 32A50 80042250 0000628C */  lw         $v0, 0x0($v1)
    /* 32A54 80042254 42811000 */  srl        $s0, $s0, 5
    /* 32A58 80042258 88004234 */  ori        $v0, $v0, 0x88
    /* 32A5C 8004225C 000062AC */  sw         $v0, 0x0($v1)
    /* 32A60 80042260 0580023C */  lui        $v0, %hi(ptr_DMA_MDEC_OUT_CHCR)
    /* 32A64 80042264 201B428C */  lw         $v0, %lo(ptr_DMA_MDEC_OUT_CHCR)($v0)
    /* 32A68 80042268 00841000 */  sll        $s0, $s0, 16
    /* 32A6C 8004226C 000040AC */  sw         $zero, 0x0($v0)
    /* 32A70 80042270 0580023C */  lui        $v0, %hi(ptr_DMA_MDEC_OUT_MADR)
    /* 32A74 80042274 181B428C */  lw         $v0, %lo(ptr_DMA_MDEC_OUT_MADR)($v0)
    /* 32A78 80042278 20001036 */  ori        $s0, $s0, 0x20
    /* 32A7C 8004227C 000051AC */  sw         $s1, 0x0($v0)
    /* 32A80 80042280 0580023C */  lui        $v0, %hi(D_80051B1C)
    /* 32A84 80042284 1C1B428C */  lw         $v0, %lo(D_80051B1C)($v0)
    /* 32A88 80042288 0001033C */  lui        $v1, (0x1000200 >> 16)
    /* 32A8C 8004228C 000050AC */  sw         $s0, 0x0($v0)
    /* 32A90 80042290 0580023C */  lui        $v0, %hi(ptr_DMA_MDEC_OUT_CHCR)
    /* 32A94 80042294 201B428C */  lw         $v0, %lo(ptr_DMA_MDEC_OUT_CHCR)($v0)
    /* 32A98 80042298 00026334 */  ori        $v1, $v1, (0x1000200 & 0xFFFF)
    /* 32A9C 8004229C 000043AC */  sw         $v1, 0x0($v0)
    /* 32AA0 800422A0 1800BF8F */  lw         $ra, 0x18($sp)
    /* 32AA4 800422A4 1400B18F */  lw         $s1, 0x14($sp)
    /* 32AA8 800422A8 1000B08F */  lw         $s0, 0x10($sp)
    /* 32AAC 800422AC 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 32AB0 800422B0 0800E003 */  jr         $ra
    /* 32AB4 800422B4 00000000 */   nop
endlabel func_80042228
