.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80045818, 0x18

glabel func_80045818
    /* 36018 80045818 0780013C */  lui        $at, %hi(g_gpu_gp1_command_args_mirror)
    /* 3601C 8004581C BC062124 */  addiu      $at, $at, %lo(g_gpu_gp1_command_args_mirror)
    /* 36020 80045820 21082400 */  addu       $at, $at, $a0
    /* 36024 80045824 00002290 */  lbu        $v0, 0x0($at)
    /* 36028 80045828 0800E003 */  jr         $ra
    /* 3602C 8004582C 00000000 */   nop
endlabel func_80045818

nonmatching func_80045830, 0x50

glabel func_80045830
    /* 36030 80045830 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 36034 80045834 FFFFA624 */  addiu      $a2, $a1, -0x1
    /* 36038 80045838 0680033C */  lui        $v1, %hi(ptr_GPU_GP1)
    /* 3603C 8004583C 882C638C */  lw         $v1, %lo(ptr_GPU_GP1)($v1)
    /* 36040 80045840 0004023C */  lui        $v0, (0x4000000 >> 16)
    /* 36044 80045844 000062AC */  sw         $v0, 0x0($v1)
    /* 36048 80045848 0A00A010 */  beqz       $a1, .L80045874
    /* 3604C 8004584C 21100000 */   addu      $v0, $zero, $zero
    /* 36050 80045850 FFFF0524 */  addiu      $a1, $zero, -0x1
  .L80045854:
    /* 36054 80045854 0000838C */  lw         $v1, 0x0($a0)
    /* 36058 80045858 04008424 */  addiu      $a0, $a0, 0x4
    /* 3605C 8004585C 0680023C */  lui        $v0, %hi(ptr_GPU_GP0)
    /* 36060 80045860 842C428C */  lw         $v0, %lo(ptr_GPU_GP0)($v0)
    /* 36064 80045864 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* 36068 80045868 000043AC */  sw         $v1, 0x0($v0)
    /* 3606C 8004586C F9FFC514 */  bne        $a2, $a1, .L80045854
    /* 36070 80045870 21100000 */   addu      $v0, $zero, $zero
  .L80045874:
    /* 36074 80045874 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 36078 80045878 0800E003 */  jr         $ra
    /* 3607C 8004587C 00000000 */   nop
endlabel func_80045830

nonmatching func_80045880, 0x4C

glabel func_80045880
    /* 36080 80045880 0004033C */  lui        $v1, (0x4000002 >> 16)
    /* 36084 80045884 0680023C */  lui        $v0, %hi(ptr_GPU_GP1)
    /* 36088 80045888 882C428C */  lw         $v0, %lo(ptr_GPU_GP1)($v0)
    /* 3608C 8004588C 02006334 */  ori        $v1, $v1, (0x4000002 & 0xFFFF)
    /* 36090 80045890 000043AC */  sw         $v1, 0x0($v0)
    /* 36094 80045894 0680023C */  lui        $v0, %hi(D_80062C8C)
    /* 36098 80045898 8C2C428C */  lw         $v0, %lo(D_80062C8C)($v0)
    /* 3609C 8004589C 00000000 */  nop
    /* 360A0 800458A0 000044AC */  sw         $a0, 0x0($v0)
    /* 360A4 800458A4 0680023C */  lui        $v0, %hi(D_80062C90)
    /* 360A8 800458A8 902C428C */  lw         $v0, %lo(D_80062C90)($v0)
    /* 360AC 800458AC 0001033C */  lui        $v1, (0x1000401 >> 16)
    /* 360B0 800458B0 000040AC */  sw         $zero, 0x0($v0)
    /* 360B4 800458B4 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 360B8 800458B8 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 360BC 800458BC 01046334 */  ori        $v1, $v1, (0x1000401 & 0xFFFF)
    /* 360C0 800458C0 000043AC */  sw         $v1, 0x0($v0)
    /* 360C4 800458C4 0800E003 */  jr         $ra
    /* 360C8 800458C8 00000000 */   nop
endlabel func_80045880

nonmatching func_800458CC, 0x30

glabel func_800458CC
    /* 360CC 800458CC 0010023C */  lui        $v0, (0x10000000 >> 16)
    /* 360D0 800458D0 0680033C */  lui        $v1, %hi(ptr_GPU_GP1)
    /* 360D4 800458D4 882C638C */  lw         $v1, %lo(ptr_GPU_GP1)($v1)
    /* 360D8 800458D8 25208200 */  or         $a0, $a0, $v0
    /* 360DC 800458DC 000064AC */  sw         $a0, 0x0($v1)
    /* 360E0 800458E0 0680023C */  lui        $v0, %hi(ptr_GPU_GP0)
    /* 360E4 800458E4 842C428C */  lw         $v0, %lo(ptr_GPU_GP0)($v0)
    /* 360E8 800458E8 FF00033C */  lui        $v1, (0xFFFFFF >> 16)
    /* 360EC 800458EC 0000428C */  lw         $v0, 0x0($v0)
    /* 360F0 800458F0 FFFF6334 */  ori        $v1, $v1, (0xFFFFFF & 0xFFFF)
    /* 360F4 800458F4 0800E003 */  jr         $ra
    /* 360F8 800458F8 24104300 */   and       $v0, $v0, $v1
endlabel func_800458CC

nonmatching func_800458FC, 0x24

glabel func_800458FC
    /* 360FC 800458FC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 36100 80045900 1000BFAF */  sw         $ra, 0x10($sp)
    /* 36104 80045904 2138C000 */  addu       $a3, $a2, $zero
    /* 36108 80045908 4816010C */  jal        func_80045920
    /* 3610C 8004590C 21300000 */   addu      $a2, $zero, $zero
    /* 36110 80045910 1000BF8F */  lw         $ra, 0x10($sp)
    /* 36114 80045914 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 36118 80045918 0800E003 */  jr         $ra
    /* 3611C 8004591C 00000000 */   nop
endlabel func_800458FC

nonmatching func_80045920, 0x2F4

glabel func_80045920
    /* 36120 80045920 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 36124 80045924 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 36128 80045928 21988000 */  addu       $s3, $a0, $zero
    /* 3612C 8004592C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 36130 80045930 2180A000 */  addu       $s0, $a1, $zero
    /* 36134 80045934 1400B1AF */  sw         $s1, 0x14($sp)
    /* 36138 80045938 2188C000 */  addu       $s1, $a2, $zero
    /* 3613C 8004593C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 36140 80045940 2000BFAF */  sw         $ra, 0x20($sp)
    /* 36144 80045944 6B18010C */  jal        func_800461AC
    /* 36148 80045948 2190E000 */   addu      $s2, $a3, $zero
    /* 3614C 8004594C 5B160108 */  j          .L8004596C
    /* 36150 80045950 00000000 */   nop
  .L80045954:
    /* 36154 80045954 7818010C */  jal        func_800461E0
    /* 36158 80045958 00000000 */   nop
    /* 3615C 8004595C A5004014 */  bnez       $v0, .L80045BF4
    /* 36160 80045960 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 36164 80045964 0517010C */  jal        func_80045C14
    /* 36168 80045968 00000000 */   nop
  .L8004596C:
    /* 3616C 8004596C 0680023C */  lui        $v0, %hi(s_resetgraph_temp)
    /* 36170 80045970 B82C428C */  lw         $v0, %lo(s_resetgraph_temp)($v0)
    /* 36174 80045974 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36178 80045978 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 3617C 8004597C 01004224 */  addiu      $v0, $v0, 0x1
    /* 36180 80045980 3F004230 */  andi       $v0, $v0, 0x3F
    /* 36184 80045984 F3FF4310 */  beq        $v0, $v1, .L80045954
    /* 36188 80045988 00000000 */   nop
    /* 3618C 8004598C 4EF4000C */  jal        SetIntrMask
    /* 36190 80045990 21200000 */   addu      $a0, $zero, $zero
    /* 36194 80045994 0680033C */  lui        $v1, %hi(D_80062BBC)
    /* 36198 80045998 BC2B6324 */  addiu      $v1, $v1, %lo(D_80062BBC)
    /* 3619C 8004599C 01000434 */  ori        $a0, $zero, 0x1
    /* 361A0 800459A0 000064AC */  sw         $a0, 0x0($v1)
    /* 361A4 800459A4 0680033C */  lui        $v1, %hi(g_is_graph_initialized)
    /* 361A8 800459A8 B52B6390 */  lbu        $v1, %lo(g_is_graph_initialized)($v1)
    /* 361AC 800459AC 0680013C */  lui        $at, %hi(D_80062CC0)
    /* 361B0 800459B0 C02C22AC */  sw         $v0, %lo(D_80062CC0)($at)
    /* 361B4 800459B4 15006010 */  beqz       $v1, .L80045A0C
    /* 361B8 800459B8 0004043C */   lui       $a0, (0x4000000 >> 16)
    /* 361BC 800459BC 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 361C0 800459C0 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 361C4 800459C4 0680023C */  lui        $v0, %hi(s_resetgraph_unknown_80062CBC)
    /* 361C8 800459C8 BC2C428C */  lw         $v0, %lo(s_resetgraph_unknown_80062CBC)($v0)
    /* 361CC 800459CC 00000000 */  nop
    /* 361D0 800459D0 26006214 */  bne        $v1, $v0, .L80045A6C
    /* 361D4 800459D4 00000000 */   nop
    /* 361D8 800459D8 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 361DC 800459DC 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 361E0 800459E0 00000000 */  nop
    /* 361E4 800459E4 0000428C */  lw         $v0, 0x0($v0)
    /* 361E8 800459E8 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 361EC 800459EC 24104300 */  and        $v0, $v0, $v1
    /* 361F0 800459F0 1E004014 */  bnez       $v0, .L80045A6C
    /* 361F4 800459F4 00000000 */   nop
    /* 361F8 800459F8 0680023C */  lui        $v0, %hi(D_80062BC0)
    /* 361FC 800459FC C02B428C */  lw         $v0, %lo(D_80062BC0)($v0)
    /* 36200 80045A00 00000000 */  nop
    /* 36204 80045A04 19004014 */  bnez       $v0, .L80045A6C
    /* 36208 80045A08 00000000 */   nop
  .L80045A0C:
    /* 3620C 80045A0C 0680033C */  lui        $v1, %hi(ptr_GPU_GP1)
    /* 36210 80045A10 882C638C */  lw         $v1, %lo(ptr_GPU_GP1)($v1)
  .L80045A14:
    /* 36214 80045A14 00000000 */  nop
    /* 36218 80045A18 0000628C */  lw         $v0, 0x0($v1)
    /* 3621C 80045A1C 00000000 */  nop
    /* 36220 80045A20 24104400 */  and        $v0, $v0, $a0
    /* 36224 80045A24 FBFF4010 */  beqz       $v0, .L80045A14
    /* 36228 80045A28 00000000 */   nop
    /* 3622C 80045A2C 21200002 */  addu       $a0, $s0, $zero
    /* 36230 80045A30 09F86002 */  jalr       $s3
    /* 36234 80045A34 21284002 */   addu      $a1, $s2, $zero
    /* 36238 80045A38 0680043C */  lui        $a0, %hi(D_80062CC0)
    /* 3623C 80045A3C C02C848C */  lw         $a0, %lo(D_80062CC0)($a0)
    /* 36240 80045A40 0680023C */  lui        $v0, %hi(D_80062CA8)
    /* 36244 80045A44 A82C4224 */  addiu      $v0, $v0, %lo(D_80062CA8)
    /* 36248 80045A48 000053AC */  sw         $s3, 0x0($v0)
    /* 3624C 80045A4C 0680013C */  lui        $at, %hi(D_80062CAC)
    /* 36250 80045A50 AC2C30AC */  sw         $s0, %lo(D_80062CAC)($at)
    /* 36254 80045A54 0680013C */  lui        $at, %hi(D_80062CB0)
    /* 36258 80045A58 B02C32AC */  sw         $s2, %lo(D_80062CB0)($at)
    /* 3625C 80045A5C 4EF4000C */  jal        SetIntrMask
    /* 36260 80045A60 00000000 */   nop
    /* 36264 80045A64 FD160108 */  j          .L80045BF4
    /* 36268 80045A68 21100000 */   addu      $v0, $zero, $zero
  .L80045A6C:
    /* 3626C 80045A6C 0480053C */  lui        $a1, %hi(func_80045C14)
    /* 36270 80045A70 145CA524 */  addiu      $a1, $a1, %lo(func_80045C14)
    /* 36274 80045A74 07F4000C */  jal        DMACallback
    /* 36278 80045A78 02000434 */   ori       $a0, $zero, 0x2
    /* 3627C 80045A7C 2C002012 */  beqz       $s1, .L80045B30
    /* 36280 80045A80 21300000 */   addu      $a2, $zero, $zero
    /* 36284 80045A84 0A80083C */  lui        $t0, %hi(D_8009AE60)
    /* 36288 80045A88 60AE0825 */  addiu      $t0, $t0, %lo(D_8009AE60)
    /* 3628C 80045A8C 21380002 */  addu       $a3, $s0, $zero
    /* 36290 80045A90 21102002 */  addu       $v0, $s1, $zero
  .L80045A94:
    /* 36294 80045A94 02004104 */  bgez       $v0, .L80045AA0
    /* 36298 80045A98 00000000 */   nop
    /* 3629C 80045A9C 03004224 */  addiu      $v0, $v0, 0x3
  .L80045AA0:
    /* 362A0 80045AA0 83100200 */  sra        $v0, $v0, 2
    /* 362A4 80045AA4 2A10C200 */  slt        $v0, $a2, $v0
    /* 362A8 80045AA8 0E004010 */  beqz       $v0, .L80045AE4
    /* 362AC 80045AAC 80200600 */   sll       $a0, $a2, 2
    /* 362B0 80045AB0 0000E58C */  lw         $a1, 0x0($a3)
    /* 362B4 80045AB4 0400E724 */  addiu      $a3, $a3, 0x4
    /* 362B8 80045AB8 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 362BC 80045ABC B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 362C0 80045AC0 0100C624 */  addiu      $a2, $a2, 0x1
    /* 362C4 80045AC4 40100300 */  sll        $v0, $v1, 1
    /* 362C8 80045AC8 21104300 */  addu       $v0, $v0, $v1
    /* 362CC 80045ACC 40110200 */  sll        $v0, $v0, 5
    /* 362D0 80045AD0 21104800 */  addu       $v0, $v0, $t0
    /* 362D4 80045AD4 21208200 */  addu       $a0, $a0, $v0
    /* 362D8 80045AD8 000085AC */  sw         $a1, 0x0($a0)
    /* 362DC 80045ADC A5160108 */  j          .L80045A94
    /* 362E0 80045AE0 21102002 */   addu      $v0, $s1, $zero
  .L80045AE4:
    /* 362E4 80045AE4 0680023C */  lui        $v0, %hi(s_resetgraph_temp)
    /* 362E8 80045AE8 B82C428C */  lw         $v0, %lo(s_resetgraph_temp)($v0)
    /* 362EC 80045AEC 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 362F0 80045AF0 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 362F4 80045AF4 40200200 */  sll        $a0, $v0, 1
    /* 362F8 80045AF8 21208200 */  addu       $a0, $a0, $v0
    /* 362FC 80045AFC 40210400 */  sll        $a0, $a0, 5
    /* 36300 80045B00 40100300 */  sll        $v0, $v1, 1
    /* 36304 80045B04 21104300 */  addu       $v0, $v0, $v1
    /* 36308 80045B08 40110200 */  sll        $v0, $v0, 5
    /* 3630C 80045B0C 0A80033C */  lui        $v1, %hi(D_8009AE60)
    /* 36310 80045B10 60AE6324 */  addiu      $v1, $v1, %lo(D_8009AE60)
    /* 36314 80045B14 21104300 */  addu       $v0, $v0, $v1
    /* 36318 80045B18 0A80013C */  lui        $at, %hi(D_8009AE58)
    /* 3631C 80045B1C 58AE2124 */  addiu      $at, $at, %lo(D_8009AE58)
    /* 36320 80045B20 21082400 */  addu       $at, $at, $a0
    /* 36324 80045B24 000022AC */  sw         $v0, 0x0($at)
    /* 36328 80045B28 D6160108 */  j          .L80045B58
    /* 3632C 80045B2C 00000000 */   nop
  .L80045B30:
    /* 36330 80045B30 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 36334 80045B34 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 36338 80045B38 00000000 */  nop
    /* 3633C 80045B3C 40100300 */  sll        $v0, $v1, 1
    /* 36340 80045B40 21104300 */  addu       $v0, $v0, $v1
    /* 36344 80045B44 40110200 */  sll        $v0, $v0, 5
    /* 36348 80045B48 0A80013C */  lui        $at, %hi(D_8009AE58)
    /* 3634C 80045B4C 58AE2124 */  addiu      $at, $at, %lo(D_8009AE58)
    /* 36350 80045B50 21082200 */  addu       $at, $at, $v0
    /* 36354 80045B54 000030AC */  sw         $s0, 0x0($at)
  .L80045B58:
    /* 36358 80045B58 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 3635C 80045B5C B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 36360 80045B60 00000000 */  nop
    /* 36364 80045B64 40100300 */  sll        $v0, $v1, 1
    /* 36368 80045B68 21104300 */  addu       $v0, $v0, $v1
    /* 3636C 80045B6C 40110200 */  sll        $v0, $v0, 5
    /* 36370 80045B70 0A80013C */  lui        $at, %hi(D_8009AE5C)
    /* 36374 80045B74 5CAE2124 */  addiu      $at, $at, %lo(D_8009AE5C)
    /* 36378 80045B78 21082200 */  addu       $at, $at, $v0
    /* 3637C 80045B7C 000032AC */  sw         $s2, 0x0($at)
    /* 36380 80045B80 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 36384 80045B84 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 36388 80045B88 00000000 */  nop
    /* 3638C 80045B8C 40100300 */  sll        $v0, $v1, 1
    /* 36390 80045B90 21104300 */  addu       $v0, $v0, $v1
    /* 36394 80045B94 40110200 */  sll        $v0, $v0, 5
    /* 36398 80045B98 0A80013C */  lui        $at, %hi(g_gpu_graph_env_buffer)
    /* 3639C 80045B9C 54AE2124 */  addiu      $at, $at, %lo(g_gpu_graph_env_buffer)
    /* 363A0 80045BA0 21082200 */  addu       $at, $at, $v0
    /* 363A4 80045BA4 000033AC */  sw         $s3, 0x0($at)
    /* 363A8 80045BA8 0680023C */  lui        $v0, %hi(s_resetgraph_temp)
    /* 363AC 80045BAC B82C428C */  lw         $v0, %lo(s_resetgraph_temp)($v0)
    /* 363B0 80045BB0 0680043C */  lui        $a0, %hi(D_80062CC0)
    /* 363B4 80045BB4 C02C848C */  lw         $a0, %lo(D_80062CC0)($a0)
    /* 363B8 80045BB8 01004224 */  addiu      $v0, $v0, 0x1
    /* 363BC 80045BBC 3F004230 */  andi       $v0, $v0, 0x3F
    /* 363C0 80045BC0 0680013C */  lui        $at, %hi(s_resetgraph_temp)
    /* 363C4 80045BC4 B82C22AC */  sw         $v0, %lo(s_resetgraph_temp)($at)
    /* 363C8 80045BC8 4EF4000C */  jal        SetIntrMask
    /* 363CC 80045BCC 00000000 */   nop
    /* 363D0 80045BD0 0517010C */  jal        func_80045C14
    /* 363D4 80045BD4 00000000 */   nop
    /* 363D8 80045BD8 0680023C */  lui        $v0, %hi(s_resetgraph_temp)
    /* 363DC 80045BDC B82C428C */  lw         $v0, %lo(s_resetgraph_temp)($v0)
    /* 363E0 80045BE0 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 363E4 80045BE4 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 363E8 80045BE8 00000000 */  nop
    /* 363EC 80045BEC 23104300 */  subu       $v0, $v0, $v1
    /* 363F0 80045BF0 3F004230 */  andi       $v0, $v0, 0x3F
  .L80045BF4:
    /* 363F4 80045BF4 2000BF8F */  lw         $ra, 0x20($sp)
    /* 363F8 80045BF8 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 363FC 80045BFC 1800B28F */  lw         $s2, 0x18($sp)
    /* 36400 80045C00 1400B18F */  lw         $s1, 0x14($sp)
    /* 36404 80045C04 1000B08F */  lw         $s0, 0x10($sp)
    /* 36408 80045C08 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 3640C 80045C0C 0800E003 */  jr         $ra
    /* 36410 80045C10 00000000 */   nop
endlabel func_80045920

nonmatching func_80045C14, 0x314

glabel func_80045C14
    /* 36414 80045C14 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 36418 80045C18 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 3641C 80045C1C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 36420 80045C20 1400BFAF */  sw         $ra, 0x14($sp)
    /* 36424 80045C24 1000B0AF */  sw         $s0, 0x10($sp)
    /* 36428 80045C28 0000428C */  lw         $v0, 0x0($v0)
    /* 3642C 80045C2C 0001103C */  lui        $s0, (0x1000000 >> 16)
    /* 36430 80045C30 24105000 */  and        $v0, $v0, $s0
    /* 36434 80045C34 B7004014 */  bnez       $v0, .L80045F14
    /* 36438 80045C38 01000234 */   ori       $v0, $zero, 0x1
    /* 3643C 80045C3C 4EF4000C */  jal        SetIntrMask
    /* 36440 80045C40 21200000 */   addu      $a0, $zero, $zero
    /* 36444 80045C44 0680043C */  lui        $a0, %hi(s_resetgraph_temp)
    /* 36448 80045C48 B82C848C */  lw         $a0, %lo(s_resetgraph_temp)($a0)
    /* 3644C 80045C4C 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36450 80045C50 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 36454 80045C54 0680013C */  lui        $at, %hi(D_80062CC4)
    /* 36458 80045C58 C42C22AC */  sw         $v0, %lo(D_80062CC4)($at)
    /* 3645C 80045C5C 82008310 */  beq        $a0, $v1, .L80045E68
    /* 36460 80045C60 00000000 */   nop
    /* 36464 80045C64 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 36468 80045C68 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 3646C 80045C6C 00000000 */  nop
    /* 36470 80045C70 0000428C */  lw         $v0, 0x0($v0)
    /* 36474 80045C74 00000000 */  nop
    /* 36478 80045C78 24105000 */  and        $v0, $v0, $s0
    /* 3647C 80045C7C 7A004014 */  bnez       $v0, .L80045E68
    /* 36480 80045C80 00000000 */   nop
    /* 36484 80045C84 0680103C */  lui        $s0, %hi(D_80062CA8)
    /* 36488 80045C88 A82C1026 */  addiu      $s0, $s0, %lo(D_80062CA8)
  .L80045C8C:
    /* 3648C 80045C8C 0680023C */  lui        $v0, %hi(s_resetgraph_unknown_80062CBC)
    /* 36490 80045C90 BC2C428C */  lw         $v0, %lo(s_resetgraph_unknown_80062CBC)($v0)
    /* 36494 80045C94 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 36498 80045C98 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 3649C 80045C9C 01004224 */  addiu      $v0, $v0, 0x1
    /* 364A0 80045CA0 3F004230 */  andi       $v0, $v0, 0x3F
    /* 364A4 80045CA4 09004314 */  bne        $v0, $v1, .L80045CCC
    /* 364A8 80045CA8 00000000 */   nop
    /* 364AC 80045CAC 0680023C */  lui        $v0, %hi(D_80062BC0)
    /* 364B0 80045CB0 C02B4224 */  addiu      $v0, $v0, %lo(D_80062BC0)
    /* 364B4 80045CB4 0000428C */  lw         $v0, 0x0($v0)
    /* 364B8 80045CB8 00000000 */  nop
    /* 364BC 80045CBC 03004014 */  bnez       $v0, .L80045CCC
    /* 364C0 80045CC0 02000434 */   ori       $a0, $zero, 0x2
    /* 364C4 80045CC4 07F4000C */  jal        DMACallback
    /* 364C8 80045CC8 21280000 */   addu      $a1, $zero, $zero
  .L80045CCC:
    /* 364CC 80045CCC 0680043C */  lui        $a0, %hi(ptr_GPU_GP1)
    /* 364D0 80045CD0 882C848C */  lw         $a0, %lo(ptr_GPU_GP1)($a0)
    /* 364D4 80045CD4 00000000 */  nop
    /* 364D8 80045CD8 0000828C */  lw         $v0, 0x0($a0)
    /* 364DC 80045CDC 0004033C */  lui        $v1, (0x4000000 >> 16)
    /* 364E0 80045CE0 24104300 */  and        $v0, $v0, $v1
    /* 364E4 80045CE4 07004014 */  bnez       $v0, .L80045D04
    /* 364E8 80045CE8 21188000 */   addu      $v1, $a0, $zero
    /* 364EC 80045CEC 0004043C */  lui        $a0, (0x4000000 >> 16)
  .L80045CF0:
    /* 364F0 80045CF0 0000628C */  lw         $v0, 0x0($v1)
    /* 364F4 80045CF4 00000000 */  nop
    /* 364F8 80045CF8 24104400 */  and        $v0, $v0, $a0
    /* 364FC 80045CFC FCFF4010 */  beqz       $v0, .L80045CF0
    /* 36500 80045D00 00000000 */   nop
  .L80045D04:
    /* 36504 80045D04 0680053C */  lui        $a1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36508 80045D08 BC2CA58C */  lw         $a1, %lo(s_resetgraph_unknown_80062CBC)($a1)
    /* 3650C 80045D0C 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36510 80045D10 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 36514 80045D14 00000000 */  nop
    /* 36518 80045D18 40100300 */  sll        $v0, $v1, 1
    /* 3651C 80045D1C 21104300 */  addu       $v0, $v0, $v1
    /* 36520 80045D20 40110200 */  sll        $v0, $v0, 5
    /* 36524 80045D24 40180500 */  sll        $v1, $a1, 1
    /* 36528 80045D28 21186500 */  addu       $v1, $v1, $a1
    /* 3652C 80045D2C 0A80013C */  lui        $at, %hi(D_8009AE58)
    /* 36530 80045D30 58AE2124 */  addiu      $at, $at, %lo(D_8009AE58)
    /* 36534 80045D34 21082200 */  addu       $at, $at, $v0
    /* 36538 80045D38 0000248C */  lw         $a0, 0x0($at)
    /* 3653C 80045D3C 0680053C */  lui        $a1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36540 80045D40 BC2CA58C */  lw         $a1, %lo(s_resetgraph_unknown_80062CBC)($a1)
    /* 36544 80045D44 40190300 */  sll        $v1, $v1, 5
    /* 36548 80045D48 40100500 */  sll        $v0, $a1, 1
    /* 3654C 80045D4C 21104500 */  addu       $v0, $v0, $a1
    /* 36550 80045D50 40110200 */  sll        $v0, $v0, 5
    /* 36554 80045D54 0A80013C */  lui        $at, %hi(D_8009AE5C)
    /* 36558 80045D58 5CAE2124 */  addiu      $at, $at, %lo(D_8009AE5C)
    /* 3655C 80045D5C 21082200 */  addu       $at, $at, $v0
    /* 36560 80045D60 0000258C */  lw         $a1, 0x0($at)
    /* 36564 80045D64 0A80013C */  lui        $at, %hi(g_gpu_graph_env_buffer)
    /* 36568 80045D68 54AE2124 */  addiu      $at, $at, %lo(g_gpu_graph_env_buffer)
    /* 3656C 80045D6C 21082300 */  addu       $at, $at, $v1
    /* 36570 80045D70 0000228C */  lw         $v0, 0x0($at)
    /* 36574 80045D74 00000000 */  nop
    /* 36578 80045D78 09F84000 */  jalr       $v0
    /* 3657C 80045D7C 00000000 */   nop
    /* 36580 80045D80 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36584 80045D84 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 36588 80045D88 00000000 */  nop
    /* 3658C 80045D8C 40100300 */  sll        $v0, $v1, 1
    /* 36590 80045D90 21104300 */  addu       $v0, $v0, $v1
    /* 36594 80045D94 40110200 */  sll        $v0, $v0, 5
    /* 36598 80045D98 0A80013C */  lui        $at, %hi(g_gpu_graph_env_buffer)
    /* 3659C 80045D9C 54AE2124 */  addiu      $at, $at, %lo(g_gpu_graph_env_buffer)
    /* 365A0 80045DA0 21082200 */  addu       $at, $at, $v0
    /* 365A4 80045DA4 0000228C */  lw         $v0, 0x0($at)
    /* 365A8 80045DA8 00000000 */  nop
    /* 365AC 80045DAC 000002AE */  sw         $v0, 0x0($s0)
    /* 365B0 80045DB0 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 365B4 80045DB4 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 365B8 80045DB8 00000000 */  nop
    /* 365BC 80045DBC 40100300 */  sll        $v0, $v1, 1
    /* 365C0 80045DC0 21104300 */  addu       $v0, $v0, $v1
    /* 365C4 80045DC4 40110200 */  sll        $v0, $v0, 5
    /* 365C8 80045DC8 0A80013C */  lui        $at, %hi(D_8009AE58)
    /* 365CC 80045DCC 58AE2124 */  addiu      $at, $at, %lo(D_8009AE58)
    /* 365D0 80045DD0 21082200 */  addu       $at, $at, $v0
    /* 365D4 80045DD4 0000228C */  lw         $v0, 0x0($at)
    /* 365D8 80045DD8 00000000 */  nop
    /* 365DC 80045DDC 040002AE */  sw         $v0, 0x4($s0)
    /* 365E0 80045DE0 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 365E4 80045DE4 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 365E8 80045DE8 00000000 */  nop
    /* 365EC 80045DEC 40100300 */  sll        $v0, $v1, 1
    /* 365F0 80045DF0 21104300 */  addu       $v0, $v0, $v1
    /* 365F4 80045DF4 40110200 */  sll        $v0, $v0, 5
    /* 365F8 80045DF8 0A80013C */  lui        $at, %hi(D_8009AE5C)
    /* 365FC 80045DFC 5CAE2124 */  addiu      $at, $at, %lo(D_8009AE5C)
    /* 36600 80045E00 21082200 */  addu       $at, $at, $v0
    /* 36604 80045E04 0000228C */  lw         $v0, 0x0($at)
    /* 36608 80045E08 00000000 */  nop
    /* 3660C 80045E0C 080002AE */  sw         $v0, 0x8($s0)
    /* 36610 80045E10 0680023C */  lui        $v0, %hi(s_resetgraph_unknown_80062CBC)
    /* 36614 80045E14 BC2C428C */  lw         $v0, %lo(s_resetgraph_unknown_80062CBC)($v0)
    /* 36618 80045E18 00000000 */  nop
    /* 3661C 80045E1C 01004224 */  addiu      $v0, $v0, 0x1
    /* 36620 80045E20 3F004230 */  andi       $v0, $v0, 0x3F
    /* 36624 80045E24 0680013C */  lui        $at, %hi(s_resetgraph_unknown_80062CBC)
    /* 36628 80045E28 BC2C22AC */  sw         $v0, %lo(s_resetgraph_unknown_80062CBC)($at)
    /* 3662C 80045E2C 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 36630 80045E30 B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 36634 80045E34 0680023C */  lui        $v0, %hi(s_resetgraph_unknown_80062CBC)
    /* 36638 80045E38 BC2C428C */  lw         $v0, %lo(s_resetgraph_unknown_80062CBC)($v0)
    /* 3663C 80045E3C 00000000 */  nop
    /* 36640 80045E40 09006210 */  beq        $v1, $v0, .L80045E68
    /* 36644 80045E44 00000000 */   nop
    /* 36648 80045E48 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 3664C 80045E4C 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 36650 80045E50 00000000 */  nop
    /* 36654 80045E54 0000428C */  lw         $v0, 0x0($v0)
    /* 36658 80045E58 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 3665C 80045E5C 24104300 */  and        $v0, $v0, $v1
    /* 36660 80045E60 8AFF4010 */  beqz       $v0, .L80045C8C
    /* 36664 80045E64 00000000 */   nop
  .L80045E68:
    /* 36668 80045E68 0680043C */  lui        $a0, %hi(D_80062CC4)
    /* 3666C 80045E6C C42C848C */  lw         $a0, %lo(D_80062CC4)($a0)
    /* 36670 80045E70 4EF4000C */  jal        SetIntrMask
    /* 36674 80045E74 00000000 */   nop
    /* 36678 80045E78 0680033C */  lui        $v1, %hi(s_resetgraph_temp)
    /* 3667C 80045E7C B82C638C */  lw         $v1, %lo(s_resetgraph_temp)($v1)
    /* 36680 80045E80 0680023C */  lui        $v0, %hi(s_resetgraph_unknown_80062CBC)
    /* 36684 80045E84 BC2C428C */  lw         $v0, %lo(s_resetgraph_unknown_80062CBC)($v0)
    /* 36688 80045E88 00000000 */  nop
    /* 3668C 80045E8C 1A006214 */  bne        $v1, $v0, .L80045EF8
    /* 36690 80045E90 00000000 */   nop
    /* 36694 80045E94 0680023C */  lui        $v0, %hi(ptr_DPCR)
    /* 36698 80045E98 942C428C */  lw         $v0, %lo(ptr_DPCR)($v0)
    /* 3669C 80045E9C 00000000 */  nop
    /* 366A0 80045EA0 0000428C */  lw         $v0, 0x0($v0)
    /* 366A4 80045EA4 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 366A8 80045EA8 24104300 */  and        $v0, $v0, $v1
    /* 366AC 80045EAC 12004014 */  bnez       $v0, .L80045EF8
    /* 366B0 80045EB0 00000000 */   nop
    /* 366B4 80045EB4 0680033C */  lui        $v1, %hi(D_80062BBC)
    /* 366B8 80045EB8 BC2B6324 */  addiu      $v1, $v1, %lo(D_80062BBC)
    /* 366BC 80045EBC 0000628C */  lw         $v0, 0x0($v1)
    /* 366C0 80045EC0 00000000 */  nop
    /* 366C4 80045EC4 0C004010 */  beqz       $v0, .L80045EF8
    /* 366C8 80045EC8 00000000 */   nop
    /* 366CC 80045ECC 0680023C */  lui        $v0, %hi(D_80062BC0)
    /* 366D0 80045ED0 C02B428C */  lw         $v0, %lo(D_80062BC0)($v0)
    /* 366D4 80045ED4 00000000 */  nop
    /* 366D8 80045ED8 07004010 */  beqz       $v0, .L80045EF8
    /* 366DC 80045EDC 00000000 */   nop
    /* 366E0 80045EE0 000060AC */  sw         $zero, 0x0($v1)
    /* 366E4 80045EE4 0680023C */  lui        $v0, %hi(D_80062BC0)
    /* 366E8 80045EE8 C02B428C */  lw         $v0, %lo(D_80062BC0)($v0)
    /* 366EC 80045EEC 00000000 */  nop
    /* 366F0 80045EF0 09F84000 */  jalr       $v0
    /* 366F4 80045EF4 00000000 */   nop
  .L80045EF8:
    /* 366F8 80045EF8 0680023C */  lui        $v0, %hi(s_resetgraph_temp)
    /* 366FC 80045EFC B82C428C */  lw         $v0, %lo(s_resetgraph_temp)($v0)
    /* 36700 80045F00 0680033C */  lui        $v1, %hi(s_resetgraph_unknown_80062CBC)
    /* 36704 80045F04 BC2C638C */  lw         $v1, %lo(s_resetgraph_unknown_80062CBC)($v1)
    /* 36708 80045F08 00000000 */  nop
    /* 3670C 80045F0C 23104300 */  subu       $v0, $v0, $v1
    /* 36710 80045F10 3F004230 */  andi       $v0, $v0, 0x3F
  .L80045F14:
    /* 36714 80045F14 1400BF8F */  lw         $ra, 0x14($sp)
    /* 36718 80045F18 1000B08F */  lw         $s0, 0x10($sp)
    /* 3671C 80045F1C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 36720 80045F20 0800E003 */  jr         $ra
    /* 36724 80045F24 00000000 */   nop
endlabel func_80045C14
