.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80041E70, 0x8C

glabel func_80041E70
    /* 32670 80041E70 21308000 */  addu       $a2, $a0, $zero
    /* 32674 80041E74 0580053C */  lui        $a1, %hi(D_80051A08)
    /* 32678 80041E78 081AA524 */  addiu      $a1, $a1, %lo(D_80051A08)
    /* 3267C 80041E7C 0F000334 */  ori        $v1, $zero, 0xF
    /* 32680 80041E80 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L80041E84:
    /* 32684 80041E84 0000A28C */  lw         $v0, 0x0($a1)
    /* 32688 80041E88 0400A524 */  addiu      $a1, $a1, 0x4
    /* 3268C 80041E8C FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 32690 80041E90 0000C2AC */  sw         $v0, 0x0($a2)
    /* 32694 80041E94 FBFF6714 */  bne        $v1, $a3, .L80041E84
    /* 32698 80041E98 0400C624 */   addiu     $a2, $a2, 0x4
    /* 3269C 80041E9C 40008624 */  addiu      $a2, $a0, 0x40
    /* 326A0 80041EA0 0580053C */  lui        $a1, %hi(D_80051A48)
    /* 326A4 80041EA4 481AA524 */  addiu      $a1, $a1, %lo(D_80051A48)
    /* 326A8 80041EA8 0F000334 */  ori        $v1, $zero, 0xF
    /* 326AC 80041EAC FFFF0724 */  addiu      $a3, $zero, -0x1
  .L80041EB0:
    /* 326B0 80041EB0 0000A28C */  lw         $v0, 0x0($a1)
    /* 326B4 80041EB4 0400A524 */  addiu      $a1, $a1, 0x4
    /* 326B8 80041EB8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 326BC 80041EBC 0000C2AC */  sw         $v0, 0x0($a2)
    /* 326C0 80041EC0 FBFF6714 */  bne        $v1, $a3, .L80041EB0
    /* 326C4 80041EC4 0400C624 */   addiu     $a2, $a2, 0x4
    /* 326C8 80041EC8 80008624 */  addiu      $a2, $a0, 0x80
    /* 326CC 80041ECC 0580053C */  lui        $a1, %hi(D_80051A8C)
    /* 326D0 80041ED0 8C1AA524 */  addiu      $a1, $a1, %lo(D_80051A8C)
    /* 326D4 80041ED4 1F000334 */  ori        $v1, $zero, 0x1F
    /* 326D8 80041ED8 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L80041EDC:
    /* 326DC 80041EDC 0000A28C */  lw         $v0, 0x0($a1)
    /* 326E0 80041EE0 0400A524 */  addiu      $a1, $a1, 0x4
    /* 326E4 80041EE4 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 326E8 80041EE8 0000C2AC */  sw         $v0, 0x0($a2)
    /* 326EC 80041EEC FBFF6714 */  bne        $v1, $a3, .L80041EDC
    /* 326F0 80041EF0 0400C624 */   addiu     $a2, $a2, 0x4
    /* 326F4 80041EF4 0800E003 */  jr         $ra
    /* 326F8 80041EF8 21108000 */   addu      $v0, $a0, $zero
endlabel func_80041E70

nonmatching func_80041EFC, 0x60

glabel func_80041EFC
    /* 326FC 80041EFC 0580063C */  lui        $a2, %hi(D_80051A08)
    /* 32700 80041F00 081AC624 */  addiu      $a2, $a2, %lo(D_80051A08)
    /* 32704 80041F04 21288000 */  addu       $a1, $a0, $zero
    /* 32708 80041F08 0F000334 */  ori        $v1, $zero, 0xF
    /* 3270C 80041F0C FFFF0724 */  addiu      $a3, $zero, -0x1
  .L80041F10:
    /* 32710 80041F10 0000A28C */  lw         $v0, 0x0($a1)
    /* 32714 80041F14 0400A524 */  addiu      $a1, $a1, 0x4
    /* 32718 80041F18 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 3271C 80041F1C 0000C2AC */  sw         $v0, 0x0($a2)
    /* 32720 80041F20 FBFF6714 */  bne        $v1, $a3, .L80041F10
    /* 32724 80041F24 0400C624 */   addiu     $a2, $a2, 0x4
    /* 32728 80041F28 0580063C */  lui        $a2, %hi(D_80051A48)
    /* 3272C 80041F2C 481AC624 */  addiu      $a2, $a2, %lo(D_80051A48)
    /* 32730 80041F30 40008524 */  addiu      $a1, $a0, 0x40
    /* 32734 80041F34 0F000334 */  ori        $v1, $zero, 0xF
    /* 32738 80041F38 FFFF0724 */  addiu      $a3, $zero, -0x1
  .L80041F3C:
    /* 3273C 80041F3C 0000A28C */  lw         $v0, 0x0($a1)
    /* 32740 80041F40 0400A524 */  addiu      $a1, $a1, 0x4
    /* 32744 80041F44 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 32748 80041F48 0000C2AC */  sw         $v0, 0x0($a2)
    /* 3274C 80041F4C FBFF6714 */  bne        $v1, $a3, .L80041F3C
    /* 32750 80041F50 0400C624 */   addiu     $a2, $a2, 0x4
    /* 32754 80041F54 0800E003 */  jr         $ra
    /* 32758 80041F58 21108000 */   addu      $v0, $a0, $zero
endlabel func_80041EFC

nonmatching func_80041F5C, 0xC

glabel func_80041F5C
    /* 3275C 80041F5C 00008294 */  lhu        $v0, 0x0($a0)
    /* 32760 80041F60 0800E003 */  jr         $ra
    /* 32764 80041F64 00000000 */   nop
endlabel func_80041F5C
