.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_8003DAB4, 0x10

glabel func_8003DAB4
    /* 2E2B4 8003DAB4 0580023C */  lui        $v0, %hi(g_video_mode)
    /* 2E2B8 8003DAB8 4C15428C */  lw         $v0, %lo(g_video_mode)($v0)
    /* 2E2BC 8003DABC 0800E003 */  jr         $ra
    /* 2E2C0 8003DAC0 00000000 */   nop
endlabel func_8003DAB4

nonmatching StSetRing, 0x30

glabel StSetRing
    /* 2E2C4 8003DAC4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E2C8 8003DAC8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E2CC 8003DACC 0A80013C */  lui        $at, %hi(D_8009C7E8)
    /* 2E2D0 8003DAD0 E8C724AC */  sw         $a0, %lo(D_8009C7E8)($at)
    /* 2E2D4 8003DAD4 0A80013C */  lui        $at, %hi(D_8009FFA4)
    /* 2E2D8 8003DAD8 A4FF25AC */  sw         $a1, %lo(D_8009FFA4)($at)
    /* 2E2DC 8003DADC EF01010C */  jal        StClearRing
    /* 2E2E0 8003DAE0 00000000 */   nop
    /* 2E2E4 8003DAE4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E2E8 8003DAE8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E2EC 8003DAEC 0800E003 */  jr         $ra
    /* 2E2F0 8003DAF0 00000000 */   nop
endlabel StSetRing

nonmatching CdInit, 0x7C

glabel CdInit
    /* 2E2F4 8003DAF4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E2F8 8003DAF8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2E2FC 8003DAFC 04001034 */  ori        $s0, $zero, 0x4
    /* 2E300 8003DB00 1400BFAF */  sw         $ra, 0x14($sp)
  EVENT_OBJ_10:
    /* 2E304 8003DB04 0FF7000C */  jal        func_8003DC3C
    /* 2E308 8003DB08 01000434 */   ori       $a0, $zero, 0x1
    /* 2E30C 8003DB0C 01000334 */  ori        $v1, $zero, 0x1
    /* 2E310 8003DB10 0F004314 */  bne        $v0, $v1, EVENT_OBJ_5C
    /* 2E314 8003DB14 FFFF1026 */   addiu     $s0, $s0, -0x1
    /* 2E318 8003DB18 0480043C */  lui        $a0, %hi(def_cbsync)
    /* 2E31C 8003DB1C 84DB8424 */  addiu      $a0, $a0, %lo(def_cbsync)
    /* 2E320 8003DB20 64F7000C */  jal        func_8003DD90
    /* 2E324 8003DB24 00000000 */   nop
    /* 2E328 8003DB28 0480043C */  lui        $a0, %hi(def_cbready)
    /* 2E32C 8003DB2C ACDB8424 */  addiu      $a0, $a0, %lo(def_cbready)
    /* 2E330 8003DB30 6AF7000C */  jal        func_8003DDA8
    /* 2E334 8003DB34 00000000 */   nop
    /* 2E338 8003DB38 0480043C */  lui        $a0, %hi(def_cbread)
    /* 2E33C 8003DB3C D4DB8424 */  addiu      $a0, $a0, %lo(def_cbread)
    /* 2E340 8003DB40 8807010C */  jal        func_80041E20
    /* 2E344 8003DB44 00000000 */   nop
    /* 2E348 8003DB48 DCF60008 */  j          EVENT_OBJ_7C
    /* 2E34C 8003DB4C 01000234 */   ori       $v0, $zero, 0x1
  EVENT_OBJ_5C:
    /* 2E350 8003DB50 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 2E354 8003DB54 EBFF0216 */  bne        $s0, $v0, EVENT_OBJ_10
    /* 2E358 8003DB58 00000000 */   nop
    /* 2E35C 8003DB5C 0180043C */  lui        $a0, %hi(D_80010650)
    /* 2E360 8003DB60 50068424 */  addiu      $a0, $a0, %lo(D_80010650)
    /* 2E364 8003DB64 3B0B010C */  jal        printf
    /* 2E368 8003DB68 00000000 */   nop
    /* 2E36C 8003DB6C 21100000 */  addu       $v0, $zero, $zero
endlabel CdInit

nonmatching EVENT_OBJ_7C, 0x14

glabel EVENT_OBJ_7C
    /* 2E370 8003DB70 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2E374 8003DB74 1000B08F */  lw         $s0, 0x10($sp)
    /* 2E378 8003DB78 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E37C 8003DB7C 0800E003 */  jr         $ra
    /* 2E380 8003DB80 00000000 */   nop
endlabel EVENT_OBJ_7C

nonmatching def_cbsync, 0x28

glabel def_cbsync
    /* 2E384 8003DB84 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E388 8003DB88 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E38C 8003DB8C 00F0043C */  lui        $a0, (0xF0000003 >> 16)
    /* 2E390 8003DB90 03008434 */  ori        $a0, $a0, (0xF0000003 & 0xFFFF)
    /* 2E394 8003DB94 450A010C */  jal        DeliverEvent
    /* 2E398 8003DB98 20000534 */   ori       $a1, $zero, 0x20
    /* 2E39C 8003DB9C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E3A0 8003DBA0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E3A4 8003DBA4 0800E003 */  jr         $ra
    /* 2E3A8 8003DBA8 00000000 */   nop
endlabel def_cbsync

nonmatching def_cbready, 0x28

glabel def_cbready
    /* 2E3AC 8003DBAC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E3B0 8003DBB0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E3B4 8003DBB4 00F0043C */  lui        $a0, (0xF0000003 >> 16)
    /* 2E3B8 8003DBB8 03008434 */  ori        $a0, $a0, (0xF0000003 & 0xFFFF)
    /* 2E3BC 8003DBBC 450A010C */  jal        DeliverEvent
    /* 2E3C0 8003DBC0 40000534 */   ori       $a1, $zero, 0x40
    /* 2E3C4 8003DBC4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E3C8 8003DBC8 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E3CC 8003DBCC 0800E003 */  jr         $ra
    /* 2E3D0 8003DBD0 00000000 */   nop
endlabel def_cbready

nonmatching def_cbread, 0x28

glabel def_cbread
    /* 2E3D4 8003DBD4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E3D8 8003DBD8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E3DC 8003DBDC 00F0043C */  lui        $a0, (0xF0000003 >> 16)
    /* 2E3E0 8003DBE0 03008434 */  ori        $a0, $a0, (0xF0000003 & 0xFFFF)
    /* 2E3E4 8003DBE4 450A010C */  jal        DeliverEvent
    /* 2E3E8 8003DBE8 40000534 */   ori       $a1, $zero, 0x40
    /* 2E3EC 8003DBEC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E3F0 8003DBF0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E3F4 8003DBF4 0800E003 */  jr         $ra
    /* 2E3F8 8003DBF8 00000000 */   nop
endlabel def_cbread

nonmatching func_8003DBFC, 0x10

glabel func_8003DBFC
    /* 2E3FC 8003DBFC 0580023C */  lui        $v0, %hi(D_800515F0)
    /* 2E400 8003DC00 F0154290 */  lbu        $v0, %lo(D_800515F0)($v0)
    /* 2E404 8003DC04 0800E003 */  jr         $ra
    /* 2E408 8003DC08 00000000 */   nop
endlabel func_8003DBFC

nonmatching func_8003DC0C, 0x10

glabel func_8003DC0C
    /* 2E40C 8003DC0C 0580023C */  lui        $v0, %hi(D_80051600)
    /* 2E410 8003DC10 00164290 */  lbu        $v0, %lo(D_80051600)($v0)
    /* 2E414 8003DC14 0800E003 */  jr         $ra
    /* 2E418 8003DC18 00000000 */   nop
endlabel func_8003DC0C

nonmatching func_8003DC1C, 0x10

glabel func_8003DC1C
    /* 2E41C 8003DC1C 0580023C */  lui        $v0, %hi(D_80051601)
    /* 2E420 8003DC20 01164290 */  lbu        $v0, %lo(D_80051601)($v0)
    /* 2E424 8003DC24 0800E003 */  jr         $ra
    /* 2E428 8003DC28 00000000 */   nop
endlabel func_8003DC1C

nonmatching func_8003DC2C, 0x10

glabel func_8003DC2C
    /* 2E42C 8003DC2C 0580023C */  lui        $v0, %hi(D_800515FC)
    /* 2E430 8003DC30 FC154224 */  addiu      $v0, $v0, %lo(D_800515FC)
    /* 2E434 8003DC34 0800E003 */  jr         $ra
    /* 2E438 8003DC38 00000000 */   nop
endlabel func_8003DC2C

nonmatching func_8003DC3C, 0x6C

glabel func_8003DC3C
    /* 2E43C 8003DC3C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E440 8003DC40 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2E444 8003DC44 21808000 */  addu       $s0, $a0, $zero
    /* 2E448 8003DC48 02000234 */  ori        $v0, $zero, 0x2
    /* 2E44C 8003DC4C 05000216 */  bne        $s0, $v0, .L8003DC64
    /* 2E450 8003DC50 1400BFAF */   sw        $ra, 0x14($sp)
    /* 2E454 8003DC54 46FD000C */  jal        func_8003F518
    /* 2E458 8003DC58 00000000 */   nop
    /* 2E45C 8003DC5C 25F70008 */  j          .L8003DC94
    /* 2E460 8003DC60 01000234 */   ori       $v0, $zero, 0x1
  .L8003DC64:
    /* 2E464 8003DC64 5AFD000C */  jal        func_8003F568
    /* 2E468 8003DC68 00000000 */   nop
    /* 2E46C 8003DC6C 09004014 */  bnez       $v0, .L8003DC94
    /* 2E470 8003DC70 21100000 */   addu      $v0, $zero, $zero
    /* 2E474 8003DC74 01000234 */  ori        $v0, $zero, 0x1
    /* 2E478 8003DC78 06000216 */  bne        $s0, $v0, .L8003DC94
    /* 2E47C 8003DC7C 00000000 */   nop
    /* 2E480 8003DC80 09FD000C */  jal        func_8003F424
    /* 2E484 8003DC84 00000000 */   nop
    /* 2E488 8003DC88 02004014 */  bnez       $v0, .L8003DC94
    /* 2E48C 8003DC8C 21100000 */   addu      $v0, $zero, $zero
    /* 2E490 8003DC90 01000234 */  ori        $v0, $zero, 0x1
  .L8003DC94:
    /* 2E494 8003DC94 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2E498 8003DC98 1000B08F */  lw         $s0, 0x10($sp)
    /* 2E49C 8003DC9C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E4A0 8003DCA0 0800E003 */  jr         $ra
    /* 2E4A4 8003DCA4 00000000 */   nop
endlabel func_8003DC3C

nonmatching func_8003DCA8, 0x20

glabel func_8003DCA8
    /* 2E4A8 8003DCA8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2E4AC 8003DCAC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E4B0 8003DCB0 D1FC000C */  jal        func_8003F344
    /* 2E4B4 8003DCB4 00000000 */   nop
    /* 2E4B8 8003DCB8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E4BC 8003DCBC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E4C0 8003DCC0 0800E003 */  jr         $ra
    /* 2E4C4 8003DCC4 00000000 */   nop
endlabel func_8003DCA8
