.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80041FE4, 0x20

glabel func_80041FE4
    /* 327E4 80041FE4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 327E8 80041FE8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 327EC 80041FEC 8A08010C */  jal        func_80042228
    /* 327F0 80041FF0 00000000 */   nop
    /* 327F4 80041FF4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 327F8 80041FF8 1800BD27 */  addiu      $sp, $sp, 0x18
  func_80041FFC:
    /* 327FC 80041FFC 0800E003 */  jr         $ra
    /* 32800 80042000 00000000 */   nop
endlabel func_80041FE4

nonmatching func_80042004, 0x20

glabel func_80042004
    /* 32804 80042004 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 32808 80042008 1000BFAF */  sw         $ra, 0x10($sp)
    /* 3280C 8004200C AE08010C */  jal        movie_unknown_800422B8
    /* 32810 80042010 00000000 */   nop
    /* 32814 80042014 1000BF8F */  lw         $ra, 0x10($sp)
    /* 32818 80042018 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 3281C 8004201C 0800E003 */  jr         $ra
    /* 32820 80042020 00000000 */   nop
endlabel func_80042004

nonmatching func_80042024, 0x20

glabel func_80042024
    /* 32824 80042024 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 32828 80042028 1000BFAF */  sw         $ra, 0x10($sp)
    /* 3282C 8004202C D408010C */  jal        func_80042350
    /* 32830 80042030 00000000 */   nop
    /* 32834 80042034 1000BF8F */  lw         $ra, 0x10($sp)
    /* 32838 80042038 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 3283C 8004203C 0800E003 */  jr         $ra
    /* 32840 80042040 00000000 */   nop
endlabel func_80042024

nonmatching func_80042044, 0x24

glabel func_80042044
    /* 32844 80042044 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 32848 80042048 1000BFAF */  sw         $ra, 0x10($sp)
    /* 3284C 8004204C 21288000 */  addu       $a1, $a0, $zero
    /* 32850 80042050 07F4000C */  jal        DMACallback
    /* 32854 80042054 21200000 */   addu      $a0, $zero, $zero
    /* 32858 80042058 1000BF8F */  lw         $ra, 0x10($sp)
    /* 3285C 8004205C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 32860 80042060 0800E003 */  jr         $ra
    /* 32864 80042064 00000000 */   nop
endlabel func_80042044

nonmatching func_80042068, 0x24

glabel func_80042068
    /* 32868 80042068 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 3286C 8004206C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 32870 80042070 21288000 */  addu       $a1, $a0, $zero
    /* 32874 80042074 07F4000C */  jal        DMACallback
    /* 32878 80042078 01000434 */   ori       $a0, $zero, 0x1
    /* 3287C 8004207C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 32880 80042080 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 32884 80042084 0800E003 */  jr         $ra
    /* 32888 80042088 00000000 */   nop
endlabel func_80042068
