.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80042350, 0x98

glabel func_80042350
    /* 32B50 80042350 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 32B54 80042354 0580033C */  lui        $v1, %hi(ptr_DMA_MDEC_OUT_CHCR)
    /* 32B58 80042358 201B638C */  lw         $v1, %lo(ptr_DMA_MDEC_OUT_CHCR)($v1)
    /* 32B5C 8004235C 1000023C */  lui        $v0, (0x100000 >> 16)
    /* 32B60 80042360 1800BFAF */  sw         $ra, 0x18($sp)
    /* 32B64 80042364 1000A2AF */  sw         $v0, 0x10($sp)
    /* 32B68 80042368 0000628C */  lw         $v0, 0x0($v1)
    /* 32B6C 8004236C 0001033C */  lui        $v1, (0x1000000 >> 16)
    /* 32B70 80042370 24104300 */  and        $v0, $v0, $v1
    /* 32B74 80042374 18004010 */  beqz       $v0, .L800423D8
    /* 32B78 80042378 21100000 */   addu      $v0, $zero, $zero
    /* 32B7C 8004237C FFFF0424 */  addiu      $a0, $zero, -0x1
  .L80042380:
    /* 32B80 80042380 1000A28F */  lw         $v0, 0x10($sp)
    /* 32B84 80042384 00000000 */  nop
    /* 32B88 80042388 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 32B8C 8004238C 1000A2AF */  sw         $v0, 0x10($sp)
    /* 32B90 80042390 1000A28F */  lw         $v0, 0x10($sp)
    /* 32B94 80042394 00000000 */  nop
    /* 32B98 80042398 07004414 */  bne        $v0, $a0, .L800423B8
    /* 32B9C 8004239C 00000000 */   nop
    /* 32BA0 800423A0 0180043C */  lui        $a0, %hi(s_unknown_80010B3C)
    /* 32BA4 800423A4 3C0B8424 */  addiu      $a0, $a0, %lo(s_unknown_80010B3C)
    /* 32BA8 800423A8 FA08010C */  jal        movie_print_mdec_timeout
    /* 32BAC 800423AC 00000000 */   nop
    /* 32BB0 800423B0 F6080108 */  j          .L800423D8
    /* 32BB4 800423B4 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L800423B8:
    /* 32BB8 800423B8 0580023C */  lui        $v0, %hi(ptr_DMA_MDEC_OUT_CHCR)
    /* 32BBC 800423BC 201B428C */  lw         $v0, %lo(ptr_DMA_MDEC_OUT_CHCR)($v0)
    /* 32BC0 800423C0 00000000 */  nop
    /* 32BC4 800423C4 0000428C */  lw         $v0, 0x0($v0)
    /* 32BC8 800423C8 00000000 */  nop
    /* 32BCC 800423CC 24104300 */  and        $v0, $v0, $v1
    /* 32BD0 800423D0 EBFF4014 */  bnez       $v0, .L80042380
    /* 32BD4 800423D4 21100000 */   addu      $v0, $zero, $zero
  .L800423D8:
    /* 32BD8 800423D8 1800BF8F */  lw         $ra, 0x18($sp)
    /* 32BDC 800423DC 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 32BE0 800423E0 0800E003 */  jr         $ra
    /* 32BE4 800423E4 00000000 */   nop
endlabel func_80042350
