.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

/* Handwritten function */
nonmatching InitGeom, 0x80

glabel InitGeom
    /* 2A5D8 80039DD8 0580013C */  lui        $at, %hi(D_8004B60C)
    /* 2A5DC 80039DDC 0CB63FAC */  sw         $ra, %lo(D_8004B60C)($at)
    /* 2A5E0 80039DE0 26F3000C */  jal        _patch_gte
    /* 2A5E4 80039DE4 00000000 */   nop
    /* 2A5E8 80039DE8 05801F3C */  lui        $ra, %hi(D_8004B60C)
    /* 2A5EC 80039DEC 0CB6FF8F */  lw         $ra, %lo(D_8004B60C)($ra)
    /* 2A5F0 80039DF0 00000000 */  nop
    /* 2A5F4 80039DF4 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 2A5F8 80039DF8 0040033C */  lui        $v1, (0x40000000 >> 16)
    /* 2A5FC 80039DFC 25104300 */  or         $v0, $v0, $v1
    /* 2A600 80039E00 00608240 */  mtc0       $v0, $12 /* handwritten instruction */
    /* 2A604 80039E04 00000000 */  nop
    /* 2A608 80039E08 55010824 */  addiu      $t0, $zero, 0x155
    /* 2A60C 80039E0C 00E8C848 */  ctc2       $t0, $29 /* handwritten instruction */
    /* 2A610 80039E10 00000000 */  nop
    /* 2A614 80039E14 00010824 */  addiu      $t0, $zero, 0x100
    /* 2A618 80039E18 00F0C848 */  ctc2       $t0, $30 /* handwritten instruction */
    /* 2A61C 80039E1C 00000000 */  nop
    /* 2A620 80039E20 E8030824 */  addiu      $t0, $zero, 0x3E8
    /* 2A624 80039E24 00D0C848 */  ctc2       $t0, $26 /* handwritten instruction */
    /* 2A628 80039E28 00000000 */  nop
    /* 2A62C 80039E2C 9EEF0824 */  addiu      $t0, $zero, -0x1062
    /* 2A630 80039E30 00D8C848 */  ctc2       $t0, $27 /* handwritten instruction */
    /* 2A634 80039E34 00000000 */  nop
    /* 2A638 80039E38 4001083C */  lui        $t0, (0x1400000 >> 16)
    /* 2A63C 80039E3C 00E0C848 */  ctc2       $t0, $28 /* handwritten instruction */
    /* 2A640 80039E40 00000000 */  nop
    /* 2A644 80039E44 00C0C048 */  ctc2       $zero, $24 /* handwritten instruction */
    /* 2A648 80039E48 00C8C048 */  ctc2       $zero, $25 /* handwritten instruction */
    /* 2A64C 80039E4C 00000000 */  nop
    /* 2A650 80039E50 0800E003 */  jr         $ra
    /* 2A654 80039E54 00000000 */   nop
endlabel InitGeom
