.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching ResetCallback, 0x30

glabel ResetCallback
    /* 2D7BC 8003CFBC 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D7C0 8003CFC0 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D7C4 8003CFC4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D7C8 8003CFC8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D7CC 8003CFCC 0C00428C */  lw         $v0, 0xC($v0)
    /* 2D7D0 8003CFD0 00000000 */  nop
    /* 2D7D4 8003CFD4 09F84000 */  jalr       $v0
    /* 2D7D8 8003CFD8 00000000 */   nop
    /* 2D7DC 8003CFDC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D7E0 8003CFE0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D7E4 8003CFE4 0800E003 */  jr         $ra
    /* 2D7E8 8003CFE8 00000000 */   nop
endlabel ResetCallback

nonmatching InterruptCallback, 0x30

glabel InterruptCallback
    /* 2D7EC 8003CFEC 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D7F0 8003CFF0 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D7F4 8003CFF4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D7F8 8003CFF8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D7FC 8003CFFC 0800428C */  lw         $v0, 0x8($v0)
    /* 2D800 8003D000 00000000 */  nop
    /* 2D804 8003D004 09F84000 */  jalr       $v0
    /* 2D808 8003D008 00000000 */   nop
    /* 2D80C 8003D00C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D810 8003D010 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D814 8003D014 0800E003 */  jr         $ra
    /* 2D818 8003D018 00000000 */   nop
endlabel InterruptCallback

nonmatching DMACallback, 0x30

glabel DMACallback
    /* 2D81C 8003D01C 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D820 8003D020 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D824 8003D024 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D828 8003D028 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D82C 8003D02C 0400428C */  lw         $v0, 0x4($v0)
    /* 2D830 8003D030 00000000 */  nop
    /* 2D834 8003D034 09F84000 */  jalr       $v0
    /* 2D838 8003D038 00000000 */   nop
    /* 2D83C 8003D03C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D840 8003D040 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D844 8003D044 0800E003 */  jr         $ra
    /* 2D848 8003D048 00000000 */   nop
endlabel DMACallback
