.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching start, 0x24

glabel start
    /* 18C0 800110C0 0680023C */  lui        $v0, %hi(_bss)
    /* 18C4 800110C4 C02D4224 */  addiu      $v0, $v0, %lo(_bss)
    /* 18C8 800110C8 0A80033C */  lui        $v1, %hi(_bss_end)
    /* 18CC 800110CC A8FF6324 */  addiu      $v1, $v1, %lo(_bss_end)
  .L800110D0:
    /* 18D0 800110D0 000040AC */  sw         $zero, 0x0($v0)
    /* 18D4 800110D4 04004224 */  addiu      $v0, $v0, 0x4
    /* 18D8 800110D8 2B084300 */  sltu       $at, $v0, $v1
    /* 18DC 800110DC FCFF2014 */  bnez       $at, .L800110D0
    /* 18E0 800110E0 00000000 */   nop
endlabel start

/* Handwritten function */
nonmatching stup1, 0x78

glabel stup1
    /* 18E4 800110E4 04000224 */  addiu      $v0, $zero, 0x4
    /* 18E8 800110E8 00000000 */  nop
    /* 18EC 800110EC 00000000 */  nop
    /* 18F0 800110F0 00000000 */  nop
    /* 18F4 800110F4 00000000 */  nop
    /* 18F8 800110F8 0180043C */  lui        $a0, %hi(D_8001116C)
    /* 18FC 800110FC 6C118424 */  addiu      $a0, $a0, %lo(D_8001116C)
    /* 1900 80011100 21208200 */  addu       $a0, $a0, $v0
    /* 1904 80011104 0000828C */  lw         $v0, 0x0($a0)
    /* 1908 80011108 0080083C */  lui        $t0, %hi(D_80000004)
    /* 190C 8001110C 25E84800 */  or         $sp, $v0, $t0
    /* 1910 80011110 0A80043C */  lui        $a0, %hi(_bss_end)
    /* 1914 80011114 A8FF8424 */  addiu      $a0, $a0, %lo(_bss_end)
    /* 1918 80011118 C0200400 */  sll        $a0, $a0, 3
    /* 191C 8001111C C2200400 */  srl        $a0, $a0, 3
    /* 1920 80011120 0680033C */  lui        $v1, %hi(D_80062CE8)
    /* 1924 80011124 E82C638C */  lw         $v1, %lo(D_80062CE8)($v1)
    /* 1928 80011128 00000000 */  nop
    /* 192C 8001112C 23284300 */  subu       $a1, $v0, $v1
    /* 1930 80011130 2328A400 */  subu       $a1, $a1, $a0
    /* 1934 80011134 25208800 */  or         $a0, $a0, $t0
    /* 1938 80011138 0680013C */  lui        $at, %hi(_bss)
    /* 193C 8001113C C02D3FAC */  sw         $ra, %lo(_bss)($at)
    /* 1940 80011140 06801C3C */  lui        $gp, %hi(_gp)
    /* 1944 80011144 F82C9C27 */  addiu      $gp, $gp, %lo(_gp)
    /* 1948 80011148 21F0A003 */  addu       $fp, $sp, $zero
    /* 194C 8001114C 2D0A010C */  jal        InitHeap
    /* 1950 80011150 04008420 */   addi      $a0, $a0, %lo(D_80000004) /* handwritten instruction */
    /* 1954 80011154 06801F3C */  lui        $ra, %hi(_bss)
    /* 1958 80011158 C02DFF8F */  lw         $ra, %lo(_bss)($ra)
endlabel stup1
    /* 195C 8001115C 00000000 */  nop

nonmatching stup0

glabel stup0
    /* 1960 80011160 0E47000C */ .word 0x0C00470E
    /* 1964 80011164 00000000 */ .word 0x00000000
    /* 1968 80011168 4D000000 */ .word 0x0000004D

nonmatching D_8001116C

dlabel D_8001116C
    /* 196C 8001116C 00002000 */ .word 0x00200000 /* invalid instruction */
    /* 1970 80011170 00002000 */ .word 0x00200000 /* invalid instruction */
    /* 1974 80011174 00002000 */ .word 0x00200000 /* invalid instruction */
    /* 1978 80011178 00002000 */ .word 0x00200000 /* invalid instruction */
enddlabel stup0
