.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching StopCallback, 0x30

glabel StopCallback
    /* 2D8B0 8003D0B0 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D8B4 8003D0B4 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D8B8 8003D0B8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D8BC 8003D0BC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D8C0 8003D0C0 1000428C */  lw         $v0, 0x10($v0)
    /* 2D8C4 8003D0C4 00000000 */  nop
    /* 2D8C8 8003D0C8 09F84000 */  jalr       $v0
    /* 2D8CC 8003D0CC 00000000 */   nop
    /* 2D8D0 8003D0D0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D8D4 8003D0D4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D8D8 8003D0D8 0800E003 */  jr         $ra
    /* 2D8DC 8003D0DC 00000000 */   nop
endlabel StopCallback

nonmatching RestartCallback, 0x30

glabel RestartCallback
    /* 2D8E0 8003D0E0 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D8E4 8003D0E4 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D8E8 8003D0E8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D8EC 8003D0EC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D8F0 8003D0F0 1800428C */  lw         $v0, 0x18($v0)
    /* 2D8F4 8003D0F4 00000000 */  nop
    /* 2D8F8 8003D0F8 09F84000 */  jalr       $v0
    /* 2D8FC 8003D0FC 00000000 */   nop
    /* 2D900 8003D100 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D904 8003D104 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D908 8003D108 0800E003 */  jr         $ra
    /* 2D90C 8003D10C 00000000 */   nop
endlabel RestartCallback

nonmatching CheckCallback, 0x10

glabel CheckCallback
    /* 2D910 8003D110 0580023C */  lui        $v0, %hi(D_80050462)
    /* 2D914 8003D114 62044294 */  lhu        $v0, %lo(D_80050462)($v0)
    /* 2D918 8003D118 0800E003 */  jr         $ra
    /* 2D91C 8003D11C 00000000 */   nop
endlabel CheckCallback

nonmatching GetIntrMask, 0x18

glabel GetIntrMask
    /* 2D920 8003D120 0580023C */  lui        $v0, %hi(D_800514F0)
    /* 2D924 8003D124 F014428C */  lw         $v0, %lo(D_800514F0)($v0)
    /* 2D928 8003D128 00000000 */  nop
    /* 2D92C 8003D12C 00004294 */  lhu        $v0, 0x0($v0)
    /* 2D930 8003D130 0800E003 */  jr         $ra
    /* 2D934 8003D134 00000000 */   nop
endlabel GetIntrMask

nonmatching SetIntrMask, 0x1C

glabel SetIntrMask
    /* 2D938 8003D138 0580033C */  lui        $v1, %hi(D_800514F0)
    /* 2D93C 8003D13C F014638C */  lw         $v1, %lo(D_800514F0)($v1)
    /* 2D940 8003D140 00000000 */  nop
    /* 2D944 8003D144 00006294 */  lhu        $v0, 0x0($v1)
    /* 2D948 8003D148 000064A4 */  sh         $a0, 0x0($v1)
    /* 2D94C 8003D14C 0800E003 */  jr         $ra
    /* 2D950 8003D150 00000000 */   nop
endlabel SetIntrMask

nonmatching startIntr, 0xDC

glabel startIntr
    /* 2D954 8003D154 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D958 8003D158 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2D95C 8003D15C 0580103C */  lui        $s0, %hi(D_80050460)
    /* 2D960 8003D160 60041026 */  addiu      $s0, $s0, %lo(D_80050460)
    /* 2D964 8003D164 1400BFAF */  sw         $ra, 0x14($sp)
    /* 2D968 8003D168 00000296 */  lhu        $v0, 0x0($s0)
    /* 2D96C 8003D16C 00000000 */  nop
    /* 2D970 8003D170 2A004014 */  bnez       $v0, INTR_OBJ_260
    /* 2D974 8003D174 21100000 */   addu      $v0, $zero, $zero
    /* 2D978 8003D178 0580033C */  lui        $v1, %hi(D_800514EC)
    /* 2D97C 8003D17C EC14638C */  lw         $v1, %lo(D_800514EC)($v1)
    /* 2D980 8003D180 0580023C */  lui        $v0, %hi(D_800514F0)
    /* 2D984 8003D184 F014428C */  lw         $v0, %lo(D_800514F0)($v0)
    /* 2D988 8003D188 3333053C */  lui        $a1, (0x33333333 >> 16)
    /* 2D98C 8003D18C 000040A4 */  sh         $zero, 0x0($v0)
    /* 2D990 8003D190 00004294 */  lhu        $v0, 0x0($v0)
    /* 2D994 8003D194 3333A534 */  ori        $a1, $a1, (0x33333333 & 0xFFFF)
    /* 2D998 8003D198 000062A4 */  sh         $v0, 0x0($v1)
    /* 2D99C 8003D19C 0580023C */  lui        $v0, %hi(D_800514F4)
    /* 2D9A0 8003D1A0 F414428C */  lw         $v0, %lo(D_800514F4)($v0)
    /* 2D9A4 8003D1A4 21200002 */  addu       $a0, $s0, $zero
    /* 2D9A8 8003D1A8 000045AC */  sw         $a1, 0x0($v0)
    /* 2D9AC 8003D1AC A8F5000C */  jal        memclr
    /* 2D9B0 8003D1B0 1A040534 */   ori       $a1, $zero, 0x41A
    /* 2D9B4 8003D1B4 1F0B010C */  jal        setjmp
    /* 2D9B8 8003D1B8 38000426 */   addiu     $a0, $s0, 0x38
    /* 2D9BC 8003D1BC 03004010 */  beqz       $v0, INTR_OBJ_210
    /* 2D9C0 8003D1C0 00000000 */   nop
    /* 2D9C4 8003D1C4 8CF4000C */  jal        trapIntr
    /* 2D9C8 8003D1C8 00000000 */   nop
  INTR_OBJ_210:
    /* 2D9CC 8003D1CC 0580103C */  lui        $s0, %hi(D_8005049C)
    /* 2D9D0 8003D1D0 9C041026 */  addiu      $s0, $s0, %lo(D_8005049C)
    /* 2D9D4 8003D1D4 FCFF0426 */  addiu      $a0, $s0, -0x4
    /* 2D9D8 8003D1D8 DC0F0226 */  addiu      $v0, $s0, 0xFDC
    /* 2D9DC 8003D1DC 7D0A010C */  jal        HookEntryInt
    /* 2D9E0 8003D1E0 000002AE */   sw        $v0, 0x0($s0)
    /* 2D9E4 8003D1E4 01000234 */  ori        $v0, $zero, 0x1
    /* 2D9E8 8003D1E8 B3F5000C */  jal        startIntrVSync
    /* 2D9EC 8003D1EC C4FF02A6 */   sh        $v0, -0x3C($s0)
    /* 2D9F0 8003D1F0 0580033C */  lui        $v1, %hi(D_800514E8)
    /* 2D9F4 8003D1F4 E814638C */  lw         $v1, %lo(D_800514E8)($v1)
    /* 2D9F8 8003D1F8 FDF5000C */  jal        startIntrDMA
    /* 2D9FC 8003D1FC 140062AC */   sw        $v0, 0x14($v1)
    /* 2DA00 8003D200 0580043C */  lui        $a0, %hi(D_800514E8)
    /* 2DA04 8003D204 E814848C */  lw         $a0, %lo(D_800514E8)($a0)
    /* 2DA08 8003D208 390A010C */  jal        func_800428E4
    /* 2DA0C 8003D20C 040082AC */   sw        $v0, 0x4($a0)
    /* 2DA10 8003D210 890A010C */  jal        func_80042A24
    /* 2DA14 8003D214 C4FF1026 */   addiu     $s0, $s0, -0x3C
    /* 2DA18 8003D218 21100002 */  addu       $v0, $s0, $zero
  INTR_OBJ_260:
    /* 2DA1C 8003D21C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2DA20 8003D220 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DA24 8003D224 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2DA28 8003D228 0800E003 */  jr         $ra
    /* 2DA2C 8003D22C 00000000 */   nop
endlabel startIntr

nonmatching trapIntr, 0x1B4

glabel trapIntr
    /* 2DA30 8003D230 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2DA34 8003D234 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2DA38 8003D238 0580113C */  lui        $s1, %hi(D_80050460)
    /* 2DA3C 8003D23C 60043126 */  addiu      $s1, $s1, %lo(D_80050460)
    /* 2DA40 8003D240 2400BFAF */  sw         $ra, 0x24($sp)
    /* 2DA44 8003D244 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2DA48 8003D248 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2DA4C 8003D24C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2DA50 8003D250 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DA54 8003D254 00002296 */  lhu        $v0, 0x0($s1)
    /* 2DA58 8003D258 00000000 */  nop
    /* 2DA5C 8003D25C 0B004014 */  bnez       $v0, INTR_OBJ_2D0
    /* 2DA60 8003D260 00000000 */   nop
    /* 2DA64 8003D264 0580023C */  lui        $v0, %hi(D_800514EC)
    /* 2DA68 8003D268 EC14428C */  lw         $v0, %lo(D_800514EC)($v0)
    /* 2DA6C 8003D26C 00000000 */  nop
    /* 2DA70 8003D270 00004594 */  lhu        $a1, 0x0($v0)
    /* 2DA74 8003D274 0180043C */  lui        $a0, %hi(D_800105EC)
    /* 2DA78 8003D278 EC058424 */  addiu      $a0, $a0, %lo(D_800105EC)
    /* 2DA7C 8003D27C 3B0B010C */  jal        printf
    /* 2DA80 8003D280 00000000 */   nop
    /* 2DA84 8003D284 750A010C */  jal        ReturnFromException
    /* 2DA88 8003D288 00000000 */   nop
  INTR_OBJ_2D0:
    /* 2DA8C 8003D28C 0580043C */  lui        $a0, %hi(D_800514EC)
    /* 2DA90 8003D290 EC14848C */  lw         $a0, %lo(D_800514EC)($a0)
    /* 2DA94 8003D294 01000234 */  ori        $v0, $zero, 0x1
    /* 2DA98 8003D298 0580013C */  lui        $at, %hi(D_80050462)
    /* 2DA9C 8003D29C 620422A4 */  sh         $v0, %lo(D_80050462)($at)
    /* 2DAA0 8003D2A0 0580023C */  lui        $v0, %hi(D_80050490)
    /* 2DAA4 8003D2A4 90044294 */  lhu        $v0, %lo(D_80050490)($v0)
    /* 2DAA8 8003D2A8 0580033C */  lui        $v1, %hi(D_800514F0)
    /* 2DAAC 8003D2AC F014638C */  lw         $v1, %lo(D_800514F0)($v1)
    /* 2DAB0 8003D2B0 00008494 */  lhu        $a0, 0x0($a0)
    /* 2DAB4 8003D2B4 00006394 */  lhu        $v1, 0x0($v1)
    /* 2DAB8 8003D2B8 24104400 */  and        $v0, $v0, $a0
    /* 2DABC 8003D2BC 24806200 */  and        $s0, $v1, $v0
    /* 2DAC0 8003D2C0 26000012 */  beqz       $s0, INTR_OBJ_3A0
    /* 2DAC4 8003D2C4 00000000 */   nop
    /* 2DAC8 8003D2C8 01001334 */  ori        $s3, $zero, 0x1
    /* 2DACC 8003D2CC 04003426 */  addiu      $s4, $s1, 0x4
  INTR_OBJ_314:
    /* 2DAD0 8003D2D0 16000012 */  beqz       $s0, INTR_OBJ_370
    /* 2DAD4 8003D2D4 21880000 */   addu      $s1, $zero, $zero
    /* 2DAD8 8003D2D8 21908002 */  addu       $s2, $s4, $zero
  INTR_OBJ_320:
    /* 2DADC 8003D2DC 0B00222A */  slti       $v0, $s1, 0xB
    /* 2DAE0 8003D2E0 12004010 */  beqz       $v0, INTR_OBJ_370
    /* 2DAE4 8003D2E4 01000232 */   andi      $v0, $s0, 0x1
    /* 2DAE8 8003D2E8 0B004010 */  beqz       $v0, INTR_OBJ_35C
    /* 2DAEC 8003D2EC 04103302 */   sllv      $v0, $s3, $s1
    /* 2DAF0 8003D2F0 0580033C */  lui        $v1, %hi(D_800514EC)
    /* 2DAF4 8003D2F4 EC14638C */  lw         $v1, %lo(D_800514EC)($v1)
    /* 2DAF8 8003D2F8 27100200 */  nor        $v0, $zero, $v0
    /* 2DAFC 8003D2FC 000062A4 */  sh         $v0, 0x0($v1)
    /* 2DB00 8003D300 0000428E */  lw         $v0, 0x0($s2)
    /* 2DB04 8003D304 00000000 */  nop
    /* 2DB08 8003D308 03004010 */  beqz       $v0, INTR_OBJ_35C
    /* 2DB0C 8003D30C 00000000 */   nop
    /* 2DB10 8003D310 09F84000 */  jalr       $v0
    /* 2DB14 8003D314 00000000 */   nop
  INTR_OBJ_35C:
    /* 2DB18 8003D318 04005226 */  addiu      $s2, $s2, 0x4
    /* 2DB1C 8003D31C 42801000 */  srl        $s0, $s0, 1
    /* 2DB20 8003D320 FFFF0232 */  andi       $v0, $s0, 0xFFFF
    /* 2DB24 8003D324 EDFF4014 */  bnez       $v0, INTR_OBJ_320
    /* 2DB28 8003D328 01003126 */   addiu     $s1, $s1, 0x1
  INTR_OBJ_370:
    /* 2DB2C 8003D32C 0580043C */  lui        $a0, %hi(D_800514EC)
    /* 2DB30 8003D330 EC14848C */  lw         $a0, %lo(D_800514EC)($a0)
    /* 2DB34 8003D334 0580023C */  lui        $v0, %hi(D_80050490)
    /* 2DB38 8003D338 90044294 */  lhu        $v0, %lo(D_80050490)($v0)
    /* 2DB3C 8003D33C 0580033C */  lui        $v1, %hi(D_800514F0)
    /* 2DB40 8003D340 F014638C */  lw         $v1, %lo(D_800514F0)($v1)
    /* 2DB44 8003D344 00008494 */  lhu        $a0, 0x0($a0)
    /* 2DB48 8003D348 00006394 */  lhu        $v1, 0x0($v1)
    /* 2DB4C 8003D34C 24104400 */  and        $v0, $v0, $a0
    /* 2DB50 8003D350 24806200 */  and        $s0, $v1, $v0
    /* 2DB54 8003D354 DEFF0016 */  bnez       $s0, INTR_OBJ_314
    /* 2DB58 8003D358 00000000 */   nop
  INTR_OBJ_3A0:
    /* 2DB5C 8003D35C 0580053C */  lui        $a1, %hi(D_800514EC)
    /* 2DB60 8003D360 EC14A58C */  lw         $a1, %lo(D_800514EC)($a1)
    /* 2DB64 8003D364 0580063C */  lui        $a2, %hi(D_800514F0)
    /* 2DB68 8003D368 F014C68C */  lw         $a2, %lo(D_800514F0)($a2)
    /* 2DB6C 8003D36C 0000A294 */  lhu        $v0, 0x0($a1)
    /* 2DB70 8003D370 0000C394 */  lhu        $v1, 0x0($a2)
    /* 2DB74 8003D374 00000000 */  nop
    /* 2DB78 8003D378 24104300 */  and        $v0, $v0, $v1
    /* 2DB7C 8003D37C 17004010 */  beqz       $v0, INTR_OBJ_420
    /* 2DB80 8003D380 00000000 */   nop
    /* 2DB84 8003D384 0580023C */  lui        $v0, %hi(D_800514F8)
    /* 2DB88 8003D388 F814428C */  lw         $v0, %lo(D_800514F8)($v0)
    /* 2DB8C 8003D38C 00000000 */  nop
    /* 2DB90 8003D390 01004324 */  addiu      $v1, $v0, 0x1
    /* 2DB94 8003D394 01084228 */  slti       $v0, $v0, 0x801
    /* 2DB98 8003D398 0580013C */  lui        $at, %hi(D_800514F8)
    /* 2DB9C 8003D39C F81423AC */  sw         $v1, %lo(D_800514F8)($at)
    /* 2DBA0 8003D3A0 10004014 */  bnez       $v0, INTR_OBJ_428
    /* 2DBA4 8003D3A4 00000000 */   nop
    /* 2DBA8 8003D3A8 0180043C */  lui        $a0, %hi(D_80010608)
    /* 2DBAC 8003D3AC 08068424 */  addiu      $a0, $a0, %lo(D_80010608)
    /* 2DBB0 8003D3B0 0000A594 */  lhu        $a1, 0x0($a1)
    /* 2DBB4 8003D3B4 0000C694 */  lhu        $a2, 0x0($a2)
    /* 2DBB8 8003D3B8 3B0B010C */  jal        printf
    /* 2DBBC 8003D3BC 00000000 */   nop
    /* 2DBC0 8003D3C0 0580023C */  lui        $v0, %hi(D_800514EC)
    /* 2DBC4 8003D3C4 EC14428C */  lw         $v0, %lo(D_800514EC)($v0)
    /* 2DBC8 8003D3C8 0580013C */  lui        $at, %hi(D_800514F8)
    /* 2DBCC 8003D3CC F81420AC */  sw         $zero, %lo(D_800514F8)($at)
    /* 2DBD0 8003D3D0 000040A4 */  sh         $zero, 0x0($v0)
    /* 2DBD4 8003D3D4 F9F40008 */  j          INTR_OBJ_428
    /* 2DBD8 8003D3D8 00000000 */   nop
  INTR_OBJ_420:
    /* 2DBDC 8003D3DC 0580013C */  lui        $at, %hi(D_800514F8)
    /* 2DBE0 8003D3E0 F81420AC */  sw         $zero, %lo(D_800514F8)($at)
endlabel trapIntr

nonmatching INTR_OBJ_428, 0x34

glabel INTR_OBJ_428
    /* 2DBE4 8003D3E4 0580013C */  lui        $at, %hi(D_80050462)
    /* 2DBE8 8003D3E8 620420A4 */  sh         $zero, %lo(D_80050462)($at)
    /* 2DBEC 8003D3EC 750A010C */  jal        ReturnFromException
    /* 2DBF0 8003D3F0 00000000 */   nop
    /* 2DBF4 8003D3F4 2400BF8F */  lw         $ra, 0x24($sp)
    /* 2DBF8 8003D3F8 2000B48F */  lw         $s4, 0x20($sp)
    /* 2DBFC 8003D3FC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2DC00 8003D400 1800B28F */  lw         $s2, 0x18($sp)
    /* 2DC04 8003D404 1400B18F */  lw         $s1, 0x14($sp)
    /* 2DC08 8003D408 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DC0C 8003D40C 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 2DC10 8003D410 0800E003 */  jr         $ra
    /* 2DC14 8003D414 00000000 */   nop
endlabel INTR_OBJ_428

nonmatching setIntr, 0xB8

glabel setIntr
    /* 2DC18 8003D418 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2DC1C 8003D41C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2DC20 8003D420 21888000 */  addu       $s1, $a0, $zero
    /* 2DC24 8003D424 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2DC28 8003D428 2190A000 */  addu       $s2, $a1, $zero
    /* 2DC2C 8003D42C 0580053C */  lui        $a1, %hi(D_80050464)
    /* 2DC30 8003D430 6404A524 */  addiu      $a1, $a1, %lo(D_80050464)
    /* 2DC34 8003D434 80101100 */  sll        $v0, $s1, 2
    /* 2DC38 8003D438 21204500 */  addu       $a0, $v0, $a1
    /* 2DC3C 8003D43C 2400BFAF */  sw         $ra, 0x24($sp)
    /* 2DC40 8003D440 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2DC44 8003D444 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2DC48 8003D448 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DC4C 8003D44C 0000948C */  lw         $s4, 0x0($a0)
    /* 2DC50 8003D450 00000000 */  nop
    /* 2DC54 8003D454 3C005412 */  beq        $s2, $s4, INTR_OBJ_58C
    /* 2DC58 8003D458 21108002 */   addu      $v0, $s4, $zero
    /* 2DC5C 8003D45C FCFFA294 */  lhu        $v0, -0x4($a1)
    /* 2DC60 8003D460 00000000 */  nop
    /* 2DC64 8003D464 38004010 */  beqz       $v0, INTR_OBJ_58C
    /* 2DC68 8003D468 21108002 */   addu      $v0, $s4, $zero
    /* 2DC6C 8003D46C 0580023C */  lui        $v0, %hi(D_800514F0)
    /* 2DC70 8003D470 F014428C */  lw         $v0, %lo(D_800514F0)($v0)
    /* 2DC74 8003D474 00000000 */  nop
    /* 2DC78 8003D478 00004394 */  lhu        $v1, 0x0($v0)
    /* 2DC7C 8003D47C 000040A4 */  sh         $zero, 0x0($v0)
    /* 2DC80 8003D480 09004012 */  beqz       $s2, INTR_OBJ_4EC
    /* 2DC84 8003D484 FFFF7330 */   andi      $s3, $v1, 0xFFFF
    /* 2DC88 8003D488 01000334 */  ori        $v1, $zero, 0x1
    /* 2DC8C 8003D48C 04182302 */  sllv       $v1, $v1, $s1
    /* 2DC90 8003D490 000092AC */  sw         $s2, 0x0($a0)
    /* 2DC94 8003D494 2C00A294 */  lhu        $v0, 0x2C($a1)
    /* 2DC98 8003D498 25986302 */  or         $s3, $s3, $v1
    /* 2DC9C 8003D49C 25104300 */  or         $v0, $v0, $v1
    /* 2DCA0 8003D4A0 34F50008 */  j          INTR_OBJ_514
    /* 2DCA4 8003D4A4 2C00A2A4 */   sh        $v0, 0x2C($a1)
  INTR_OBJ_4EC:
    /* 2DCA8 8003D4A8 01000234 */  ori        $v0, $zero, 0x1
    /* 2DCAC 8003D4AC 04102202 */  sllv       $v0, $v0, $s1
    /* 2DCB0 8003D4B0 27100200 */  nor        $v0, $zero, $v0
    /* 2DCB4 8003D4B4 000080AC */  sw         $zero, 0x0($a0)
    /* 2DCB8 8003D4B8 0580033C */  lui        $v1, %hi(D_80050490)
    /* 2DCBC 8003D4BC 90046394 */  lhu        $v1, %lo(D_80050490)($v1)
    /* 2DCC0 8003D4C0 24986202 */  and        $s3, $s3, $v0
    /* 2DCC4 8003D4C4 24186200 */  and        $v1, $v1, $v0
    /* 2DCC8 8003D4C8 0580013C */  lui        $at, %hi(D_80050490)
    /* 2DCCC 8003D4CC 900423A4 */  sh         $v1, %lo(D_80050490)($at)
endlabel setIntr

nonmatching INTR_OBJ_514, 0x9C

glabel INTR_OBJ_514
    /* 2DCD0 8003D4D0 08002016 */  bnez       $s1, INTR_OBJ_538
    /* 2DCD4 8003D4D4 04000234 */   ori       $v0, $zero, 0x4
    /* 2DCD8 8003D4D8 0100502E */  sltiu      $s0, $s2, 0x1
    /* 2DCDC 8003D4DC B10A010C */  jal        ChangeClearPAD
    /* 2DCE0 8003D4E0 21200002 */   addu      $a0, $s0, $zero
    /* 2DCE4 8003D4E4 03000434 */  ori        $a0, $zero, 0x3
    /* 2DCE8 8003D4E8 B50A010C */  jal        ChangeClearRCnt
    /* 2DCEC 8003D4EC 21280002 */   addu      $a1, $s0, $zero
    /* 2DCF0 8003D4F0 04000234 */  ori        $v0, $zero, 0x4
  INTR_OBJ_538:
    /* 2DCF4 8003D4F4 05002216 */  bne        $s1, $v0, INTR_OBJ_550
    /* 2DCF8 8003D4F8 05000234 */   ori       $v0, $zero, 0x5
    /* 2DCFC 8003D4FC 21200000 */  addu       $a0, $zero, $zero
    /* 2DD00 8003D500 B50A010C */  jal        ChangeClearRCnt
    /* 2DD04 8003D504 0100452E */   sltiu     $a1, $s2, 0x1
    /* 2DD08 8003D508 05000234 */  ori        $v0, $zero, 0x5
  INTR_OBJ_550:
    /* 2DD0C 8003D50C 05002216 */  bne        $s1, $v0, INTR_OBJ_568
    /* 2DD10 8003D510 06000234 */   ori       $v0, $zero, 0x6
    /* 2DD14 8003D514 01000434 */  ori        $a0, $zero, 0x1
    /* 2DD18 8003D518 B50A010C */  jal        ChangeClearRCnt
    /* 2DD1C 8003D51C 0100452E */   sltiu     $a1, $s2, 0x1
    /* 2DD20 8003D520 06000234 */  ori        $v0, $zero, 0x6
  INTR_OBJ_568:
    /* 2DD24 8003D524 03002216 */  bne        $s1, $v0, INTR_OBJ_578
    /* 2DD28 8003D528 02000434 */   ori       $a0, $zero, 0x2
    /* 2DD2C 8003D52C B50A010C */  jal        ChangeClearRCnt
    /* 2DD30 8003D530 0100452E */   sltiu     $a1, $s2, 0x1
  INTR_OBJ_578:
    /* 2DD34 8003D534 0580023C */  lui        $v0, %hi(D_800514F0)
    /* 2DD38 8003D538 F014428C */  lw         $v0, %lo(D_800514F0)($v0)
    /* 2DD3C 8003D53C 00000000 */  nop
    /* 2DD40 8003D540 000053A4 */  sh         $s3, 0x0($v0)
    /* 2DD44 8003D544 21108002 */  addu       $v0, $s4, $zero
  INTR_OBJ_58C:
    /* 2DD48 8003D548 2400BF8F */  lw         $ra, 0x24($sp)
    /* 2DD4C 8003D54C 2000B48F */  lw         $s4, 0x20($sp)
    /* 2DD50 8003D550 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2DD54 8003D554 1800B28F */  lw         $s2, 0x18($sp)
    /* 2DD58 8003D558 1400B18F */  lw         $s1, 0x14($sp)
    /* 2DD5C 8003D55C 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DD60 8003D560 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 2DD64 8003D564 0800E003 */  jr         $ra
    /* 2DD68 8003D568 00000000 */   nop
endlabel INTR_OBJ_514

nonmatching stopIntr, 0xAC

glabel stopIntr
    /* 2DD6C 8003D56C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2DD70 8003D570 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DD74 8003D574 0580103C */  lui        $s0, %hi(D_80050460)
    /* 2DD78 8003D578 60041026 */  addiu      $s0, $s0, %lo(D_80050460)
    /* 2DD7C 8003D57C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 2DD80 8003D580 00000296 */  lhu        $v0, 0x0($s0)
    /* 2DD84 8003D584 00000000 */  nop
    /* 2DD88 8003D588 1E004010 */  beqz       $v0, INTR_OBJ_648
    /* 2DD8C 8003D58C 21100000 */   addu      $v0, $zero, $zero
    /* 2DD90 8003D590 850A010C */  jal        func_80042A14
    /* 2DD94 8003D594 00000000 */   nop
    /* 2DD98 8003D598 0580023C */  lui        $v0, %hi(D_800514F0)
    /* 2DD9C 8003D59C F014428C */  lw         $v0, %lo(D_800514F0)($v0)
    /* 2DDA0 8003D5A0 0580043C */  lui        $a0, %hi(D_800514F4)
    /* 2DDA4 8003D5A4 F414848C */  lw         $a0, %lo(D_800514F4)($a0)
    /* 2DDA8 8003D5A8 00004394 */  lhu        $v1, 0x0($v0)
    /* 2DDAC 8003D5AC 0580013C */  lui        $at, %hi(D_80050492)
    /* 2DDB0 8003D5B0 920423A4 */  sh         $v1, %lo(D_80050492)($at)
    /* 2DDB4 8003D5B4 0000838C */  lw         $v1, 0x0($a0)
    /* 2DDB8 8003D5B8 0580043C */  lui        $a0, %hi(D_800514EC)
    /* 2DDBC 8003D5BC EC14848C */  lw         $a0, %lo(D_800514EC)($a0)
    /* 2DDC0 8003D5C0 0580013C */  lui        $at, %hi(D_80050494)
    /* 2DDC4 8003D5C4 940423AC */  sw         $v1, %lo(D_80050494)($at)
    /* 2DDC8 8003D5C8 000040A4 */  sh         $zero, 0x0($v0)
    /* 2DDCC 8003D5CC 00004294 */  lhu        $v0, 0x0($v0)
    /* 2DDD0 8003D5D0 00000000 */  nop
    /* 2DDD4 8003D5D4 000082A4 */  sh         $v0, 0x0($a0)
    /* 2DDD8 8003D5D8 0580043C */  lui        $a0, %hi(D_800514F4)
    /* 2DDDC 8003D5DC F414848C */  lw         $a0, %lo(D_800514F4)($a0)
    /* 2DDE0 8003D5E0 7777033C */  lui        $v1, (0x77777777 >> 16)
    /* 2DDE4 8003D5E4 0000828C */  lw         $v0, 0x0($a0)
    /* 2DDE8 8003D5E8 77776334 */  ori        $v1, $v1, (0x77777777 & 0xFFFF)
    /* 2DDEC 8003D5EC 24104300 */  and        $v0, $v0, $v1
    /* 2DDF0 8003D5F0 000082AC */  sw         $v0, 0x0($a0)
    /* 2DDF4 8003D5F4 790A010C */  jal        ResetEntryInt
    /* 2DDF8 8003D5F8 00000000 */   nop
    /* 2DDFC 8003D5FC 21100002 */  addu       $v0, $s0, $zero
    /* 2DE00 8003D600 000040A4 */  sh         $zero, 0x0($v0)
  INTR_OBJ_648:
    /* 2DE04 8003D604 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2DE08 8003D608 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DE0C 8003D60C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2DE10 8003D610 0800E003 */  jr         $ra
    /* 2DE14 8003D614 00000000 */   nop
endlabel stopIntr

nonmatching restartIntr, 0x74

glabel restartIntr
    /* 2DE18 8003D618 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2DE1C 8003D61C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DE20 8003D620 0580103C */  lui        $s0, %hi(D_80050460)
    /* 2DE24 8003D624 60041026 */  addiu      $s0, $s0, %lo(D_80050460)
    /* 2DE28 8003D628 1400BFAF */  sw         $ra, 0x14($sp)
    /* 2DE2C 8003D62C 00000296 */  lhu        $v0, 0x0($s0)
    /* 2DE30 8003D630 00000000 */  nop
    /* 2DE34 8003D634 14004014 */  bnez       $v0, INTR_OBJ_6CC
    /* 2DE38 8003D638 00000000 */   nop
    /* 2DE3C 8003D63C 7D0A010C */  jal        HookEntryInt
    /* 2DE40 8003D640 38000426 */   addiu     $a0, $s0, 0x38
    /* 2DE44 8003D644 0580043C */  lui        $a0, %hi(D_800514F0)
    /* 2DE48 8003D648 F014848C */  lw         $a0, %lo(D_800514F0)($a0)
    /* 2DE4C 8003D64C 0580033C */  lui        $v1, %hi(D_80050492)
    /* 2DE50 8003D650 92046394 */  lhu        $v1, %lo(D_80050492)($v1)
    /* 2DE54 8003D654 01000234 */  ori        $v0, $zero, 0x1
    /* 2DE58 8003D658 000002A6 */  sh         $v0, 0x0($s0)
    /* 2DE5C 8003D65C 000083A4 */  sh         $v1, 0x0($a0)
    /* 2DE60 8003D660 0580033C */  lui        $v1, %hi(D_800514F4)
    /* 2DE64 8003D664 F414638C */  lw         $v1, %lo(D_800514F4)($v1)
    /* 2DE68 8003D668 0580023C */  lui        $v0, %hi(D_80050494)
    /* 2DE6C 8003D66C 9404428C */  lw         $v0, %lo(D_80050494)($v0)
    /* 2DE70 8003D670 00000000 */  nop
    /* 2DE74 8003D674 000062AC */  sw         $v0, 0x0($v1)
    /* 2DE78 8003D678 890A010C */  jal        func_80042A24
    /* 2DE7C 8003D67C 00000000 */   nop
    /* 2DE80 8003D680 A3F50008 */  j          INTR_OBJ_6D0
    /* 2DE84 8003D684 21100002 */   addu      $v0, $s0, $zero
  INTR_OBJ_6CC:
    /* 2DE88 8003D688 21100000 */  addu       $v0, $zero, $zero
endlabel restartIntr

nonmatching INTR_OBJ_6D0, 0x14

glabel INTR_OBJ_6D0
    /* 2DE8C 8003D68C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2DE90 8003D690 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DE94 8003D694 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2DE98 8003D698 0800E003 */  jr         $ra
    /* 2DE9C 8003D69C 00000000 */   nop
endlabel INTR_OBJ_6D0

nonmatching memclr, 0x2C

glabel memclr
    /* 2DEA0 8003D6A0 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 2DEA4 8003D6A4 0600A010 */  beqz       $a1, INTR_OBJ_704
    /* 2DEA8 8003D6A8 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* 2DEAC 8003D6AC FFFF0324 */  addiu      $v1, $zero, -0x1
  INTR_OBJ_6F4:
    /* 2DEB0 8003D6B0 000080AC */  sw         $zero, 0x0($a0)
    /* 2DEB4 8003D6B4 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2DEB8 8003D6B8 FDFF4314 */  bne        $v0, $v1, INTR_OBJ_6F4
    /* 2DEBC 8003D6BC 04008424 */   addiu     $a0, $a0, 0x4
  INTR_OBJ_704:
    /* 2DEC0 8003D6C0 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 2DEC4 8003D6C4 0800E003 */  jr         $ra
    /* 2DEC8 8003D6C8 00000000 */   nop
endlabel memclr

nonmatching startIntrVSync, 0x58

glabel startIntrVSync
    /* 2DECC 8003D6CC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2DED0 8003D6D0 0580043C */  lui        $a0, %hi(D_800514FC)
    /* 2DED4 8003D6D4 FC148424 */  addiu      $a0, $a0, %lo(D_800514FC)
    /* 2DED8 8003D6D8 0580033C */  lui        $v1, %hi(D_80051520)
    /* 2DEDC 8003D6DC 2015638C */  lw         $v1, %lo(D_80051520)($v1)
    /* 2DEE0 8003D6E0 07010234 */  ori        $v0, $zero, 0x107
    /* 2DEE4 8003D6E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2DEE8 8003D6E8 000062AC */  sw         $v0, 0x0($v1)
    /* 2DEEC 8003D6EC 0580013C */  lui        $at, %hi(D_8005151C)
    /* 2DEF0 8003D6F0 1C1520AC */  sw         $zero, %lo(D_8005151C)($at)
    /* 2DEF4 8003D6F4 F2F5000C */  jal        func_8003D7C8
    /* 2DEF8 8003D6F8 08000534 */   ori       $a1, $zero, 0x8
    /* 2DEFC 8003D6FC 0480053C */  lui        $a1, %hi(trapIntrVSync)
    /* 2DF00 8003D700 24D7A524 */  addiu      $a1, $a1, %lo(trapIntrVSync)
    /* 2DF04 8003D704 FBF3000C */  jal        InterruptCallback
    /* 2DF08 8003D708 21200000 */   addu      $a0, $zero, $zero
    /* 2DF0C 8003D70C 0480023C */  lui        $v0, %hi(setIntrVSync)
    /* 2DF10 8003D710 9CD74224 */  addiu      $v0, $v0, %lo(setIntrVSync)
    /* 2DF14 8003D714 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2DF18 8003D718 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2DF1C 8003D71C 0800E003 */  jr         $ra
    /* 2DF20 8003D720 00000000 */   nop
endlabel startIntrVSync

nonmatching trapIntrVSync, 0x78

glabel trapIntrVSync
    /* 2DF24 8003D724 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2DF28 8003D728 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
    /* 2DF2C 8003D72C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2DF30 8003D730 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2DF34 8003D734 21880000 */  addu       $s1, $zero, $zero
    /* 2DF38 8003D738 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2DF3C 8003D73C 0580103C */  lui        $s0, %hi(D_800514FC)
    /* 2DF40 8003D740 FC141026 */  addiu      $s0, $s0, %lo(D_800514FC)
    /* 2DF44 8003D744 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2DF48 8003D748 01004224 */  addiu      $v0, $v0, 0x1
    /* 2DF4C 8003D74C 0580013C */  lui        $at, %hi(D_8005151C)
    /* 2DF50 8003D750 1C1522AC */  sw         $v0, %lo(D_8005151C)($at)
    /* 2DF54 8003D754 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2DF58 8003D758 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
  INTR_VB_OBJ_90:
    /* 2DF5C 8003D75C 0000028E */  lw         $v0, 0x0($s0)
    /* 2DF60 8003D760 00000000 */  nop
    /* 2DF64 8003D764 03004010 */  beqz       $v0, INTR_VB_OBJ_A8
    /* 2DF68 8003D768 04001026 */   addiu     $s0, $s0, 0x4
    /* 2DF6C 8003D76C 09F84000 */  jalr       $v0
    /* 2DF70 8003D770 00000000 */   nop
  INTR_VB_OBJ_A8:
    /* 2DF74 8003D774 01003126 */  addiu      $s1, $s1, 0x1
    /* 2DF78 8003D778 0800222A */  slti       $v0, $s1, 0x8
    /* 2DF7C 8003D77C F7FF4014 */  bnez       $v0, INTR_VB_OBJ_90
    /* 2DF80 8003D780 00000000 */   nop
    /* 2DF84 8003D784 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2DF88 8003D788 1400B18F */  lw         $s1, 0x14($sp)
    /* 2DF8C 8003D78C 1000B08F */  lw         $s0, 0x10($sp)
    /* 2DF90 8003D790 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2DF94 8003D794 0800E003 */  jr         $ra
    /* 2DF98 8003D798 00000000 */   nop
endlabel trapIntrVSync

nonmatching setIntrVSync, 0x2C

glabel setIntrVSync
    /* 2DF9C 8003D79C 0580023C */  lui        $v0, %hi(D_800514FC)
    /* 2DFA0 8003D7A0 FC144224 */  addiu      $v0, $v0, %lo(D_800514FC)
    /* 2DFA4 8003D7A4 80200400 */  sll        $a0, $a0, 2
    /* 2DFA8 8003D7A8 21208200 */  addu       $a0, $a0, $v0
    /* 2DFAC 8003D7AC 0000828C */  lw         $v0, 0x0($a0)
    /* 2DFB0 8003D7B0 00000000 */  nop
    /* 2DFB4 8003D7B4 0200A210 */  beq        $a1, $v0, INTR_VB_OBJ_F4
    /* 2DFB8 8003D7B8 00000000 */   nop
    /* 2DFBC 8003D7BC 000085AC */  sw         $a1, 0x0($a0)
  INTR_VB_OBJ_F4:
    /* 2DFC0 8003D7C0 0800E003 */  jr         $ra
    /* 2DFC4 8003D7C4 00000000 */   nop
endlabel setIntrVSync

nonmatching func_8003D7C8, 0x2C

glabel func_8003D7C8
    /* 2DFC8 8003D7C8 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 2DFCC 8003D7CC 0600A010 */  beqz       $a1, INTR_VB_OBJ_11C
    /* 2DFD0 8003D7D0 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* 2DFD4 8003D7D4 FFFF0324 */  addiu      $v1, $zero, -0x1
  INTR_VB_OBJ_10C:
    /* 2DFD8 8003D7D8 000080AC */  sw         $zero, 0x0($a0)
    /* 2DFDC 8003D7DC FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2DFE0 8003D7E0 FDFF4314 */  bne        $v0, $v1, INTR_VB_OBJ_10C
    /* 2DFE4 8003D7E4 04008424 */   addiu     $a0, $a0, 0x4
  INTR_VB_OBJ_11C:
    /* 2DFE8 8003D7E8 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 2DFEC 8003D7EC 0800E003 */  jr         $ra
    /* 2DFF0 8003D7F0 00000000 */   nop
endlabel func_8003D7C8

nonmatching startIntrDMA, 0x50

glabel startIntrDMA
    /* 2DFF4 8003D7F4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2DFF8 8003D7F8 0580043C */  lui        $a0, %hi(D_80051528)
    /* 2DFFC 8003D7FC 28158424 */  addiu      $a0, $a0, %lo(D_80051528)
    /* 2E000 8003D800 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2E004 8003D804 9CF6000C */  jal        func_8003DA70
    /* 2E008 8003D808 08000534 */   ori       $a1, $zero, 0x8
    /* 2E00C 8003D80C 03000434 */  ori        $a0, $zero, 0x3
    /* 2E010 8003D810 0580023C */  lui        $v0, %hi(D_80051524)
    /* 2E014 8003D814 2415428C */  lw         $v0, %lo(D_80051524)($v0)
    /* 2E018 8003D818 0480053C */  lui        $a1, %hi(trapIntrDMA)
    /* 2E01C 8003D81C 44D8A524 */  addiu      $a1, $a1, %lo(trapIntrDMA)
    /* 2E020 8003D820 000040AC */  sw         $zero, 0x0($v0)
    /* 2E024 8003D824 FBF3000C */  jal        InterruptCallback
    /* 2E028 8003D828 00000000 */   nop
    /* 2E02C 8003D82C 0480023C */  lui        $v0, %hi(setIntrDMA)
    /* 2E030 8003D830 C8D94224 */  addiu      $v0, $v0, %lo(setIntrDMA)
    /* 2E034 8003D834 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2E038 8003D838 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2E03C 8003D83C 0800E003 */  jr         $ra
    /* 2E040 8003D840 00000000 */   nop
endlabel startIntrDMA

nonmatching trapIntrDMA, 0x184

glabel trapIntrDMA
    /* 2E044 8003D844 0580023C */  lui        $v0, %hi(D_80051524)
    /* 2E048 8003D848 2415428C */  lw         $v0, %lo(D_80051524)($v0)
    /* 2E04C 8003D84C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 2E050 8003D850 2800BFAF */  sw         $ra, 0x28($sp)
    /* 2E054 8003D854 2400B5AF */  sw         $s5, 0x24($sp)
    /* 2E058 8003D858 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2E05C 8003D85C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2E060 8003D860 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2E064 8003D864 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2E068 8003D868 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2E06C 8003D86C 0000428C */  lw         $v0, 0x0($v0)
    /* 2E070 8003D870 00000000 */  nop
    /* 2E074 8003D874 02160200 */  srl        $v0, $v0, 24
    /* 2E078 8003D878 7F005130 */  andi       $s1, $v0, 0x7F
    /* 2E07C 8003D87C 28002012 */  beqz       $s1, INTR_DMA_OBJ_12C
    /* 2E080 8003D880 00000000 */   nop
    /* 2E084 8003D884 01001434 */  ori        $s4, $zero, 0x1
    /* 2E088 8003D888 FF00133C */  lui        $s3, (0xFFFFFF >> 16)
    /* 2E08C 8003D88C FFFF7336 */  ori        $s3, $s3, (0xFFFFFF & 0xFFFF)
    /* 2E090 8003D890 0580153C */  lui        $s5, %hi(D_80051528)
    /* 2E094 8003D894 2815B526 */  addiu      $s5, $s5, %lo(D_80051528)
  INTR_DMA_OBJ_A4:
    /* 2E098 8003D898 18002012 */  beqz       $s1, INTR_DMA_OBJ_108
    /* 2E09C 8003D89C 21800000 */   addu      $s0, $zero, $zero
    /* 2E0A0 8003D8A0 2190A002 */  addu       $s2, $s5, $zero
  INTR_DMA_OBJ_B0:
    /* 2E0A4 8003D8A4 0700022A */  slti       $v0, $s0, 0x7
    /* 2E0A8 8003D8A8 14004010 */  beqz       $v0, INTR_DMA_OBJ_108
    /* 2E0AC 8003D8AC 01002232 */   andi      $v0, $s1, 0x1
    /* 2E0B0 8003D8B0 0E004010 */  beqz       $v0, INTR_DMA_OBJ_F8
    /* 2E0B4 8003D8B4 18000226 */   addiu     $v0, $s0, 0x18
    /* 2E0B8 8003D8B8 0580043C */  lui        $a0, %hi(D_80051524)
    /* 2E0BC 8003D8BC 2415848C */  lw         $a0, %lo(D_80051524)($a0)
    /* 2E0C0 8003D8C0 04105400 */  sllv       $v0, $s4, $v0
    /* 2E0C4 8003D8C4 0000838C */  lw         $v1, 0x0($a0)
    /* 2E0C8 8003D8C8 25105300 */  or         $v0, $v0, $s3
    /* 2E0CC 8003D8CC 24104300 */  and        $v0, $v0, $v1
    /* 2E0D0 8003D8D0 000082AC */  sw         $v0, 0x0($a0)
    /* 2E0D4 8003D8D4 0000428E */  lw         $v0, 0x0($s2)
    /* 2E0D8 8003D8D8 00000000 */  nop
    /* 2E0DC 8003D8DC 03004010 */  beqz       $v0, INTR_DMA_OBJ_F8
    /* 2E0E0 8003D8E0 00000000 */   nop
    /* 2E0E4 8003D8E4 09F84000 */  jalr       $v0
    /* 2E0E8 8003D8E8 00000000 */   nop
  INTR_DMA_OBJ_F8:
    /* 2E0EC 8003D8EC 04005226 */  addiu      $s2, $s2, 0x4
    /* 2E0F0 8003D8F0 42881100 */  srl        $s1, $s1, 1
    /* 2E0F4 8003D8F4 EBFF2016 */  bnez       $s1, INTR_DMA_OBJ_B0
    /* 2E0F8 8003D8F8 01001026 */   addiu     $s0, $s0, 0x1
  INTR_DMA_OBJ_108:
    /* 2E0FC 8003D8FC 0580023C */  lui        $v0, %hi(D_80051524)
    /* 2E100 8003D900 2415428C */  lw         $v0, %lo(D_80051524)($v0)
    /* 2E104 8003D904 00000000 */  nop
    /* 2E108 8003D908 0000428C */  lw         $v0, 0x0($v0)
    /* 2E10C 8003D90C 00000000 */  nop
    /* 2E110 8003D910 02160200 */  srl        $v0, $v0, 24
    /* 2E114 8003D914 7F005130 */  andi       $s1, $v0, 0x7F
    /* 2E118 8003D918 DFFF2016 */  bnez       $s1, INTR_DMA_OBJ_A4
    /* 2E11C 8003D91C 00000000 */   nop
  INTR_DMA_OBJ_12C:
    /* 2E120 8003D920 0580053C */  lui        $a1, %hi(D_80051524)
    /* 2E124 8003D924 2415A58C */  lw         $a1, %lo(D_80051524)($a1)
    /* 2E128 8003D928 00000000 */  nop
    /* 2E12C 8003D92C 0000A28C */  lw         $v0, 0x0($a1)
    /* 2E130 8003D930 00FF033C */  lui        $v1, (0xFF000000 >> 16)
    /* 2E134 8003D934 24104300 */  and        $v0, $v0, $v1
    /* 2E138 8003D938 0080033C */  lui        $v1, (0x80000000 >> 16)
    /* 2E13C 8003D93C 06004310 */  beq        $v0, $v1, INTR_DMA_OBJ_164
    /* 2E140 8003D940 00000000 */   nop
    /* 2E144 8003D944 0000A28C */  lw         $v0, 0x0($a1)
    /* 2E148 8003D948 00000000 */  nop
    /* 2E14C 8003D94C 00804230 */  andi       $v0, $v0, 0x8000
    /* 2E150 8003D950 13004010 */  beqz       $v0, INTR_DMA_OBJ_1AC
    /* 2E154 8003D954 00000000 */   nop
  INTR_DMA_OBJ_164:
    /* 2E158 8003D958 0180043C */  lui        $a0, %hi(D_80010624)
    /* 2E15C 8003D95C 24068424 */  addiu      $a0, $a0, %lo(D_80010624)
    /* 2E160 8003D960 0000A58C */  lw         $a1, 0x0($a1)
    /* 2E164 8003D964 3B0B010C */  jal        printf
    /* 2E168 8003D968 21800000 */   addu      $s0, $zero, $zero
  INTR_DMA_OBJ_178:
    /* 2E16C 8003D96C 0180043C */  lui        $a0, %hi(D_80010640)
    /* 2E170 8003D970 40068424 */  addiu      $a0, $a0, %lo(D_80010640)
    /* 2E174 8003D974 21280002 */  addu       $a1, $s0, $zero
    /* 2E178 8003D978 0580023C */  lui        $v0, %hi(D_80051548)
    /* 2E17C 8003D97C 4815428C */  lw         $v0, %lo(D_80051548)($v0)
    /* 2E180 8003D980 00191000 */  sll        $v1, $s0, 4
    /* 2E184 8003D984 21186200 */  addu       $v1, $v1, $v0
    /* 2E188 8003D988 0000668C */  lw         $a2, 0x0($v1)
    /* 2E18C 8003D98C 3B0B010C */  jal        printf
    /* 2E190 8003D990 01001026 */   addiu     $s0, $s0, 0x1
    /* 2E194 8003D994 0700022A */  slti       $v0, $s0, 0x7
    /* 2E198 8003D998 F4FF4014 */  bnez       $v0, INTR_DMA_OBJ_178
    /* 2E19C 8003D99C 00000000 */   nop
  INTR_DMA_OBJ_1AC:
    /* 2E1A0 8003D9A0 2800BF8F */  lw         $ra, 0x28($sp)
    /* 2E1A4 8003D9A4 2400B58F */  lw         $s5, 0x24($sp)
    /* 2E1A8 8003D9A8 2000B48F */  lw         $s4, 0x20($sp)
    /* 2E1AC 8003D9AC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2E1B0 8003D9B0 1800B28F */  lw         $s2, 0x18($sp)
    /* 2E1B4 8003D9B4 1400B18F */  lw         $s1, 0x14($sp)
    /* 2E1B8 8003D9B8 1000B08F */  lw         $s0, 0x10($sp)
    /* 2E1BC 8003D9BC 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 2E1C0 8003D9C0 0800E003 */  jr         $ra
    /* 2E1C4 8003D9C4 00000000 */   nop
endlabel trapIntrDMA

nonmatching setIntrDMA, 0xA0

glabel setIntrDMA
    /* 2E1C8 8003D9C8 21308000 */  addu       $a2, $a0, $zero
    /* 2E1CC 8003D9CC 0580033C */  lui        $v1, %hi(D_80051528)
    /* 2E1D0 8003D9D0 28156324 */  addiu      $v1, $v1, %lo(D_80051528)
    /* 2E1D4 8003D9D4 80100600 */  sll        $v0, $a2, 2
    /* 2E1D8 8003D9D8 21184300 */  addu       $v1, $v0, $v1
    /* 2E1DC 8003D9DC 0000678C */  lw         $a3, 0x0($v1)
    /* 2E1E0 8003D9E0 2120A000 */  addu       $a0, $a1, $zero
    /* 2E1E4 8003D9E4 20008710 */  beq        $a0, $a3, INTR_DMA_OBJ_274
    /* 2E1E8 8003D9E8 00000000 */   nop
    /* 2E1EC 8003D9EC 10008010 */  beqz       $a0, INTR_DMA_OBJ_23C
    /* 2E1F0 8003D9F0 FF00023C */   lui       $v0, (0xFFFFFF >> 16)
    /* 2E1F4 8003D9F4 0580053C */  lui        $a1, %hi(D_80051524)
    /* 2E1F8 8003D9F8 2415A58C */  lw         $a1, %lo(D_80051524)($a1)
    /* 2E1FC 8003D9FC FFFF4234 */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 2E200 8003DA00 000064AC */  sw         $a0, 0x0($v1)
    /* 2E204 8003DA04 0000A48C */  lw         $a0, 0x0($a1)
    /* 2E208 8003DA08 1000C324 */  addiu      $v1, $a2, 0x10
    /* 2E20C 8003DA0C 24208200 */  and        $a0, $a0, $v0
    /* 2E210 8003DA10 01000234 */  ori        $v0, $zero, 0x1
    /* 2E214 8003DA14 04106200 */  sllv       $v0, $v0, $v1
    /* 2E218 8003DA18 8000033C */  lui        $v1, (0x800000 >> 16)
    /* 2E21C 8003DA1C 25104300 */  or         $v0, $v0, $v1
    /* 2E220 8003DA20 25208200 */  or         $a0, $a0, $v0
    /* 2E224 8003DA24 0000A4AC */  sw         $a0, 0x0($a1)
    /* 2E228 8003DA28 9AF60008 */  j          INTR_DMA_OBJ_274
    /* 2E22C 8003DA2C 00000000 */   nop
  INTR_DMA_OBJ_23C:
    /* 2E230 8003DA30 0580053C */  lui        $a1, %hi(D_80051524)
    /* 2E234 8003DA34 2415A58C */  lw         $a1, %lo(D_80051524)($a1)
    /* 2E238 8003DA38 FFFF4234 */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 2E23C 8003DA3C 000060AC */  sw         $zero, 0x0($v1)
    /* 2E240 8003DA40 0000A38C */  lw         $v1, 0x0($a1)
    /* 2E244 8003DA44 1000C424 */  addiu      $a0, $a2, 0x10
    /* 2E248 8003DA48 24186200 */  and        $v1, $v1, $v0
    /* 2E24C 8003DA4C 8000023C */  lui        $v0, (0x800000 >> 16)
    /* 2E250 8003DA50 25186200 */  or         $v1, $v1, $v0
    /* 2E254 8003DA54 01000234 */  ori        $v0, $zero, 0x1
    /* 2E258 8003DA58 04108200 */  sllv       $v0, $v0, $a0
    /* 2E25C 8003DA5C 27100200 */  nor        $v0, $zero, $v0
    /* 2E260 8003DA60 24186200 */  and        $v1, $v1, $v0
    /* 2E264 8003DA64 0000A3AC */  sw         $v1, 0x0($a1)
endlabel setIntrDMA

nonmatching INTR_DMA_OBJ_274, 0x8

glabel INTR_DMA_OBJ_274
    /* 2E268 8003DA68 0800E003 */  jr         $ra
    /* 2E26C 8003DA6C 2110E000 */   addu      $v0, $a3, $zero
endlabel INTR_DMA_OBJ_274

nonmatching func_8003DA70, 0x2C

glabel func_8003DA70
    /* 2E270 8003DA70 F8FFBD27 */  addiu      $sp, $sp, -0x8
    /* 2E274 8003DA74 0600A010 */  beqz       $a1, INTR_DMA_OBJ_29C
    /* 2E278 8003DA78 FFFFA224 */   addiu     $v0, $a1, -0x1
    /* 2E27C 8003DA7C FFFF0324 */  addiu      $v1, $zero, -0x1
  INTR_DMA_OBJ_28C:
    /* 2E280 8003DA80 000080AC */  sw         $zero, 0x0($a0)
    /* 2E284 8003DA84 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2E288 8003DA88 FDFF4314 */  bne        $v0, $v1, INTR_DMA_OBJ_28C
    /* 2E28C 8003DA8C 04008424 */   addiu     $a0, $a0, 0x4
  INTR_DMA_OBJ_29C:
    /* 2E290 8003DA90 0800BD27 */  addiu      $sp, $sp, 0x8
    /* 2E294 8003DA94 0800E003 */  jr         $ra
    /* 2E298 8003DA98 00000000 */   nop
endlabel func_8003DA70
