.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching VSyncCallback, 0x34

glabel VSyncCallback
    /* 2D84C 8003D04C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D850 8003D050 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D854 8003D054 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D858 8003D058 21288000 */  addu       $a1, $a0, $zero
    /* 2D85C 8003D05C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D860 8003D060 1400428C */  lw         $v0, 0x14($v0)
    /* 2D864 8003D064 00000000 */  nop
    /* 2D868 8003D068 09F84000 */  jalr       $v0
    /* 2D86C 8003D06C 21200000 */   addu      $a0, $zero, $zero
    /* 2D870 8003D070 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D874 8003D074 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D878 8003D078 0800E003 */  jr         $ra
    /* 2D87C 8003D07C 00000000 */   nop
endlabel VSyncCallback

nonmatching VSyncCallbacks, 0x30

glabel VSyncCallbacks
    /* 2D880 8003D080 0580023C */  lui        $v0, %hi(D_800514E8)
    /* 2D884 8003D084 E814428C */  lw         $v0, %lo(D_800514E8)($v0)
    /* 2D888 8003D088 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2D88C 8003D08C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2D890 8003D090 1400428C */  lw         $v0, 0x14($v0)
    /* 2D894 8003D094 00000000 */  nop
    /* 2D898 8003D098 09F84000 */  jalr       $v0
    /* 2D89C 8003D09C 00000000 */   nop
    /* 2D8A0 8003D0A0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D8A4 8003D0A4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2D8A8 8003D0A8 0800E003 */  jr         $ra
    /* 2D8AC 8003D0AC 00000000 */   nop
endlabel VSyncCallbacks
