.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching VSync, 0x84

glabel VSync
    /* 2D5D8 8003CDD8 0580023C */  lui        $v0, %hi(D_80050450)
    /* 2D5DC 8003CDDC 5004428C */  lw         $v0, %lo(D_80050450)($v0)
    /* 2D5E0 8003CDE0 0580033C */  lui        $v1, %hi(D_80050454)
    /* 2D5E4 8003CDE4 5404638C */  lw         $v1, %lo(D_80050454)($v1)
    /* 2D5E8 8003CDE8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2D5EC 8003CDEC 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2D5F0 8003CDF0 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2D5F4 8003CDF4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2D5F8 8003CDF8 0000508C */  lw         $s0, 0x0($v0)
    /* 2D5FC 8003CDFC 0000628C */  lw         $v0, 0x0($v1)
    /* 2D600 8003CE00 0580033C */  lui        $v1, %hi(D_80050458)
    /* 2D604 8003CE04 5804638C */  lw         $v1, %lo(D_80050458)($v1)
    /* 2D608 8003CE08 00000000 */  nop
    /* 2D60C 8003CE0C 23104300 */  subu       $v0, $v0, $v1
    /* 2D610 8003CE10 05008104 */  bgez       $a0, VSYNC_OBJ_50
    /* 2D614 8003CE14 FFFF5130 */   andi      $s1, $v0, 0xFFFF
    /* 2D618 8003CE18 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2D61C 8003CE1C 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
    /* 2D620 8003CE20 C2F30008 */  j          VSYNC_OBJ_130
    /* 2D624 8003CE24 00000000 */   nop
  VSYNC_OBJ_50:
    /* 2D628 8003CE28 01000234 */  ori        $v0, $zero, 0x1
    /* 2D62C 8003CE2C 36008210 */  beq        $a0, $v0, VSYNC_OBJ_130
    /* 2D630 8003CE30 21102002 */   addu      $v0, $s1, $zero
    /* 2D634 8003CE34 07008018 */  blez       $a0, VSYNC_OBJ_7C
    /* 2D638 8003CE38 00000000 */   nop
    /* 2D63C 8003CE3C 0580023C */  lui        $v0, %hi(D_8005045C)
    /* 2D640 8003CE40 5C04428C */  lw         $v0, %lo(D_8005045C)($v0)
    /* 2D644 8003CE44 00000000 */  nop
    /* 2D648 8003CE48 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2D64C 8003CE4C 97F30008 */  j          VSYNC_OBJ_84
    /* 2D650 8003CE50 21104400 */   addu      $v0, $v0, $a0
  VSYNC_OBJ_7C:
    /* 2D654 8003CE54 0580023C */  lui        $v0, %hi(D_8005045C)
    /* 2D658 8003CE58 5C04428C */  lw         $v0, %lo(D_8005045C)($v0)
endlabel VSync

nonmatching VSYNC_OBJ_84, 0xAC

glabel VSYNC_OBJ_84
    /* 2D65C 8003CE5C 02008018 */  blez       $a0, VSYNC_OBJ_90
    /* 2D660 8003CE60 21280000 */   addu      $a1, $zero, $zero
    /* 2D664 8003CE64 FFFF8524 */  addiu      $a1, $a0, -0x1
  VSYNC_OBJ_90:
    /* 2D668 8003CE68 C8F3000C */  jal        v_wait
    /* 2D66C 8003CE6C 21204000 */   addu      $a0, $v0, $zero
    /* 2D670 8003CE70 0580023C */  lui        $v0, %hi(D_80050450)
    /* 2D674 8003CE74 5004428C */  lw         $v0, %lo(D_80050450)($v0)
    /* 2D678 8003CE78 00000000 */  nop
    /* 2D67C 8003CE7C 0000508C */  lw         $s0, 0x0($v0)
    /* 2D680 8003CE80 0580043C */  lui        $a0, %hi(D_8005151C)
    /* 2D684 8003CE84 1C15848C */  lw         $a0, %lo(D_8005151C)($a0)
    /* 2D688 8003CE88 01000534 */  ori        $a1, $zero, 0x1
    /* 2D68C 8003CE8C C8F3000C */  jal        v_wait
    /* 2D690 8003CE90 01008424 */   addiu     $a0, $a0, 0x1
    /* 2D694 8003CE94 0800023C */  lui        $v0, (0x80000 >> 16)
    /* 2D698 8003CE98 24100202 */  and        $v0, $s0, $v0
    /* 2D69C 8003CE9C 10004010 */  beqz       $v0, VSYNC_OBJ_108
    /* 2D6A0 8003CEA0 00000000 */   nop
    /* 2D6A4 8003CEA4 0580033C */  lui        $v1, %hi(D_80050450)
    /* 2D6A8 8003CEA8 5004638C */  lw         $v1, %lo(D_80050450)($v1)
    /* 2D6AC 8003CEAC 00000000 */  nop
    /* 2D6B0 8003CEB0 0000628C */  lw         $v0, 0x0($v1)
    /* 2D6B4 8003CEB4 00000000 */  nop
    /* 2D6B8 8003CEB8 26100202 */  xor        $v0, $s0, $v0
    /* 2D6BC 8003CEBC 08004004 */  bltz       $v0, VSYNC_OBJ_108
    /* 2D6C0 8003CEC0 00000000 */   nop
    /* 2D6C4 8003CEC4 0080043C */  lui        $a0, (0x80000000 >> 16)
  VSYNC_OBJ_F0:
    /* 2D6C8 8003CEC8 0000628C */  lw         $v0, 0x0($v1)
    /* 2D6CC 8003CECC 00000000 */  nop
    /* 2D6D0 8003CED0 26100202 */  xor        $v0, $s0, $v0
    /* 2D6D4 8003CED4 24104400 */  and        $v0, $v0, $a0
    /* 2D6D8 8003CED8 FBFF4010 */  beqz       $v0, VSYNC_OBJ_F0
    /* 2D6DC 8003CEDC 00000000 */   nop
  VSYNC_OBJ_108:
    /* 2D6E0 8003CEE0 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2D6E4 8003CEE4 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
    /* 2D6E8 8003CEE8 0580033C */  lui        $v1, %hi(D_80050454)
    /* 2D6EC 8003CEEC 5404638C */  lw         $v1, %lo(D_80050454)($v1)
    /* 2D6F0 8003CEF0 0580013C */  lui        $at, %hi(D_8005045C)
    /* 2D6F4 8003CEF4 5C0422AC */  sw         $v0, %lo(D_8005045C)($at)
    /* 2D6F8 8003CEF8 0000638C */  lw         $v1, 0x0($v1)
    /* 2D6FC 8003CEFC 21102002 */  addu       $v0, $s1, $zero
    /* 2D700 8003CF00 0580013C */  lui        $at, %hi(D_80050458)
    /* 2D704 8003CF04 580423AC */  sw         $v1, %lo(D_80050458)($at)
endlabel VSYNC_OBJ_84

nonmatching VSYNC_OBJ_130, 0x18

glabel VSYNC_OBJ_130
    /* 2D708 8003CF08 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2D70C 8003CF0C 1400B18F */  lw         $s1, 0x14($sp)
    /* 2D710 8003CF10 1000B08F */  lw         $s0, 0x10($sp)
    /* 2D714 8003CF14 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2D718 8003CF18 0800E003 */  jr         $ra
    /* 2D71C 8003CF1C 00000000 */   nop
endlabel VSYNC_OBJ_130

nonmatching v_wait, 0x8C

glabel v_wait
    /* 2D720 8003CF20 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2D724 8003CF24 C02B0500 */  sll        $a1, $a1, 15
    /* 2D728 8003CF28 1000A5AF */  sw         $a1, 0x10($sp)
    /* 2D72C 8003CF2C 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2D730 8003CF30 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
    /* 2D734 8003CF34 00000000 */  nop
    /* 2D738 8003CF38 2A104400 */  slt        $v0, $v0, $a0
    /* 2D73C 8003CF3C 1B004010 */  beqz       $v0, VSYNC_OBJ_1D4
    /* 2D740 8003CF40 1800BFAF */   sw        $ra, 0x18($sp)
    /* 2D744 8003CF44 FFFF0324 */  addiu      $v1, $zero, -0x1
  VSYNC_OBJ_170:
    /* 2D748 8003CF48 1000A28F */  lw         $v0, 0x10($sp)
    /* 2D74C 8003CF4C 00000000 */  nop
    /* 2D750 8003CF50 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 2D754 8003CF54 1000A2AF */  sw         $v0, 0x10($sp)
    /* 2D758 8003CF58 1000A28F */  lw         $v0, 0x10($sp)
    /* 2D75C 8003CF5C 00000000 */  nop
    /* 2D760 8003CF60 0C004314 */  bne        $v0, $v1, VSYNC_OBJ_1BC
    /* 2D764 8003CF64 00000000 */   nop
    /* 2D768 8003CF68 0180043C */  lui        $a0, %hi(D_800105A8)
    /* 2D76C 8003CF6C A8058424 */  addiu      $a0, $a0, %lo(D_800105A8)
    /* 2D770 8003CF70 1B0B010C */  jal        func_80042C6C
    /* 2D774 8003CF74 00000000 */   nop
    /* 2D778 8003CF78 B10A010C */  jal        ChangeClearPAD
    /* 2D77C 8003CF7C 21200000 */   addu      $a0, $zero, $zero
    /* 2D780 8003CF80 03000434 */  ori        $a0, $zero, 0x3
    /* 2D784 8003CF84 B50A010C */  jal        ChangeClearRCnt
    /* 2D788 8003CF88 21280000 */   addu      $a1, $zero, $zero
    /* 2D78C 8003CF8C EBF30008 */  j          VSYNC_OBJ_1D4
    /* 2D790 8003CF90 00000000 */   nop
  VSYNC_OBJ_1BC:
    /* 2D794 8003CF94 0580023C */  lui        $v0, %hi(D_8005151C)
    /* 2D798 8003CF98 1C15428C */  lw         $v0, %lo(D_8005151C)($v0)
    /* 2D79C 8003CF9C 00000000 */  nop
    /* 2D7A0 8003CFA0 2A104400 */  slt        $v0, $v0, $a0
    /* 2D7A4 8003CFA4 E8FF4014 */  bnez       $v0, VSYNC_OBJ_170
    /* 2D7A8 8003CFA8 00000000 */   nop
endlabel v_wait

nonmatching VSYNC_OBJ_1D4, 0x10

glabel VSYNC_OBJ_1D4
    /* 2D7AC 8003CFAC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2D7B0 8003CFB0 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 2D7B4 8003CFB4 0800E003 */  jr         $ra
    /* 2D7B8 8003CFB8 00000000 */   nop
endlabel VSYNC_OBJ_1D4
