TARGET := SCES_008.68

CROSS := mipsel-linux-gnu-
AS := $(CROSS)as
LD := $(CROSS)ld
OBJCOPY := $(CROSS)objcopy

LDFLAGS = -T config/symbols/$(TARGET).garbage_syms.txt -T config/symbols/$(TARGET).undefined_funcs_auto.txt -T config/symbols/$(TARGET).undefined_syms_auto.txt -T $(LD_SCRIPT) -Map $(BUILD_DIR)/$(TARGET).map

ASFLAGS := -I include -march=mips2 -mabi=32 -O0 -G0 -no-pad-sections

BUILD_DIR := build
ASM_DIR := asm
LD_SCRIPT := ld/$(TARGET).ld

ELF := $(BUILD_DIR)/$(TARGET).elf
BIN := $(BUILD_DIR)/$(TARGET).bin

# Find all assembly files generated by splat
ASM_FILES := $(wildcard $(ASM_DIR)/$(TARGET)/*.s)
OBJ_FILES := $(patsubst $(ASM_DIR)/%.s, $(BUILD_DIR)/$(ASM_DIR)/%.s.o, $(ASM_FILES))

# Include the psx header object if extracted by splat
PSX_HEADER_SRC := assets/$(TARGET)/psx_header.bin
PSX_HEADER_OBJ := $(BUILD_DIR)/assets/$(TARGET)/psx_header.bin.o

.PHONY: all clean

all: $(BIN)

$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@

$(ELF): $(OBJ_FILES) $(PSX_HEADER_OBJ) $(LD_SCRIPT)
	$(LD) $(LDFLAGS) -o $@

$(BUILD_DIR)/$(ASM_DIR)/%.s.o: $(ASM_DIR)/%.s
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

$(PSX_HEADER_OBJ): $(PSX_HEADER_SRC)
	@mkdir -p $(dir $@)
	$(LD) -r -b binary -o $@ $<

# The psx header is generated by splat, this just ensures the dir exists
$(PSX_HEADER_SRC):
	@echo "Error: psx_header.bin missing. Run 'python -m splat split config/splat/$(TARGET).yaml' first."
	@exit 1

clean:
	rm -rf $(BUILD_DIR)
