TARGET := SCES_008.68

CROSS := mipsel-linux-gnu-
AS := $(CROSS)as
LD := $(CROSS)ld
OBJCOPY := $(CROSS)objcopy


ASFLAGS := -I include -march=mips2 -mabi=32 -O0 -G0 -no-pad-sections

BUILD_DIR := build

SYMBOL_LD_FILES := $(BUILD_DIR)/$(TARGET).garbage_syms.txt.ld \
                   $(BUILD_DIR)/$(TARGET).undefined_funcs_auto.txt.ld \
                   $(BUILD_DIR)/$(TARGET).undefined_syms_auto.txt.ld \
                   $(BUILD_DIR)/$(TARGET).manual_syms.txt.ld \
                   $(BUILD_DIR)/$(TARGET).sys_syms.txt.ld \
                   $(BUILD_DIR)/$(TARGET).sdk_syms.txt.ld \
                   $(BUILD_DIR)/$(TARGET).symbols.from_ghidra.txt.ld

LDFLAGS = $(foreach f,$(SYMBOL_LD_FILES),-T $(f)) -T $(LD_SCRIPT) -Map $(BUILD_DIR)/$(TARGET).map

$(BUILD_DIR)/%.txt.ld: config/symbols/%.txt
	@mkdir -p $(dir $@)
	sed 's/\/\/.*//g; s/#.*//g' $< > $@

$(BUILD_DIR)/%.txt.ld: ghidra_exports/splat/%.txt
	@mkdir -p $(dir $@)
	sed 's/\/\/.*//g; s/#.*//g' $< > $@
ASM_DIR := asm
LD_SCRIPT := ld/$(TARGET).ld

ELF := $(BUILD_DIR)/$(TARGET).elf
BIN := $(BUILD_DIR)/$(TARGET).bin

CPP := $(CROSS)cpp
CC1_MAIN := tools/compilers/cc1-psx-263
CC1_AKAO := tools/compilers/cc1-psx-263
MASPSX := tools/maspsx/maspsx.py
CFLAGS_MAIN := -quiet -O2 -G0 -g0 -funsigned-char -fno-builtin
CFLAGS_AKAO := -quiet -O2 -g0 -funsigned-char -fno-builtin

# Find all assembly files generated by splat
ASM_FILES := $(shell find $(ASM_DIR)/$(TARGET) -type f -name '*.s' ! -path '*/nonmatchings/*')
OBJ_FILES := $(patsubst $(ASM_DIR)/%.s, $(BUILD_DIR)/$(ASM_DIR)/%.s.o, $(ASM_FILES))

# Find all C files
SRC_DIR := src
SRC_FILES := $(shell find $(SRC_DIR)/$(TARGET) -name '*.c')
SRC_OBJ_FILES := $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/$(SRC_DIR)/%.c.o, $(SRC_FILES))

# Find all bin files generated by splat
BIN_FILES := $(wildcard assets/$(TARGET)/*.bin)
BIN_OBJ_FILES := $(patsubst assets/$(TARGET)/%.bin, $(BUILD_DIR)/assets/$(TARGET)/%.bin.o, $(BIN_FILES))

.PHONY: all clean

all: $(BIN)

$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@

$(ELF): $(OBJ_FILES) $(SRC_OBJ_FILES) $(BIN_OBJ_FILES) $(LD_SCRIPT) $(SYMBOL_LD_FILES)
	$(LD) $(LDFLAGS) -o $@

$(BUILD_DIR)/$(ASM_DIR)/%.s.o:
	@mkdir -p $(dir $@)
	@if [ -f "src/$*.s" ]; then \
		$(AS) $(ASFLAGS) "src/$*.s" -o $@; \
	else \
		echo "Asm didn't found in src, looking in asm"; \
		$(AS) $(ASFLAGS) "asm/$*.s" -o $@; \
	fi

$(BUILD_DIR)/$(SRC_DIR)/%.c.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	python3 tools/compile_psyq_c.py --cc1 $(CC1_MAIN) --cflags "$(CFLAGS_MAIN)" --cpp "$(CPP)" --cppflags "-nostdinc -I include" --maspsx $(MASPSX) --maspsx_args "--expand-div --aspsx-version=2.21" --as_bin $(AS) --asflags "$(ASFLAGS)" --input $< --output $@

$(BUILD_DIR)/$(SRC_DIR)/%.c.o: $(SRC_DIR)/%.s
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

$(BUILD_DIR)/assets/$(TARGET)/%.bin.o: assets/$(TARGET)/%.bin
	@mkdir -p $(dir $@)
	$(LD) -r -b binary -o $@ $<

clean:
	rm -rf $(BUILD_DIR)

# ==========================================
# Préparation pour le mode Object-Diffing (-o)
# ==========================================
# Plus tard, pour éviter les soucis avec `asm-differ` sur les binaires, 
# nous pourrons utiliser cette cible pour compiler l'assembleur pur 
# du jeu d'origine dans un dossier `expected/`.
# `asm-differ -o` comparera alors directement le .o généré par C avec le .o original.
# 
# EXPECTED_DIR := expected
# 
# expected:
# 	@mkdir -p $(EXPECTED_DIR)/$(BUILD_DIR)
# 	# 1. Compiler les .s extraits dans $(EXPECTED_DIR)
# 	# 2. Cela permettra à asm-differ de comparer les tailles exactes via les symboles des .o
# 	@echo "Dossier expected/ préparé (à implémenter complètement plus tard)."
