.include "macro.inc"

.set noat
.set noreorder

.set noat
.set noreorder


.section .text, "ax"

/* Generated by spimdisasm 1.42.0 */

nonmatching func_80034424, 0x20

glabel func_80034424
    /* 24C24 80034424 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24C28 80034428 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24C2C 8003442C E1D0000C */  jal        ff7_unknown_80034384
    /* 24C30 80034430 00000000 */   nop
    /* 24C34 80034434 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24C38 80034438 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24C3C 8003443C 0800E003 */  jr         $ra
    /* 24C40 80034440 00000000 */   nop
endlabel func_80034424

nonmatching func_80034444, 0x10

glabel func_80034444
    /* 24C44 80034444 0780023C */  lui        $v0, %hi(g_cd_task_index)
    /* 24C48 80034448 8C1B428C */  lw         $v0, %lo(g_cd_task_index)($v0)
    /* 24C4C 8003444C 0800E003 */  jr         $ra
    /* 24C50 80034450 00000000 */   nop
endlabel func_80034444

nonmatching func_80034454, 0x8

glabel func_80034454
    /* 24C54 80034454 0800E003 */  jr         $ra
    /* 24C58 80034458 00000000 */   nop
endlabel func_80034454

nonmatching func_8003445C, 0x8

glabel func_8003445C
    /* 24C5C 8003445C 0800E003 */  jr         $ra
    /* 24C60 80034460 00000000 */   nop
endlabel func_8003445C

nonmatching func_80034464, 0x14

glabel func_80034464
    /* 24C64 80034464 10000234 */  ori        $v0, $zero, 0x10
    /* 24C68 80034468 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24C6C 8003446C 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24C70 80034470 0800E003 */  jr         $ra
    /* 24C74 80034474 00000000 */   nop
endlabel func_80034464

nonmatching func_80034478, 0x38

glabel func_80034478
    /* 24C78 80034478 0780023C */  lui        $v0, %hi(D_80071BB0)
    /* 24C7C 8003447C B01B428C */  lw         $v0, %lo(D_80071BB0)($v0)
    /* 24C80 80034480 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24C84 80034484 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24C88 80034488 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24C8C 8003448C 8C1B20AC */  sw         $zero, %lo(g_cd_task_index)($at)
    /* 24C90 80034490 03004010 */  beqz       $v0, .L800344A0
    /* 24C94 80034494 00000000 */   nop
    /* 24C98 80034498 09F84000 */  jalr       $v0
    /* 24C9C 8003449C 00000000 */   nop
  .L800344A0:
    /* 24CA0 800344A0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24CA4 800344A4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24CA8 800344A8 0800E003 */  jr         $ra
    /* 24CAC 800344AC 00000000 */   nop
endlabel func_80034478

nonmatching func_800344B0, 0x40

glabel func_800344B0
    /* 24CB0 800344B0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24CB4 800344B4 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24CB8 800344B8 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24CBC 800344BC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24CC0 800344C0 BEF7000C */  jal        func_8003DEF8
    /* 24CC4 800344C4 02000434 */   ori       $a0, $zero, 0x2
    /* 24CC8 800344C8 02000234 */  ori        $v0, $zero, 0x2
    /* 24CCC 800344CC 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24CD0 800344D0 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24CD4 800344D4 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24CD8 800344D8 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 24CDC 800344DC 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24CE0 800344E0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24CE4 800344E4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24CE8 800344E8 0800E003 */  jr         $ra
    /* 24CEC 800344EC 00000000 */   nop
endlabel func_800344B0

nonmatching func_800344F0, 0xF8

glabel func_800344F0
    /* 24CF0 800344F0 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24CF4 800344F4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24CF8 800344F8 01000434 */  ori        $a0, $zero, 0x1
    /* 24CFC 800344FC 54F7000C */  jal        func_8003DD50
    /* 24D00 80034500 21280000 */   addu      $a1, $zero, $zero
    /* 24D04 80034504 21184000 */  addu       $v1, $v0, $zero
    /* 24D08 80034508 02000234 */  ori        $v0, $zero, 0x2
    /* 24D0C 8003450C 05006210 */  beq        $v1, $v0, .L80034524
    /* 24D10 80034510 05000234 */   ori       $v0, $zero, 0x5
    /* 24D14 80034514 08006210 */  beq        $v1, $v0, .L80034538
    /* 24D18 80034518 00000000 */   nop
    /* 24D1C 8003451C 62D10008 */  j          .L80034588
    /* 24D20 80034520 00000000 */   nop
  .L80034524:
    /* 24D24 80034524 11000234 */  ori        $v0, $zero, 0x11
    /* 24D28 80034528 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24D2C 8003452C 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24D30 80034530 76D10008 */  j          .L800345D8
    /* 24D34 80034534 00000000 */   nop
  .L80034538:
    /* 24D38 80034538 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24D3C 8003453C 00000000 */  nop
    /* 24D40 80034540 01004224 */  addiu      $v0, $v0, 0x1
    /* 24D44 80034544 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24D48 80034548 10004228 */  slti       $v0, $v0, 0x10
    /* 24D4C 8003454C 0A004014 */  bnez       $v0, .L80034578
    /* 24D50 80034550 01000234 */   ori       $v0, $zero, 0x1
    /* 24D54 80034554 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24D58 80034558 4ED0000C */  jal        func_80034138
    /* 24D5C 8003455C 00000000 */   nop
  .L80034560:
    /* 24D60 80034560 2ED3000C */  jal        func_80034CB8
    /* 24D64 80034564 03000434 */   ori       $a0, $zero, 0x3
    /* 24D68 80034568 61D0000C */  jal        func_80034184
    /* 24D6C 8003456C 00000000 */   nop
    /* 24D70 80034570 FBFF4014 */  bnez       $v0, .L80034560
    /* 24D74 80034574 01000234 */   ori       $v0, $zero, 0x1
  .L80034578:
    /* 24D78 80034578 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24D7C 8003457C 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24D80 80034580 76D10008 */  j          .L800345D8
    /* 24D84 80034584 00000000 */   nop
  .L80034588:
    /* 24D88 80034588 76F3000C */  jal        VSync
    /* 24D8C 8003458C FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 24D90 80034590 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 24D94 80034594 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 24D98 80034598 0000A38C */  lw         $v1, 0x0($a1)
    /* 24D9C 8003459C 21204000 */  addu       $a0, $v0, $zero
    /* 24DA0 800345A0 0D006410 */  beq        $v1, $a0, .L800345D8
    /* 24DA4 800345A4 100E0334 */   ori       $v1, $zero, 0xE10
    /* 24DA8 800345A8 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 24DAC 800345AC 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 24DB0 800345B0 0000A4AC */  sw         $a0, 0x0($a1)
    /* 24DB4 800345B4 01004224 */  addiu      $v0, $v0, 0x1
    /* 24DB8 800345B8 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24DBC 800345BC 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 24DC0 800345C0 05004314 */  bne        $v0, $v1, .L800345D8
    /* 24DC4 800345C4 01000234 */   ori       $v0, $zero, 0x1
    /* 24DC8 800345C8 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24DCC 800345CC 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24DD0 800345D0 2ED3000C */  jal        func_80034CB8
    /* 24DD4 800345D4 03000434 */   ori       $a0, $zero, 0x3
  .L800345D8:
    /* 24DD8 800345D8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24DDC 800345DC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24DE0 800345E0 0800E003 */  jr         $ra
    /* 24DE4 800345E4 00000000 */   nop
endlabel func_800344F0

nonmatching func_800345E8, 0x40

glabel func_800345E8
    /* 24DE8 800345E8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24DEC 800345EC 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24DF0 800345F0 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24DF4 800345F4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24DF8 800345F8 BEF7000C */  jal        func_8003DEF8
    /* 24DFC 800345FC 02000434 */   ori       $a0, $zero, 0x2
    /* 24E00 80034600 04000234 */  ori        $v0, $zero, 0x4
    /* 24E04 80034604 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24E08 80034608 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24E0C 8003460C 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24E10 80034610 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 24E14 80034614 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24E18 80034618 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24E1C 8003461C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24E20 80034620 0800E003 */  jr         $ra
    /* 24E24 80034624 00000000 */   nop
endlabel func_800345E8

nonmatching func_80034628, 0xF4

glabel func_80034628
    /* 24E28 80034628 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24E2C 8003462C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24E30 80034630 01000434 */  ori        $a0, $zero, 0x1
    /* 24E34 80034634 54F7000C */  jal        func_8003DD50
    /* 24E38 80034638 21280000 */   addu      $a1, $zero, $zero
    /* 24E3C 8003463C 21184000 */  addu       $v1, $v0, $zero
    /* 24E40 80034640 02000234 */  ori        $v0, $zero, 0x2
    /* 24E44 80034644 05006210 */  beq        $v1, $v0, .L8003465C
    /* 24E48 80034648 05000234 */   ori       $v0, $zero, 0x5
    /* 24E4C 8003464C 07006210 */  beq        $v1, $v0, .L8003466C
    /* 24E50 80034650 00000000 */   nop
    /* 24E54 80034654 AFD10008 */  j          .L800346BC
    /* 24E58 80034658 00000000 */   nop
  .L8003465C:
    /* 24E5C 8003465C 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24E60 80034660 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24E64 80034664 C3D10008 */  j          .L8003470C
    /* 24E68 80034668 00000000 */   nop
  .L8003466C:
    /* 24E6C 8003466C 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24E70 80034670 00000000 */  nop
    /* 24E74 80034674 01004224 */  addiu      $v0, $v0, 0x1
    /* 24E78 80034678 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 24E7C 8003467C 10004228 */  slti       $v0, $v0, 0x10
    /* 24E80 80034680 0A004014 */  bnez       $v0, .L800346AC
    /* 24E84 80034684 03000234 */   ori       $v0, $zero, 0x3
    /* 24E88 80034688 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 24E8C 8003468C 4ED0000C */  jal        func_80034138
    /* 24E90 80034690 00000000 */   nop
  .L80034694:
    /* 24E94 80034694 2ED3000C */  jal        func_80034CB8
    /* 24E98 80034698 03000434 */   ori       $a0, $zero, 0x3
    /* 24E9C 8003469C 61D0000C */  jal        func_80034184
    /* 24EA0 800346A0 00000000 */   nop
    /* 24EA4 800346A4 FBFF4014 */  bnez       $v0, .L80034694
    /* 24EA8 800346A8 03000234 */   ori       $v0, $zero, 0x3
  .L800346AC:
    /* 24EAC 800346AC 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24EB0 800346B0 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24EB4 800346B4 C3D10008 */  j          .L8003470C
    /* 24EB8 800346B8 00000000 */   nop
  .L800346BC:
    /* 24EBC 800346BC 76F3000C */  jal        VSync
    /* 24EC0 800346C0 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 24EC4 800346C4 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 24EC8 800346C8 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 24ECC 800346CC 0000A38C */  lw         $v1, 0x0($a1)
    /* 24ED0 800346D0 21204000 */  addu       $a0, $v0, $zero
    /* 24ED4 800346D4 0D006410 */  beq        $v1, $a0, .L8003470C
    /* 24ED8 800346D8 100E0334 */   ori       $v1, $zero, 0xE10
    /* 24EDC 800346DC 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 24EE0 800346E0 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 24EE4 800346E4 0000A4AC */  sw         $a0, 0x0($a1)
    /* 24EE8 800346E8 01004224 */  addiu      $v0, $v0, 0x1
    /* 24EEC 800346EC 0780013C */  lui        $at, %hi(D_8006E240)
    /* 24EF0 800346F0 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 24EF4 800346F4 05004314 */  bne        $v0, $v1, .L8003470C
    /* 24EF8 800346F8 03000234 */   ori       $v0, $zero, 0x3
    /* 24EFC 800346FC 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24F00 80034700 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24F04 80034704 2ED3000C */  jal        func_80034CB8
    /* 24F08 80034708 03000434 */   ori       $a0, $zero, 0x3
  .L8003470C:
    /* 24F0C 8003470C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24F10 80034710 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24F14 80034714 0800E003 */  jr         $ra
    /* 24F18 80034718 00000000 */   nop
endlabel func_80034628

nonmatching func_8003471C, 0x5C

glabel func_8003471C
    /* 24F1C 8003471C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24F20 80034720 0780043C */  lui        $a0, %hi(D_80071B98)
    /* 24F24 80034724 981B848C */  lw         $a0, %lo(D_80071B98)($a0)
    /* 24F28 80034728 0780053C */  lui        $a1, %hi(D_80071BAC)
    /* 24F2C 8003472C AC1BA58C */  lw         $a1, %lo(D_80071BAC)($a1)
    /* 24F30 80034730 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24F34 80034734 1307010C */  jal        func_80041C4C
    /* 24F38 80034738 80000634 */   ori       $a2, $zero, 0x80
    /* 24F3C 8003473C 08004014 */  bnez       $v0, .L80034760
    /* 24F40 80034740 06000234 */   ori       $v0, $zero, 0x6
    /* 24F44 80034744 03000234 */  ori        $v0, $zero, 0x3
    /* 24F48 80034748 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24F4C 8003474C 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24F50 80034750 2ED3000C */  jal        func_80034CB8
    /* 24F54 80034754 10000434 */   ori       $a0, $zero, 0x10
    /* 24F58 80034758 DAD10008 */  j          .L80034768
    /* 24F5C 8003475C 00000000 */   nop
  .L80034760:
    /* 24F60 80034760 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24F64 80034764 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
  .L80034768:
    /* 24F68 80034768 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24F6C 8003476C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24F70 80034770 0800E003 */  jr         $ra
    /* 24F74 80034774 00000000 */   nop
endlabel func_8003471C

nonmatching func_80034778, 0x60

glabel func_80034778
    /* 24F78 80034778 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24F7C 8003477C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24F80 80034780 01000434 */  ori        $a0, $zero, 0x1
    /* 24F84 80034784 5507010C */  jal        func_80041D54
    /* 24F88 80034788 21280000 */   addu      $a1, $zero, $zero
    /* 24F8C 8003478C 21184000 */  addu       $v1, $v0, $zero
    /* 24F90 80034790 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 24F94 80034794 07006210 */  beq        $v1, $v0, .L800347B4
    /* 24F98 80034798 00000000 */   nop
    /* 24F9C 8003479C 0A006014 */  bnez       $v1, .L800347C8
    /* 24FA0 800347A0 11000234 */   ori       $v0, $zero, 0x11
    /* 24FA4 800347A4 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24FA8 800347A8 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24FAC 800347AC F2D10008 */  j          .L800347C8
    /* 24FB0 800347B0 00000000 */   nop
  .L800347B4:
    /* 24FB4 800347B4 03000234 */  ori        $v0, $zero, 0x3
    /* 24FB8 800347B8 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24FBC 800347BC 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24FC0 800347C0 2ED3000C */  jal        func_80034CB8
    /* 24FC4 800347C4 03000434 */   ori       $a0, $zero, 0x3
  .L800347C8:
    /* 24FC8 800347C8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 24FCC 800347CC 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 24FD0 800347D0 0800E003 */  jr         $ra
    /* 24FD4 800347D4 00000000 */   nop
endlabel func_80034778

nonmatching func_800347D8, 0x40

glabel func_800347D8
    /* 24FD8 800347D8 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 24FDC 800347DC 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 24FE0 800347E0 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 24FE4 800347E4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 24FE8 800347E8 BEF7000C */  jal        func_8003DEF8
    /* 24FEC 800347EC 02000434 */   ori       $a0, $zero, 0x2
    /* 24FF0 800347F0 0C000234 */  ori        $v0, $zero, 0xC
    /* 24FF4 800347F4 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 24FF8 800347F8 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 24FFC 800347FC 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25000 80034800 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 25004 80034804 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 25008 80034808 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2500C 8003480C 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25010 80034810 0800E003 */  jr         $ra
    /* 25014 80034814 00000000 */   nop
endlabel func_800347D8

nonmatching func_80034818, 0xF8

glabel func_80034818
    /* 25018 80034818 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2501C 8003481C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25020 80034820 01000434 */  ori        $a0, $zero, 0x1
    /* 25024 80034824 54F7000C */  jal        func_8003DD50
    /* 25028 80034828 21280000 */   addu      $a1, $zero, $zero
    /* 2502C 8003482C 21184000 */  addu       $v1, $v0, $zero
    /* 25030 80034830 02000234 */  ori        $v0, $zero, 0x2
    /* 25034 80034834 05006210 */  beq        $v1, $v0, .L8003484C
    /* 25038 80034838 05000234 */   ori       $v0, $zero, 0x5
    /* 2503C 8003483C 08006210 */  beq        $v1, $v0, .L80034860
    /* 25040 80034840 00000000 */   nop
    /* 25044 80034844 2CD20008 */  j          .L800348B0
    /* 25048 80034848 00000000 */   nop
  .L8003484C:
    /* 2504C 8003484C 0D000234 */  ori        $v0, $zero, 0xD
    /* 25050 80034850 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 25054 80034854 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 25058 80034858 40D20008 */  j          .L80034900
    /* 2505C 8003485C 00000000 */   nop
  .L80034860:
    /* 25060 80034860 9401828F */  lw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 25064 80034864 00000000 */  nop
    /* 25068 80034868 01004224 */  addiu      $v0, $v0, 0x1
    /* 2506C 8003486C 940182AF */  sw         $v0, %gp_rel(D_80062E8C)($gp)
    /* 25070 80034870 10004228 */  slti       $v0, $v0, 0x10
    /* 25074 80034874 0A004014 */  bnez       $v0, .L800348A0
    /* 25078 80034878 0B000234 */   ori       $v0, $zero, 0xB
    /* 2507C 8003487C 940180AF */  sw         $zero, %gp_rel(D_80062E8C)($gp)
    /* 25080 80034880 4ED0000C */  jal        func_80034138
    /* 25084 80034884 00000000 */   nop
  .L80034888:
    /* 25088 80034888 2ED3000C */  jal        func_80034CB8
    /* 2508C 8003488C 03000434 */   ori       $a0, $zero, 0x3
    /* 25090 80034890 61D0000C */  jal        func_80034184
    /* 25094 80034894 00000000 */   nop
    /* 25098 80034898 FBFF4014 */  bnez       $v0, .L80034888
    /* 2509C 8003489C 0B000234 */   ori       $v0, $zero, 0xB
  .L800348A0:
    /* 250A0 800348A0 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 250A4 800348A4 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 250A8 800348A8 40D20008 */  j          .L80034900
    /* 250AC 800348AC 00000000 */   nop
  .L800348B0:
    /* 250B0 800348B0 76F3000C */  jal        VSync
    /* 250B4 800348B4 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 250B8 800348B8 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 250BC 800348BC 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 250C0 800348C0 0000A38C */  lw         $v1, 0x0($a1)
    /* 250C4 800348C4 21204000 */  addu       $a0, $v0, $zero
    /* 250C8 800348C8 0D006410 */  beq        $v1, $a0, .L80034900
    /* 250CC 800348CC 100E0334 */   ori       $v1, $zero, 0xE10
    /* 250D0 800348D0 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 250D4 800348D4 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 250D8 800348D8 0000A4AC */  sw         $a0, 0x0($a1)
    /* 250DC 800348DC 01004224 */  addiu      $v0, $v0, 0x1
    /* 250E0 800348E0 0780013C */  lui        $at, %hi(D_8006E240)
    /* 250E4 800348E4 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 250E8 800348E8 05004314 */  bne        $v0, $v1, .L80034900
    /* 250EC 800348EC 0B000234 */   ori       $v0, $zero, 0xB
    /* 250F0 800348F0 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 250F4 800348F4 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 250F8 800348F8 2ED3000C */  jal        func_80034CB8
    /* 250FC 800348FC 03000434 */   ori       $a0, $zero, 0x3
  .L80034900:
    /* 25100 80034900 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25104 80034904 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25108 80034908 0800E003 */  jr         $ra
    /* 2510C 8003490C 00000000 */   nop
endlabel func_80034818

nonmatching func_80034910, 0x80

glabel func_80034910
    /* 25110 80034910 0780023C */  lui        $v0, %hi(D_80071B98)
    /* 25114 80034914 981B428C */  lw         $v0, %lo(D_80071B98)($v0)
    /* 25118 80034918 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 2511C 8003491C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25120 80034920 0780013C */  lui        $at, %hi(D_8006E244)
    /* 25124 80034924 44E222AC */  sw         $v0, %lo(D_8006E244)($at)
    /* 25128 80034928 0900422C */  sltiu      $v0, $v0, 0x9
    /* 2512C 8003492C 03004014 */  bnez       $v0, .L8003493C
    /* 25130 80034930 09000234 */   ori       $v0, $zero, 0x9
    /* 25134 80034934 0780013C */  lui        $at, %hi(D_8006E244)
    /* 25138 80034938 44E222AC */  sw         $v0, %lo(D_8006E244)($at)
  .L8003493C:
    /* 2513C 8003493C 0780043C */  lui        $a0, %hi(D_8006E244)
    /* 25140 80034940 44E2848C */  lw         $a0, %lo(D_8006E244)($a0)
    /* 25144 80034944 0780053C */  lui        $a1, %hi(g_cd_diskinfo_buffer)
    /* 25148 80034948 3C9AA524 */  addiu      $a1, $a1, %lo(g_cd_diskinfo_buffer)
    /* 2514C 8003494C 1307010C */  jal        func_80041C4C
    /* 25150 80034950 80000634 */   ori       $a2, $zero, 0x80
    /* 25154 80034954 08004014 */  bnez       $v0, .L80034978
    /* 25158 80034958 0E000234 */   ori       $v0, $zero, 0xE
    /* 2515C 8003495C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25160 80034960 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 25164 80034964 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 25168 80034968 2ED3000C */  jal        func_80034CB8
    /* 2516C 8003496C 03000434 */   ori       $a0, $zero, 0x3
    /* 25170 80034970 60D20008 */  j          .L80034980
    /* 25174 80034974 00000000 */   nop
  .L80034978:
    /* 25178 80034978 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 2517C 8003497C 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
  .L80034980:
    /* 25180 80034980 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25184 80034984 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25188 80034988 0800E003 */  jr         $ra
    /* 2518C 8003498C 00000000 */   nop
endlabel func_80034910

nonmatching func_80034990, 0xD4

glabel func_80034990
    /* 25190 80034990 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 25194 80034994 01000434 */  ori        $a0, $zero, 0x1
    /* 25198 80034998 21280000 */  addu       $a1, $zero, $zero
    /* 2519C 8003499C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 251A0 800349A0 5507010C */  jal        func_80041D54
    /* 251A4 800349A4 1000B0AF */   sw        $s0, 0x10($sp)
    /* 251A8 800349A8 21184000 */  addu       $v1, $v0, $zero
    /* 251AC 800349AC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 251B0 800349B0 1D006210 */  beq        $v1, $v0, .L80034A28
    /* 251B4 800349B4 00000000 */   nop
    /* 251B8 800349B8 25006014 */  bnez       $v1, .L80034A50
    /* 251BC 800349BC 00000000 */   nop
    /* 251C0 800349C0 0780023C */  lui        $v0, %hi(g_cd_diskinfo_buffer)
    /* 251C4 800349C4 3C9A4224 */  addiu      $v0, $v0, %lo(g_cd_diskinfo_buffer)
    /* 251C8 800349C8 0780103C */  lui        $s0, %hi(g_cd_task_index)
    /* 251CC 800349CC 8C1B1026 */  addiu      $s0, $s0, %lo(g_cd_task_index)
    /* 251D0 800349D0 0380013C */  lui        $at, %hi(D_80034CFC)
    /* 251D4 800349D4 FC4C22AC */  sw         $v0, %lo(D_80034CFC)($at)
    /* 251D8 800349D8 0780023C */  lui        $v0, %hi(D_80071B98)
    /* 251DC 800349DC 981B428C */  lw         $v0, %lo(D_80071B98)($v0)
    /* 251E0 800349E0 9001838F */  lw         $v1, %gp_rel(D_80062E88)($gp)
    /* 251E4 800349E4 F7FF4224 */  addiu      $v0, $v0, -0x9
    /* 251E8 800349E8 09006324 */  addiu      $v1, $v1, 0x9
    /* 251EC 800349EC 0780013C */  lui        $at, %hi(D_80071B98)
    /* 251F0 800349F0 981B22AC */  sw         $v0, %lo(D_80071B98)($at)
    /* 251F4 800349F4 900183AF */  sw         $v1, %gp_rel(D_80062E88)($gp)
    /* 251F8 800349F8 5AD3000C */  jal        func_80034D68
    /* 251FC 800349FC 00000000 */   nop
    /* 25200 80034A00 03004014 */  bnez       $v0, .L80034A10
    /* 25204 80034A04 11000234 */   ori       $v0, $zero, 0x11
    /* 25208 80034A08 94D20008 */  j          .L80034A50
    /* 2520C 80034A0C 000002AE */   sw        $v0, 0x0($s0)
  .L80034A10:
    /* 25210 80034A10 9001848F */  lw         $a0, %gp_rel(D_80062E88)($gp)
    /* 25214 80034A14 7DF8000C */  jal        func_8003E1F4
    /* 25218 80034A18 08000526 */   addiu     $a1, $s0, 0x8
    /* 2521C 80034A1C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25220 80034A20 94D20008 */  j          .L80034A50
    /* 25224 80034A24 000002AE */   sw        $v0, 0x0($s0)
  .L80034A28:
    /* 25228 80034A28 9001848F */  lw         $a0, %gp_rel(D_80062E88)($gp)
    /* 2522C 80034A2C 0780053C */  lui        $a1, %hi(D_80071B94)
    /* 25230 80034A30 941BA524 */  addiu      $a1, $a1, %lo(D_80071B94)
    /* 25234 80034A34 7DF8000C */  jal        func_8003E1F4
    /* 25238 80034A38 00000000 */   nop
    /* 2523C 80034A3C 0B000234 */  ori        $v0, $zero, 0xB
    /* 25240 80034A40 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 25244 80034A44 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 25248 80034A48 2ED3000C */  jal        func_80034CB8
    /* 2524C 80034A4C 03000434 */   ori       $a0, $zero, 0x3
  .L80034A50:
    /* 25250 80034A50 1400BF8F */  lw         $ra, 0x14($sp)
    /* 25254 80034A54 1000B08F */  lw         $s0, 0x10($sp)
    /* 25258 80034A58 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 2525C 80034A5C 0800E003 */  jr         $ra
    /* 25260 80034A60 00000000 */   nop
endlabel func_80034990

nonmatching func_80034A64, 0x38

glabel func_80034A64
    /* 25264 80034A64 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 25268 80034A68 09000434 */  ori        $a0, $zero, 0x9
    /* 2526C 80034A6C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 25270 80034A70 BEF7000C */  jal        func_8003DEF8
    /* 25274 80034A74 21280000 */   addu      $a1, $zero, $zero
    /* 25278 80034A78 14000234 */  ori        $v0, $zero, 0x14
    /* 2527C 80034A7C 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 25280 80034A80 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 25284 80034A84 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25288 80034A88 40E220AC */  sw         $zero, %lo(D_8006E240)($at)
    /* 2528C 80034A8C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25290 80034A90 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25294 80034A94 0800E003 */  jr         $ra
    /* 25298 80034A98 00000000 */   nop
endlabel func_80034A64

nonmatching func_80034A9C, 0xB4

glabel func_80034A9C
    /* 2529C 80034A9C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 252A0 80034AA0 1000BFAF */  sw         $ra, 0x10($sp)
    /* 252A4 80034AA4 01000434 */  ori        $a0, $zero, 0x1
    /* 252A8 80034AA8 54F7000C */  jal        func_8003DD50
    /* 252AC 80034AAC 21280000 */   addu      $a1, $zero, $zero
    /* 252B0 80034AB0 21184000 */  addu       $v1, $v0, $zero
    /* 252B4 80034AB4 02000234 */  ori        $v0, $zero, 0x2
    /* 252B8 80034AB8 05006210 */  beq        $v1, $v0, .L80034AD0
    /* 252BC 80034ABC 05000234 */   ori       $v0, $zero, 0x5
    /* 252C0 80034AC0 07006210 */  beq        $v1, $v0, .L80034AE0
    /* 252C4 80034AC4 13000234 */   ori       $v0, $zero, 0x13
    /* 252C8 80034AC8 BCD20008 */  j          .L80034AF0
    /* 252CC 80034ACC 00000000 */   nop
  .L80034AD0:
    /* 252D0 80034AD0 1ED1000C */  jal        func_80034478
    /* 252D4 80034AD4 00000000 */   nop
    /* 252D8 80034AD8 D0D20008 */  j          .L80034B40
    /* 252DC 80034ADC 00000000 */   nop
  .L80034AE0:
    /* 252E0 80034AE0 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 252E4 80034AE4 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 252E8 80034AE8 D0D20008 */  j          .L80034B40
    /* 252EC 80034AEC 00000000 */   nop
  .L80034AF0:
    /* 252F0 80034AF0 76F3000C */  jal        VSync
    /* 252F4 80034AF4 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 252F8 80034AF8 0780053C */  lui        $a1, %hi(D_8006E23C)
    /* 252FC 80034AFC 3CE2A524 */  addiu      $a1, $a1, %lo(D_8006E23C)
    /* 25300 80034B00 0000A38C */  lw         $v1, 0x0($a1)
    /* 25304 80034B04 21204000 */  addu       $a0, $v0, $zero
    /* 25308 80034B08 0D006410 */  beq        $v1, $a0, .L80034B40
    /* 2530C 80034B0C 100E0334 */   ori       $v1, $zero, 0xE10
    /* 25310 80034B10 0780023C */  lui        $v0, %hi(D_8006E240)
    /* 25314 80034B14 40E2428C */  lw         $v0, %lo(D_8006E240)($v0)
    /* 25318 80034B18 0000A4AC */  sw         $a0, 0x0($a1)
    /* 2531C 80034B1C 01004224 */  addiu      $v0, $v0, 0x1
    /* 25320 80034B20 0780013C */  lui        $at, %hi(D_8006E240)
    /* 25324 80034B24 40E222AC */  sw         $v0, %lo(D_8006E240)($at)
    /* 25328 80034B28 05004314 */  bne        $v0, $v1, .L80034B40
    /* 2532C 80034B2C 13000234 */   ori       $v0, $zero, 0x13
    /* 25330 80034B30 0780013C */  lui        $at, %hi(g_cd_task_index)
    /* 25334 80034B34 8C1B22AC */  sw         $v0, %lo(g_cd_task_index)($at)
    /* 25338 80034B38 2ED3000C */  jal        func_80034CB8
    /* 2533C 80034B3C 03000434 */   ori       $a0, $zero, 0x3
  .L80034B40:
    /* 25340 80034B40 1000BF8F */  lw         $ra, 0x10($sp)
    /* 25344 80034B44 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 25348 80034B48 0800E003 */  jr         $ra
    /* 2534C 80034B4C 00000000 */   nop
endlabel func_80034A9C
